- internal/params/config.go
`hmy_getNodeMetadata` reply formatting is inconsistant
```
$ ./hmy utility metadata
{
"id": "0",
"result": {
"blocks-per-epoch": 5,
"blskey": "65f55eb3052f9e9f632b2923be594ba77c55543f5c58ee1454b9cfd658d25e06373b0f7d42a19c84768139ea294f6204",
"chain-config": {
"chainId": 2,
"crossLinkEpoch": 3,
"crossTxEpoch": 0,
"eip155Epoch": 0,
"preStakingEpoch": 2,
"s3Epoch": 0,
"stakingEpoch": 4
},
"current-epoch": 0,
"is-leader": true,
"network": "localnet",
"role": "Validator",
"shard-id": 0,
"version": "Harmony (C) 2019. harmony, version v5472-master-20191208.0-95-ge2003b48-dirty (edgar@ 2020-01-20T17:11:16-0800)"
}
}
```
```
$ ./hmy utility metadata
{
"id": "0",
"result": {
"blocks-per-epoch": 5,
"blskey": …
```
> [rpc] Update ChainConfig json format to match rpc formatting

- internal/hmyapi/apiv1/backend.go
- internal/hmyapi/apiv1/harmony.go
- internal/hmyapi/apiv2/harmony.go
- internal/hmyapi/backend.go
- node/rpc.go
Some refactoring of current APIs on s3.
Before:
```
```
After:
```
```
**YES|NO**
Note that …
> Refactoring of API s3

- internal/configs/sharding/testnet.go
> [config] a small test net configuration for open staking

- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv2/blockchain.go
- internal/hmyapi/apiv2/transactionpool.go
- internal/hmyapi/backend.go
- node/rpc.go
Same as for s3.
Before:
```
```
After:
```
```
**YES|NO**
Note that this must be enough to …
> hmyv2 is back for master

- scripts/node.sh
> [node.sh] disable archival node mode by default

- core/block_validator.go
> Add one-off block verification rule for beacon chain bad block

- hmy/api_backend.go
- internal/chain/reward.go
- internal/hmyapi/apiv1/backend.go
- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv2/backend.go
- internal/hmyapi/apiv2/blockchain.go
- internal/hmyapi/backend.go
- staking/network/reward.go
- staking/network/values.go
Talked with @flicker-harmony about finishing second RPC half of this PR. There should be a new shard 0 only RPC called GetCurrentNetworkUtilityMetrics
> [network] Factor out reward, prepare data structure for RPC

- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv2/blockchain.go
Add estimate gas to s3.
Before:
```
```
After:
```
```
**YES|NO**
Note that this must be enough …
> S3 estimate gas

- hmy/api_backend.go
- internal/hmyapi/apiv1/backend.go
- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv2/backend.go
- internal/hmyapi/apiv2/blockchain.go
- internal/hmyapi/backend.go
Same for master.
Before:
```
```
After:
```
```
**YES|NO**
Note that this must be enough to …
> Balance by block master

- consensus/votepower/roster.go
Closes https://github.com/harmony-one/harmony-ops/issues/367
> [votepower] Wrong index used on non-harmony node

- consensus/view_change.go
Before:
```
```
After:
```
```
**YES|NO** …
> exponential viewchange timeout

- cmd/harmony/main.go
- core/blockchain.go
- node/node.go
- node/node_handler.go
====== WALLET BALANCES ======
Using local profile for wallet
Account: one1spshr72utf6rwxseaz339j09ed8p6f8ke370zj:
Balance in Shard 0:  184.475980476, nonce: 10
Balance in Shard 1:  0.0000, nonce: 0
Using local profile for wallet
Account: one1uyshu2jgv8w465yc8kkny36thlt2wvel89tcmg:
Balance in Shard 0:  0.0000, nonce: 0
Balance in Shard 1:  185.38074238, nonce: 10
Using local profile for wallet
Account: one1r4zyyjqrulf935a479sgqlpa78kz7zlcg2jfen:
Balance in Shard 0:  1.0000, nonce: 0
Balance in Shard 1:  1.0000, nonce: 0
====== RESULTS ======
PASS
^CGot interrupt signal. Dumping state to DB...
...
> Cherrypick node graceful shutdown

- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv2/blockchain.go
@mikedoan requested hmy_getAllValidatorInfo method. It doesn't accept args, so curl is simple.
Before:
```
```
After:
```
```
NO
6. **What are the planned flag epoch …
> All validator info

- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv2/blockchain.go
@mikedoan requested pagination for hmy_getAllValidatorInformation: page arg is either -1, which means it will just return all validators info or >= 0 and it returns page of 100 validators info.
Before:
```
```
After:
```
```
**YES|NO**
5. …
> Add pagination

- scripts/node.sh
To verify the signature of downloaded binaries, make it optional.
For engineering build, there is no need to verify the signature.
https://github.com/harmony-one/harmony/issues/2245
> [node.sh] make verify signature optional

- consensus/consensus_service.go
- consensus/quorum/one-node-one-vote.go
- consensus/quorum/one-node-staked-vote.go
- consensus/quorum/one-node-staked-vote_test.go
- consensus/quorum/quorum.go
- hmy/api_backend.go
- internal/chain/engine.go
- internal/hmyapi/apiv1/backend.go
- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv2/backend.go
- internal/hmyapi/apiv2/blockchain.go
- internal/hmyapi/backend.go
- node/node_cross_link.go
- shard/committee/assignment.go
- shard/shard_state.go
- shard/shard_state_test.go
With as our consensus now depends on voting power, we need our monitoring tools to provide information about voting power in shards. This RPC will let @janet-harmony extend watchdog with another table in our HTML report page
See an example result of this RPC here, https://gist.github.com/fxfactorial/03e39465d6ffe6b69bd7f3c8f8cf104c
> [rpc][quorum] Expose SuperCommittee network wide RPC

- core/rawdb/accessors_indexes.go
https://github.com/harmony-one/harmony/issues/2278
> fixes #2278

- core/rawdb/accessors_indexes_test.go
This unit test checks for the error found in #2278 and fixed by #2283
> Add unit test to ensure tx fetch is correct

- hmy/api_backend.go
- hmy/backend.go
- internal/hmyapi/apiv1/backend.go
- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv2/backend.go
- internal/hmyapi/apiv2/blockchain.go
- internal/hmyapi/apiv2/types.go
- internal/hmyapi/backend.go
@mikedoan requested staking info method.
Before:
```
```
After:
```
```
**YES|NO**
Note that …
> Staking info

- scripts/go_executable_build.sh
> [build] fix static upload path

- cmd/harmony/main.go
- node/node.go
> Make graceful shutdown more robust and faster

- hmy/backend.go
Stupid bug, Mike noticed that median raw stake was returning null though it was okay before. No wonder why it doest it now.
Before:
```
```
After:
```
```
**YES|NO**
6. …
> Fix median stake

- staking/types/transaction.go
> Make staking tx shardID use common val

- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv2/blockchain.go
API didn't apply pagination because of index mistake.
Before:
```
```
After:
```
```
**YES|NO** …
> Fix pagination

- go.mod
> [go.mod] update libp2p module version

- api/service/explorer/service.go
Requested circulating supply and total supply. Localhost:5099. So will need to use explorer nodes address with 5000 port.
Before:
```
```
After:
```
```
NO
6. **What are …
> Add queries

- staking/availability/measure.go
use current state for validator information query
> Fix undelegate bug

- internal/configs/sharding/testnet.go
update network nodes before and after the staking epoch
> new profile for OSTN

- core/tx_list.go
- core/tx_pool.go
- core/tx_pool_test.go
- core/types/transaction.go
- core/types/tx_pool.go
- staking/types/transaction.go
fixing the transaction pool cost estimation. before it was wrongly estimating the cost and leading to no error message for the cli.
> fix gas cost check for tx pool

- node/node.go
> Do not rebroadcast if the txn is not accepted into txpool

- scripts/node.sh
Master node.sh doesn't have support for static binaries using -I.
This PR cherrypicks the static binary functionality from s3 and merges it with master's node.sh so that static binaries can be used for e.g. OSTN.
```
$ ./node.sh -k bls.key -N staking -z -S -I
node.sh: using manually specified BLS key file: bls.key
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   799  100   799    0     0   1948      0 --:--:-- --:--:-- --:--:--  1948
diff: md5sum.txt: No such file or directory
node.sh: downloaded harmony
node.sh: downloaded wallet
node.sh: downloaded bootnode
node.sh: public IP address autodetected: 164.68.120.87
Enter passphrase for …
```
> Add support for static binaries in node.sh

- internal/utils/singleton.go
Make logger use thread safe writer
> [utils] Make logger use diode writer

- staking/types/transaction.go
Need to also fix casting error of previous cherry-pick
> OSTN for 3-2-20 (Fix)

- scripts/go_executable_build.sh
> [build] hardcode libcrypto in md5sum.txt

- core/blockchain.go
- node/node.go
- shard/committee/assignment.go
> Add more log for committee compute (#2366)

- scripts/docker/Dockerfile
- scripts/docker/docker-node.sh
- scripts/docker/run
port Docker support to master branch.
> Docker support

- hmy/api_backend.go
- internal/hmyapi/apiv1/backend.go
- internal/hmyapi/apiv1/transactionpool.go
- internal/hmyapi/apiv1/util.go
- internal/hmyapi/apiv2/backend.go
- internal/hmyapi/apiv2/transactionpool.go
- internal/hmyapi/apiv2/types.go
- internal/hmyapi/apiv2/util.go
- internal/hmyapi/backend.go
Reverts harmony-one/harmony#2343
> Revert "Add and fix missing txn/staking txn rpc apis"

- internal/chain/engine.go
- internal/chain/reward.go
- staking/availability/measure.go
- staking/availability/measure_test.go
...after convo with RJ, I had to pull over at a starbucks in millbrae to bang out this much more elegant solution.
> [availability] Adjust design to set active field on each block

- core/staking_verifier_test.go
Already tested:
- CV1
- CV3
- CV4
staking test plan:
https://docs.google.com/spreadsheets/d/17kSRWWIqacO-trshVrW2EgH16eVjQdj1Tnx7G2Tx_GI/edit?ts=5e307ae1#gid=0
> [WIP] Unit test for core/staking_verifier.go

- staking/types/delegation_test.go
- staking/types/transaction_test.go
- staking/types/validator_test.go
> test coverage: 0% --> 18.3%
Test functions:
```
NewDelegation()
Undelegation()
TotalInUndelegation()
DeleteEntry()
RemoveUnlockedUndelegations()
```
> Add Unit test for staking/types

- scripts/node.sh
Cherry-picked Verify change from master
> Fix static download issue

- api/service/explorer/storage.go
- api/service/explorer/structs.go
- core/types/cx_receipt.go
- hmy/api_backend.go
- hmy/backend.go
- internal/hmyapi/apiv1/backend.go
- internal/hmyapi/apiv1/transactionpool.go
- internal/hmyapi/apiv1/util.go
- internal/hmyapi/apiv1/util_test.go
- internal/hmyapi/apiv2/backend.go
- internal/hmyapi/apiv2/transactionpool.go
- internal/hmyapi/apiv2/util.go
- internal/hmyapi/apiv2/util_test.go
- internal/hmyapi/backend.go
- node/node_explorer.go
https://github.com/harmony-one/harmony/issues/2300
Before:
```
```
After:
```
```
**YES|NO** …
> Cross shard tx history

- cmd/harmony/main.go
- consensus/consensus_service.go
- core/genesis.go
- hmy/api_backend.go
- internal/configs/node/config.go
- internal/hmyapi/apiv1/backend.go
- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv1/harmony.go
- internal/hmyapi/apiv2/backend.go
- internal/hmyapi/apiv2/blockchain.go
- internal/hmyapi/backend.go
- node/node.go
- node/node_genesis.go
- node/node_handler.go
- shard/committee/assignment.go
- shard/shard_state.go
- staking/availability/measure.go
- staking/slash/report.go
- staking/types/validator.go
- staking/webhooks/yaml.go
Cherry pick of commits from 
https://github.com/harmony-one/harmony/pull/2396
> [project][rpc][log][config] OSTN improvements 

- consensus/quorum/quorum.go
- hmy/api_backend.go
Expose external slot count via extending existing super committee RPC
> [rpc] Extend super committee with external slot count

- scripts/node.sh
> [node.sh] fix static binary in download only mode

- internal/configs/sharding/pangaea.go
- internal/params/config.go
- scripts/node.sh
Use Pangaea Chain-ID for OSTN to not clash with LRTN
> OSTN config

- internal/configs/sharding/pangaea.go
> [config] Change internal config nodes to 27

- api/service/explorer/service.go
- api/service/explorer/storage.go
- api/service/explorer/structs.go
- core/state/statedb.go
- internal/hmyapi/apiv1/transactionpool.go
- internal/hmyapi/apiv2/transactionpool.go
- node/service_setup.go
Updated explorer service to collect top addresses and API /top for it.
Before:
```
```
After:
```
```
NO
6. **What are the planned flag epoch numbers and their ETAs on …
> Top addresses

- block/factory/factory.go
- cmd/harmony/main.go
- internal/configs/node/config.go
- internal/configs/node/group.go
- internal/configs/sharding/instance.go
- internal/configs/sharding/partner.go
- internal/configs/sharding/stress.go
- internal/params/config.go
- internal/wallet/configfile.go
- node/node_genesis.go
- scripts/node.sh
* Add partner config to main.go
* Add partner config internals
* Refactor and add partner logic to genesis node
Partner config is needed for PSTN
> Add partner & stress network config

- consensus/consensus.go
- consensus/leader.go
- core/rawdb/accessors_offchain.go
- internal/chain/engine.go
- node/worker/worker.go
- shard/committee/assignment.go
- staking/effective/calculate.go
- staking/slash/double-sign.go
Add more todos and small fixes as I went through the code.
> [audit] more audit todos and fixes

- internal/configs/sharding/stress.go
Small config to keep STN up for a longer period of time
> [config] small STN config

- core/types/crosslink.go
- hmy/api_backend.go
- internal/hmyapi/apiv1/backend.go
- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv2/backend.go
- internal/hmyapi/apiv2/blockchain.go
- internal/hmyapi/backend.go
Add RPC for https://github.com/harmony-one/harmony-ops/issues/463
From Postman:
```
{"jsonrpc":"2.0", "method":"hmy_getLastCrossLinks", "params":[], "id":1}
{
"id": 1,
"result": [
{
"parentHash": "0xfb7b0bae66dd10780ec7aa6baa52a552ef7fc86ac15f5fb7b6aedbca5b434ad6",
"blockNumber": 28,
"signature": "1ad743b56a9915564dbe8102f0cbdaa218f855aa0d0d922205b675ababd18aa7d49b6c355a279db08889f5c33d5dc20c2a074275a593bf4a90cb8992c3feac4a124425441ca84a5f4fc674a868a3fa695d1a49f459c842a82e6b890cfeafdb0b",
"signatureBitmap": "3f",
"shardId": 1,
"epochNumber": 4
}
]
}
```
**NO**
8. **Does this PR introduce backward-incompatible changes …
> [RPC] Add GetLastCrossLinks RPC

- scripts/node.sh
> [node.sh] enable clean up db/log

- internal/configs/sharding/stress.go
STN should focus more on CPU analysis than network size.
> [config] make STN 2 shards

- consensus/checks.go
> fixing synching issue

- cmd/harmony/main.go
> [pruning] re-enable the is_archival parameter

- scripts/node.sh
> [node.sh] support static binary by default

- core/tx_pool.go
- staking/apr/compute.go
... because GetHeaderByNumber doesn't work on epoch -1 for whatever (existing and known as quirky) reason
> [apr] Traverse till find right epochs or bottom out 

- block/header.go
- core/blockchain.go
- staking/apr/compute.go
- staking/availability/measure.go
Additional logs needed, // TODO remove them later. Adjust seconds per year as stephen point last in last PR
> [apr] More log in various steps of actual compute for apr

- block/header.go
- core/blockchain.go
- staking/apr/compute.go
- staking/availability/measure.go
- staking/types/validator.go
Will notify @mikedoan when I have example JSON for him
> [rpc][validator] Expose lifetime signing counters again 

- internal/configs/sharding/pangaea.go
> [p2] use 5 minutes per epoch

- core/core_test.go
- internal/configs/sharding/stress.go
- internal/configs/sharding/testnet.go
Increase epoch time to ~5 min.
> [config] P2 Testnet configs

- staking/apr/compute.go
GetHeaderByHash still not working reliabily, now trying this more explict way , removal of some logs as well. Non-protocol breaking changes in this PR
> [apr] Follow breadcrumb with hash and number

- core/core_test.go
- hmy/api_backend.go
- internal/chain/engine.go
- internal/chain/reward.go
- internal/configs/sharding/stress.go
- internal/configs/sharding/testnet.go
- internal/utils/singleton.go
- node/node_handler.go
- node/node_newblock.go
- shard/committee/assignment.go
- staking/apr/compute.go
- staking/availability/measure.go
- staking/effective/eligible.go
- staking/types/validator.go
> roll up T3 with master

- node/node_genesis.go
Needed for fund distribution as dictated in P2 token distribution plan.
> [node] Change testnet faucet init bal to 10B

- shard/shard_state.go
we can tweak the cache forget time
> [shard] singleflight on committees bls public keys

- internal/chain/engine.go
- internal/chain/reward.go
- node/node_newblock.go
...for downstream data science analysis
> [log] Data epoch & blocknum to subset of ds logs

- scripts/node.sh
tested with Haodi. This should be the proper fix.
> adjust location of timeout param, tested

- core/staking_verifier.go
- core/staking_verifier_test.go
- core/tx_pool_test.go
- staking/slash/double-sign_test.go
- staking/types/validator.go
- staking/types/validator_test.go
Restrictions imposed for create validator and delegation:
* create validator must have 10,000 ONE
* delegation must have at least 1000 ONE
> Adding minimum stake for create validator and delegation

- staking/apr/compute.go
...because going back headers is long loop when doesn't find right headers
> [apr] Temp comment out

- consensus/checks.go
- core/staking_verifier.go
- core/staking_verifier_test.go
- core/tx_pool_test.go
- node/node_genesis.go
- staking/slash/double-sign_test.go
- staking/types/validator.go
- staking/types/validator_test.go
> Merge master to t3 0321

- consensus/checks.go
> Fix nil pointer error

- hmy/api_backend.go
- internal/hmyapi/apiv1/backend.go
- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv2/backend.go
- internal/hmyapi/apiv2/blockchain.go
- internal/hmyapi/backend.go
Include latest changes from T3 - including new RPC's get-validator-info-by-block
> Merge master t3

- consensus/votepower/roster.go
- core/blockchain.go
- staking/apr/compute.go
- staking/slash/double-sign.go
Fix: 
https://github.com/harmony-one/security-audit/issues/15
https://github.com/harmony-one/security-audit/issues/16
> fix peckshield audit issues on slashing

- consensus/double_sign.go
- consensus/leader.go
This is consistent with the previous logic.
Since the check didn't return on the OnCommit(). The double signed msg pass through to the code below and actually got accepted into the votes and overwritten the original good signature, causing the final aggregated signature to be invalid and the validator won't be able to verify it.
> Return if potential double sign

- scripts/node.sh
> [node.sh] enable archival mode if node type is explorer

- internal/chain/reward.go
- staking/network/reward.go
Simply removed the logic to do the dynamic adjustment and use a flat rate reward of 28 ONE per block.
> Set block reward to flat-rate 28 ONE

- core/staking_verifier_test.go
- hmy/api_backend.go
- hmy/backend.go
- node/node_handler.go
- staking/types/validator.go
Fixes #2530 & #2620 .
Tested locally, but unable to reproduce overflow error on localnet.
New error message:
```
[Undelegate] min_self_delegation 10000000000000000000000, after undelegation amount 0: self delegation can not be less than min_self_delegation -- 2020-03-27 15:48:40 -0700 PDT
```
> Update undelegate error message & fix overflow for 'current-epoch-blocks-left'

- staking/slash/double-sign.go
From audit-1, another check on slash
> [slash] Quick hash sanity check for conflicting ballots

- core/state/statedb.go
Early return if validator is banned
> [state] Do not add reward to banned validator

- staking/types/validator.go
Can easily avoid this loop, hide state in closure. 
// TODO Clear out the cache map of epochs more than 5 ago, or something like that.
> [validator] Cache harmony keys in a closure

- shard/committee/assignment.go
@mindstyle85 now you'll have the JSON field `stake-per-key` in `epos-slot-candidates` of `hmy blockchain median-stake`
> [assignment] Add StakePerKey as feature request of epos candidates

- consensus/quorum/one-node-staked-vote.go
Add external slot count, reflected in usage for watchdog
> [quorum] Expose external slot count for JSON of Decider

- block/header.go
Add same logic to master , https://github.com/harmony-one/harmony/pull/2640
> [header] Error out if header receiver is nil

- hmy/api_backend.go
- staking/effective/eligible.go
expose if banned validator in `hmy blockchain validator information <ADDR>`
> [effective][rpc] Add banned string in virtual eposstatus field

- core/tx_pool.go
- core/types/transaction.go
- internal/hmyapi/apiv1/transactionpool.go
- internal/hmyapi/apiv2/transactionpool.go
- node/node_handler.go
Implementation of https://github.com/harmony-one/harmony/pull/2382 on s3
> [Core + API + Node] Add raw tx size limitation

- scripts/node.sh
> [node.sh] enable p2p tracefile using -R option

- staking/effective/eligible.go
This closes #2545
No test files
**NO**
**NO**
**NO**
> [staking] Remove per block EPOS status msgs

- internal/blsgen/lib.go
- internal/blsgen/lib_test.go
from an interaction with node volunteer having issues and better error message will help to debug
> [blsgen] LoadFromKey with passphrase more robustly

- shard/shard_state.go
- shard/shard_state_test.go
- staking/apr/compute.go
- staking/slash/double-sign.go
- staking/slash/double-sign_test.go
removal of dead code pointed out by 
```
staticcheck github.com/harmony-one/harmony/...
```
with excellent tool of https://github.com/dominikh/go-tools
> [project] Fix first round issue from static analysis check

- README.md
> [README] minor update of README.md

- cmd/harmony/main.go
- go.mod
- internal/blsgen/lib.go
cherry pick code from master PR https://github.com/harmony-one/harmony/pull/2650
> cherry pick bls aws encryption support code to harmony S3 

- core/tx_pool.go
Issue #2690 
Simple change to severity level of log message
> Issue #2690 - reduce severity of "Pooled new future transaction" message

- core/state/statedb.go
I think could be 0% commision rate and better safe than sorry error on 0 total delegation
> [state] ValidatorWrapper div zero panic fix - 

- core/blockchain.go
- core/offchain.go
- staking/availability/measure.go
Bring back ganesha's change and make code tolerate 0 toSign.
> Final attempt: Don't div by 0; print out debug info

- core/blockchain.go
- core/chain_makers.go
- core/tx_cacher.go
- core/tx_pool_test.go
- staking/availability/measure.go
commit ba1c0cd0a3237dcc094266c30253e401b65e3552
Author: Edgar Aroutiounian <edgar.factorial@gmail.com>
Date:   Sun Apr 5 23:53:03 2020 -0700
[blockchain] Create fresh big int, remove more dead code from static … (#2749)
* [blockchain] Create fresh big int, remove more dead code from static analysis
* [measure] Remove IzZero/IsNil checks
commit 191f1d5ee266d32cf08f243f953925718fdb61c1
Author: Rongjian Lan <rongjian.lan@gmail.com>
Date:   Sun Apr 5 21:11:21 2020 -0700
Final attempt: Don't div by 0; print out debug info (#2746)
* Revert "Revert "fix earned-reward by writing the stats only once, remove from UpdateValdiatorVotingPower (#2737)" (#2742)"
This reverts commit 832b01dfff0b2fec3cc647f507a8d105a8dbf4a7.
* Don't div by 0; print out debug info
commit …
> Squashed commit of the following:

- api/service/explorer/storage.go
- api/service/explorer/storage_test.go
- cmd/harmony/main.go
change explorer node storage folder (#2720)
cherry-pick from master code
Before:
```
```
After:
```
```
**YES|NO**
6. **What are the planned flag epoch numbers and their …
> change explorer node storage folder (#2720)

- internal/configs/node/config.go
fixes https://github.com/harmony-one/harmony/issues/2696
> enhance multikey validation error message

- core/blockchain.go
- staking/apr/compute.go
minor mistake. should fix the issue.
> [apr] fix the validator stats not showing up for two epochs issue

- .travis.yml
- Dockerfile
- core/tx_pool_test.go
- go.mod
> [go] upgrade golang to 1.14

- Makefile
surprised this hasn't been done
> [project] Build in parallel

- Makefile
- go.mod
- hmy/api_backend.go
- hmy/backend.go
- internal/hmyapi/apiv1/backend.go
- internal/hmyapi/apiv1/harmony.go
- internal/hmyapi/apiv2/backend.go
- internal/hmyapi/apiv2/harmony.go
- internal/hmyapi/backend.go
- internal/hmyapi/common/types.go
- node/node.go
- node/rpc.go
- scripts/go_executable_build.sh
1) build with ability to trace unsafe pointers 
2) trace unix time at nodeboot, expose in metadata rpc
3) factor out redundant data type in RPC 
4) Remove dead dependencies
> [project] Use tracepointer

- scripts/node.sh
Fix https://github.com/harmony-one/harmony/issues/2730
> [node.sh] install unzip as dependency of rlcone

- api/service/explorer/storage.go
Cherry pick from master #2786
Before:
```
```
After:
```
```
**YES|NO**
Note that this must be …
> fix explorer folder path (#2786)

- api/service/explorer/storage.go
> No batch commit for explorer db

- node/node_handler.go
fixes https://github.com/harmony-one/harmony/issues/2771
> [node] bingo with signature information

- consensus/consensus_v2.go
Previously, if multiple committed msges found, only try the first one, but the first one may not be valid.
Should try all of them and use the valid one.
Fixed: https://github.com/harmony-one/harmony/issues/2801
> Try all messages on committed msg

- scripts/node.sh
> [node.sh] detect hmy profile in rclone.conf

- consensus/consensus_v2.go
- consensus/engine/consensus_engine.go
- core/blockchain.go
- core/chain_makers.go
- core/offchain.go
- core/rawdb/accessors_offchain.go
- core/rawdb/schema.go
- hmy/api_backend.go
- staking/network/reward.go
Previously, elected validator list are stored separately in offchain db. It's not necessary because it can be computed from shard state. So removed.
Also make sure the list of all validator doesn't contain duplicate addresses.
tested locally
> Remove elected validator list and make sure validator list addrs are unique

- cmd/harmony/main.go
- go.mod
> [main] fix a logic error when reading multibls key

- scripts/node.sh
> [node.sh] keep all the logs for debugging

- core/blockchain.go
Boot status was set inside the incoming/retained validator slots, instead should have been set for the outgoing validator slots.
> [core] fix validator boot status for outgoing validators

- scripts/node.sh
> [node.sh] time out deleting passphrase file

- shard/committee/assignment.go
- staking/effective/calculate.go
- staking/effective/calculate_test.go
...as requested in p-ops discord, expose the raw stake used
> [effective] Hold onto raw stake used per slot purchase as well

- api/service/explorer/storage.go
Point 1. Explorer goes through all blocks and process them again everytime explorer node is restarted.
from https://github.com/harmony-one/harmony/issues/2831
Launched explorer node from the binary built with this change, and checked the log for block dumps being skipped for blocks that are already saved on the node ldb.
> explorer node. Skip dump for redundant blocks with lower block number than the checkpoint block number

- consensus/view_change.go
view change bug was introduced during multi key feature. this fix is applied to master already (https://github.com/harmony-one/harmony/pull/2826). this pr is just porting it. the view change will be more robust with this fix on mainnet.
> [consensus][viewchange] porting multikey regression fix to s3

- api/service/explorer/storage.go
- api/service/explorer/structs.go
- api/service/explorer/structs_test.go
> explorer node. handle get txn/staking txn being nil during block dump

- core/state_processor.go
- core/types/transaction.go
- core/types/transaction_test.go
- core/types/tx_pool.go
- node/node_handler_test.go
- node/node_newblock.go
- node/worker/worker.go
- node/worker/worker_test.go
- test/chain/main.go
* For block proposal, process pending PoolTransactions in the TransactionsByPriceAndNonce order (regardless of normal or staking)
* For block verification, pull and put normal and staking transactions into the same PoolTransactions list and apply and process in TransactionsByPriceAndNonce order
> [core][node/worker] processing staking and normal transactions together

- cmd/harmony/main.go
- consensus/consensus.go
- consensus/consensus_v2.go
- consensus/validator.go
- core/blockchain.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_offchain.go
- core/rawdb/schema.go
- core/types/block.go
- node/node_cross_shard.go
- node/node_handler.go
- node/node_newblock.go
- node/worker/worker.go
Last commit wasn't consistently written to db as blocks. This change fixes it.
> Make commit sig committed along with the block

- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv2/blockchain.go
Port GetBlockSigners RPC from master to s3.
Tested on localnet:
> [RPC] Implement getBlockSigners RPC from master

- internal/configs/sharding/pangaea.go
> [p3] sharding configuration for p3 launch

- scripts/go_executable_build.sh
- scripts/node.sh
> [build] upload node.sh

- hmy/api_backend.go
- internal/hmyapi/apiv1/backend.go
- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv2/backend.go
- internal/hmyapi/apiv2/blockchain.go
- internal/hmyapi/backend.go
added singleflight for:
* GetAllValidatorInformation
* GetSuperCommittee
* GetMedianRawStakeSnapshot
apis
> [rpc] singleflight for all validator info, median, and super committee rpcs

- core/state_processor.go
- core/types/transaction.go
- core/types/transaction_test.go
- core/types/tx_pool.go
- node/node_handler_test.go
- node/node_newblock.go
- node/worker/worker.go
- node/worker/worker_test.go
- test/chain/main.go
Manually revert : https://github.com/harmony-one/harmony/pull/2869
> Revert merge normal and staking txns

- core/staking_verifier.go
- core/staking_verifier_test.go
- core/state_transition.go
- core/tx_pool.go
- core/tx_pool_test.go
- test/chain/reward/main.go
move checkDuplicateFields inside staking_verifier such that tx_pool can also use it.
> refactor check duplicates to staking_verifier

- internal/configs/sharding/testnet.go
- scripts/go_executable_build.sh
> [testnet] use different dns for testnet config

- cmd/harmony/main.go
- scripts/node.sh
cherry-pick the pprof change to s3
> Add support for pprof in harmony + node.sh (#2424)

- scripts/node.sh
Some deploy scripts depend on being able to pass `-N stn` to node.sh. Also added support for "stressnet" so now `-N stn`, `-N stress` and `-N stressnet` are valid options.
Before:
```
```
After:
```
```
**YES|NO**
5. **What are the planned …
> Add support for additional "stn" and "stressnet" matches for -N for stn/stressnet

- staking/types/validator.go
Fix a mistakenly committed local change.
> revert min stake change for validator

- scripts/node.sh
> [node.sh] add a tn network type

- scripts/node.sh
> [node.sh] forget : in getopts

- internal/hmyapi/apiv1/transactionpool.go
- internal/hmyapi/apiv1/types.go
- internal/hmyapi/apiv2/transactionpool.go
- internal/hmyapi/apiv2/types.go
This closes #2922 
Tested locally with multiple txs, here is a screenshot: 
**NO**
**NO**
**NO**
> [rpc] Fix pending tx & stx fetch

- internal/configs/sharding/mainnet.go
- internal/configs/sharding/shardingconfig_test.go
- internal/params/config.go
> [dryrun] set prestaking/staking epoch

- scripts/node.sh
> [node.sh] include node.sh during upgrade

- scripts/go_executable_build.sh
> [build] include node.sh in md5sum.txt

- scripts/node.sh
we will use up to 10 keys per node in mainnet
> [node.sh] set default bls per node to 10

- internal/hmyapi/apiv1/transactionpool.go
- internal/hmyapi/apiv2/transactionpool.go
Fixed issue raised in comments of #2935
> [rpc] Make pending tx & stx fetch return non-nil for mixed txs

- block/header.go
- core/tx_pool_test.go
- hmy/api_backend.go
- hmy/backend.go
- internal/hmyapi/apiv1/backend.go
- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv2/backend.go
- internal/hmyapi/apiv2/blockchain.go
- internal/hmyapi/backend.go
Probably helpful RPC to have when debugging s3 -> master upgrade.
> [RPC] Port hmy_getLatestChainHeaders from master

- internal/configs/sharding/mainnet.go
> [t3.dryrun] set v2 epoch to 178

- node/node_newblock.go
Cherrypick from dryrun network to master. This is already tested in dryrun network and it fixes a view change issue.
> verify block before proposal

- core/types/block.go
current work in another PR has many situation of parallelism , so during race condition testing, I hit this open issue. 
> by doing a blk.ShardID() in one thread and a rlp.DecodeBytes in another thread, they both hit up 
> the global tagged RLP registry and it exploded
> [blockchain] singleflight on tagged rlp registry

- consensus/consensus_v2.go
- consensus/leader.go
- consensus/reward/schedule.go
- consensus/view_change.go
- core/block_validator.go
- go.mod
- node/node.go
- node/node_handler.go
- node/node_syncing.go
- p2p/host.go
Throttle acceptance of p2p with business logic
> [node] Throttle acceptance of incoming messages

- core/blockchain.go
- hmy/api_backend.go
- staking/types/validator.go
RLP decode was failing due to usage of map for stats APRs. Changed this to slice.
> validator stats regression due to apr bug fixed

- hmy/api_backend.go
super-committee rpc returns nil epoch to for roster compute for staking epoch where the committee is actually available due to not available previous committee epoch. This pr will skip computing for previous committee before staking epoch.
> super-committee for staking epoch should have empty previous committee not error out

- hmy/api_backend.go
cherry pick 9c112c53c4a48d6fa1b28fd0e98001fc49b75c1e
> super-committee for staking epoch should have empty previous committee rpc

- scripts/node.sh
> [node.sh] chmod +x node.sh after download

- node/node_handler.go
- p2p/host.go
- scripts/node.sh
Tested running node locally, with proper log level, the log is much less noisy.
> Support log level in node.sh

- core/tx_pool.go
> [txpool] Correct logging level

- core/offchain.go
- hmy/api_backend.go
cherry pick 2d09478531e3983109c99a52dc38ce20c8ed9694
> write validator stats at the end of prestaking epoch

- cmd/harmony/main.go
- consensus/consensus_service.go
- consensus/votepower/roster.go
- internal/chain/engine.go
- internal/configs/viper/viper_config.go
- internal/hmyapi/apiv1/transactionpool.go
- internal/hmyapi/apiv2/sendtxargs.go
- internal/hmyapi/apiv2/transactionpool.go
- internal/hmyapi/apiv2/types.go
- staking/availability/measure_test.go
- staking/slash/double-sign_test.go
- staking/slash/interface_test.go
- staking/types/test/copy_test.go
- staking/types/validator_test.go
- webhooks/yaml.go
Fix some issues reported by lint tool `staticcheck`. 
Note this PR is only about code formatting and shall not change any of the code logic. Please let me know if any of the change is inappropriate. Thanks.
> Code formatting fix based on `staticcheck`

- core/offchain.go
- node/node.go
> [log] adust level and clean up

- consensus/consensus_v2.go
- core/blockchain.go
- internal/chain/engine.go
- internal/hmyapi/apiv1/blockchain.go
Fix : https://github.com/harmony-one/harmony/issues/3022
> Add nil checks on all GetHeader* func.

- consensus/consensus_v2.go
- core/blockchain.go
- internal/chain/engine.go
- internal/hmyapi/apiv1/blockchain.go
> add nil check on getHeader

- node/node_cross_link.go
- node/node_handler.go
- node/node_syncing.go
Reverts harmony-one/harmony#3036
> Revert "[wip]make crosslink broadcast smarter and more efficient"

- consensus/quorum/one-node-staked-vote.go
- consensus/quorum/quorum.go
- node/node_cross_link.go
- node/node_handler.go
- node/node_newblock.go
- node/node_syncing.go
- staking/verify/verify.go
Optimize crosslink verification logic and add more cache (#3032)
@rlan35
rlan35 committed 2 days ago
make crosslink broadcast smarter and more efficient (#3036)
@rlan35
rlan35 committed yesterday
adjust catch up speed to be a sane number
@rlan35
rlan35 committed 5 hours ago
Fix crosslink broadcast condition (#3041)
@rlan35
rlan35 committed 4 hours ago
> Cherrypick crosslink related fixes from t3 to master.

- staking/apr/compute.go
apr computation should use total delegation of the validator at the time of the election and not the latest total delegation from the wrapper.
> [apr] use snapshot total delegation instead of current total delegation

- staking/apr/compute.go
APR computation was using the snapshot from last epoch, instead it should use the current epoch snapshot, as snapshot for the current epoch was created in the last block of last epoch (this is the snapshot corresponding to the last election)
> [apr] should not use snapshot from last epoch, use current epoch snapshot

- internal/configs/sharding/testnet.go
- internal/params/config.go
- scripts/node.sh
> [config] Create Testnet config

- internal/configs/sharding/testnet.go
> [config] correct testnet config

- consensus/validator.go
Parallelize signing and sending PREPARE and COMMIT messages from validator to boost current signing issues.
> [multi-bls] validator sign and send message in parallel

- cmd/harmony/main.go
> [main] Enable beacon sync for explorer nodes

- cmd/harmony/main.go
> [main] Enable beacon sync for explorer nodes (#3059)

- consensus/validator.go
Reverts harmony-one/harmony#3054
> Revert "[multi-bls] validator sign and send message in parallel"

- core/offchain.go
fix the first staking epoch apr in the third staking epoch.
> [apr] fix wrong staking apr in the third staking epoch

- scripts/node.sh
Generated blskey pass files can potentially be read by others on same machine in node.sh when run in multisig mode.
```
hsiung@harmony:~/test$ ./node.sh -S -z -M
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   799  100   799    0     0   6603      0 --:--:-- --:--:-- --:--:--  6603
node.sh: binaries did not change
node.sh: public IP address autodetected: 104.238.130.36
Enter passphrase for the BLS key file ./.hmy/blskeys/710366b83f9d120a763f2e68c994e10033940ddf7ec0eeefef3d4c990dd5d45f4c7d7ccc7ca67d99f0e40c354e539e00.key:
Passphrase is temporarily saved to: ./.hmy/blskeys/710366b83f9d120a763f2e68c994e10033940ddf7ec0eeefef3d4c990dd5d45f …
```
> Chmod og-rw generated blskey pass file in node.sh

- scripts/node.sh
node.sh cleanup and add randomized download/update to avoid massive download/restart.
> Node.sh cleanup

- go.mod
> [go.mod] update go.mod for libp2p

- core/block_validator.go
> fix nil pointer of block

- core/block_validator.go
- internal/chain/engine.go
Cherry-pick the nil pointer fixes to t3 for rolling upgrade.
> Cherry pick nil pointer fix to t3

- internal/hmyapi/apiv1/blockchain.go
Cherry-pick fix for smart contract deployment issue from master.
> Cherry-pick fix for smart contract deployment issue from master.

- README.md
> [readme] update readme with static library info

- scripts/node.sh
> [node.sh] compare the right md5sum.txt file

- internal/configs/sharding/mainnet.go
The exact epoch is not finalized yet.
> Add epoch transition to increase open slots

- core/offchain.go
the code removed in this pr was added temporary to fix previous epoch apr values. the code was only usable at epoch 191 to 192 transition in mainnet. this code is no longer needed.
> [apr] remove temporary fix for correcting previous apr values, no longer needed

- api/proto/common.go
- cmd/harmony/main.go
- consensus/checks.go
- consensus/consensus.go
- consensus/consensus_service.go
- consensus/consensus_v2.go
- go.mod
- node/node.go
- node/node_explorer.go
- node/node_handler.go
- p2p/host.go
- test/deploy.sh
This PR is mostly a subset of the original PR of https://github.com/harmony-one/harmony/pull/2984
with a few minor fixes based on review feedback.
Authored-by: Edgar Aroutiounian <edgar.factorial@gmail.com >
> [libp2p] validate pubsub messages

- scripts/node.sh
increase the latency of auto-download from 5-10m to 30-60m.
> [node.sh] change mainnet folder

- p2p/host.go
> [p2p] add remote tracer

- p2p/host.go
> [libp2p] support both local json and remote event tracer

- api/proto/node/node.go
- api/service/manager.go
- api/service/networkinfo/service.go
- consensus/consensus.go
- consensus/consensus_service.go
- consensus/consensus_v2.go
- consensus/leader.go
- consensus/threshold.go
- consensus/view_change.go
- core/blockchain.go
- core/offchain.go
- core/tx_list.go
- core/tx_pool.go
- hmy/api_backend.go
- internal/configs/sharding/mainnet.go
- internal/hmyapi/apiv1/types.go
- internal/hmyapi/apiv2/types.go
- p2p/host.go
- test/debug.sh
- test/deploy.sh
Changes merge to this release.
```
$ git log --oneline origin/t3..origin/master
9ebeef21 (HEAD -> t3, origin/master, origin/HEAD, leo/merge_master_to_t3_0608) [core] repair nil pointer fix
2f30790e (master) Merge pull request #3144 from LeoHChen/merge_t3_to_master_0608
899a6438 (leo/merge_t3_to_master_0608) Merge remote-tracking branch 'origin/t3'
386b20c4 [RPC] add input on newRPCTransaction (#3140)
3c4a514b [libp2p] support both local json and remote event tracer
8665ed41 [p2p] add remote tracer
3d02fe64 (node) Fix multi-key related issues when keys are not in committee (#3132)
17ea7119 Merge pull request #3114 from LeoHChen/libp2p_pubsub_spam_defense
890cc4d7 [libp2p] increase size of outbound queue
395d0df0 [misc] rename needFriends to enoughMinPeers
86263bd6 [consensus] do not verify …
```
> Merge master to t3 0608

- internal/hmyapi/apiv1/types.go
- internal/hmyapi/apiv2/types.go
Example return from localnet
```
$ curl --location --request POST 'http://localhost:9500' --header 'Content-Type: application/json' --data-raw '{
"method": "hmyv2_latestHeader",
"params": [],
"id": 1
}' | jq
{
"id": 1,
"result": {
"blockHash": "0x9c6c5d97d7a2f7b91fbf7112d40c2d9bd192a0731ff0f9047650c283b8e3a5bf",
"blockNumber": 498,
"shardID": 0,
"leader": "one1dygmwke9vzlf4rm3ze9rxzrtu3g3ljv6cxwhvs",
"viewID": 498,
"epoch": 98,
"timestamp": "2020-06-12 14:30:27 +0000 UTC",
"unixtime": 1591972227,
"lastCommitSig": "f696a24ee00353a93d73fe2351b18ef4b5e1e0ee62d135f59405a0aac4879b3a54cd04cee9d05ac434be086f1550bf1295ca2bf1cbbdc065e36aece95024ae7ebcf11db660a91e40de0280f222e3e443fe95f41e47cdac3259307b94cc7bf112",
"lastCommitBitmap": "3f",
"crossLinks": [
{ …
```
> [rpc] Expose crosslinks in RPCs that return block headers

- core/blockchain.go
- internal/configs/sharding/fixedschedule.go
- internal/configs/sharding/localnet.go
- internal/configs/sharding/mainnet.go
- internal/configs/sharding/pangaea.go
- internal/configs/sharding/partner.go
- internal/configs/sharding/shardingconfig.go
- internal/configs/sharding/stress.go
- internal/configs/sharding/testnet.go
[internal] Add IsSkippedEpoch to each network config & interface
[blockchain] Add check to ReadShardState error to check if the epoch was skipped due to staking
Example on Shard 3:
```
$ curl --location --request POST 'http://localhost:9500' --header 'Content-Type: application/json' --data-raw '{
"method": "hmyv2_getValidators",
"params": [185],
"id": 1
}' | jq
{
"id": 1,
"error": {
"code": -32000,
"message": "epoch skipped on chain: failed to read shard state from DB"
}
}
```
> Add list of epochs skipped on chain due to staking release

- api/service/syncing/syncing.go
- node/node_syncing.go
> [syncing] fix mis-matched min syncing peers

- consensus/consensus_msg_sender.go
- consensus/consensus_service.go
- consensus/consensus_v2.go
atomic.Value is faster than the Mutex we used in messageSender.
> Remove mutex in message sender

- node/node.go
> [p2p] add counters of valid/invalid messages

- cmd/harmony/main.go
- internal/utils/singleton.go
> [cleanup] remove unused flag and log file

- internal/configs/sharding/testnet.go
> Add slot increase for testnet

- node/node.go
> [p2p] add a buffer in msgChan

- consensus/consensus.go
- consensus/consensus_v2.go
- core/staking_verifier.go
- core/state/statedb.go
- go.mod
- hmy/api_backend.go
- internal/configs/sharding/mainnet.go
- internal/configs/sharding/testnet.go
- node/node.go
- shard/committee/assignment.go
- staking/slash/double-sign.go
- staking/types/validator.go
- staking/types/validator_test.go
Changes to be merged to t3.
```
5c8c7d1c (HEAD -> t3, leo/merge_master_to_t3_0619) Merge remote-tracking branch 'origin/master' into t3
131e8f9c (origin/master, origin/HEAD, master) Merge pull request #3174 from LeoHChen/buffered_msgChan
033d986e (leo/buffered_msgChan) [p2p] add a buffer in msgChan
d5a3b9ce [p2p] add a counter of total p2p messages being validated
3e95ca62 [p2p] do not invalidate p2p message w/o prefix size
80456364 [log] fix nil item in errChan
1ad8b038 [p2p] not an error when the message is ignored
cc5e19cf [p2p] ignore messages not intended for leader/validator
fcb4d9d8 [consensus] count the number of handler calls
0494a0be Add slot increase for testnet
23d18906 Merge pull request #3171 from rlan35/master
e7cf038a Make EPoS compute work with correct epoch shard config …
```
> Merge master to t3 0619

- cmd/harmony/main.go
- node/node.go
- node/node_handler.go
- p2p/host.go
forget a few changes from master branch
> [bootstrap] fix bootstrap on localnet failed issue

- consensus/validator.go
- consensus/view_change.go
> Avoid validator sending msgs if the key is not in committee

- node/node.go
> [libp2p] increase semaphore number

- consensus/checks.go
- consensus/consensus_service.go
- consensus/consensus_v2.go
- consensus/quorum/quorum.go
> Add cache to validator membership check

- consensus/checks.go
- consensus/consensus.go
- consensus/consensus_service.go
- go.mod
> [consensus] replace infoMutex with atomic bool

- consensus/checks.go
- consensus/consensus_v2.go
> [log] remove cost log for each consensus message

- cmd/harmony/main.go
- go.mod
- node/node.go
- node/node_syncing.go
Tested on STN with rolling upgrade.
> [node] replace node.State with node.IsInSync atomic bool

- cmd/harmony/main.go
Need to pass by reference for the slice that's appended in a func.
> Fix slice append in multikey func

- cmd/harmony/main.go
- hmy/api_backend.go
- internal/configs/node/config.go
- internal/hmyapi/common/types.go
> [rpc] add node peer id in node metadata

- hmy/api_backend.go
- hmy/backend.go
- internal/hmyapi/apiv1/backend.go
- internal/hmyapi/apiv1/blockchain.go
- internal/hmyapi/apiv1/types.go
- internal/hmyapi/apiv2/backend.go
- internal/hmyapi/apiv2/blockchain.go
- internal/hmyapi/apiv2/types.go
- internal/hmyapi/backend.go
Continuation of #3216 , since it stopped getting latest updates to the branch.
> [RPC] Fix block "miner" field

- api/service/config.go
- cmd/harmony/main.go
- internal/configs/node/config.go
- internal/configs/node/config_test.go
- node/node.go
> [cleanup] remove unused shard client group

- api/service/explorer/service.go
- api/service/syncing/syncing.go
- cmd/harmony/main.go
- node/node.go
- node/node_syncing.go
- node/rpc.go
- node/service_setup.go
[explorer port]/node-sync
Returns `true` if in sync, `false` if not
Status code 200 if in sync, 418 if not in sync, 500 if error
Example CURL request:
```
root@245a9d7580dc:~/go/src/github.com/harmony-one/harmony# curl -I http://localhost:5099/node-sync
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 14 Jul 2020 07:52:23 GMT
Content-Length: 5
```
Also minor typo fixes & export fixes found
> [Explorer] Add explorer node in sync check

- README.md
- scripts/travis_node_checker.sh
Small nit fixes to the README and Travis node checking script.
> Small nit fixes

- node/node.go
> [p2p] ignore messages not intended for explorer nodes

- consensus/consensus_service.go
- internal/chain/reward.go
- internal/configs/sharding/mainnet.go
- internal/params/config.go
- staking/network/reward.go
- staking/network/reward_test.go
Add 5 second block and reward at epoch 230 (around July 39 Wed 2020)
Add slot increase from 480 to 640 at epoch 231 (around July 31 Fri 2020)
> Add 5 seconds block time at epoch 230 and slot increase 480->640 at epoch 231

- cmd/harmony/main.go
- node/node.go
- node/node_handler.go
> [p2p] node message validation

- node/node.go
> [p2p] propogate cross-shard node messages

- api/service/syncing/syncing.go
Fix the corner case where syncing is blocked in testnet
> [sync] fix the testnet sync issue

- consensus/consensus.go
- consensus/consensus_v2.go
- consensus/leader.go
- consensus/validator.go
The fine grained mutex logic still need more testing and debugging (https://gist.github.com/LeoHChen/bf41c25fc49236883c30e75cec38ca07). 
Reverting it for now.
> Revert to use simple mutex

- consensus/consensus_service.go
Should be checking on curEpoch to enable 5 seconds block time.
> fix 5 second duration fork

- README.md
got "Permission denied" when clone repositories.
Please make sure you have the correct access rights
and the repository exists.
````shell
git clone git@github.com:harmony-one/mcl.git
Cloning into 'mcl'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
````
Before:
After:
**NO**
3. …
> switch to https to fix "Permission denied"

- cmd/harmony/main.go
- node/node.go
- scripts/node.sh
> [p2p] forward valid commit messages by validators

- Makefile
> [build] add arm_static build target

- go.mod
> [go.mod] version upgrade of libp2p modules

- .travis.yml
- README.md
I found dangling PR on my disk related to #390 and decided to commit its parts that may still be relevant.
> .travis.yml Run tests on Ubuntu 18.04 LTS

- README.md
- scripts/go_executable_build.sh
> [build] Mac OS build using upgraded openssl library

- scripts/package/harmony-rclone.sh
- scripts/package/readme.md
> [package] specify the rclone path

- .travis.yml
- README.md
- scripts/travis_checker.sh
modify .travis.yml to integrate with codecov.io
> [travis]integrate with codecov.io

- rosetta/rosetta.go
- rosetta/services/account.go
[ #3210 ] Implements Rosetta's `/account/balance` endpoint
There is no major logic outside of existing RPC functions, so no testing file included.
> [rosetta] Implement account endpoint

- internal/params/config.go
Will upgrade testnet with this PR before epoch 36500.
> Enable redelegation and 7 epoch locking on testnet epoch 36500

- Makefile
> [Makefile] add distclean and some help info

- consensus/checks.go
- consensus/consensus.go
- consensus/consensus_service.go
- consensus/consensus_service_test.go
- consensus/consensus_v2.go
- consensus/construct.go
- consensus/construct_test.go
- consensus/debug.go
- consensus/leader.go
- consensus/view_change.go
- node/api.go
- node/node_newblock.go
- Fix ViewID function calls
- Rename SetCurViewID to SetCurBlockViewID
- Rename GetCurViewID to GetCurBlockViewID
- Rename curViewID to blockViewID
> View ID fix and rename

- consensus/consensus_viewchange_msg.go
- consensus/quorum/quorum.go
- consensus/view_change.go
- consensus/view_change_test.go
This reverts commit 9dc8f43288ae552293b9efda9adc7bce2a4db301.
> Revert "[viewchange] fix getNextLeader"

- cmd/harmony/main.go
> [misc] print Version during node bootup

- consensus/consensus_v2.go
Fix an error caused for sync_consensus_fix caused by rebasing.
> Sync consensus fix

- .gitignore
- cmd/harmony/config.go
- cmd/harmony/default.go
- cmd/harmony/flags.go
- cmd/harmony/flags_test.go
- cmd/harmony/main.go
- common/ntp/ntp.go
- common/ntp/ntp_test.go
- go.mod
- internal/configs/node/config.go
* add sys.ntp flag
* exit the node program if local time is 30 seconds off the NTP time
> [ntp] check local time against ntp server

- consensus/consensus_v2.go
> [viewchange] fix view change

- go.mod
- rosetta/common/config.go
This PR also sets the release version for the `rosetta` pkg.
> Update to v1.4.6 of Rosetta SDK

- node/node.go
- rosetta/services/construction_check.go
This PR checks if a tx (staking or cross-shard) can be submitted at the current epoch.
This will not affect any of our live networks, but it does affect any tools we build to test. Also, it makes the code complete.
> Tx submission epoch checks

- consensus/consensus_service.go
- consensus/consensus_v2.go
- consensus/construct_test.go
- consensus/quorum/one-node-one-vote.go
- consensus/quorum/one-node-staked-vote.go
- consensus/quorum/quorom_test.go
- consensus/quorum/quorum.go
- consensus/validator.go
- consensus/view_change.go
Reverts harmony-one/harmony#3419
> Revert "Fix view change stuck issue"

- consensus/consensus_service.go
- consensus/construct_test.go
- consensus/quorum/one-node-one-vote.go
- consensus/quorum/one-node-staked-vote.go
- consensus/quorum/quorom_test.go
- consensus/quorum/quorum.go
redo part of https://github.com/harmony-one/harmony/pull/3430/files
> fix self commit voting

- consensus/view_change.go
redo part of https://github.com/harmony-one/harmony/pull/3430/files
> Fix view id calc

- cmd/harmony/config.go
- cmd/harmony/default.go
- cmd/harmony/flags.go
- cmd/harmony/flags_test.go
- cmd/harmony/main.go
- consensus/consensus_service.go
- consensus/validator.go
add flag to control aggregate signature turn-on
tested on local net
> add aggregateSig flag

- consensus/view_change.go
> [log] print out view change messages

- consensus/view_change.go
> [viewchange] use last known viewID from blockchain

- consensus/consensus_service.go
- consensus/consensus_v2.go
- consensus/metrics.go
- consensus/validator.go
- consensus/view_change.go
- node/node_handler.go
```
ubuntu@ip-172-26-12-195:~$ curl -s http://localhost:9900/metrics | grep ^hmy
hmy_consensus_bingo{consensus="bingo"} 993
hmy_consensus_bingo{consensus="signatures"} 5958
hmy_consensus_finality_bucket{le="800"} 0
hmy_consensus_finality_bucket{le="1000"} 0
hmy_consensus_finality_bucket{le="1250"} 0
hmy_consensus_finality_bucket{le="1562.5"} 8
hmy_consensus_finality_bucket{le="1953.125"} 550
hmy_consensus_finality_bucket{le="2441.40625"} 889
hmy_consensus_finality_bucket{le="3051.7578125"} 896
hmy_consensus_finality_bucket{le="3814.697265625"} 896
hmy_consensus_finality_bucket{le="4768.37158203125"} 897
hmy_consensus_finality_bucket{le="5960.4644775390625"} 897
hmy_consensus_finality_bucket{le="+Inf"} 898
hmy_consensus_finality_sum 1.736376e+06
hmy_consensus_finality_count 898 …
```
> Prometheus consensus

- consensus/validator.go
Enlarge the lock scope to include the out of sync check, so when committed messages takes too long to process (due to block commit), new messages such as prepared in next round won't trigger "out of sync" check. (tested locally, it works well)
Also update some of the log levels for better debugging.
> change lock scope for validator to avoid premature sync check

- consensus/consensus_service.go
- consensus/view_change.go
- consensus/view_change_construct.go
> [viewchange] use consensus mutex, remove vc lock

- consensus/consensus_service.go
- internal/chain/reward.go
- internal/params/config.go
- staking/network/reward.go
- staking/network/reward_test.go
Add fork logic for 3s block time and updated block rewards.
> Add 3s block time and change of block reward

- cmd/harmony/main.go
- core/blockchain.go
- internal/chain/reward.go
- internal/configs/sharding/fixedschedule.go
- internal/configs/sharding/instance.go
- internal/configs/sharding/localnet.go
- internal/configs/sharding/mainnet.go
- internal/configs/sharding/pangaea.go
- internal/configs/sharding/partner.go
- internal/configs/sharding/shardingconfig.go
- internal/configs/sharding/stress.go
- internal/configs/sharding/testnet.go
- internal/params/config.go
Add the transition logic of number of blocks per epoch for localnet so it can be tested locally too.
> Cleanup sharding config code and add epoch block change for localnet

- go.mod
> [go.mod] upgrade go-libp2p to 0.12.0

- internal/configs/sharding/localnet.go
- internal/configs/sharding/mainnet.go
- internal/configs/sharding/testnet.go
- internal/params/config.go
EPOCH 432 starts around `Wed Jan 27 22:00 PDT 2021`
> [epoch] decrease internal voting power to 60%

- consensus/view_change.go
https://github.com/harmony-one/harmony/issues/3499
> [viewchange] protect startViewChange

- consensus/votepower/roster.go
Force having 70% voting power for harmony node in testnet at epoch 73314
> Recover testnet

- consensus/quorum/quorum.go
- consensus/votepower/roster.go
- hmy/staking.go
Also fix the one-off epoch issue on SuperCommittees() rpc.
> Give testnet internal node 70% voting power for stuck epochs

- rpc/eth/types.go
Our RPC:s currently return an empty string for the to/receiver field (`to: ''`) meanwhile ethers.js expects `to: null` for transactions where there's no recipient (e.g. when creating smart contracts).
> Fix to field - should return null instead of an empty string to be compatible with ethers.js

- consensus/consensus_v2.go
- consensus/quorum/one-node-staked-vote.go
- internal/chain/engine.go
also add testnet hack to workaround the stuck block with invalid signature in shard 0.
> add lastcommit sig verification in leader

- core/state_transition.go
- hmy/staking.go
Fixing: https://github.com/harmony-one/harmony/issues/3541
> fix concurrent map read issue

- rpc/blockchain.go
Some of our RPC methods currently return an error when you request blocks that haven't been finalized or which do not exist yet: `requested block number greater than current block number`.
This is inconsistent with Ethereum's RPC:s which simply return empty results (`"result": null`) when querying for non-existing blocks (https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L652-L675).
The current behavior breaks Ethereum-tooling that rely on being able to query for future blocks and retry until the expected block has been finalized, e.g: https://github.com/MetaMask/web3-provider-engine/blob/master/index.js#L134-L168
This PR:
- disables `isBlockGreaterThanLatest` checks for Ethereum RPC:s, but keeps them in place for legacy hmy_ RPC:s to ensure backwards …
> [Ethereum RPC] Do not throw errors for future blocks

- api/service/syncing/syncing.go
Shall fix issue #3547. Added an error handle logic in GetConsensusHashes in sync.
> [sync] fix #3547 runtime panic in sync module

- p2p/stream/types/stream.go
This is a breakdown PR for https://github.com/harmony-one/harmony/pull/3535. 
* Fixed the read/write method of the BaseStream.
* Updated some BaseStream method: `Close` and `ResetOnClose`.
BaseStream is the wrapper of `libp2p_network.Stream` and defines the basic read/write rules. 
* First write 4 bytes as the size of this message (uint32).
* Write the message payload to the stream.
* The message shall not exceed 20MB in size.
* First read 4 bytes as the size of this message (uint32).
* Read the bytes of exactly the size read.
* The message size shall not exceed 20MB in size.
Currently, we have an assumption that block size is smaller 2MB. Since the pub-sub message should contain the full block in announce, 2MB is the current upper limit of the block size. 
```
// p2p/host.go:70 …
```
> [stream] Fix p2p base stream read/write

- consensus/votepower/roster.go
Re-enable 40% external power for testnet from Epoch 43490
> [testnet] re-enable 40% external voting power

- internal/chain/engine.go
- node/node.go
https://github.com/harmony-one/harmony/issues/3575
> increase context timeout to recover testnet shard0

- p2p/stream/protocols/sync/client.go
- p2p/stream/protocols/sync/const.go
- p2p/stream/protocols/sync/protocol.go
Address comments in https://github.com/harmony-one/harmony/pull/3583 regarding syncprotocol module.
> [Stream] fix some sync protocol comments

- hmy/downloader/downloader.go
- hmy/downloader/longrange.go
- hmy/downloader/longrange_test.go
- p2p/stream/common/requestmanager/interface_test.go
Address some comments from https://github.com/harmony-one/harmony/pull/3584. Basically some comments updates.
Also fix a race condition in unit test.
> [stream] Fix a unit test race, resolve comments in downloader PR

- LICENSE
This is to address the issue raised in this ticket.
https://github.com/harmony-one/harmony/issues/3600
The original content is copied from https://www.gnu.org/licenses/lgpl-3.0.html
> update License to LGPL-3.0

- hmy/downloader/inserthelper.go
A small bug fix in `insertHelper` at downloader module. This bug will prevent the cache of decider being used, and increase the CPU usage during intensive block insertion.
> [stream] fix a bug in insertHelper

- hmy/downloader/beaconhelper.go
- hmy/downloader/downloader.go
- hmy/downloader/longrange.go
- hmy/downloader/longrange_test.go
- hmy/downloader/metric.go
- hmy/downloader/shortrange.go
- p2p/stream/common/ratelimiter/metric.go
- p2p/stream/common/ratelimiter/ratelimiter.go
- p2p/stream/common/streammanager/metric.go
- p2p/stream/common/streammanager/streammanager.go
- p2p/stream/protocols/sync/client.go
- p2p/stream/protocols/sync/metric.go
- p2p/stream/protocols/sync/stream.go
- p2p/stream/types/metric.go
- p2p/stream/types/stream.go
https://github.com/harmony-one/harmony/issues/3555
Added a lot of prometheus metrics to stream protocol. 
Tested locally. Also deployed to testnet. 
Following is the result metrics pulled from ${IP}:9900/metrics:
https://gist.github.com/JackyWYX/0997fa98fe8958ee6b3a58f0a5a21330
> [Stream] Prometheus metrics

- README.md
Reference to license name in README.md is out of date and should be updated to reflect the new license.
N/A
N/A
N/A
N/A
> Update license name in README.md to LGPL v3.0

- cmd/harmony/main.go
- consensus/consensus.go
- consensus/consensus_v2.go
- consensus/validator.go
- node/node_handler.go
- shard/committee/assignment.go
Remove some unused code and add a few todos for optimization (based on code in this PR https://github.com/harmony-one/harmony/pull/3612)
> clean up and todos

- consensus/quorum/one-node-staked-vote.go
> [log] remove excessive ballot log

- api/service/explorer/storage.go
explorer node indexing logic is not scalable for address with large number of txns. This change add cache so the db read on large data blob is reduced.
> Add cache for address index for explorer node

- README.md
> [readme] fix package name on ubuntu

- rpc/v1/types.go
Add the same ethHash logic in hmy v2 rpc (https://github.com/harmony-one/harmony/pull/3646) to hmy v1 rpc
> Add ethHash to hmy v1 rpc

- rosetta/common/errors.go
- rosetta/common/operations.go
- rosetta/common/operations_test.go
- rosetta/services/block.go
- rosetta/services/construction_check.go
- rosetta/services/construction_create.go
- rosetta/services/construction_create_test.go
- rosetta/services/construction_parse.go
- rosetta/services/construction_parse_test.go
- rosetta/services/construction_submit.go
- rosetta/services/mempool.go
- rosetta/services/tx_construction.go
- rosetta/services/tx_format.go
- rosetta/services/tx_format_test.go
- rosetta/services/tx_operation.go
- rosetta/services/tx_operation_components.go
- rosetta/services/tx_operation_components_test.go
- rosetta/services/tx_operation_test.go
- rpc/pool.go
- rpc/transaction.go
- rpc/v2/types.go
- staking/types/transaction.go
- test/helpers/transaction.go
This PR is to address issue #3431 
Before:
```
In file included from _cgo_export.c:4:
debugger.go:23:13: warning: unused function '_duk_debugger_attach' [-Wunused-function]
?       github.com/harmony-one/harmony/rosetta  [no test files]
ok      github.com/harmony-one/harmony/rosetta/common   0.410s  coverage: 22.9% of statements
ok      github.com/harmony-one/harmony/rosetta/services 0.787s  coverage: 43.9% of statements
```
After:
```
In file included from _cgo_export.c:4:
debugger.go:23:13: warning: unused function '_duk_debugger_attach' [-Wunused-function]
?       github.com/harmony-one/harmony/rosetta  [no test files]
ok      github.com/harmony-one/harmony/rosetta/common   1.816s  coverage: 41.4% of statements
ok      github.com/harmony-one/harmony/rosetta/services (cached) …
```
> [Rosetta] Implement Staking Transaction Construction 

- go.mod
> [go.mod] upgrade libp2p to 0.14

- api/service/legacysync/syncing.go
> [log] set noisy log message to debug level

- core/staking_verifier.go
- core/staking_verifier_test.go
- core/state_transition.go
- core/tx_pool.go
- internal/params/config.go
As per requested in the passed proposal: https://governance.harmony.one/#/staking-mainnet/proposal/Qmf5k8GH3ZBAze6uru8Qk85jpDaMjzqQbXunVXji5upg7N
> Reduce min delegation from 1000 to 100

- hmy/staking.go
- internal/params/config.go
- shard/committee/assignment.go
- staking/effective/calculate.go
- staking/effective/calculate_test.go
As requested in the passed governance proposal: https://governance.harmony.one/#/staking-mainnet/proposal/QmdmnVwW6ob5UfB9hNYxKsRXAyM52jQpNXsV5Vw4fNbiqa
> extend EPoS bound to 35%

- rosetta/infra/Dockerfile
> [docker] fix docker image build error

- rpc/staking.go
A fix to #3717 expect to fix issue #3738.
Instead of reverting the PR, let's also try fixing the issue?
> [rpc] Fix an rpc endpoint bug

- cmd/harmony/flags_test.go
- internal/configs/node/network.go
- rpc/blockchain.go
- rpc/metrics.go
Add message to metrics when rpc Access frequency exceeds limit via RPC
> [rpc] Add rate limit data to metrics

- node/node_syncing.go
Add a hard cap to getBlocks request at server end. The server will send a maximum of 4MB message over DNS sync service.
This is a temporary fix to an unusual case where a block sync request exceededing gRPC 4MB message upper limit. 
Need to be tested on server to see whether this helps a validator with old binary file (still have batch size of 15) to continue syncing.
> [SYNC] Add a hard cap to getBlocks request at server end

- node/node_syncing.go
previously crosslink broadcast is triggered even for received beacon block that's not valid.
> only broad crosslink if a new block is added to beacon chain

- consensus/view_change_construct.go
> [vc] print out size of m1 message

- consensus/leader.go
> [fix] remove double sign checking

- hmy/tracers/block_tracer.go
when call trace_block on some block, it returns error: `json: error calling MarshalJSON for type json.RawMessage: invalid character 'r' looking for beginning of object key string`.
This is due to the go version of trace module does not handle the suicide opcode correctly.
```
curl --request POST 'http://54.189.61.183:9500' --header 'Content-Type: application/json' --data-raw '{
"method": "trace_block",
"params": ["0xd6739e"],
"id": 1
}'
```
Before:
`{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"json: error calling MarshalJSON for type json.RawMessage: invalid character 'r' looking for beginning of object key string"}}
`
After:
```
{
"id": 1,
"result": [
...,
{
"blockNumber": 14054302,
"blockHash": …
```
> [tracer] fix bug of trace suicide opcode

- go.mod
> [go.mod] fixed by go mod tidy

- api/service/explorer/service.go
- api/service/legacysync/syncing.go
- hmy/downloader/downloader.go
- hmy/downloader/downloaders.go
- hmy/hmy.go
- node/node_syncing.go
- rosetta/services/network.go
- rpc/blockchain.go
Fix https://github.com/harmony-one/harmony/issues/3784
> [sync] add a tolerance number for node-sync checking

- internal/params/config.go
Epoch 631 is estimated to happen around July 7th 2021
> launch vrf and 3 governance proposal at epoch 631

- rpc/private_debug.go
- rpc/public_debug.go
- rpc/rpc.go
https://github.com/harmony-one/harmony/issues/3752
NO
NO
NO
> Add public debug api

- hmy/tracer.go
* use single Goroutines to deal trace task
* drop trace task if the request is canceled.
the trace RPC may causing higher CPU usage, especially if there are a lot of malicious transactions. 
This PR does not reduce execution time(nor does not increase it), but it does reduce CPU usage.
```
curl --request POST 'http://54.189.61.183:9500' --header 'Content-Type: application/json' --data-raw '{
"method": "trace_block",
"params": ["0xd6739e"],
"id": 1
}'
```
**NO**
8. **Does this PR introduce backward-incompatible changes *NOT* related to on-disk data structure and/or over-the-wire protocol?** (If no, continue to question …
> [tracer] optimize CPU usage of trace_block RPC

- cmd/harmony/flags.go
- cmd/harmony/flags_test.go
> fix issue 3683

- go.mod
- p2p/discovery/option.go
- p2p/discovery/option_test.go
Reword commit log history https://github.com/harmony-one/harmony/commit/1c363c73f43e319b56ec2f4720dfb489230cbfd1
> [p2p] Reduce memory and CPU usage of libp2p 

- api/service/legacysync/syncing.go
- core/state_processor.go
- internal/chain/engine.go
- internal/chain/reward.go
- test/chain/vrf/main.go
> Add logs for elapsed time for block processing; Add bls agg sig benchmark test code.

- Dockerfile
Add `go mod tidy` to Dockerfile to install go dependencies before building executables
#3806  
**NO**
6. **What are the planned flag epoch numbers and their ETAs on …
> Update Dev Docker Image

- go.mod
- p2p/discovery/option.go
- p2p/types/peerAddr.go
> [p2p] Fix libp2p version lead the consensus issue 

- rpc/harmony.go
- rpc/pool.go
https://github.com/harmony-one/watchdog/issues/31
NO
NO
NO
> add number of pending cross-shard

- core/rawdb/accessors_offchain.go
https://github.com/harmony-one/harmony/issues/2268
> [core] Fix log msg are misleading

- go.mod
- internal/configs/sharding/mainnet.go
- internal/params/config.go
> [epoch] support HIP-6 and HIP-8

- cmd/bootnode/main.go
- cmd/harmony/config_migrations.go
- cmd/harmony/default.go
- cmd/harmony/flags.go
- cmd/harmony/flags_test.go
- cmd/harmony/main.go
- internal/configs/harmony/harmony.go
- internal/configs/node/network.go
- p2p/host.go
- p2p/security/security.go
- p2p/security/security_test.go
- test/deploy.sh
[BOUNTY]
https://github.com/harmony-one/bounties/issues/66
**NO**
Note that this must be enough …
> [BOUNTY]Feat: mitigate single-Host P2P sybil attack

- rpc/rpc.go
remove private method from public port and add public method to private port
> add public method to private port

- cmd/harmony/config_migrations.go
- cmd/harmony/default.go
- cmd/harmony/flags.go
- cmd/harmony/flags_test.go
- cmd/harmony/main.go
- internal/configs/harmony/harmony.go
- internal/configs/node/config.go
- internal/configs/node/network.go
- rpc/rpc.go
https://github.com/harmony-one/harmony/issues/3931
NO
NO
NO
> add auth-ws port

- p2p/security/security.go
> [log] log too much peers

- rpc/rpc.go
> [rpc] align public rpc method to the private rpcs

- consensus/validator.go
Fix nil pointer issue when the node is running as non-validating nodes.
> fix block decode bug and add more nil check

- rpc/blockchain.go
- rpc/metrics.go
add a new rpc method to return raw header in hex(rlp(header)) format
> add GetHeaderByNumberRLPHex and GetProof to rpc

- api/service/legacysync/syncing.go
Remove two unnecessary use of global mutex at StateSync. Use a local mutex instead. This is suspect to cause the sync loop stuck issue
Passed local tests.
> [sync] remove two unnecessary use of global mutex in StateSync

- internal/configs/node/network.go
> [pstn] fix the hardcode partner network bootnode

- consensus/consensus_v2.go
Previously, the committed message is only sent out after the leader successfully inserted the block into chain DB. If the leader has trouble inserting the block into DB, then the committed message would be delayed which could lead to validators believing the leader is malfunctioning and starting view change prematurely.
The better way to do this is to send out the committed message before doing block insertion, which totally makes sense because it's never a bad idea to send out 2/3 committed message as soon as they are collected. This PR does that so block insertion wouldn't mess up the committed message broadcasting.
> send committed message before block insertion

- cmd/harmony/main.go
- internal/chain/sig.go
- rpc/blockchain.go
- rpc/metrics.go
> exit after revert

- cmd/harmony/main.go
> [revert] exit after revert is done

- node/node.go
> [log] set adding tx to debug level

- consensus/consensus_v2.go
- consensus/view_change_construct.go
- node/node_newblock.go
Send 2/3 commit before block insertion in final commit; do not include txns in epoch block.
And revert https://github.com/harmony-one/harmony/commit/79947fb167a514035eb907d7bda187c86d9b7e9c
> Send 2/3 commit before block insertion in final commit; do not include txns in epoch block

- consensus/checks.go
- consensus/consensus_v2.go
- consensus/validator.go
- consensus/view_change.go
- core/tx_pool.go
- node/node.go
- node/node_newblock.go
merge v4 branch into main branch
> Merge v4 to main

- go.mod
- rosetta/rosetta.go
> [rosetta] update rosetta sdk to 0.7.0

- rosetta/infra/harmony-pstn.conf
add a sample harmony.conf file
to support explorer nodes on PSTN
> [config] add harmony.conf for pstn

- rosetta/infra/Dockerfile
> [rosetta] copy config file to final image

- internal/params/config.go
The epoch 871 happens around Tue Feb 11 2022.
> enable staking precompile at epoch 871 on mainnet

- core/rawdb/accessors_offchain.go
Fixed an issue that could cause prune to get stuck (too much data compact once)
> Fix pruner bug

- api/service/prometheus/service.go
- core/blockchain.go
- core/headerchain.go
- p2p/host.go
- p2p/metrics.go
https://github.com/harmony-one/harmony/issues/4008
* chain/head/block
* chain/head/header
* chain/head/receipt
* chain/account/reads
* chain/account/hashes
* chain/account/updates
* chain/account/commits
* chain/storage/reads
* chain/storage/hashes
* chain/storage/updates
* chain/storage/commits
* chain/inserts
* chain/validation
* chain/execution
* chain/write
* p2p/ingress
* p2p/egress
> Ethereum compatible metrics

- cmd/harmony/config.go
- cmd/harmony/default.go
- go.mod
- hmy/downloader/downloader.go
- hmy/downloader/shortrange.go
- p2p/stream/common/streammanager/cooldown.go
- p2p/stream/common/streammanager/streammanager.go
- p2p/stream/types/stream.go
Enable default config to turn on stream protocol at localnet and testnet. Also with some bug fixes.
```
Default Testnet:
sync.server = true
sync.client = false
dnsSync.server = true 
dnsSync.client = true
Localnet
sync.Enabled = true
sync.Downloader = true
dnsSync.server = true
dnsSync.client = true
```
Passed all unit tests and local tests. Run on stressnet (resource limited) for a while, and need to have it roll out in testnet.
> [stream] Enable downloader

- hmy/staking.go
- staking/availability/measure.go
- staking/types/validator.go
https://github.com/harmony-one/harmony/issues/4014
> Add epoch, block number to hmyv2_getValidatorInformation response

- hmy/staking.go
Incorrect response for block and epoch.
> Fix Stacking response.

- hmy/tracer.go
> [tracer] fix tracer crash

- internal/chain/reward.go
Refactored `accumulateRewardsAndCountSigs` function. This is somewhat essential before implementing dynamic rewards since the forks would lead to an unreadable code.
Manual tested, by logging both the old and new implementation inside the code and asserting that nothing has changed. 
Before refactoring: https://gist.github.com/pkakelas/73974af3b68b95482984bdbffa3edad0
After refactoring: https://gist.github.com/pkakelas/318445f508806a2f8540b903a8899e93
Nothing is affected
1. **Does this PR introduce backward-incompatible changes to the on-disk data structure and/or the over-the-wire protocol?
**NO**
**NO**
9. **Does the …
> Refactor AccumulateRewardsAndCountSigs

- rpc/filters/filter.go
> fix log range limit

- internal/params/config.go
Updated chain-id fixes epoch number for test net
> changed chain-id fixes epoch number for test net

- scripts/travis_rpc_checker.sh
fix travis_rpc_checker script that submitted by mistake in #4181.
> recover the travis_rpc_checker script

- internal/params/config.go
Before:
```
```
After:
```
```
**YES|NO** …
> ChainIdFixEpoch, CrossShardXferPrecompileEpoch, AllowlistEpoch : 75907

- consensus/quorum/one-node-one-vote.go
- consensus/quorum/one-node-staked-vote.go
- consensus/quorum/one-node-staked-vote_test.go
- consensus/quorum/quorum.go
- consensus/quorum/verifier.go
- consensus/validator.go
- consensus/view_change.go
- consensus/view_change_construct.go
- internal/chain/engine.go
- internal/configs/sharding/testnet.go
- node/node_explorer.go
- staking/verify/verify.go
Testnet failed to propose the last block of epoch 75893. It stopped at 26481646, and the last block of epoch 75893 is 26481647. 
Increase voting power of harmony nodes in testnet to 0.7
> Increase voting power of harmony nodes in testnet to 0.7

- core/tx_pool.go
- core/tx_pool_test.go
- hmy/gasprice.go
- hmy/hmy.go
- internal/utils/singleton.go
- node/worker/worker.go
- rosetta/services/construction.go
- rpc/harmony.go
Increase suggested gas to be 70 percentile and max suggested gas to 1000 gwei.
Reduce block gas limit to be 30M.
> Increase suggested gas and reduce block gas limit

- core/epochchain.go
- core/rawdb/accessors_chain.go
- p2p/stream/protocols/sync/chain.go
> [core] Epoch chain: update reference to head block - fix s0 redownload issue

- core/blockchain_impl.go
Before:
```
```
After:
```
```
**YES|NO** …
> Fix epoch sync.

- cmd/harmony/config_migrations.go
> Fix migration version.

- hmy/hmy.go
- hmy/staking.go
- rpc/metrics.go
- rpc/staking.go
GetValidatorsStakeByBlockNumber calculates each validator's total
delegation at the specified block.
> [rpc] add GetValidatorsStakeByBlockNumber

- core/blockchain_impl.go
- internal/tikv/redis_helper/lock.go
> Fix staking bug in elastic rpc mode

- node/api.go
- p2p/host.go
Fix race error and code style.
> Fix race error and code style.

- core/blockchain_impl.go
- core/evm_test.go
- core/tx_pool_test.go
- internal/shardchain/shardchains.go
- node/worker/worker_test.go
- test/chain/main.go
- test/chain/reward/main.go
Removed shouldPreserve dead code.
> Removed shouldPreserve dead code.

- cmd/harmony/main.go
- consensus/consensus.go
- consensus/consensus_service_test.go
- consensus/consensus_test.go
- consensus/construct_test.go
- core/blockchain.go
- core/blockchain_impl.go
- core/blockchain_stub.go
- node/node.go
- node/node_cross_link.go
- node/node_cross_shard.go
- node/node_handler.go
- node/node_handler_test.go
- node/node_newblock_test.go
- node/node_test.go
This feature allows consensus accept `blockchain` as a parameter, so it removes double initialization like 
`currentConsensus.Blockchain = currentNode.Blockchain()` and makes code more clean. I need this feature for future resharding.
> Consensus accepts blockchain as a parameter.

- hmy/downloader/downloader.go
- rpc/harmony.go
> [rpc] query node for syncing calls

- cmd/harmony/main.go
- node/node.go
Issue raised here: https://github.com/harmony-one/harmony/pull/4296/files/1ebc0a4731f4fc5e4b785c9893eac0207dc85edb#r1057475792
> Fix not disable cache in archival mode

- cmd/harmony/main.go
- consensus/consensus.go
- consensus/consensus_service.go
- consensus/consensus_test.go
- consensus/consensus_v2.go
- consensus/double_sign.go
- consensus/downloader.go
- consensus/leader.go
- consensus/threshold.go
- consensus/validator.go
- consensus/view_change.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- node/node.go
- node/node_handler.go
- node/node_handler_test.go
- node/node_newblock_test.go
- node/node_test.go
Registry for services. First moved `core.Blockchain`, because node can change it's shard during epoch change.
> Feature registry

- api/service/legacysync/epoch_syncing.go
- api/service/legacysync/helpers.go
- api/service/legacysync/syncing.go
- api/service/legacysync/syncing_test.go
- api/service/stagedsync/stagedsync.go
- api/service/stagedsync/sync_config.go
- cmd/harmony/main.go
- node/node.go
- node/node_syncing.go
- node/node_test.go
> fix self query issue

- .github/workflows/ci-tag.yaml
- .github/workflows/ci.yaml
- scripts/docker/Dockerfile
- fix issue https://github.com/harmony-one/harmony/actions/runs/4014263067/jobs/6894656037
- update github action tasks
github action run showing the build now works (only the push to the harmony docker repo is failing since it is done from my personal account)
https://github.com/sophoah/harmony/actions/runs/4023250279/jobs/6914199451
> [devops] Update Dockerfile and github action

- api/service/explorer/schema.go
- api/service/explorer/storage.go
- go.mod
- go.sum
- scripts/go_executable_build.sh
Wrapped Bitmap in thread safe struct.
> Fixed Bitmap race error.

- consensus/consensus_v2.go
- consensus/quorum/quorum.go
- consensus/view_change.go
Shards 1-3 will rotate all validators.
> Feature rotate external validators.

- cmd/harmony/config_migrations_test.go
- cmd/harmony/config_test.go
- cmd/harmony/default.go
- cmd/harmony/flags_test.go
Reverts harmony-one/harmony#3894
> Revert "Turn pprof default on with local saved files"

- internal/params/config.go
Epoch 1451 begins on 2023-05-17 04:02:00+00:00
> internal/params: schedule HIP28v2 + val code fix for mainnet

- core/tx_pool_test.go
- go.mod
- go.sum
Before:
```
```
After:
```
```
**YES|NO** …
> Dev fix conflicts.

- scripts/docker/Dockerfile
> Remove dockerfile hardcoded version numbers

- core/state/state_object.go
- internal/params/config.go
and add logs to help debug the recent consensus loss
> internal/params: un-schedule mainnet hard forks

- core/block_validator.go
- internal/chain/reward.go
- node/worker/worker.go
- test/chain/chain/chain_makers.go
- test/chain/main.go
Before:
```
```
After:
```
```
**YES|NO** …
> Use Header instead Block. 

- api/service/stagedstreamsync/downloader.go
- api/service/stagedstreamsync/downloaders.go
- api/service/stagedstreamsync/service.go
- api/service/stagedstreamsync/syncing.go
- api/service/stagedsync/stage_blockhashes.go
- api/service/stagedsync/stage_bodies.go
- api/service/stagedsync/syncing.go
- cmd/harmony/main.go
- node/node_syncing.go
This PR moves cache folder under data folder. That helps to have more organized folder structure and have all db stuff in one place.
> change cache folder path for sync and move it under data folder

- api/service/stagedstreamsync/block_manager.go
- api/service/stagedstreamsync/stage_bodies.go
Before:
```
```
After:
```
```
**YES|NO** …
> Fix panic.

- internal/params/config.go
> internal/params: schedule HIP28 and val code fix

- internal/params/config.go
- scripts/docker/Dockerfile
> Release Candidate 2023.2.4 - HIP28 hardfork schedule

- consensus/checks.go
- consensus/consensus.go
- consensus/consensus_service.go
- consensus/consensus_test.go
- consensus/consensus_v2.go
- consensus/double_sign.go
- consensus/fbft_log.go
- consensus/leader.go
- consensus/threshold.go
- consensus/validator.go
- consensus/view_change.go
- consensus/view_change_msg.go
- node/node_explorer.go
Fixed concurrent map access in FBFTLog https://github.com/harmony-one/harmony/issues/4468
> Fixed concurrent map access in FBFTLog

- consensus/consensus_service.go
- consensus/construct.go
- consensus/view_change_construct.go
- consensus/view_change_msg.go
- core/state/journal.go
- crypto/bls/mask.go
- crypto/bls/mask_test.go
- hmy/blockchain.go
- internal/chain/sig.go
- staking/availability/measure.go
NewMask doesn't accept `myKey` anymore.
> Consensus Mask. Removed unnecessary argument.

- api/service/stagedstreamsync/const.go
- api/service/stagedstreamsync/default_stages.go
- api/service/stagedstreamsync/downloader.go
- api/service/stagedstreamsync/downloaders.go
- api/service/stagedstreamsync/service.go
- api/service/stagedstreamsync/short_range_helper.go
- api/service/stagedstreamsync/stage_bodies.go
- api/service/stagedstreamsync/stage_epoch.go
- api/service/stagedstreamsync/stage_lastmile.go
- api/service/stagedstreamsync/stage_short_range.go
- api/service/stagedstreamsync/stage_state.go
- api/service/stagedstreamsync/staged_stream_sync.go
- api/service/stagedstreamsync/stages.go
- api/service/stagedstreamsync/syncing.go
- api/service/stagedsync/stagedsync.go
- api/service/stagedsync/syncing.go
- cmd/harmony/default.go
- cmd/harmony/main.go
- consensus/consensus_v2.go
- consensus/validator.go
- internal/configs/harmony/harmony.go
- internal/configs/node/config.go
- node/node_syncing.go
- p2p/stream/protocols/sync/protocol.go
This PR improves the stream sync on the items below:
- improves the short range stage
- improves the epoch sync stage
- adds the last mile stage to staged stream sync
- adds Debug logs to  staged stream sync
- removes redundant stage executions
- addresses the issue for one of the dev-net nodes.
> Improve staged stream sync, fix the devnet node stuck issue

- core/genesis.go
- core/preimages.go
- core/state_processor.go
- internal/params/config.go
Before:
```
```
After:
```
```
**YES|NO** …
> Hip30/testing minor fixes.

- internal/configs/sharding/partner.go
We will have to reset devenet again
> Reduce the epoch time devnet

- cmd/harmony/main.go
- consensus/consensus.go
- consensus/consensus_v2.go
- consensus/quorum/quorum.go
- internal/utils/math.go
Checks last 10 blocks. If no sigs from future leader - skip.
> Leader rotation. Check next leader aliveness.

- internal/params/config.go
> Activate external rotation devnet.

- internal/params/config.go
activate leader rotation at epoch 4.
> Devnet: activate leader rotation at epoch 4 .

- core/blockchain_impl.go
Removes blocks from blockchain, rewrites reference to head block.
> Fix for revert.

- internal/params/config.go
Missed the window I'll have to push it a little bit
> push the activation of the external devnet epoch

- cmd/harmony/config.go
- cmd/harmony/config_migrations.go
- cmd/harmony/default.go
- cmd/harmony/flags.go
- cmd/harmony/flags_test.go
- cmd/harmony/main.go
- core/blockchain_impl.go
- internal/configs/harmony/harmony.go
- internal/shardchain/shardchains.go
The snapshot creation was broken due to an incorrect root hash. This PR addresses that issue and also adds a new configuration section for cache settings.
> Fix snapshot creation, add snapshot configurations

- internal/params/config.go
Pushing this to give validators enough time to join the test
> push devnet external and leader rotation epochs

- consensus/fbft_log.go
- consensus/view_change_msg.go
Added new filter condition to skip invalid blocks.
> Get only valid blocks.

- consensus/fbft_log.go
- consensus/view_change_msg.go
This reverts commit f0dc999e1bed55b1a08749b99303f0336164ed5e.
> Revert "Get only valid blocks. (#4628)"

- consensus/leader.go
Provides leader metrics for sigs count
> Leader sigs count for prometheus. 

- internal/params/config.go
Enabling leader rotation and the externalization of testnet.
> Enable testnet leader rotation and external

- internal/configs/sharding/partner.go
https://github.com/harmony-one/harmony/issues/4654
> Update devnet internal vote power back to 90%

- cmd/bootnode/main.go
Before:
```
```
After:
```
```
**YES|NO** …
> Feature: pprof bootnode

- consensus/validator.go
Force sync when view change and received message with higher height.
> Force sync when view change and received message with higher height.

- core/preimages.go
Before:
```
```
After:
```
```
**YES|NO** …
> fix: close file

- cmd/harmony/main.go
- go.mod
- go.sum
- internal/registry/registry.go
- node/addresses.go
- node/node.go
- node/node_handler.go
- node/node_newblock.go
- shard/shard_state.go
Extracted `GetAddressForBLSKey` from `Node`.
> Extracts `GetAddressForBLSKey` functionality from `Node` struct.

- cmd/bootnode/main.go
This PR adds a flag to set Muxer for bootnode.
> add muxer to bootnode flags

- internal/params/config.go
Before:
```
```
After:
```
```
**YES|NO** …
> HF activation epoch for MaxRateEpoch .

- internal/params/config.go
Before:
```
```
After:
```
```
**YES|NO** …
> HF activation epoch for TopMaxRateEpoch

- cmd/bootnode/main.go
- internal/configs/node/network.go
This PR enables p2p transport security by default.
> Enable p2p transport security by default

- core/evm.go
> Fixed condition which is always true.

- .travis.yml
This PR replicates travis fix for hotfix branch.
> replicate travis fix for main_hotfix branch

- node/node.go
Before:
```
```
After:
```
```
**YES|NO** …
> Genesis block hash log.

- staking/availability/measure_test.go
> Fixed failing tests.

- core/blockchain_impl.go
- node/harmony/node_cross_link.go
This PR adds a mutex for crosslink retrieving and refactors max crosslinks handling.
> Improve Crosslinks Retrieving and Processing

- .github/workflows/build-docker-proto-image.yaml
- .github/workflows/ci-tag.yaml
- .github/workflows/ci.yaml
[4774](https://github.com/harmony-one/harmony/pull/4774) - [ci] upgrade github actions and merge artifacts
> v2024.3.1 - [ci] upgrade github actions and merge artifacts

- Makefile
- cmd/config/config.go
- cmd/config/config_migrations.go
- cmd/config/default.go
- cmd/config/flags.go
- cmd/config/flags_test.go
- cmd/harmony/main.go
- consensus/quorum/one-node-staked-vote_test.go
- consensus/votepower/roster_test.go
- core/state_transition_test.go
- internal/configs/harmony/harmony.go
- internal/configs/node/config_test.go
- internal/configs/node/network.go
- internal/configs/sharding/localnet.go
- internal/configs/sharding/localnet_config.go
- internal/configs/sharding/localnet_test.go
- staking/reward/values.go
- test/debug.sh
- test/deploy.sh
This PR adds a new config to adjust localnet blocks per epoch.
config file 2.6.4 added for localnet configuration
> Add Localnet Config to Adjust Blocks per Epoch

- p2p/host.go
This PR introduces a conditional inclusion of the Resource Manager in P2P configurations, ensuring it is added only when explicitly enabled.
> Add Resource Manager to P2P Configs When Enabled

- Makefile
- README.md
This pull request enhances the `README.md` by adding configuration instructions tailored for macOS users. These additions aim to streamline the setup process for developers on macOS, ensuring a smoother onboarding experience. By providing clear guidance specific to macOS, the update addresses potential setup challenges and contributes to a more efficient development workflow.
> Add MacOS configurations to Readme.md 

- api/service/stagedstreamsync/download_manager.go
- api/service/stagedstreamsync/download_manager_test.go
- api/service/stagedstreamsync/errors.go
- api/service/stagedstreamsync/stage_blockhashes.go
- api/service/stagedstreamsync/stage_bodies.go
- api/service/stagedstreamsync/stage_receipts.go
- api/service/stagedstreamsync/stage_states.go
- api/service/stagedstreamsync/stage_statesync.go
- api/service/stagedstreamsync/stage_statesync_full.go
- api/service/stagedstreamsync/state_download_manager.go
- api/service/stagedstreamsync/state_sync_full.go
- api/service/stagedstreamsync/syncing.go
This PR refactors the initialization process for stage block hashes, improving clarity and efficiency. It addresses a nil pointer issue that previously caused failures in final block hash calculations, ensuring more robust handling of edge cases. Additionally, it enhances the management of stream removals, reducing inconsistencies and improving stability.  
The download manager has been restructured to handle the current height internally, simplifying its logic and reducing redundant state tracking. This update optimizes the block bodies stage by introducing a dedicated thread for reading hashes from the database, significantly improving performance and concurrency.
> Optimize Staged Stream Sync Block Download Process and Improve Stage Hash Handling

- api/service/stagedstreamsync/stage_bodies.go
This PR improves the redownloadBadBlock function by introducing a structured retry mechanism, better error handling, and fixes the bad block saving issue.
> Enhance Bad Block Re-download with Retry Logic, Stream Tracking & Error Handling

- api/service/stagedstreamsync/downloader.go
This PR refactors the staged stream sync downloader's sync loop to enhance concurrency, remove sync overlaps caused by multiple downloader triggering. To remove the sync overlaps, if the node is syncing and the ticker fires, the trigger will attempt to queue another sync, but only if no sync is already in progress. But, if a sync is running, the trigger does nothing at that moment, avoiding unnecessary sync overlap.
> Refactor Staged Stream Sync Downloader Loop, Remove Sync Overlaps

- api/service/stagedstreamsync/stage_blockhashes.go
- api/service/stagedstreamsync/stage_bodies.go
- api/service/stagedstreamsync/stage_states.go
- api/service/stagedstreamsync/staged_stream_sync.go
- api/service/stagedstreamsync/syncing.go
- p2p/stream/types/stream.go
This PR enhances Stream Management by implementing a reconnection mechanism and optimizing buffer and memory usage. Key improvements include:  
- **Reconnection Logic:** Streams now supports reconnecting function. Later we use this function to attempt to reconnect up to 3 times with a few seconds interval between attempts before failing.  
- **Memory Optimization:** Improved buffer pooling to reduce unnecessary allocations and enhance performance.  
- **Block Request Timeout:** Increased timeout for Block Requests in stream sync to fix context deadline issue.  
- **Unexpected Block Handling:** Added validation for unexpected blocks in the database and ensured proper head adjustments.  
- **Estimate Current Number:** Minor optimization for more accurate block height estimation in long …
> Enhance Stream Handling, Fix Streamnet Sync Issues

- consensus/consensus.go
- consensus/consensus_block_proposing.go
- consensus/consensus_service.go
- consensus/consensus_v2.go
- consensus/construct.go
- consensus/post_processing.go
- consensus/proposer.go
- consensus/threshold.go
- consensus/validator.go
- consensus/view_change.go
- internal/utils/timer.go
- internal/utils/timer_test.go
Feature/improved consensus logging
> Improved consensus logging

- consensus/consensus_service.go
- consensus/consensus_test.go
- consensus/debug.go
- consensus/state.go
- consensus/threshold.go
- consensus/view_change.go
- consensus/view_change_test.go
- node/harmony/api.go
Removed locks from GetLogger method.
> Removed locks from GetLogger method.

- api/service/stagedstreamsync/adapter.go
- api/service/stagedstreamsync/block_by_hash_manager.go
- api/service/stagedstreamsync/block_by_hash_manager_test.go
- api/service/stagedstreamsync/download_manager.go
- api/service/stagedstreamsync/download_manager_test.go
- api/service/stagedstreamsync/downloader.go
- api/service/stagedstreamsync/errors.go
- api/service/stagedstreamsync/memory_leak_test.go
- api/service/stagedstreamsync/short_range_helper.go
- api/service/stagedstreamsync/stage_blockhashes.go
- api/service/stagedstreamsync/stage_bodies.go
- api/service/stagedstreamsync/stage_epoch.go
- api/service/stagedstreamsync/stage_finish.go
- api/service/stagedstreamsync/stage_short_range.go
- api/service/stagedstreamsync/stage_states.go
- api/service/stagedstreamsync/staged_stream_sync.go
- api/service/stagedstreamsync/syncing.go
- node/harmony/node.go
- p2p/host.go
- p2p/stream/common/streammanager/streammanager.go
- p2p/stream/protocols/sync/protocol.go
This pull request introduces a series of significant improvements to the staged stream sync subsystem, focusing on robustness, maintainability, and clarity. The changes address several edge cases and operational pain points observed during localnet and devnet testing, particularly around block and signature validation, stream management, and the handling of bad or missing data from peers.
The error handling logic has been refactored to provide more granular responses to different failure scenarios, distinguishing between protocol errors, empty or malformed responses, and partial or missing data. Logging has been enhanced throughout the sync pipeline, making it easier to diagnose issues and trace the source of failures. The management of bad blocks and redownload attempts is now more …
> StagedStreamSync: Robustness Improvements, Refactoring, and Enhanced Error Handling
