harmony-one/harmony

.gitmodules

Peg at commit 8d0c54c1246661d9a51ca0ba455d22116d485eaa in order to avoid
https://github.com/golang/protobuf/issues/763.

Vendor github.com/golang/protobuf

---

README.md

Fixing a small typo so that the correct scripts directory is referenced when building.

Fix README.md to reference scripts correctly

---

scripts/travis_checker.sh

use -count=1 to disable test cache. This is useful, especially in the local test.

be verbose in travis checker

---

cmd/client/txgen/main.go

My recent test had got consensus on 3 shards testing on AWS.
```
3 shards, 1535 consensus, 610 total TPS, 165 nodes
3.90.6.34, 530, 221.398
34.219.212.230, 509, 201.104
34.240.197.109, 496, 188.317
```

reduce wait to join shard

---

.travis.yml

The Go installation (gimme) step of Travis-CI is super slow (~3m),
because we use master version of Go, which gimme needs to
download/compile/install out of the Git repository.
Use stable instead of master, which lets gimme to download/install the
binary version (if available), of the latest stable release, and fall
back to source only if that fails.

Fetch and use (“gimme”) stable Go, not master

---

.gitmodules

Kyber is going through version 3 release process, in which they are
switching to being a full module and requiring the import path to be
go.dedis.ch/kyber. This breaks fresh installs and likely CI builds too.
Peg at the version right before the modularization so that our code (yet
to be adjusted for the new import path) continues to build.
This is a temporary bandaid.  We will be getting rid of Kyber soon in
favor of https://github.com/herumi/bls.

Vendor Kyber at pre-modularization

---

.travis.yml

Currently we get an import problem for forks, for example “someone-else/harmony”.  Travis-CI job set up for such a fork will check out the repo under GOPATH/src/github.com/someone-else/harmony, importable as `"github.com/someone-else/harmony"` and not as the intended `"github.com/harmony-one/harmony"`.
Recording the canonical import path (go_import_path) in .travis.yml lets Travis-CI check out the repo under GOPATH/src always using the canonical import path, resolving build issues for forks.

Make Travis-CI use the canonical import path

---

api/proto/node/pingpong_test.go
node/node_test.go
p2p/p2p.go

Originally #320, which can't go through 'cause it somehow doesn't trigger Travis-CI builds anymore.

Remove deprecated ready field

---

internal/utils/utils.go
internal/utils/utils_test.go

```
PASS
coverage: 49.2% of statements
ok      github.com/harmony-one/harmony/internal/utils   1.395s
```

add util functions to convert p2p private keys to/from base64 string

---

api/proto/common.go
api/proto/discovery/pingpong.go
api/proto/discovery/pingpong_test.go
api/proto/node/node.go
consensus/consensus.go
node/node.go
node/node_handler.go
node/node_test.go

This is needed for the new peer discovery enabled by libp2p
I am adding new peerdiscovery service and will use pingpong messages
```
PASS
coverage: 87.5% of statements
ok      github.com/harmony-one/harmony/api/proto/discovery      0.066s
```
run "./test/deploy.sh test/configs/local_config1.txt" locally and got the consensus working fine.
====== RESULTS ======
++ ./test/../test/cal_tps.sh tmp_log/log-20190130-224854/all-leaders.txt tmp_log/log-20190130-224854/all-validators.txt
+ results='2 shards, 45 consensus, 105 total TPS, 11 nodes
127.0.0.1, 23, 51.8767'
+ echo 2 shards, 45 consensus, 5 total TPS, 11 nodes 127.0.0.1, 23, 51.8767
+ tee -a tmp_log/log-20190130-224854/r.log
2 shards, 45 consensus, 105 total TPS, 11 nodes …

move proto/pingping to discovery module

---

cmd/bootnode/main.go
internal/utils/flags.go
internal/utils/flags_test.go

2019/01/29 20:16:16 No priviate key can be loaded from filekeyfile/tmp/please_ignore_the_non-exist_file
2019/01/29 20:16:16 Using random private key
PASS
coverage: 74.8% of statements
ok      github.com/harmony-one/harmony/internal/utils   1.057s
[20:16] ec2-user @ leo-cloud: ~/go/src/github.com/harmony-one/harmony/internal/utils [bootnode]: Added
$ mv /tmp/flags* .
[20:16] ec2-user @ leo-cloud: ~/go/src/github.com/harmony-one/harmony/internal/utils [bootnode]: Added
2019/01/29 20:16:27 No priviate key can be loaded from filekeyfile/tmp/please_ignore_the_non-exist_file
2019/01/29 20:16:27 Using random private key
PASS
coverage: 76.0% of statements
ok      github.com/harmony-one/harmony/internal/utils   1.459s

Add addrlist in utils for bootnode

---

cmd/harmony.go
node/node.go

enable consensus service in service manager
====== RESULTS ======
++ ./test/../test/cal_tps.sh tmp_log/log-20190130-160304/all-leaders.txt tmp_log/log-20190130-160304/all-validators.txt
+ results='2 shards, 128 consensus, 386 total TPS, 11 nodes
127.0.0.1, 64, 195.656'
+ echo 2 shards, 128 consensus, 386 total TPS, 11 nodes 127.0.0.1, 64, 195.656
+ tee -a tmp_log/log-20190130-160304/r.log
2 shards, 128 consensus, 386 total TPS, 11 nodes 127.0.0.1, 64, 195.656
+ echo 2 shards, 128 consensus, 386 total TPS, 11 nodes 127.0.0.1, 64, 195.656
Not applied.
* Before
* After
https://gist.github.com/mikedoan/3e84bf02c2af713b17f060cf0a6156f3
NA

enable consensus service in service manager

---

.gitignore
.gitmodules
api/service/discovery/discovery_test.go
api/service/discovery/errors.go
api/service/discovery/service.go
api/service/manager.go
internal/utils/flags.go
p2p/host/hostv2/hostv2.go

https://github.com/harmony-one/harmony/issues/373
This is the first step to add the discovery service in the new service framework. The discovery service is not enabled yet.
* Before
n/a
* After
```
PASS
coverage: 9.8% of statements
ok      github.com/harmony-one/harmony/api/service/discovery    0.240s
```
Passed local travis_checker.go.  Haven't enabled the peer discovery service in harmony.go.
Enable and integrate peer discovery service into harmony.go.

Add peer discovery service

---

api/service/manager.go
api/service/networkinfo/service.go
api/service/staking/service.go
node/node.go

https://github.com/harmony-one/harmony/issues/368
NA
++ ./test/../test/cal_tps.sh tmp_log/log-20190204-141654/all-leaders.txt tmp_log/log-20190204-141654/all-validators.txt
+ results='2 shards, 96 consensus, 503 total TPS, 11 nodes
127.0.0.1, 73, 293.412'
+ echo 2 shards, 96 consensus, 503 total TPS, 11 nodes 127.0.0.1, 73, 293.412
+ tee -a tmp_log/log-20190204-141654/r.log
2 shards, 96 consensus, 503 total TPS, 11 nodes 127.0.0.1, 73, 293.412
+ echo 2 shards, 96 consensus, 503 total TPS, 11 nodes 127.0.0.1, 73, 293.412

adding more services: staking, networkinfo and wired-up logic

---

api/service/discovery/service.go

Without this, the `foundPeers()` goroutine will enter a tight infinite loop when the DHT query ends and the peer channel gets closed, as `<-s.peerChan` will immediately return a zero-valued PeerInfo.

Handle peer channel closure gracefully

---

cmd/harmony.go
scripts/go_executable_build.sh
test/deploy.sh

#373 
the original test/deploy.sh works fine.  I just added a new parameter "-P" to enable libp2p peer discovery test.
Also, for harmony.go, I added a parameter -libp2p_pd for testing as well.

Enable libp2p peer discovery and test

---

api/service/discovery/service.go
cmd/harmony.go
node/node.go

add networkinfo/discovery service to beacon chain roles
During the bootstrap process, we need to indicate the node is a beacon chain node.
Thus, we introduce a flag as an indicator.
local travis_checker, build, and test passed.

add isBeacon flag to specify the node is a beacon chain node

---

.gitignore
cmd/client/txgen/main.go
cmd/harmony.go

support libp2p peer discovery in txgen
#373 
local build, travis_checker passed.
I also tested using bootnode/beacon node, the txgen can connect to boot node.

Add libp2p peer discovery to txgen

---

node/node_handler.go

Jenkins test reported a crash on integer divide by zero.
17:18:45 panic: runtime error: integer divide by zero
17:18:45 
17:18:45 goroutine 3843 [running]:
17:18:45 github.com/harmony-one/harmony/node.(*Node).messageHandler(0xc0014b8200, 0xc0011d8d9c, 0x3, 0x3)
17:18:45 	/mnt/jenkins/workspace/auto-benchmark/node/node_handler.go:161 +0x1884
17:18:45 github.com/harmony-one/harmony/node.(*Node).StreamHandler(0xc0014b8200, 0x7fe7b0499170, 0xc0021c8ee0)
* Before
* After
local build passed

[FIX] integer divide by zero error

---

api/service/staking/service.go
node/contract.go
node/node.go

call a request to beacon to get nonce & create staking transaction
NA 
14968 Done                    | tee -a $LOG_FILE
+ rm -rf ./db/harmony_127.0.0.1_9000 ./db/harmony_127.0.0.1_9001 ./db/harmony_127.0.0.1_9002 ./db/harmony_127.0.0.1_9003 ./db/harmony_127.0.0.1_9004 ./db/harmony_127.0.0.1_9005 ./db/harmony_127.0.0.1_9006 ./db/harmony_127.0.0.1_9007 ./db/harmony_127.0.0.1_9008 ./db/harmony_127.0.0.1_9009 ./db/harmony_127.0.0.1_9010 ./db/harmony_127.0.0.1_9011 ./db/harmony_127.0.0.1_9012
./test/deploy.sh: line 21: 14970 Killed: 9               $DRYRUN $ROOT/bin/harmony -ip $ip -port $port -log_folder $log_folder $DB -min_peers $MIN $HMY_OPT $HMY_OPT2 -key /tmp/$ip-$port.key 2>&1
14971 Done                    | tee -a $LOG_FILE
+ check_result
+ find tmp_log/log-20190208-230443 -name …

call a request to beacon to get nonce & create staking transaction

---

README.md
scripts/setup_bls_build_flags.sh

`DYLD_LIBRARY_PATH` has a “look here first before usual places” semantics, in order to let users use an alternative version of a shared library.  On the other side, `DYLD_FALLBACK_LIBRARY_PATH` has a “look here if not found in usual places” semantics, in order to let users specify additional locations where a shared library is found.
In our case, if a binary refers to a common shared library found in usual places, we want to use it; we simply want to specify additional locations where BLS/MCL/OpenSSL libraries are found.  So it is more appropriate to use `DYLD_FALLBACK_LIBRARY_PATH`.
This also fixes a nasty symbol table mismatch, which is the main reason for this change: Certain commonly used shared libraries - such as `libJPEG.dylib`, co-located within the ImageIO framework and expected …

DYLD_LIBRARY_PATH → DYLD_FALLBACK_LIBRARY_PATH

---

api/service/discovery/service.go
node/node_handler.go
p2p/errors.go
p2p/group.go
p2p/host.go
p2p/host/hostv2/hostv2.go
p2p/host/hostv2/hostv2_test.go
p2p/host/hostv2/mock/hostv2_mock.go
p2p/host/message_test.go
p2p/p2p.go
p2p/p2pimpl/p2pimpl.go

This is a spin-off of #447, and contains various improvements not directly related to the host/peer/group discovery that #447 is addressing.

Clean up p2p

---

cmd/client/wallet/main.go

be consistent with the testnet document
The command is not compatible with the previous release.  A case changed.
* Before
* After
run wallet test locally.

fix command parameter in wallet

---

p2p/host/hostv2/hostv2.go

Since streams were multiplexed over connections, this wouldn't have caused file descriptor/socket leaks; however, it would have definitely caused memory leak (for the stream data structures).

Fix stream leak

---

api/service/discovery/service.go
api/service/networkinfo/service.go
cmd/client/txgen/main.go
consensus/consensus_leader.go
drand/drand.go
drand/drand_leader.go
drand/drand_validator.go
node/node.go
node/node.md
node/node_handler.go
p2p/group.go

When we integrate libp2p, txgen also has to work with the libp2p based gossiping.
All new nodes started as a beacon chain client, in order to send a message and recv blocks.
* Before
* After
Test manually, using -libp2p_pd flag, started 3 nodes for beacon chain, and started txgen using libp2p_pd flag as well.  Saw HOORAY was reached for a few times.

Txgen using Libp2p gossip to send TX to shard

---

node/node.md

Fixed the markdown format of the node.md with the content I added about libp2p integration with node structure.

fix format in node.md

---

README.md

This is to deal with third-party code – hard-forked and embedded – such as Ethereum and Google Key Transparency.  Ran the idea through @stephen-tse.

Add a third-party license clause to README.md

---

go.mod
scripts/go_executable_build.sh

this shall fix the ambiguous import issue
we have to deal with build errors when modules changed version.
tested on both mac and linux. needs golang v1.11 to build.

set module version

---

test/deploy.sh

Jenkins test on Jenkins server has a conflicting port with bootnode already running there.
* Before
* After
Local test passed.

use different port for bootnode in local test

---

crypto/bls/bls_test.go

https://github.com/harmony-one/harmony/issues/316
* Before
PASS
coverage: 44.7% of statements
ok  	github.com/harmony-one/harmony/crypto/bls	0.022s
* After
PASS
coverage: 97.6% of statements
ok  	github.com/harmony-one/harmony/crypto/bls	0.032s

Increase test coverage in bls

---

node/node_handler.go

this will parallel the processing of messages.
When we launch deploy test on AWS, more than 45 nodes in one shard, the consensus will get stuck after only two consensuses.  It turns out the leader wasn't able to process the commit messages from validators fast enough.
Run deployment on AWS, 45 nodes reached 107 consensuses with 300s run of txgen.
---
Tue Feb 26 00:28:16 UTC 2019 : deinit took 0 minutes and 2 seconds
1 shards, 107 consensus, 96 total TPS, 45 nodes
54.212.107.133, 107, 96.0816

process each message using a goroutine

---

consensus/consensus.go
node/node.go
node/node_handler.go

reduce the number of log messages on leader/validators when receiving consensus messages.
* Before
* After

[debug] remove excessive logging on receiving messages

---

api/service/discovery/discovery_test.go
api/service/discovery/service.go
api/service/networkinfo/service.go
node/node.go
node/node_syncing.go
node/node_test.go
node/service_setup.go

The new node needs to get a list of beacon peers for state syncing on beacon chain blockchain.
Added test program for the AddBeaconPeer function.
+ results='1 shards, 166 consensus, 269 total TPS, 10 nodes, 11 total nodes, 8 total signatures
127.0.0.1, 166, 269.298

Add beacon peer for every node

---

api/service/networkinfo/service.go
api/service/networkinfo/service_test.go
node/service_setup.go

instead of always using global bootnode, networkinfo now support a list
of new bootnodes.  This is to enable 2nd stage peer discovery, which can
use existing beacon peers as the bootnode to discover shard peers.
The bootnode was fixed in networkinfo service before.  Now it supports a new list of bootnodes.
* Before
api/service/networkinfo 0%
* After
coverage: 53.1% of statements

add bootnode parameter in networkinfo service

---

api/service/discovery/discovery_test.go
api/service/discovery/service.go
cmd/client/txgen/main.go
consensus/consensus_leader.go
node/node_handler.go

this shall speed up the bootstrap process by sending a ping message
immediately entering the goroutine
The original service sends the 1st ping message after the timer tick (5sec).
This patch speeds up the process by sending one ping message immediately.
+ results='1 shards, 30 consensus, 62 total TPS, 10 nodes, 11 total nodes, 8 total signatures
127.0.0.1, 30, 62.2404

send a ping message before the timer tick

---

.travis.yml
p2p/host/hostv2/mock/hostv2_mock.go
p2p/host/mock/host_mock.go
p2p/mock_stream.go
scripts/travis_checker.sh

This is an offshoot of #516, where I found out `mockgen` was not installed so `go generate` was failing, yet `travis_checker.sh` didn't catch that.  Things done here:
* Ensure mockgen is installed (`go get -t -v ./...` is not enough for that)
* Catch and fail if `gogenerate.sh` fails.
* Skip file change detection step if `gogenerate.sh` fails, because the failure would mean some/all of the files were not brought up to date and their working copy remained the same, essentially a false positive.
Working branch builds on [Travis](https://travis-ci.org/harmony-ek/harmony/branches):
* [#51](https://travis-ci.org/harmony-ek/harmony/builds/500506700) – after the second commit: `go generate` is functioning again, and it detected out-of-date mocks (in this case, mockgen itself was updated, so …

Fix go generate step of travis_checker.sh

---

node/node_newblock.go

We reach only 30 consensuses on AWS devnet deployment test. One consensus got the time out in 300 seconds. This patch shortens the timeout. In a normal case, a consensus can be reached in 3-5 seconds.
* Before
* After
http://jenkins.harmony.one/view/Benchmark/job/branch_build_test/20/console
1 shards, 60 consensus, 33 total TPS, 165 nodes

shorten timeout for consensus

---

api/service/networkinfo/service.go
internal/utils/utils.go
internal/utils/utils_test.go

Private IP wasn't filter out by net.IsGlobalUnicast function
```
IsGlobalUnicast reports whether ip is a global unicast address.
The identification of global unicast addresses uses address type identification as defined in RFC 1122, RFC 4632 and RFC 4291 with the exception of IPv4 directed broadcast addresses. It returns true even if ip is in IPv4 private address space or local IPv6 unicast address space.
```
Add a TestIsPrivateIP function as well.

#540 filter out private IP

---

go.mod

fix jenkins build issue. The error was in #558 
13:42:09 build command-line-arguments: cannot load github.com/ipfs/go-datastore/autobatch: cannot find module providing package github.com/ipfs/go-datastore/autobatch
Tested on my linux dev desktop and Jenkins server separately.

Go module fix on Jenkins

---

api/service/networkinfo/service.go
api/service/networkinfo/service_test.go
cmd/client/txgen/main.go
internal/wallet/wallet/lib_test.go
test/deploy.sh

We experienced a few cases that node failed to connect to bootnode and
the node program will not be useable. So, we add a retry mechanism to
increase the connection times to bootnode.

[networkinfo] retry for bootnode connection

---

go.mod

bls v0.0.1 has the fix of the following PR.
https://github.com/harmony-one/harmony/issues/564
https://github.com/harmony-one/bls/pull/1

[gomod] update bls to v0.0.1 version

---

api/service/networkinfo/service.go

DHT will clear out the entries every 24 hours.
The node needs to regularly announce to bootnode so that other peers can
find the peer.
We do regular advertise every 12 hours.

[networkinfo] regular advertise to bootnode

---

consensus/consensus.go
scripts/go_executable_build.sh

Default is no verbose output.  That helps identify the build errors.

Add  verbose to build process

---

scripts/setup_bls_build_flags.sh

This will fix the Jenkins build issue after the removal of $GOPATH in Jenkins configuration.
This is needed for go_executable_build.sh script to locate the MCL and BLS libraries.

[build] fix jenkins build issue

---

cmd/harmony/main.go
node/node_handler.go

validators reported, "Failed to validate multi-signature". It is because of the item/order of the public key was updated when the ping message received from the new node.
The original logic was intended for the leader to receive the ping message only. Since we moved to gossip, the validators are actually receiving and handling the ping message as well.  We now skip the validator in addPeer function.

Skip ping for validator

---

cmd/client/wallet/main.go
internal/wallet/wallet/lib.go
internal/wallet/wallet/lib_test.go

The main problem is the wallet is using p2p for async communication and
it exits too fast before p2p finished the tasks.
So, we added a few seconds waiting in the program and it works fine.

[wallet] fix transfer not working

---

node/contract.go

Previously, JSON-to-ABI conversion failure or `listLockedAddresses` argument packing failure would result in calling the contract with empty data.  The proper thing to do is to log error (already being done) *and* early terminate the function and return an error indication.

Abort QueryStakeInfo on early errors

---

scripts/setup_bls_build_flags.sh

realpath(1) is not available on macOS.
(Funny, because realpath(3) originated in FreeBSD, so it came to macOS before Linux adopted it, but Linux beat macOS to realpath(1).)

Use a rough equivalent of realpath

---

cmd/client/wallet/main.go

SSIA.  This fixes harmony-one/harmony#633.
Balances before are 10.00/0.00:
```
quelthalas 13:02:22 bin (pay_gas_for_data) $ 80 wallet balances
Account 0: 0x2139c763215a801aA4FdE2520dB84c11a6Cd3061:
Balance in Shard 0:  10.0000, nonce: 0 
Account 1: 0xDf6C34F754f028fcAF77a5260581bBccc0e45D3F:
Balance in Shard 0:  0.0000, nonce: 0 
Account 2: 0x6F3FE5De8A32401f91Da946aa4397b621528Cc17:
Balance in Shard 0:  0.0000, nonce: 0 
Account 3: 0x32ecba42e6Bc099C5eb19BE9147aA226DaB2FF68:
Balance in Shard 0:  0.0000, nonce: 0 
Account 4: 0x93714353dEc28C9ba95171A70B2eB8DBf7949E3E:
Balance in Shard 0:  0.0000, nonce: 0 
```
Transfer 0.01 with non-empty input data:
```
quelthalas 13:04:07 bin (pay_gas_for_data) $ 82 wallet transfer --from=0x2139c763215a801aA4FdE2520dB84c11a6Cd3061 …
```

Pay data gases

---

cmd/client/wallet/main.go

The previous fix for #633 was botched: It incorrectly used byte indices (`b := range inputData`) instead of byte values (`_, b := range inputData`).  The incorrectly calculated gas was enough for input data containing at least one NUL byte, a condition which all my test cases met—`AAAA` (which is 3 NUL bytes) as well as 10KiB data read from `/dev/urandom` (which was highly likely to contain at least one NUL byte).  However, it failed test cases such as `$(echo 1234 | base64)`, where none of the 4 characters are `NUL`.
I could've used the correct `_, b := range inputData` but here I use `core.IntrinsicGas()` which is the same gas calculation used on the server side.  Less logic duplication for DRY (and in turn future-proofing).

Pay data gas redux

---

node/node_syncing.go

On AWS launch, every node is using the same port number.
The original function filtered out all the peer with the same port and
got 0 peer on AWS test.

[sync] fix getNeighborPeers return 0

---

cmd/client/wallet/main.go
internal/utils/flags.go
internal/utils/utils_test.go

use an external environment variable to specify the rpc servers
of the wallet. this will greatly simplify the testing.
example of the environment variable:
export RpcNodes="127.0.0.1:8989,192.168.129.1:5555"

[wallet] support rpc server using environment variable

---

scripts/setup_bls_build_flags.sh

Modules-based workflow makes it possible to put the harmony repo and friends outside `${GOPATH[0]}/src`, and without using the full import path.  That is, `~/h/harmony`, or even `~/harmony` should be usable.  This can be done by setting `HMY_PATH="${HOME}/h"`, or `HMY_PATH="${HOME}"`.  In order for this to work without modifying `setup_bls_build_flags.sh`, however, `HMY_PATH` set in the environment should be honored.

Honor HMY_PATH if set

---

api/service/syncing/downloader/client.go
api/service/syncing/syncing.go
node/node_syncing.go

A new node will begin state syncing as soon as its join network now.

start sync when a new node join instead of waiting for consensus

---

cmd/client/wallet/main.go

Minor update:
Currently the `balances` command shows output like this:
```
Account 0: 0x50118d7E7106b038489804e63999eCb3bd1C6f1a:
Balance in Shard 0:  10.0000, nonce: 0 
```
When copying the address, the `:` is always included. Not desirable.

update balance output

---

test/deploy_newnode.sh

SSIA.  This is done by reading bootnode address from the newest bootnode log file in tmp_log.
Also remove the unused P2P (-P) option.

Make deploy_newnode.sh autodetect bootnode

---

cmd/harmony/main.go
internal/configs/node/config.go
internal/configs/node/config_test.go

Currently if a node is asked whether its a beacon node, it responds `true` if its shardID is zero. If it is a beaconnode [it won't add peers ](https://github.com/harmony-one/harmony/blob/72dd417202ab02b08437ad221d65a67436040ce6/api/service/discovery/service.go#L90 )
However we want light nodes/client nodes to join shardID=0, have peers, so that they can state-sync and possibly send transactions to this shard. This change makes the distinction (without a difference) between `shardID=0` and being a beaconnode.

Seperate the notion of shardId=0 from a beacon node

---

cmd/harmony/main.go
consensus/consensus.go
node/node.go

SSIA.  To use this:
```sh
logfile=... # change this
acct=$(head -100 "$logfile" | jq -r 'select(.msg == "node account set") | .address')
tail -fc+0 "$logfile" | jq --arg acct "${acct}" 'select(.msg == "accumulateRewards: rewarding" and .account == $acct)'
```
Sample output (`amount` is in Wei; 1000000000000000 Wei = 0.001 token):
```json
{
"account": "0xE2bD4413172C98d5094B94de1A8AC6a383d68b84",
"amount": "1000000000000000",
"block": "0x021f2fe4c387de859b8c341099e116bb37cf5e1729a590d0a0aee58d8b63e6ad",
"ip": "127.0.0.1",
"lvl": "info",
"msg": "accumulateRewards: rewarding",
"node": "ac286808e6ce0e56559d08b99a3e0e71af1f6dec",
"port": "9000",
"t": "2019-04-01T19:24:26.856624-07:00"
}
```
Logging-only PR.  No coverage change.
Local test passes.

Log block rewards

---

.travis.yml
go.mod
scripts/add_build_tool_package.sh
scripts/goget.sh
scripts/install_build_tools.sh
scripts/protobuf_setup.md
tools/tools.go

Our builds do not fully specify versions of tools, especially code generators.  As a result, the builds are not fully reproducible, and what passed yesterday may fail now and vice versa, because the same `go get` command for the same tool package may fetch and install different versions of the package over time as the package gets updated.
To fix this, this PR introduces the following mechanisms, in line with [the officially recommended approach](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module):
* `tools/tools.go` (new) has a list of `go get`-able build tools such as `golint` and `goimports`.
* `go.mod` contains the specific pegged versions of the `go get`-able build tools.
* `scripts/goget.sh` (new) installs—that is, `go get`-s—given import paths …

Version-peg tools (#600)

---

node/node_newblock.go

I suspect the new block proposing service is stopped in testnet. That's why leader still receive transaction but never propose new block on banjo testnet.
Add a few debug log to isolate the issue.

[log] adding log to debug #680

---

core/resharding.go

this is only for temporary fix; we cannot really proceed without previous sharding state

temporary fix for issue #684

---

consensus/consensus.go

This may fail the newnode case because the new node may still be trying to sync up before joining the consensus, hence its key is not in `consensus.PublicKeys` yet.
When this happens, the new node will not be able to sync blocks and won't join consensus.

Do not try to add self key to mask

---

scripts/node.sh

This is based on the feedback from one of our foundation node runners.
Since we only support IPv4 address at this stage, we should just
retrieve the IPv4 address if both IPv6 and IPv4 addresses exist.

[node] get ipv4 address only

---

core/blockchain.go
node/node_newblock.go

the excessive logs have caused leader node out of space only after 8k
consensuses.
* Before
* After

[log] disable huge debug log in leader

---

cmd/client/txgen/main.go
cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_leader_msg_test.go
consensus/consensus_leader_test.go
consensus/consensus_test.go
consensus/consensus_validator_msg_test.go
consensus/consensus_validator_test.go
node/contract_test.go
node/node_handler_test.go
node/node_test.go
node/staking_test.go

we don't do static peers initialization in consensus anymore.
all peers should be added by calling AddPeers function.

[cleanup] remove peers variable from consensus New function

---

test/deploy.sh

The deploy.sh doesn't work on my ubuntu 18.04 bash environment. This fixes it.

fix deploy.sh not work on ubuntu bash environment

---

cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_test.go
test/deploy.sh

The consensusID always starts from 0, which is used to display as the block height in explorer in our current design. This can be confusing as in Issue (https://github.com/harmony-one/harmony/issues/714)
So, the solution is when we launch a blockchain with persisted data from the previous launch, we set the init consensus ID to be the block height restored from persisted data. So, it at least displays the right block height.

Set init consensus ID

---

node/contract.go
node/node.go

Tested using a new devnet. I can request tokens on all 4 shards.
https://0.harmony.one/#/

[sc] enable faucet for all shards

---

cmd/client/wallet/main.go
cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_leader.go
node/node.go
node/node_handler.go
test/deploy.sh

The current 1+3 shards p2p communication is using beacon client topic for all client communication, which is wrong.  Each shard should have its own client topic for communication with their own clients.
This patch set fixed the client side multi-shard communication by using shard specific topic for communication. Each shard has a unique topic to talk to shard client.
Tested locally by:
* launch a blockchain with 4 shards
* use local wallet.ini to talk to four shards
* getFreeToken from all shards
* do the token transfer on different shards with different tx amount
* all tx went through
The full test log is available at https://gist.github.com/LeoHChen/d7161b16f5f8ecf3c28eb05c23ccc11b

Fix multi shard client communication

---

node/contract.go
node/node.go
node/node_handler.go

Fixing issue: https://github.com/harmony-one/harmony/issues/711, which is due to our design of faucet where we use a master account to call the contract for the users (so they don't have to pay tx fees). This fix streamline the nonce so multiple calls can have correct and non-overlapping nonce.
Tested locally a single block can handle multiple (11) getFreeToken request at once.
PROPOSING NEW BLOCK ------------------------------------------------ port=9005 ip=127.0.0.1 blockNum=2 threshold=1 pendingTransactions=11
DEBUG[04-20|16:32:37.823] Selecting Transactions                   port=9005 ip=127.0.0.1 remainPending=0 selected=11 invalidDiscarded=0
DEBUG[04-20|16:32:37.826] Successfully proposed new block          port=9005 ip=127.0.0.1 blockNum=2 numTxs=11

Fix getFreeToken blocking issue

---

gomock_matchers/path.go
gomock_matchers/path_test.go
gomock_matchers/slice.go
gomock_matchers/slice_test.go
gomock_matchers/struct.go
gomock_matchers/struct_test.go
gomock_matchers/util.go

SSIA.  These matchers can be passed as gomock expected call arguments.  I use them in my other UTs for the upcoming block rewards code.
```go
mock.EXPECT().Method(matchers.Slice{3, gomock.Not(4), 5})
```
ensures that the method is called with a three-member slice or array, whose first/third element must be 3 and 5 respectively, and the second element must not be 4.
```go
mock.EXPECT().Method(matchers.Struct{"A": 10, "B": 20})
```
ensures that the method is called with a struct or a pointer to a struct with two data members named `A` and `B`, and with values 10 and 20 respectively.
```go
mock.EXPECT().Method(matchers.Path("core/types/block.go"))
```
ensures that the method is called with a pathname whose trailing part is `core/types/block.go`, such as:
* `core/types/block.go`
* …

Add gomock matcher utilities

---

.gitignore
cmd/client/wallet/main.go

ethereum compatible keystore
support passphrase for wallet new/list/import functions
support export keystore using encrypted json format
https://github.com/harmony-one/harmony/issues/824

[wallet] use ethereum keystore in wallet

---

node/rpc.go

The 10/20 offset will upset local test with more than 10 nodes being
launched.
The error I encountered is like:
panic: failed to listen on any addresses: [listen tcp4 0.0.0.0:9015: bind: address already in use]
goroutine 1 [running]:
github.com/harmony-one/harmony/p2p/host/hostv2.catchError(...)
/Users/leochen/work/go/src/github.com/harmony-one/harmony/p2p/host/hostv2/util.go:10

[rpc] increase the offset of rpc port

---

cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_test.go
consensus/consensus_v2.go
node/node.go
node/node_handler.go

1/ use a single source of truth instead of having is_leader in 2 objects. that would cause inconsistency in case you missed to update it at both places.
2/ Clean up code in main file

use single source of truth instead having is_leader truth in 2 objects

---

core/resharding.go
core/types/shard_state.go

This is to make shard state comparison, e.g. for validation, a convenient one-shot operation.
Spun off from #839.

Make shard state comparable recursively

---

api/proto/node/node_test.go
consensus/consensus_validator_test.go
core/chain_makers.go
core/genesis.go
core/types/block.go
node/worker/worker.go
test/chain/main.go

This ~~does not~~ actually does change RLP encoding.
Spun off of #839.

Use uint32 as shard ID type instead of [4]byte

---

node/node.go

Out-of-range account index (currently >= 200) translates into a shard ID
(>= 4) not found in the genesis table, so its genesis cannot be
initialized.  Since this can be induced by misconfiguration, do not
panic but just crit out.
This error was seen during drum testnet launch.

Do not panic upon out-of-range account index

---

consensus/consensus.go
consensus/consensus_leader.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/view_change.go

The current scheme accepts and rewards only the first `2f+1` signers.  Topologically disadvantaged nodes, i.e. far away from the leader, typically loses out the commit race and earn no block rewards.  This commit allows a 1-second grace period after reaching the `2f+1` quorum.

Add signature grace period

---

consensus/consensus_service.go
consensus/view_change.go
node/node_syncing.go

The previous code sets viewchanging viewID into the consensus.viewID, which is incorrect. This will make the timeout of viewchange period to be always 0. But we want it to be a non-zero value, which depends on how many consecutive view changing happen before the new leader response with newview message

fix timeout duration bug

---

consensus/consensus_service.go
node/node_handler.go

Fixed two bugs:
1) duplicate code in node_handler.go
2) clean the VDF list after it is consumed
* Before
* After
$cd consensus
go: downloading github.com/davecgh/go-spew v1.1.1
go: extracting github.com/davecgh/go-spew v1.1.1
PASS
coverage: 21.0% of statements
ok  	github.com/harmony-one/harmony/consensus	9.557s
$cd ../node
haobo@UpstairsLinux:/opt/haobo/work/go/src/github.com/harmony-one/harmony/node$ go test -cover
wait 5 seconds to terminate the process ...
ok  	github.com/harmony-one/harmony/node	7.035s

fix VDF bug

---

consensus/consensus_service.go

common.Address is itself a byte array, so the %s format specifier
outputs its (binary) bytes directly without any encoding.  Explicitly
Hex() it.

Fix garbled validator address errors

---

consensus/consensus_v2.go
consensus/pbft_log.go

The current design for commit message is validator sign on |blockNum|blockHash| message. Thus, it's important for leader to keep track of the order of message it received. Leader must verify it has sent prepared message before accept the commit message from validator.

fix potential security issue in onCommit for leader

---

consensus/consensus.go
core/resharding.go
core/resharding_test.go
core/types/shard_state.go
core/types/shard_state_test.go

It's better to have fixed-length bytes than string in the blockchain data structure.

Change shard state ECDSA address to use common address/byte format

---

api/client/service/client.go
api/client/service/server.go
api/proto/message/client.go
api/proto/message/client_test.go
api/proto/message/server.go
api/proto/message/server_test.go
api/proto/node/node_test.go
api/service/explorer/service.go
api/service/explorer/storage.go
api/service/explorer/storage_test.go
api/service/staking/service.go
api/service/syncing/downloader/server.go
api/service/syncing/syncing.go
cmd/client/txgen/main.go
cmd/client/wallet/main.go
cmd/harmony/main.go
consensus/consensus_leader_msg_test.go
consensus/consensus_service.go
consensus/consensus_v2.go
internal/ctxerror/ctxerror.go

`Warn` level was chosen for the current behavior: Alert about uncaught failures but do not alter the code path (yet).  More proper error handling will come later.
This PR handles about 60 errors.  There are ~150 more, but I am moving onto Bech32 for now.  One c an see the current tally by running `errcheck ./...` from the repo root.

Log errors, mostly at warn (or fatal for UT) level

---

consensus/config.go
consensus/consensus_v2.go

to make the new node join consensus quickly without multiple state syncing:
add catchup logic in announce, prepare phase;
ignore viewID check at committed stage

add catchup logic in announce,prepare phase; ignore viewID check at committed stage

---

accounts/keystore/account_cache.go
api/client/service/server.go
api/client/service/server_test.go
api/service/explorer/service.go
api/service/explorer/structs.go
api/service/explorer/structs_test.go
api/service/staking/service.go
cmd/client/wallet/main.go
cmd/harmony/main.go
cmd/keygen/main.go
consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_service_test.go
core/resharding.go
core/state/statedb_test.go
core/types/shard_state.go
core/vm/contracts_test.go
drand/drand.go
drand/drand_test.go
internal/bech32/bech32.go
internal/common/address.go
internal/hmyapi/util.go
node/contract.go
node/node_genesis.go
test/txgen/main.go

This is an interim fix that reuses the existing `common.Address` from Ethereum, instead of using our own.  We take this lighter approach because changing the Ethereum `Address` with ours has a recursive ripple effect that forces us to start soft-forking Ethereum code to use our type.

Use bech32

---

scripts/wallet.sh

we have switched to use dns based rpc query, no longer need wallet.ini

[wallet] remove wallet.ini

---

cmd/client/wallet/main.go
internal/blsgen/lib.go

use serialized public key instead of standard public key in wallet tool

use serialized public key instead of standard public key in wallet tool

---

scripts/node.sh

Add `-c` option, which backs up the contents of log (`latest`) and database (`harmony_db_*`) into a backup directory.
The backup directory is found in `backups/`, named `YYYY-MM-DDTHH:MM:SSZ.XXXXXX`, where `XXXXXX` is a random alphanumeric string chosen by mktemp(1).

Add clean (-c) option

---

accounts/keystore/keystore.go
cmd/client/wallet/main.go

./bin/wallet format --address 0x053515CC2CAae77F7e2F0A9C48A27c8f6D76E99d
account address in Bech32: one1q563tnpv4tnh7l30p2wy3gnu3akhd6va97w7ku
account address in Base16 (deprecated): 0x053515CC2CAae77F7e2F0A9C48A27c8f6D76E99d
./bin/wallet format --address one1djwg5f0l3ccnscupqz6htcqsjnl85jt8xvpwhc
account address in Bech32: one1djwg5f0l3ccnscupqz6htcqsjnl85jt8xvpwhc
account address in Base16 (deprecated): 0x6c9C8a25Ff8e3138638100B575e01094Fe7a4967

Add address format and exportPriKey utility in wallet

---

consensus/consensus.go
consensus/consensus_leader_msg_test.go
consensus/consensus_service.go
consensus/consensus_service_test.go
consensus/consensus_v2.go
consensus/view_change.go
node/node_handler.go
node/node_syncing.go

* remove the common.Address or Bech32 address usage in consensus to avoid confusion; use publickey instead
* clean up some codes

remove address and use publickey in consensus; clean up consensus code

---

internal/genesis/genesis.go

SSIA.  Previously whatever string form—bech32 OR base16—in foundational.go or genesis.go needed to be used (case-sensitive too) as `-account` argument, and the other form was rejected.  With this change the code accepts both versions, case-insensitively.

Make -account handle both base16 and bech32

---

cmd/harmony/main.go
internal/utils/passphrase.go
internal/utils/passphrase_test.go
internal/utils/testing/tempfile.go

Add openssl(1)-compatible non-interactive passphrase argument handling:
* `harmony -pass stdin` reads the passphrase from standard input (file descriptor 0)
* `harmony -pass fd:3` reads the passphrase from file descriptor 3
* `harmony -pass file:omg.txt` reads the passphrase from file named `omg.txt` (beware permission)
* `harmony -pass pass:omgwtfbbq` uses the string `omgwtfbbq` itself as a passphrase (INSECURE)

Support non-interactive passphrase

---

consensus/consensus.go

add log for pbft log because it stores block by memory

add log for pbft log because it stores block by memory

---

cmd/harmony/main.go

To opt-out, one can specify the `-is_archival false` option.
Two benefits:
1. Less memory consumption (trie cache can consume up to 256MiB of memory).
2. Better overall shard health (no more manual database syncing

Run in archival mode by default

---

cmd/harmony/main.go
internal/utils/passphrase.go

When `GetPassphraseFromSource` is used with `stdin` or `fd:xyz`, it exhausts the standard input or the given file descriptor `xyz`, so a second call to it returns an empty string.  Deal with this by ensuring it is called only once from `main`.

Call GetPassphraseFromSource only once

---

internal/blsgen/lib.go

fix passphrase when it is trailed with whitespace

fix passphrase when it is trailed with whitespace

---

scripts/node.sh

This is because the same file will be discovered twice.  Identify this case by using the same-file test(1) predicate (`X -ef Y`) and error out if the files are distinct.

Fix “multiple key files found” if pwd is $HOME

---

cmd/harmony/main.go

`-version` and other print-and-exit processing should be done right after options processing.  Do so.

Fix -version flag

---

internal/utils/connlogger.go

An extra argument was passed and it was causing `LOG15_ERROR` context messages in connection logs.

Fix connection logging

---

cmd/harmony/main.go
internal/configs/net/config.go
node/node.go
node/node_syncing.go

If a non-empty zone name is given, obtain syncing peers from the given zone; otherwise, use libp2p peer discovery.
For backward compatibility:
* `-dns=true` (default) is equivalent to `-dns_zone=t.hmny.io`;
* `-dns=false` is equivalent to `-dns-zone=""`;
* `-dns_zone` takes precedence over the `-dns` boolean setting.

Make DNS zone configurable via -dns_zone

---

consensus/consensus.go
consensus/consensus_v2.go
core/blockchain.go
node/node_newblock.go
test/cal_tps.sh

The consensus readySignal should be given when the startConsensus signal is given, rather than when the consensus object is constructed.

Fix consensus start issue.

---

cmd/harmony/main.go

Reverts harmony-one/harmony#1128
we still want to enable debug log at the v0 stage.

Revert "[log] filter out debug log by default"

---

cmd/bootnode/main.go
cmd/harmony/main.go
go.mod
internal/utils/singleton.go

#1170 
N/A
N/A
Tested by launching a node with `-log_max_size 1` (1MB), waited for logs to generate and verified logs are GZIP compressed once it goes over set size:
N/A

Implement Log File Rotation with GZIP

---

consensus/consensus_v2.go
core/blockchain.go
core/chain_indexer.go
core/headerchain.go
core/rawdb/accessors_chain.go
core/rawdb/accessors_indexes.go
core/tx_pool.go
core/types/block.go

Log common.Hash in hex instead of TerminalString/Bytes

---

cmd/client/txgen/main.go
cmd/harmony/main.go
core/resharding.go
internal/configs/sharding/fixedschedule.go
internal/configs/sharding/instance.go
internal/configs/sharding/mainnet.go
internal/configs/sharding/shardingconfig.go
internal/configs/sharding/testnet.go

This is done by introducing two concepts: sharding configuration instance and sharding configuration schedule.
A *sharding configuration instance* is a particular set of sharding parameters in effect, namely:
- Number of shards;
- Number of nodes/shard; and
- Number of Harmony-operated nodes per shard.
A *sharding configuration schedule* is a mapping from an epoch to the corresponding sharding configuration for that epoch.
Two schedules are provided and to be maintained in the long term: Mainnet sharding schedule (4 shards, 150 nodes/shard, 112 Harmony-operated nodes/shard) and public testnet sharding schedule (2 shards, 150 nodes/shard, 150 Harmony-operated nodes/shard).
Harmony node binary uses one of these for `-network_type=mainnet` and `-network_type=testnet` respectively.
In …

Make sharding configuration flexible

---

api/service/config.go
cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_test.go
consensus/consensus_v2.go
internal/configs/node/config.go
internal/configs/node/config_test.go
node/node.go
node/node_handler.go

use consensus.IsLeader to replace the static nodeConfig
by checking the public key of the leader with the consensus public key

[cleanup] remove IsLeader of nodeConfig

---

scripts/pagerduty.sh

Script checks timestamp of last bingo in log and triggers an alert to Pagerduty if more than 60 seconds have passed since. The script should be used with crontab to be run every minute in order to constantly check for validation status.
> NOTE: If a Pagerduty has been triggered and node somehow starts validating again, the script will automatically send a resolve event to Pagerduty. This means that if the alert on Pagerduty is manually resolved (not simply acknowledged), the script will hang because it will try to post a resolve for an alert that doesn't exist. Not 100% sure if this functionality is wanted.
EDIT: Fixed

Add pagerduty validation status script

---

cmd/bootnode/main.go
p2p/host/hostv2/hostv2.go
p2p/host/hostv2/util.go
p2p/p2pimpl/p2pimpl.go

#1171 
Verified that `.Panic()` log event calls `panic(msg)` (instead of `panic(err)`) after logging.
N/A, ran `./test/test_before_submit.sh`

Replace all logs in p2p module to use zerolog

---

node/node_syncing.go

*\[@harmony-ek: the following rationale is mine]*
Since our rolling upgrade procedure restarts a stride of 4 nodes at a time, a restarted node sees up to 3 stale copies.  Setting the minimum gRPC peer count to 10 (from 5) ensures that there will be a supermajority (≥7) reply from non-stale nodes, ensuring that their chain will be chosen.

increase number of min peers in state syncing from 5 to 10

---

internal/genesis/foundational.go

This reverts commit e70c60cd2d51e93684a9bbd65234a18d7ecd407d.

Revert "[foundation] fixed a typo in the account address"

---

scripts/node.sh

Valid networks are main (mainnet), beta (betanet), pangaea (Pangaea);
default is main.
Vary release channel (folder), bootnodes, and network type.
TODO @harmony-ek – replace hardcoded bootnode with DNS

Add -N (network) option to node.sh

---

consensus/consensus_service.go
consensus/consensus_v2.go
core/blockchain.go
internal/configs/sharding/fixedschedule.go
internal/configs/sharding/localnet.go
internal/configs/sharding/mainnet.go
internal/configs/sharding/pangaea.go
internal/configs/sharding/shardingconfig.go
internal/configs/sharding/testnet.go

Need to adjust mainnet DRG feature on EPOCH
mainnetRandomnessStartingEpoch = 10
The code should be removed after DRG is on mainnet. 
* Before
* After

Added wrapper for DRG generation based on epoch number

---

.hmy/wallet.ini
cmd/client/wallet/generated_wallet.ini.go

Also add more bootnodes to default, and replace devnet with beta.
Betanet does not have official dns_zone, so currently using b.hmny.io.

[Pangaea] Add Pangaea profile to wallet.ini

---

api/service/syncing/downloader/client.go

It is helpful to know who the misbehaving endpoint is when download registration fails.

Add target to "Register failed" error to help debug issue #1336

---

core/types/block.go

Log blockEpoch and blockNumber as Uint64 not Str

---

internal/genesis/foundational_test.go
internal/genesis/genesis_test.go
internal/genesis/harmony_test.go
internal/genesis/localnodes_test.go
internal/genesis/newnodes.go
internal/genesis/newnodes_test.go
internal/genesis/tn_harmony_test.go

Introduce unit tests for `DeployAccount` tables which are often manually updated thus prone to errors.  Enforce the following:
* `Address` is a valid Bech32 address (guard against typo)
* `BlsPublicKey` is a valid BLS public key (guard against typo)
* `Address` and `BlsPublicKey` are unique within the table (common copy/paste glitch)
Before @LeoHChen's fix (#1273) and with a few intentional duplications:
```
$ go test ./internal/genesis
--- FAIL: TestFoundationalNodeAccountsV1 (0.03s)
genesis_test.go:63: account one1pjn8zz5av5ddenaxmu6qrs381xuapygkeatxga/71c907378831009328f28db0e324848767b58e49eae1f2774e81276e25732bfea5ed8a567fed15afb010be05b9732b16:0 at index 158 has invalid address (cannot decode "one1pjn8zz5av5ddenaxmu6qrs381xuapygkeatxga" as bech32 address: decoding bech32 failed: …
```

Unit test DeployAccount tables

---

cmd/harmony/main.go
core/blockchain.go
core/rawdb/accessors_chain.go
core/types/block.go
node/node.go
node/node_syncing.go
node/node_test.go

This is the part 1 of beaconchain syncing.  It plumbs the machinery to get shard 0 syncing peers via DNS and localnet sharding config.  The non-DNS legacy method is still provided, but due to the way `Node.BeaconNeighbors` is filled (or lack thereof), the non-DNS method is still broken.

Get syncing peers using DNS, part 1

---

test/deploy.sh
test/kill_node.sh

Do not target processes with `harmony`, `txgen`, `soldier`, `commander`, `profiler`, or `bootnode` somewhere in their full command line, but just kill processes whose binary name exactly matches one of these.
Also retire port-number-based node killer, which is unused.

Fix node killing in local test

---

cmd/client/wallet/main.go
core/types/transaction_signing.go

We shouldn't change the signer without adding correct forking logic.

Revert signer change and add shard info in tx hash for eip155

---

cmd/client/wallet_stress_test/README.md
node/worker/worker.go

1 line of code unintentionally reverted in s3. Re-adding the bug fix line in worker.go.
impact: max amount transaction throttling will not work. After declaring the transaction to be over-the-limit of throttling max amount, it will still try to commit transaction and succeed in processing the transaction.
dennis.won@jongs-mbp:~/harmony/node/worker (s3_merge_conflict) $ go test -cover
PASS
coverage: 31.1% of statements
ok  	github.com/harmony-one/harmony/node/worker	0.067s

S3 merge conflict

---

api/service/explorer/service.go
api/service/explorer/structs.go

Mechanism of adding block signers to block in explorer api was little incorrect as it returned whole list of validators instead of only signers. Need review of block signers mechanism from @chaosma at api/service/explorer/service.go L#208. I use LastCommitBitmap and if i-th validator from committee list LastCommitBitmap[i] not 0 then he signed the block.
Tested on localnet with postman.

fix block signers

---

node/node_newblock.go

transaction not enabled on mainnet
PASS
coverage: 17.2% of statements
ok  	github.com/harmony-one/harmony/node	2.452s
Test on releasenet. Locally tested that if this if check takes into effect, transaction is not inserted into the pending transactions list.

enable transaction on mainnet/releasenet

---

scripts/node.sh

This is done by the `-f` flag of `curl(1)`.
Also do not show progress indicator (`-s`) but still show errors (`-S`).
This is a preventive action from the mainnet deployment failure on 8/30/2019.

Make fetch fail on HTTP error status such as 404

---

scripts/node.sh

This is a preventive action for the 8/30/2019 mainnet deployment failure.
**Note:** the tests below were run with #1480 applied as well.
```
$ sudo ./node.sh
node.sh: autodetected BLS key file: faf143c9891a323ef2f780adb578c34d4687c986786ec4931d9e96970dd08629fcdce1b7b6dc74a9d53cac4e7da06401.key
diff: md5sum.txt: No such file or directory
node.sh: downloaded harmony
node.sh: downloaded libbls384_256.so
node.sh: downloaded libcrypto.so.10
node.sh: downloaded libgmp.so.10
node.sh: downloaded libgmpxx.so.4
node.sh: downloaded libmcl.so
node.sh: downloaded md5sum.txt
net.core.somaxconn = 1024
net.core.netdev_max_backlog = 65536
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_rmem = 4096 65536 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.tcp_mem = 65536 131072 262144
node.sh: public IP …
```

Check md5sum after download

---

api/service/syncing/syncing.go

close peer sync config connections to prevent duplicate peer sync config creation, causing inifinite memory leak, causing wallet to not function.
https://github.com/harmony-one/harmony/issues/1460
dennis.won@jongs-mbp:~/harmony/api/service/syncing (fix_socket_too_many_open) $ go test -cover
PASS
coverage: 3.8% of statements
ok  	github.com/harmony-one/harmony/api/service/syncing	0.066s
wallet balance runs fine. Do not see any more "Too many socket connections open" error on log.

close peer sync config connections to prevent duplicate peer sync config creation

---

.travis.yml

Go 1.13 has been released and it is breaking a few backward compatibility, including a module version check that one of our upstream dependencies (golangci/golangci-lint) fails.  Peg our Travis check at Go 1.12 on s3 branch.  A separate PR will be opened for master as well.

Peg s3 at go 1.12

---

api/proto/node/node.go
consensus/consensus.go
consensus/consensus_v2.go
core/block_validator.go
core/blockchain.go
core/types/cx_receipt.go
node/node_cross_shard.go
node/node_handler.go
node/node_newblock.go

- add header and signature information when broadcasting cxreceipts
- avoid crosslink verification to speedup cross shard tx finalization by around 1 block time.

improve cross shard tx receipts verification design and logic

---

consensus/consensus_v2.go
internal/params/config.go
node/node_handler.go

desides, delay the cross-link function for later, and print consensus message on stdout.

Let 30% of the validator broadcast cx-receipts

---

consensus/consensus_service.go
consensus/consensus_v2.go

migrate to zerologger removes this error log.
```
// getLogger returns logger for consensus contexts added
func (consensus *Consensus) getLogger() *zerolog.Logger {
logger := utils.Logger().With().
Uint64("myEpoch", consensus.epoch).
Uint64("myBlock", consensus.blockNum).
Uint64("myViewID", consensus.viewID).
Interface("phase", consensus.phase).
Str("mode", consensus.mode.Mode().String()).
Logger()
return &logger
}
```

nit: fix error log consensus:marshaling error: json: unsupported type: chan []uint8

---

core/state_processor.go

In localnet config. The cross shard tx will be blocked at epoch=0. After epoch >= 1, the cross shard tx will be accepted. To test it ,just run the wallet command before and after epoch transition.

prevent cross shard tx before V0 Epoch

---

.hmy/wallet.ini
cmd/client/wallet/generated_wallet.ini.go
cmd/client/wallet_stress_test/generated_wallet.ini.go
scripts/node.sh

I messed up p.hmny.io and I don't want to use pga.hmny.io as there are old nodes connecting to it. Using n as it's close to p and is the second consonant in Pa**n**gaea.

[Pangaea] Change to functional DNS server

---

internal/configs/sharding/mainnet.go
internal/configs/sharding/pangaea.go
internal/configs/sharding/testnet.go

Support https and wss as part of the mainnet v1 checklist https://github.com/harmony-one/harmony/issues/1556
This is needed for the SDK which is being used by math wallet.
As such math wallet cross shard transactions should be tested to verify this (from shard0 to shard 1)
This needs to be tested against betanet, pangea and mainnet.
math wallet cross shard transactions should be tested to verify this (from shard0 to shard 1)
* Before
* After
Merge and validate against betanet, pangaea and mainnet

Change endpoints to support for https and wss

---

internal/hmyapi/blockchain.go

add getShardID api which returns shard id of the requested node.

[blockchain.go] add getShardID api

---

cmd/harmony/main.go
internal/configs/node/config.go
node/rpc.go

for security reason, node program should only listen to localhost for rpc request by default.
-rpc_ip  option is introduced to listen to any port for rpc service

[rpc] listen to localhost by default

---

internal/hmyapi/README.md
internal/hmyapi/harmony.go

Add node meta data RPC so that we can build monitoring services. 
Tested with:
```
test/debug.sh
curl -X POST -H 'content-type:application/json' localhost:9500  \
-d  '{"id":"1","jsonrpc":"2.0","method":"hmy_getNodeMetadata","params":[]}' | json_pp
{
"id" : "1",
"jsonrpc" : "2.0",
"result" : {
"network" : "",
"version" : "Harmony (C) 2019. harmony, version - ( )",
"blskey" : "65f55eb3052f9e9f632b2923be594ba77c55543f5c58ee1454b9cfd658d25e06373b0f7d42a19c84768139ea294f6204"
}
}
```
Note:
1. network is empty, this is to be investigated as possible bug in existing code
2. version is empty, this is because of how local build of harmony binary proceeds. 
3. blskey is the public key used in consensus

[RPC] Expose node metadata

---

api/service/explorer/service.go
api/service/explorer/structs.go
node/contract.go

Balance was incorrect, because it didn't correctly consider cross-shard txs. Added shard fields (FromShard, ToShard) to explorer transacrtion. Txs on frontend should be shown separately for each shard.
Postman, localnet testing.
* Before
* After

Fix balance and add cross-shard txs

---

api/service/syncing/syncing.go
node/node.go
node/node_syncing.go
node/worker/worker.go
node/worker/worker_test.go
test/chain/main.go

Worker is not needed for state sync.
ShardID is not needed in worker.
Explorer node needs to update consensus info once sync'ed.
Tested locally on both normal and explorer node.

Cleanup state sync logic; fix explorer node sync wrong committee issue

---

node/node_cross_shard.go

We  have monitoring that sends alerts on warning/error messages after a  certain threshold. This warning is setting off our alerts.
See also https://github.com/harmony-one/harmony/pull/1566
>[12:28 AM] Chris | Harmony: That probably should be info
[12:28 AM] Chris | Harmony: That happens whenever there's no cross shard transactions
[12:28 AM] Chris | Harmony: Which is probably pretty common
[12:28 AM] Chris | Harmony: Also for all 3 shards

Make "No ReadCXReceipts found" Info() not Warn()

---

scripts/go_executable_build.sh

Currently the build script continues on no matter what error occurred.
This is problematic for three reasons:
1) the state of the build is in some indeterminate state (e.g bad m5sums wrong etc) since the script blindly moves on no matter what errors happened before
2) the `Makefile` is unaware something went wrong
3) it makes `git bisect run` impossible w/o a wrapper script.

Fail if build fails so Makefile knows something went wrong

---

api/service/syncing/syncing.go

"ip" is already used for my local ip in other places
"IP" for the peer ip is just confusing, as are any json tags that have spaces.

Unify json tags for IP

---

api/service/networkinfo/service.go
api/service/networkinfo/service_test.go
node/node.go
node/service_setup.go

DHT directory is of the form `.dht-<IP>-<port>`, e.g. `.dht-12.34.56.78-9000` in the current directory.  If a node is restarted in the current directory for a different network, e.g. from Mainnet to Pangaea due to misconfiguration, then in the new invocation (Pangaea) the node still connects to old cached nodes (on Mainnet).  Segregate cache by having chain ID embedded in the DHT cache directory name.
(19876 is bootnode, which is inherently network agnostic, so its directory name does not have the chain ID embedded.)

Include chain ID in DHT cache database directory name

---

hmy/api_backend.go
hmy/backend.go
internal/hmyapi/backend.go
internal/hmyapi/transactionpool.go
internal/hmyapi/types.go
internal/hmyapi/util.go
node/node_explorer.go

https://github.com/harmony-one/harmony/issues/1633
* Before
* After
Make adjustments on explorer frontend. GetTransactionsHistory returns list of hashes, then query each tx by hash by GetTransactionByHash and its receipt by GetTransactionReceipt and show on explorer. Such design makes all methods atomic.

add hmy getTransactionsHistory

---

api/service/explorer/service.go
api/service/explorer/storage.go

This might fix https://github.com/harmony-one/harmony/issues/1630. Adds ASC or DESC order for blocks and txs on api requests (order param "ASC" or "DESC")
Tested locally with postman.
* Before
* After

Negative balance fix for storage, ASC or DESC order for blocks and txs

---

go.mod

Use the non-initializing vdf package from github.com/harmony.one/vdf@v3.0.0
A large array of prime numbers are pre-calculated instead of calculating, saving 3 seconds system initialization time. 
Somehow the tag v3.0.0 can't be fetched automatically so has to use this tag v0.0.0-20190924052046-3ac2a5bbd98a

updated to use non-initializing vdf

---

node/node_explorer.go

Small fixes for tx transactions history api. Fixed 0x case (returned error if address wasn't in db), storage should be fetched with false flag.
* Before
* After

fix storage instance and 0x address case

---

api/service/explorer/storage.go
api/service/explorer/structs.go
internal/hmyapi/blockchain.go
internal/hmyapi/transactionpool.go
internal/hmyapi/types.go

https://github.com/harmony-one/harmony/issues/1678. Also fixed explorer to support contract tx and added one1 address formatting at missing places.
Localnet, postman, truffle.
Block methods and tx methods for fetching txs
Methods results for contract tx.
* Before
* After
Test on testnet.

Fix apis for contract tx

---

internal/hmyapi/transactionpool.go
internal/hmyapi/util.go

Richard requested tx history to have full tx info. I made a separate method to call tx history with full info using method that returns just hashes.
* Before
* After
Make adjustments on explorer back/front.

Add transactions history api with full tx info

---

api/service/config.go
api/service/discovery/service.go
api/service/manager_test.go
api/service/networkinfo/service.go
api/service/networkinfo/service_test.go
cmd/client/txgen/main.go
cmd/client/wallet/main.go
cmd/client/wallet_stress_test/main.go
cmd/harmony/main.go
consensus/consensus_msg_sender.go
consensus/consensus_v2.go
consensus/view_change.go
drand/drand_leader.go
drand/drand_validator.go
internal/configs/node/config.go
internal/configs/node/config_test.go
internal/configs/node/group.go
internal/configs/node/group_test.go
node/node.go
node/node_cross_shard.go
node/node_handler.go
node/node_resharding.go
node/service_setup.go
p2p/host.go
p2p/host/hostv2/hostv2.go
p2p/host/hostv2/hostv2_test.go
p2p/host/mock/host_mock.go
p2p/p2p.go

this is solve the problem of validators in different network connected
with each others.
* mainet is still using the original harmony prefix to keep backward
compatibility
* pangaea uses "pangaea" as network prefix
* testnet uses "testnet" as network prefix
All nodes in Pangaea and Testnet need to restart to re-connect with each
other.  Mainnet nodes have no changes.

[p2p] add network type prefix to group id

---

consensus/consensus_v2.go
crypto/vdf/vdf.go
drand/drand_leader.go
go.mod
internal/hmyapi/filters/api.go
internal/memprofiling/lib.go
internal/profiler/profiler.go
msgq/msgq.go
msgq/msgq_test.go
node/node.go
node/node_cross_shard.go
node/node_handler.go
node/node_syncing.go

Do not spawn unbounded number of goroutines for parallel message processing.  Instead, use a worker pool of 32 goroutines sharing the same intake queue.  Log (`"rx overrun"`) and tail-drop messages if the queue is full.
Local test pass; 100% coverage of the newly added core code (`./msgq`):
```sh
git checkout harmony-one/master
go test -count=1 -cover ./... > coverage-before.txt
git checkout limit_concurrency 
go test -count=1 -cover ./... > coverage-after.txt
sed -i.bak -E 's/  [0-9]+(\.[0-9]*)?s      /       /' coverage-*.txt
diff -U0 coverage-before.txt coverage-after.txt
```
```diff
--- coverage-before.txt 2019-10-08 16:13:42.000000000 -0700
+++ coverage-after.txt  2019-10-08 16:13:42.000000000 -0700
@@ -86 +86,2 @@
-ok     github.com/harmony-one/harmony/node     coverage: 15.4% of …
```

Limit concurrency

---

msgq/msgq.go
node/node.go
node/node_handler.go

This way, a flood of client messages doesn't overwhelm shard queue
(consensus messages) or global queue (cross-shard transaction receipts).

Use per-group-receiver message queue

---

accounts/address.go

Quick way to expose value from `internal/common/address`, needed for client consumers like go-sdk. 
I tried doing the right, full refactor but it was becoming a massive refactor & no real benefit for that at this time.

[accounts] Expose internal Address value, parsing

---

internal/hmyapi/harmony.go

Exposed ShardID of answering RPC node. Note, this will have to be smarter once resharding takes place. 
Useful for downstream projects, namely `harmony-watchdogd`

[rpc] Expose ShardID in NodeMetadata

---

core/core_test.go
internal/configs/sharding/testnet.go
internal/params/config.go

Now it's 75 blocks/epoch, without epoch-0 exception.  At 8 seconds/block, it amounts to 10 minutes/epoch.
Resize testnet to 100 nodes/shard * 3 shards = 300 nodes.  Shard 0/1 are Harmony-operated for now; shard 2 is operated/managed by P-OPS.
Also disable crosslinks and staking transactions because they are not used yet, and enable cross-shard transaction at genesis.
We reuse existing testnet keys.

Update Pangaea/testnet epoch/feature schedule

---

api/service/syncing/syncing.go
core/blockchain.go
node/node_handler.go
test/chain/main.go

During new node syncing specifically, we perform block header verification before insertChain(), not for every block, but for every 100 blocks batch (changed maded by @rlan35 )
But insertChain itself verifies every block header anyways, so we have been unnecessarily verifying block headers in the entire block chain being synced for new nodes twice.
This PR fixes it by adding the option in insertChain() function to not perform verification of block headers.
* Before
* After

add verifyHeaders option to blockchain.insertChain()

---

core/blockchain.go
internal/hmyapi/blockchain.go

Issue explained by Richard, quite lots of apps depend on hmy_getBlockByHash and hmy_getBlockByNumber and args formats needs to be fixed in all of them accordingly, which will take time. To not break those apps need to add compatibility back. Unfortunately it's not possible to merge methods as blockArgs struct can't be parsed to bool and missing args cause errors. So I brought back old methods and also renamed new ones by adding New in the end. They will be still available with hmy api.
Also small fix for hmy_getValidatorInformation api for slot pub keys.
Localnet, postman. New and old methods work okay.
* Before
* After

Add old api compatibility back

---

Makefile
scripts/go_executable_build.sh

Build:
a. git pull bls again to get the latest bls 
b. make linux_static
Limitation:  must build the binary under Ubuntu Linux (tested on 18.04 LTS)
I tested the generated binary with different combinations
1) Mac:  can't build static link in Mac 
2) Linux:   build on ubuntu, run on ubuntu , this works
build on ubuntu, run on centos/ami,  doesn't work
build on  centos,  run on centos,  doesn't work
NOTE:  Got some warning during linking process, which makes the static binary will have porting issue when libc is different. It is a Golang issue to me,  more information regarding this issue can be found here (https://jira.hyperledger.org/browse/FABC-313)
/tmp/go-link-996576825/000029.o: In function `mygetgrouplist':
getgrouplist_unix.cgo2.c:(.text+0x60): warning: Using 'getgrouplist' in …

added support for building static binary on Linux platforms

---

api/service/syncing/errors.go
api/service/syncing/syncing.go
node/node_syncing.go

This PR is a prep pr for the following the "robust new node state sync design" work.
Proper error handling is needed to gracefully handle state sync failures and take action more robustly.
Includes some minor naming, changes, and logging.
Ran local network, and confirm that consensus is reached.
```
BINGO !!! Reached Consensus
```
and also check that errors are logged properly.
```
ubuntu@ip-172-31-16-131:~/harmony-one/harmony/node (robust_state_sync) $ go test -cover
PASS
coverage: 14.6% of statements
ok  	github.com/harmony-one/harmony/node	2.485s
ubuntu@ip-172-31-16-131:~/harmony-one/harmony/node/worker (robust_state_sync) $ go test -cover
PASS
coverage: 24.3% of statements
ok  	github.com/harmony-one/harmony/node/worker	0.113s
```

Make ProcessStateSync to return error

---

api/service/explorer/storage.go

When running explorer, every time we restart it, this dumps megabytes of
messages into zerolog, overwhelming logstash.

Comment out "Dumping block" message

---

scripts/node.sh

The current node.sh script uses old bootnodes for the testnet - this PR updates node.sh to use the new set of bootnodes.
This PR also streamlines the testnet configuration to only use Pangaea going forward.

Update node.sh to use the new set of bootnodes for the testnet + merge the testnet sections

---

api/service/networkinfo/service.go

Previously the retry time is 10 mins and it will block the whole client process for 10 mins if a single bootnode fails to connect. Reduce the retry time to 30s, so it won't appear that the node is stuck for a long time.

Reduce wait time for bootnode connection to 30s

---

consensus/consensus_leader_msg_test.go
consensus/engine/consensus_engine.go
consensus/quorum/one-node-one-vote.go
consensus/quorum/one-node-staked-vote.go
consensus/reward/rewarder.go
internal/chain/engine.go
internal/chain/reward.go
node/node.go

This is PR #3 of breaking this PR #1762 into smaller PRs, assumes PR#1, PR#2 merged into master, then will rebase this one to reflect that.
1. Create package reward, has one interface, Distributor, reward.Distributor now a factored out block rewarder 
2. Use quorum type as the Awarder in engine/reward.go
3. Double checks that the paid out amount is indeed total amount as block-reward

[reward] Abstract out block-reward, use rewarder, check result correct 

---

test/deploy.sh

* `./test/deploy.sh` will now create validators using the hmy CLI. This set-up also allows us to easily add more staking tests/tools in the future.
> *Dependencies*: Python3 + [requests package](https://pypi.org/project/requests/) + [pyhmy package](https://pypi.org/project/pyhmy/) + built hmy CLI binary in `harmony-one/go-sdk` + latest version of `harmony-one/harmony-ops` cloned. (Packages are checked and installed if needed in `./test/deploy.sh`)
**Do not merge this to master until [this PR](https://github.com/harmony-one/harmony-ops/pull/235) is merged to master**

Add staking debugging tools to localnet deploy script

---

go.mod
staking/effective/calculate.go
staking/effective/calculate_test.go

* Generate random purchase data to test calculate.go
* Add unit test for median function
* Update JSON to pretty print randomly generated data for debug
In `median()`, in the case that `len(stakes)` is even, the median is being calculated from the `l / 2 - 1` and `l / 2 + 1` index of stakes.
If `len(stakes) = 20`, the left index will be `20 / 2 - 1 = 9` and the right index will be `20 / 2 + 1 = 11` and the median value will be `stakes[9] + stakes[11] / 2`, whereas the median value should be taken as `stakes[9] + stakes[10] / 2`.
Randomized testing data:
```json
{
"slots": [
{
"slot-owner": "one1qqqqqqqqqqqqqqqqqqqqp7cu00grrnq6mfapw9",
"bls-public-key": "364a33574556594c454e444242564f364b4b424648355951503338424858324b5845475844464c4753374237535a3456",
"actual-stake": …
```

[staking-testing] Fix staking median logic

---

internal/hmyapi/blockchain.go

Also change hmy_getValidatorInfo => hmy_getValidatorInformation to preserve compatibility as much as possible. Format for hmy_getValidatorInformation has changed. 
// RPCValidator represents a validator
type RPCValidator struct {
Address            common.Address       `json:"address"`
SlotPubKeys        []shard.BlsPublicKey `json:"slot_pub_keys"`
Stake              *big.Int             `json:"stake" yaml:"stake"`
UnbondingHeight    *big.Int             `json:"unbonding_height"`
MinSelfDelegation  *big.Int             `json:"min_self_delegation"`
MaxTotalDelegation *big.Int             `json:"max_total_delegation"`
Active             bool                 `json:"active"`
Commission         types2.Commission    `json:"commission"`
Description        types2.Description   `json:"description"` …

One address support where its missing

---

internal/chain/reward.go

Adjust block reward in staked case when deviates from the 35% target rate.

[WIP] [reward] Adjust block reward by % of current staked

---

consensus/votepower/roster.go

RawStake isn't being set for each StakedVoter when creating the Roster.
**NO**
**NO**
**NO**

[staking] Set RawStake per voter when creating roster

---

consensus/votepower/roster.go
consensus/votepower/roster_test.go
shard/shard_state.go
staking/effective/calculate_test.go

#1860 
Done: compute in `roster.go` & effective stake in`calculate.go`
**NO**
**NO**
**NO**
#1860 
`assignment.go` & `one-node-staked-vote.go` & apply in `calculate.go`

[unit-testing] Add units test for roster.go & calculate.go

---

api/service/networkinfo/service.go

Previously, `networkinfo` used a global context was being used with a 3-minute timeout.  This caused all `networkinfo` discovery/advertisement activities to stop working 3 minutes after the node startup.
Fix this by eliminating the global 3-minute context and making its consumers use locally created contexts:
* `New` uses a context that does not time out;
* `(*Service).Init` uses a context that times out in 3 minutes;
* `(*Service).DoService`—the service “body”—uses a context that does not time out;
* `(*Service).findPeers` accept a context from its caller, `DoService`.
Before:
```
ok      github.com/harmony-one/harmony/api/service/networkinfo  2.417s  coverage: 25.0% of statements
```
After:
```
ok      github.com/harmony-one/harmony/api/service/networkinfo  2.262s  coverage: 25.0% of …
```

Fix networkinfo context handling

---

internal/hmyapi/blockchain.go
internal/hmyapi/types.go

Staking txs should be optional at least for now for view in blocks. Also added optional bool param inclStaking to blockArgs to not break hmy_getBlockByHash and hmy_getBlockByNumber. Those will need to have update on block explorer and other sides to support new input with blockArgs and not break anything. For them staking txs not included by default but can be set included by default.
Before:
```
```
After:
```
```
**YES|NO**  NO
2. **Describe the migration plan.**. For each flag epoch, describe what changes take place at the flag epoch, the anticipated interactions between upgraded/non-upgraded nodes, and any special …

Make staking txs optional in blocks

---

scripts/node.sh

This enables node.sh to connect to devnet.  It also includes manual override of shard ID, required for the time being when running a staking node with node.sh.
Script-only change, no UT coverage.
`sudo ./node.sh -k XXXXXXXXXXXXXXXXX.key -N dev -i 1` connects to the devnet shard 1 and starts making consensus.
1. **Does this PR introduce backward-incompatible changes to the on-disk data structure and/or the over-the-wire protocol?**. (If no, skip to question 2.)
NO
2. **Does this PR introduce backward-incompatible changes *NOT* related to on-disk data structure and/or over-the-wire protocol?** (If no, continue to question 11.)
NO …

node.sh devnet

---

consensus/quorum/one-node-staked-vote.go
consensus/quorum/one-node-staked-vote_test.go
consensus/votepower/roster.go

* Add test for when there are 33 Harmony nodes	
* Add test for Policy
* Add test for QuorumThreshold
#1860 
`go test -v -count=1 github.com/harmony-one/harmony/consensus/quorum/...`
Before:
```
```
After:
```
```
**NO**
**NO**
**NO**

[unit-testing] one-node-staked-vote

---

consensus/quorum/one-node-staked-vote_test.go

* Generate Decider for base case of 50/50 nodes
* Add Quorum Achieved tests for all Staker nodes & all nodes signed
* Add QuorumAchieved tests for all Harmony nodes signed
* Add RewardThreshold tests for all above cases
#1860 
```
$ go test -v -count=1 github.com/harmony-one/harmony/consensus/quorum/...
=== RUN   TestPolicy
--- PASS: TestPolicy (0.00s)
=== RUN   TestQuorumThreshold
--- PASS: TestQuorumThreshold (0.00s)
=== RUN   TestEvenNodes
--- PASS: TestEvenNodes (0.19s)
=== RUN   Test33HarmonyNodes
--- PASS: Test33HarmonyNodes (0.08s)
PASS
ok  	github.com/harmony-one/harmony/consensus/quorum	0.320s
```
**NO**
8. **Does this PR …

[unit-testing] Finish one-node-staked-vote tests

---

consensus/reward/schedule.go
consensus/reward/schedule_test.go

* Fix wrong date in release schedule map
* Fix panic when PercentageForTimeStamp receives time before first bucket & time after last bucket
#1860 
```
$ go test -v -count=1 github.com/harmony-one/harmony/consensus/reward/...
=== RUN   TestPercentageForTimeStamp
--- PASS: TestPercentageForTimeStamp (0.00s)
PASS
ok  	github.com/harmony-one/harmony/consensus/reward	0.051s
```
**NO**
**NO**
11. **Does this PR introduce significant changes to the operational requirements of the …

[unit-testing] Add test for schedule.go

---

internal/hmyapi/blockchain.go

After testing APIs, staking txs are returned correctly for all cases on devnet. Block APIs simply parse it one by one and so it works for block APIs as well. Enabling it by default.
create-validator: 0x21ff643299626186599723596c3b861c17042491bf53fab5899db25044884b67
edit-validator: 0x294e02b7b0229bbdff884db90d659e6d737894ec37d47e5d3496d1bf156be55d
delegate: 0xbb8736abfb85eae13bab107a3e63aa4bc13f88141ddc6b4a84352e1ac960a6d0
undelegate: 0x16de0f7e1171650675a2b3977e506169a23eefe5336a946fc495b97dc122892a
collect-rewards: 0x52ac72e5e9b392c5299282c43c3a6e3c983ad95b4a2ceda175cca17477358af0
Before:
```
```
After:
```
```
**YES|NO**
2. …

Show staking txs in blocks by default

---

consensus/engine/consensus_engine.go
core/chain_makers.go
core/state_transition.go
internal/chain/engine.go

Besides negative balances checks.
For delegate, the balance should be subtracted by the delegation leftover instead of the whole amount.
For undelegate, we should check against all the validators, rather than only the active ones.

fix bug on undelegate and delegate

---

block/factory/factory.go
core/block_validator.go
core/blockchain.go
core/state_processor.go
internal/params/config.go
node/node_newblock.go

e79ba5fe880b56973a50a80d918b9145fce07cf0 introduced an off-by-one error which caused cross-shard-transaction-enabled header (v1) to be introduced one epoch later than expected, i.e. at `CrossTxEpoch+1`, where it should be introduced at `CrossTxEpoch`.  This was caused by a vague, confusing naming of `IsCrossTx(epoch)` function of `ChainConfig`: The name did not clarify whether it meant introduction of CX-enabled header and processing of ingress receipts (which occurs at `CrossTxEpoch`) or acceptance of cross-shard transactions (which occurs at `CrossTxEpoch+1`).
Introduce and use `params.(*ChainConfig).HasCrossTxFields` which handles the former case, and rename `params.(*ChainConfig).IsCrossTx` to `AcceptsCrossTx` to clarify its intention.
Also fix three cases where `IsCrossTx` was …

Fix CrossTxEpoch handling

---

internal/configs/sharding/testnet.go
internal/params/config.go

- Pre-staking starts at epoch 5256, around 2019-12-05T17:46:17Z
- Staking starts at epoch 5328, around 2019-12-06T05:46:17Z
Calculation is based upon Pangaea shard 0 block height 391440 at 2019-12-05T11:38:17Z.

Schedule Pangaea staking epochs

---

api/service/explorer/service.go
api/service/explorer/storage.go
api/service/explorer/storage_test.go
api/service/explorer/structs.go
cmd/harmony/main.go
node/node_explorer.go

Code with committee is redundant now, because we're using hmy api for explorer and also it started causing strange error https://github.com/harmony-one/harmony/issues/1990. hmy api also doesn't use it. So best solution to simply remove it.
I run all APIs, localnet and tests locally. Also removed committee from all places and there were no crashes.
Before:
```
```
After:
```
```
NO
3. **Describe how the …

Remove committee in explorer service

---

internal/hmyapi/transactionpool.go
internal/hmyapi/types.go

TrustWallet requested tx timestamp to be returned in transactions api. They need it tomorrow. They either can query block right now and take timestamp there or we can update explorer nodes separately from mainnet now. 
Before:
```
```
After:
```
```
NO
4. **How much minimum baking period after the last flag epoch should we allow on Pangaea before promotion onto …

Add timestamp to transactions json

---

cmd/bootnode/main.go
cmd/client/txgen/main.go
cmd/client/wallet/main.go
cmd/client/wallet_stress_test/main.go
cmd/harmony/main.go
cmd/keygen/main.go
internal/utils/utils.go
p2p/host/hostv2/hostv2.go
p2p/host/hostv2/util.go
p2p/p2pimpl/p2pimpl.go

`harmony`, `bootnode`, `wallet`, and friends panic upon various initialization errors without printing details/root causes.  Convert panics into stderr prints + graceful exits with status 1.
No change (top-level commands are not covered by UT).
When `bootnode` is run as a regular user with the cache directory with no read-write permission (stdout redirected to devnull to omit `BN_MA` message):
```
$ bin/bootnode > /dev/null
open .dht-127.0.0.1-9876: permission denied
cannot open directory ".dht-127.0.0.1-9876"
github.com/dgraph-io/badger.acquireDirectoryLock
/Users/ek/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0-rc1/dir_unix.go:56
github.com/dgraph-io/badger.Open
/Users/ek/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0-rc1/db.go:231
github.com/ipfs/go-ds-badger.NewDatastore …
```

Emit fatal init error details to stderr w/o panics

---

internal/hmyapi/transactionpool.go
internal/hmyapi/types.go

Same PR just for s3.
Before:
```
```
After:
```
```
NO
Note that this must be enough to cover …

Add rpc transaction timestamp

---

cmd/harmony/main.go
internal/utils/utils.go
libp2pctl/server.go

Make it possible to control P2P connections from outside the harmony binary without having to restart or reconfigure it.  Also expose connection stats.
Since this is a disruptive operation, it requires client authentication (TLS cert auth).  Usability is to be determined/improved.
TODO
TODO
1. Does this PR introduce backward-incompatible changes to the on-disk data structure and/or the over-the-wire protocol? – **No**
s know about this planned change?**
8. Does this PR introduce backward-incompatible changes *NOT* related to on-disk data structure and/or over-the-wire protocol? – **No**
11. Does this PR introduce significant changes to the operational requirements of the node software, such as >20% increase in CPU, memory, and/or disk usage? – **No**

Add libp2pctl

---

internal/configs/node/config.go
internal/params/config.go

Cannot do staking tests with current localnet config.
**NO**
**NO**
**NO**
Note: `test/deploy.sh` & `test/debug.sh` does not need to be changed as it already uses the Localnet network type.

[config] Add localnet config for staking

---

core/evm.go
core/state_processor.go
core/vm/evm.go
core/vm/runtime/env.go

- checking to.address() is staking validator addr or not
- avoid create cxReceipts in case of evm execution fail

fix mint new tokens when transfer money to validator addr

---

internal/hmyapi/harmony.go

for downstream consumer like watchdog, so we can easily know which node is explorer + its IP

[rpc] Expose node's role into Metadata RPC

---

internal/hmyapi/transactionpool.go

```
curl -H Content-Type:application/json -d '{"jsonrpc":"2.0", "method":"hmy_pendingTransactions", "params":[], "id":1}' -X POST http://localhost:9599 | json_pp
100   710  100   636  100    74   621k  74000 --:--:-- --:--:-- --:--:--  693k
{
"jsonrpc" : "2.0",
"result" : [
{
"from" : "one1spshr72utf6rwxseaz339j09ed8p6f8ke370zj",
"transactionIndex" : "0x0",
"input" : "0x",
"toShardID" : 1,
"nonce" : "0x4",
"blockNumber" : null,
"timestamp" : "0x0",
"s" : "0x7bda988a1992174b4cae8cd4aedc6a38e66ceddcf276d521f54394f41aabe2ca",
"to" : "one1r4zyyjqrulf935a479sgqlpa78kz7zlcg2jfen",
"v" : "0x27",
"value" : "0x16345785d8a0000",
"hash" : …
```

[rpc] Simplify Pending txn

---

hmy/api_backend.go

@mattlockyer found issue with past logs, turns out on api_backend they were not implemented.
Before:
```
```
After:
```
```
**YES|NO**
6. **What are the planned flag …

Fixes for tx logs master

---

Dockerfile

CLI wouldn't build with the old Dockerfile
I ended up moving the environmental variables to the Dockerfile itself.
**NO**
2. **Does this PR introduce backward-incompatible changes *NOT* related to on-disk data structure and/or over-the-wire protocol?** (If no, continue to question 11.)
**NO**
3. **Does the existing `node.sh` continue to work with this change?**
Yes.
Add or remove default programs.

Changed Dockerfile to get CLI to work

---

scripts/node.sh

any_new_binaries function was misplaced, it is missing in the
download_only mode. move it up before the download only mode call.

[node] fix func not defined issue

---

core/types/gen_cx_receipt_json.go
internal/hmyapi/apiv1/transactionpool.go
internal/hmyapi/apiv2/transactionpool.go

Edgar asked to output bech32 addresses and return empty array instead of null in case there are no cross links.
Before:
```
```
After:
```
```
**YES|NO**
6. **What are …

Crosslinks and cxreceipts update API format

---

core/types/gen_cx_receipt_json.go
hmy/api_backend.go
hmy/backend.go
internal/hmyapi/backend.go
internal/hmyapi/transactionpool.go
node/rpc.go

Edgar requested cross links and cx receipts to be moved to master, but node.pendingCrossLinks is missing, so moving only receipts for now.
Tested, method is available and works the same.
Before:
```
```
After:
```
```
**YES|NO**
5. **What are …

Add pending CX receipts API to master

---

internal/hmyapi/apiv1/types.go
internal/hmyapi/apiv2/types.go

Yuriy have seen that RPCStakingTransaction fetch method return 0x addresses. I'm changing to bech32, also need to check if it doesn't break anything for apps. @mikedoan @fxfactorial @rlan35 
Localnet, postman. Test please if it doesn't break anything.
Before:
```
```
After:
```
```
NO
4. **How much minimum baking period after the last flag epoch should we allow …

Fix format in staking transaction

---

internal/params/config.go

`hmy_getNodeMetadata` reply formatting is inconsistant
```
$ ./hmy utility metadata
{
"id": "0",
"result": {
"blocks-per-epoch": 5,
"blskey": "65f55eb3052f9e9f632b2923be594ba77c55543f5c58ee1454b9cfd658d25e06373b0f7d42a19c84768139ea294f6204",
"chain-config": {
"chainId": 2,
"crossLinkEpoch": 3,
"crossTxEpoch": 0,
"eip155Epoch": 0,
"s3Epoch": 0,
},
"current-epoch": 0,
"is-leader": true,
"network": "localnet",
"role": "Validator",
"shard-id": 0,
"version": "Harmony (C) 2019. harmony, version v5472-master-20191208.0-95-ge2003b48-dirty (edgar@ 2020-01-20T17:11:16-0800)"
}
}
```
```
$ ./hmy utility metadata
{
"id": "0",
"result": {
"blocks-per-epoch": 5,
"blskey": "65f55eb3052f9e9f632b2923be594ba77c55543f5c58ee1454b9cfd658d25e06373b0f7d42a19c84768139ea294f6204 …
```

[rpc] Update ChainConfig JSON tags to match RPC reply format

---

internal/hmyapi/apiv1/transactionpool.go
internal/hmyapi/apiv2/transactionpool.go

Edgar noticed that ErrorSink always returns empty array. Turns out some commit or myself deleted this method accidentelly from api. Bringing back.
Before:
```
```
After:
```
```
**YES|NO**
5. **What are the planned flag epoch numbers and their …

Return txerror

---

core/tx_pool.go
core/tx_pool_test.go
node/node.go
node/node_handler_test.go
node/node_newblock.go
node/worker/worker.go
node/worker/worker_test.go
test/chain/main.go

Currently, one can only get failed/errored transactions if one knows the leader's IP address. This PR checks for failed transactions in the transaction pool, this any node can report failed or errored transactions.
Before:
```
newNodeList:  [ECDSA: one1qqqrvvpcxu6rwvfnxc6ngvecx5mrgvf3254yj4, BLS: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 ECDSA: one1qq6n2de3xuuryven8qcnqvfcxuurwd3s837n5r, BLS: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 ECDSA: one1qqcnjv3kxqcnydfcxc6nyd3kxg6rqvpe5srx9h, BLS: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 ECDSA: one1qqqrgvp5xy6nxwf5x5mngve4xsmnvdfhekh0gx, BLS: …
```

Fix get failed/errored transactions sink

---

api/service/syncing/syncing.go
api/service/syncing/syncing_test.go

https://github.com/harmony-one/harmony/issues/1313
This PR makes the new node syncing process more robust with retries where for each try, the *previously failed sync peer config* selected as the max consensus hash (the most common block hashes of the header chain is in each sync batch) is excluded on the subsequent retries during sync peer config selection.
The updated logic, therefore, is that, if process state sync fails during chain insertion, the retry will then try with the next most common sync peer config as the source of state syncing for that batch.
artificially made the first try to fail by throwing an error from process state sync, and on the next try, subsequent sync peer config is used (which I again artificially made the 2nd common sync peer config to be the same as the …

[StateSync] add retries to process state sync where failed peer config is excluded on the next try

---

core/tx_pool.go
core/types/transaction.go
node/node.go

Currently, an explorer node only broadcasts transactions and does not processes it. This PR makes the explorer process and broadcast transactions. Moreover, there are some missing error reports when a promotion removes a transaction. This PR adds those errors to the error sink. 
Before:
```
PASS
coverage: 13.3% of statements
ok  	github.com/harmony-one/harmony/node	2.301s
```
```
newNodeList:  [ECDSA: one1qqqrvvpcxu6rwvfnxc6ngvecx5mrgvf3254yj4, BLS: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 ECDSA: one1qq6n2de3xuuryven8qcnqvfcxuurwd3s837n5r, BLS: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 ECDSA: one1qqcnjv3kxqcnydfcxc6nyd3kxg6rqvpe5srx9h, BLS: …
```

Report failed transactions

---

core/tx_pool.go
core/tx_pool_test.go
core/types/transaction.go
node/node.go
node/node_handler_test.go
node/node_newblock.go
node/worker/worker.go
node/worker/worker_test.go
test/chain/main.go

Similar to #2157 #2151, this PR will report failed (non-staking) transactions on all nodes instead of just on the leader. 
Before:
```
PASS
coverage: 13.6% of statements
ok  	github.com/harmony-one/harmony/node	2.391s
```
```
PASS
coverage: 19.5% of statements
ok  	github.com/harmony-one/harmony/core	6.853s
```
After:
```
PASS
coverage: 14.0% of statements
ok  	github.com/harmony-one/harmony/node	2.067s
```
```
PASS
coverage: 20.4% of statements
ok  	github.com/harmony-one/harmony/core	6.656s
```
**NO**
8. **Does this PR introduce backward-incompatible changes *NOT* related to on-disk data structure and/or over-the-wire protocol?** (If …

Report failed (non-staking) transactions

---

internal/hmyapi/apiv2/blockchain.go
internal/hmyapi/apiv2/transactionpool.go
internal/hmyapi/backend.go
node/rpc.go

I checked today, turns out hmy_v2 prefix fails to find rpc methods, though hmyv2 works okay. Probably underscore breaks namespacing and I tested it incorrectly before.
No one is using protocol yet and if it were then hmy_v2 bug would be noticed sooner.
Also changed blockNr arg to uint64 for api v2.
Before:
```
```
After:
```
```
**YES|NO**
4. **How much minimum …

hmyv2 is back for s3

---

BLACKLIST.md
cmd/client/txgen/main.go
cmd/client/wallet/main.go
cmd/client/wallet_stress_test/main.go
cmd/harmony/main.go
core/tx_pool.go
core/tx_pool_test.go
node/node.go
node/node_handler_test.go
node/node_test.go
scripts/node.sh

Cherry-picked from #2172.
In the (unlikely) event of a successful attack/hack, implementing and rolling out a solution will take some time. A blacklist offers an easy and fast way to contain the situation while we work out a solution. 
The blacklist that we will be using will be maintained in the main repo's root for everyone to see (it will start off empty). Moreover, any transaction that was dropped because of a blacklisted account will be reported as such in our newly added `hmy_getCurrentTransactionErrorSink` RPC; which means it will be displayed in our explorer. 
* The blacklist is read from a newline delimited file (by default it's `./blacklist.txt`).
* Each transaction added to the tx-pool has its `to` and `from` address checked against this blacklist. If there is a hit, the …

S3 blacklist

---

scripts/node.sh

There are no network settings for the staking testnet in node.sh
```
$ curl -LOs https://raw.githubusercontent.com/SebastianJ/harmony/nodesh-staking-network/scripts/node.sh && chmod u+x node.sh && curl -LO https://harmony.one/hmycli && mv hmycli hmy && chmod u+x hmy
$ ./hmy keys generate-bls-key
$ ln -s *.key bls.key
$ ./node.sh -k bls.key -N staking -z -S
node.sh: using manually specified BLS key file: bls.key
diff: md5sum.txt: No such file or directory
node.sh: downloaded harmony
node.sh: downloaded wallet
node.sh: downloaded bootnode
node.sh: public IP address autodetected: xxx.xxx.xxx.xxx
Enter passphrase for the BLS key file bls.key: 
node.sh: ############### Running Harmony Process ###############
Staking mode; node key 375b66371991246bcd27737d4ab85e74cd3c39c888278c4eefd0fcafa6a80fa3 …
```

Add staking network settings to node.sh

---

README.md
hmy/api_backend.go
internal/hmyapi/apiv1/backend.go
internal/hmyapi/apiv1/blockchain.go
internal/hmyapi/apiv2/backend.go
internal/hmyapi/apiv2/blockchain.go
internal/hmyapi/backend.go

hmy_getBalanceByBlockNumber returns balance for a particular block number. hmy_getBalance returns for current block.
Before:
```
```
After:
```
```
**YES|NO**
6. **What …

Balance by block s3

---

internal/hmyapi/apiv2/types.go

During testing on testnet found that block returns with hex numbers. Turns out it didn't make it from master to s3, which is odd.
Before:
```
```
After:
```
```
**YES|NO**
5. **What are the planned flag epoch numbers and their ETAs on …

[hotfix] Missing block decimal marshalling

---

staking/types/validator.go

https://github.com/harmony-one/harmony/issues/2196
Before:
```
```
After:
```
```
**YES|NO** …

making min/max delegations string instead of uint64

---

hmy/api_backend.go

Small typos in utility metrics but they don't affect functionality.
Before:
```
```
After:
```
```
**YES|NO**
6. **What are the planned flag epoch numbers and their ETAs …

Few typos in utility metrics

---

internal/hmyapi/apiv1/blockchain.go
internal/hmyapi/apiv2/blockchain.go

#2197 
$ hmy blockchain validator metrics one1txy0a2szxlk7z0dvvfgv24kjjv60w2mcnyfl8a
Metrics are only available for Validators that have participated in consensus committee.
commit: v267-ab1654e, error: Catch all RPC error: validator stats not found: one1txy0a2szxlk7z0dvvfgv24kjjv60w2mcnyfl8a
check hmy cookbook for valid examples or try adding a `--help` flag

[#2197] Return error address in BECH32, instead of hex

---

scripts/docker/Dockerfile
scripts/docker/docker-node.sh
scripts/docker/run

Test:
* put the keyfile and blspass.txt into keys/ directory
* start the docker image
sudo ./docker-node.sh -t test keyfile blspass.txt
* all logs will be stored in logs/ directory
* all db will be stored in db/harmony_db_0,1,2,3 directories
* to check the running log of the docker image
sudo docker logs -f harmony-test-9000

[docker] updated docker support for mainnet

---

cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_leader_msg.go
consensus/consensus_leader_msg_test.go
consensus/consensus_service.go
consensus/consensus_service_test.go
consensus/consensus_test.go
consensus/consensus_v2.go
consensus/consensus_validator_msg.go
consensus/consensus_validator_msg_test.go
consensus/consensus_viewchange_msg.go
consensus/fbft_log_test.go
consensus/view_change.go
internal/configs/node/config.go
internal/configs/sharding/testnet.go
node/node.go
node/node_handler.go
node/node_handler_test.go
node/node_metrics.go
node/node_newblock.go
node/node_test.go

- [testnet] use a new testnet for multi-key test
- adding support for multiple initial accounts for multi-key scenarios
- minor fixes
- changing viewchange duration to exponential
[multi-key] use 2 shards for testnet of multi-key (#2)
Before:
```
```
After:
```
```
**YES|NO**
4. …

multi bls key support

---

api/service/syncing/syncing.go
api/service/syncing/syncing_test.go

Reverts harmony-one/harmony#1835
as attempt to triage issue of https://github.com/harmony-one/harmony/issues/2203

Revert "[StateSync] add retries to process state sync where failed peer config is excluded on the next try"

---

cmd/harmony/main.go

Our validators are used to use Ctrl+c to shut down the node. We should keep that behavior as is.

Shutdown the node program for sys interrupt too

---

hmy/api_backend.go

When querying the validator information, if the validator is not found cli was showing `{}`.
With this fix, cli will report validator not found.
```
./hmy blockchain validator information one1...
commit: v275-874cc27, error: Catch all RPC error: validator not found: one1...
```

when validator not found, don't try to extract it from the wrapper

---

core/staking_verifier.go
core/state_processor.go
core/state_transition.go
core/tx_journal.go
core/tx_list.go
core/tx_list_test.go
core/tx_pool.go
core/tx_pool_test.go
core/types/transaction.go
core/types/tx_pool.go
hmy/api_backend.go
internal/hmyapi/apiv1/backend.go
internal/hmyapi/apiv1/transactionpool.go
internal/hmyapi/apiv1/types.go
internal/hmyapi/apiv2/backend.go
internal/hmyapi/apiv2/transactionpool.go
internal/hmyapi/apiv2/types.go
internal/hmyapi/backend.go
node/node.go
node/node_handler_test.go
node/node_newblock.go
node/worker/worker.go
node/worker/worker_test.go
staking/types/rpc-result.go
staking/types/transaction.go
staking/types/validator.go
test/chain/main.go

The transaction pool only accepts plain transactions and needs to be generalized to handle staking transactions. Moreover, only the leader can report failed staking transaction errors ( similar to #2160 ). Lastly, staking messages are only verified when they are applied, this should be separated so staking msg verification can be done at an earlier stage like the tx pool.
* Abstracts transactions in the tx pool by using a `PoolTransaction` interface. This also required some rework of the `tx_list.go` and `tx_journal.go`. This is most of the PR. 
* Implement methods for `StakingTransactions` to satisfy the tx pool interface. 
* Refactor error reporting in tx pool to handle multiple error sinks.
* Add staking transaction checks in the tx pool and report any errors to the error sink.
* …

Abstract transactions in tx pool and add staking transaction to pool with error report

---

internal/hmyapi/apiv1/blockchain.go
internal/hmyapi/apiv2/blockchain.go

@mikedoan requested block epoch.
Before:
```
```
After:
```
```
**YES|NO**
Note that this must …

Add block epoch

---

node/node_explorer.go

Explorer node is lagging on OSTN, because it's not processing `COMMITTED` messages from the leader & the node is only getting blocks from state syncing blocks.
Early return caused by inverted conditional.

[debug] Fix explorer node lagging behind

---

internal/hmyapi/apiv1/blockchain.go
internal/hmyapi/apiv2/blockchain.go

GetAllDelegationInformation is used to get all delegation info from `pageSize` validators.
This issue was introduced to avoid my requests from staking dashboard backend if # of validators is big like (4k, or 40k).

add GetAllDelegationInformation

---

internal/configs/sharding/testnet.go

For multi key network launch we changed the testnet config to 2, 30, 30. Reverting this back to 3, 10, 10.

changing the testnet config back to normal

---

cmd/harmony/main.go
core/tx_list_test.go
core/tx_pool.go
core/tx_pool_test.go
core/types/tx_pool.go
node/node.go
staking/types/transaction.go

The tx-pool currently does not check for the ShardID and there is a slight programming error for the blacklist (pointer to a map). Both are fixed with this PR.
Before:
```
PASS
coverage: 14.7% of statements
ok  	github.com/harmony-one/harmony/node	1.997s
```
```
PASS
coverage: 21.6% of statements
ok  	github.com/harmony-one/harmony/core	6.843s
```
After:
```
PASS
coverage: 14.7% of statements
ok  	github.com/harmony-one/harmony/node	2.352s
```
```
PASS
coverage: 21.7% of statements
ok  	github.com/harmony-one/harmony/core	6.709s
```
**NO**
8. **Does this PR introduce backward-incompatible changes *NOT* related to on-disk data structure …

Add shard checking to Tx-Pool & correct blacklist

---

hmy/api_backend.go

Small fix that takes validator bls pub keys into account when calculating median stake.
Before:
```
```
After:
```
```
**YES|NO**
6. **What are the planned flag epoch …

Fix median stake calc

---

node/node.go

Previously we blindly re-broadcast all received txns from RPC no matter it's valid or spammer txns. This pr correct that to only rebroadcast the txn if the current node think it's valid (not being a aid to spammers)
Tested locally, it shielded the spamming effect from other nodes.

only broadcast valid transactions

---

core/blockchain.go
core/offchain.go
internal/params/config.go

The last continuous crosslink logic doesn't work anymore after the batch update of offchain data.
Fixed by enforcing the rolling up of last continuous crosslink.
Tested locally

Fix last continuous crosslink logic

---

staking/availability/measure.go

Accidental mistake done during last minute refactoring of availability

[availability] Fix regression to skip over harmony run nodes

---

go.mod

Using 1 year old release of zero logger.
Ran `./test/debug.sh` for ~1 hour with no issues.
**NO**
**NO**
**NO**

[lib] Upgrade zerologger library from 1.14.3 to 1.18.0 release

---

multibls/multibls.go

GetNodeMetaData api returns empty due to multibls key feature integration for explorer node. This fix should fix the problem.

fixing explorer node returning empty for GetNodeMetaData api

---

core/tx_pool.go
core/types/tx_pool.go
internal/hmyapi/apiv1/transactionpool.go
internal/hmyapi/apiv2/transactionpool.go
node/node_handler.go

Currently, a node accepts transactions of any size and processes it. This could lead to OOM (described in #2187). We can help prevent this by dropping transactions that are obviously too big before ever decoding them and feeding it to the transaction pool. 
Before:
```
PASS
coverage: 21.9% of statements
ok  	github.com/harmony-one/harmony/core	6.897s
```
```
PASS
coverage: 14.2% of statements
ok  	github.com/harmony-one/harmony/node	2.035s
```
After:
```
PASS
coverage: 21.9% of statements
ok  	github.com/harmony-one/harmony/core	7.121s
```
```
PASS
coverage: 14.1% of statements
ok  	github.com/harmony-one/harmony/node	2.134s
```
Basic test suite [here](https://gist.github.com/Daniel-VDM/28d0b646c938074004c0250d218c0778).
1. **Does this PR introduce backward-incompatible changes to the …

Add raw tx size limitation at network layer to help with DOS attacks

---

internal/configs/node/config.go

GetNodeMetaData returns `{}` on explorer node. This fix should make it return metadata with `""` for the bls key field.
This fix is already in the master. I could not cherry pick it, as the multi-bls on master diverged quite a bit in terms of files and structure.
Hence this PR.

fix GetNodeMetaData bug caused by multi-bls feature for explorer node

---

cmd/harmony/main.go
internal/configs/node/config.go
internal/configs/node/config_test.go

For multi-bls feature, need to validate if all keys belong to the same shard. Fixes https://github.com/harmony-one/harmony/issues/2376

adding support for validating multibls for same shard

---

consensus/engine/consensus_engine.go
consensus/votepower/roster.go
core/blockchain.go
core/chain_makers.go
core/offchain.go
core/rawdb/accessors_offchain.go
core/state_processor.go
core/types.go
hmy/api_backend.go
hmy/backend.go
internal/chain/engine.go
internal/chain/reward.go
internal/hmyapi/apiv1/backend.go
internal/hmyapi/apiv1/blockchain.go
internal/hmyapi/apiv2/backend.go
internal/hmyapi/apiv2/blockchain.go
internal/hmyapi/backend.go
node/node.go
node/node_handler.go
node/node_newblock.go
node/worker/worker.go
staking/availability/measure.go
staking/types/validator.go

Further non-protocol changing improvements for OSTN
1. Do webhook call for when node drops in availabiltity signing
2. Remove accidential infinite recursion 
3. Never ignore errors in legacy RPCs
4. Expose bad block as an RPC, watchdog as downstream consumer
5. Remove signers that missed signing threshold from validatorlist, which is suspected of causing caching problems for median-stake.

[webhook][rpc][availability] Hooks, current signing, remove median-stake cached values

---

cmd/harmony/main.go

This error message is not needed. When the node is run, it simply misleads to the thinking that bls key was not found.

unnecessary message that is misleading node runners

---

cmd/harmony/main.go
scripts/node.sh

This PR adds support for starting a pprof server using the specified args `-pprof ADDRESS` (for the harmony binary) or `-R ADDRESS` (for node.sh) 
Using the updated node.sh file, a node can be started with a pprof enabled server using e.g:
```
./node.sh -k bls.key -N staking -z -D -S -R localhost:6060
```
The above command will start the pprof server at http://localhost:6060 and you can interact with various endpoints (e.g. using a web browser) via http://localhost:6060/debug/pprof
Here are the endpoints that can be used:
**Memory / goroutines / misc**
- http://localhost:6060/debug/pprof/allocs - A sampling of all past memory allocations
- http://localhost:6060/debug/pprof/block - Stack traces that led to blocking on synchronization primitives
- http://localhost:6060/debug/pprof/cmdline - …

[profiling] Add support for pprof in the harmony binary + node.sh

---

Makefile
scripts/go_executable_build.sh

The current build script `scripts/go_executable_build.sh` can't compile binaries using `-race` because of `-gcflags` currently being set to perform concurrent compilation (`-gcflags="all=-c 2"`).
When running `./scripts/go_executable_build.sh -r` using the current build script it will fail:
```
$ ./scripts/go_executable_build.sh -r
building cmd/client/wallet/main.go cmd/client/wallet/generated_wallet.ini.go
compile: cannot use concurrent backend compilation with provided flags; invoked as [/Users/sebastianjohnsson/.gvm/gos/go1.13.7/pkg/tool/darwin_amd64/compile -o $WORK/b042/_pkg_.a -trimpath $WORK/b042=> -race -c 2 -p unicode/utf16 -std -complete -installsuffix race -buildid qLUNkreJ40SQ4lF4MLEZ/qLUNkreJ40SQ4lF4MLEZ -goversion go1.13.7 -D  -importcfg $WORK/b042/importcfg -pack …
```

[compilation] Fix -race compilation

---

staking/slash/double-sign_test.go

https://github.com/harmony-one/harmony/issues/2330
go test -timeout 30s github.com/harmony-one/harmony/staking/slash -run ^(TestXPercentSlashed)$
ok  	github.com/harmony-one/harmony/staking/slash	0.503s
Success: Tests passed.

Expand slashing unit testing

---

cmd/harmony/main.go
scripts/node.sh

Fixes https://github.com/harmony-one/harmony/issues/2398
* Multi-bls users need to put all their keys and passphrases under `.hmy/blskeys`
* Keys need to have `<blskey>.key` extension
* Passphrases need to have `<blskey>.pass` extension
* Error if any file that has different extension than `.key` or `.pass` is found
* For any `<blskey>.key` if no passphrase file is available, it will use the default specified when running the node e.g., `./node.sh -p blspass.txt`

adding facility to read passphrase for individual multi-bls keys

---

consensus/votepower/roster.go
core/blockchain.go
core/evm.go
core/offchain.go
core/rawdb/accessors_offchain.go
core/state_processor.go
internal/utils/utils.go
staking/types/delegation.go
staking/types/delegation_test.go

Previously the change to batch write to DB would cause issue if there are multiple createValidator or delegation happens in the same block for the same address. 
The reason is that the batch write of the metadata only take effect at the end of all the changes. But it won't reflect it if reading in the middle of the operations, which may cause race condition.
This change take care of the issue by adding a cache layer to accumulate all the changes and batch write them at the end.

[Audit] Refactor offchain commit and fix consistency issue due to batch write

---

consensus/checks.go
consensus/consensus_v2.go
consensus/view_change.go

1. validator in ViewChangeMode should not trigger another view change on conflicting announce message
2. Do not process blocks that are further than max block number from the current block
3. Do not process view change that have view id further than max view id number from the current view id
4. Add more checks to onNewView for handling receive message view id and sender key verification for new leader
5. force block header verification for syncing mode
6. refactor onViewChange and onNewView sanity checks into checks.go

adding checks to prevent malicious leader behaviors

---

README.md
core/types/crosslink.go
hmy/api_backend.go
internal/hmyapi/apiv1/backend.go
internal/hmyapi/apiv1/blockchain.go
internal/hmyapi/apiv2/backend.go
internal/hmyapi/apiv2/blockchain.go
internal/hmyapi/backend.go

Fixes comments on [#2495](https://github.com/harmony-one/harmony/pull/2495).
Also, updated the go version in the README.
```
{
"id": 1,
"result": [
{
"hash": "0xaccf85735454dcb65c94888434003241821a9890b3ad027c2acd75bc4d236491",
"block-number": 226,
"signature": "f84b99bb1db4947761c909d90301a7f4aa5f4be01b2eb2a61e64906de0317a72e797e0fa9e3f8ab1c7dff2cd079e440ad0d05459fc2d909a4b3dc6ab6c70b5d707fe6769643886dac946649620f45cde1d693dc7acd98f875bd1816ab76d1a16",
"signature-bitmap": "3f",
"shard-id": 1,
"epoch-number": 43
}
]
}
```
**NO**
8. **Does this PR introduce backward-incompatible changes *NOT* related to on-disk data …

Refactor CrossLink RPC 

---

cmd/harmony/main.go
consensus/consensus_service.go
consensus/quorum/one-node-one-vote.go
consensus/quorum/one-node-staked-vote.go
consensus/quorum/one-node-staked-vote_test.go
consensus/quorum/quorum.go
consensus/votepower/roster.go
consensus/votepower/roster_test.go
core/blockchain.go
hmy/api_backend.go
internal/chain/engine.go
internal/chain/reward.go
internal/configs/sharding/instance.go
internal/configs/sharding/localnet.go
internal/configs/sharding/mainnet.go
internal/configs/sharding/mock/shardingconfig.go
internal/configs/sharding/pangaea.go
internal/configs/sharding/partner.go
internal/configs/sharding/shardingconfig.go
internal/configs/sharding/stress.go
internal/configs/sharding/testnet.go
node/node_cross_link.go
staking/verify/verify.go

Add the ability to adjust voting power based on epochs.
Give stressnet's harmony node 90% voting power.

Add shard config for harmony/external voting power

---

core/core_test.go
internal/configs/sharding/pangaea.go
internal/configs/sharding/stress.go
internal/configs/sharding/testnet.go

Should be ~64 seconds per epoch

[config] Make epoch 8 blocks for P1 open staking testnets

---

hmy/api_backend.go
internal/chain/engine.go
internal/chain/reward.go
node/node_handler.go
shard/committee/assignment.go
staking/availability/measure.go
staking/types/validator.go

Do ComputeAndMutateEPOSStatus at the last epoch, instead of at every block.
In EPoS election candidacy, validators in current committee who doesn't sign enough blocks will be kicked out no matter what. For those who signed enough, the candidacy is determined by the Status. 
Tested locally

Check signing threshold and set EPoS status only at last epoch

---

staking/effective/eligible.go

Change the return from `hmy_getValidatorInformation` to have more user-friendly output for the `epos-status` field.

[WIP][staking] Change Candidacy messages to be more user friendly

---

scripts/node.sh

read the src and understood the logic, the risk is low to remove this prompt. 
Two safety checks for this action (already there):
* `-c` enabled
* !mainnet network

suppress prompt to the action to clean up old db and logs

---

hmy/api_backend.go
staking/types/validator.go

@mikedoan @stephen-tse Here are adjustments to RPC to always show APR 
key point is that this `lifetime` field always exists 
```json
"lifetime": {
"apr": "0.000000000000000000",
"blocks": {
"signed": 0,
"to-sign": 12
},
"reward-accumulated": 0
},
```
example json of when in and not in committee 
in committee
```json
{
"id": "0",
"result": {
"current-epoch-performance": {
"current-epoch-signing-percent": {
"current-epoch-blocks-left": 7,
"current-epoch-signed": 0,
"current-epoch-signing-percentage": "0.000000000000000000",
"current-epoch-to-sign": 5
}
},
"currently-in-committee": true,
"epos-status": "currently elected and not signing enough blocks to be eligible for election next epoch",
"lifetime": {
"apr": "0.000000000000000000",
"blocks": {
"signed": 0,
"to-sign": 5 …
```

[rpc] Move lifetime outside of validator so always show APR

---

api/service/syncing/syncing.go
consensus/checks.go
consensus/consensus.go
consensus/consensus_v2.go
consensus/validator.go
core/offchain.go
node/node_handler.go
node/node_syncing.go

Node in listening mode doesn't process any consensus message, which make them less likely to stay sync'ed and have to always rely on state sync to happen once per 1 min. Also there wasn't a channel for consensus to trigger state sync in time.
This PR includes the following changes:
1. Always set consensus mode after UpdateConsenusInformation()
2. Still process consensus messages even in Listening mode
3. Don't send back consensus replies in Listening mode
4. Trigger state sync immediate if receiving a committed message that have higher height.
5. Do not print BINGO if the validator is in Listening mode
Tested in OSTN for case of 1) new validator joining consensus; 2) existing validator drop out and join again immediately

Fix node sync issue which caused failure to sign and node being kicked out

---

hmy/api_backend.go
internal/hmyapi/apiv1/backend.go
internal/hmyapi/apiv1/blockchain.go
internal/hmyapi/apiv2/backend.go
internal/hmyapi/apiv2/blockchain.go
internal/hmyapi/backend.go

Added new rpc to get the validator information by block number. The existing one works as is, the new rpc GetValidatorInformationByBlockNumber requires address and hex block number as input.

Get validator info by block

---

consensus/checks.go
consensus/consensus_service.go

* Enhanced log to print out the consensus current view id
* Also make sure to check only if the current view id is not zero. Looks like when the consensus restarts the current view id is set to zero.

adding log to print out the current view id

---

consensus/votepower/roster.go
core/blockchain.go
core/offchain.go
shard/committee/assignment.go
staking/apr/compute.go

The issue why previously the header of last block of one epoch ago is always nil, is because the last epoch is actually set to current epoch whose last block is actually the current block to commit, thus it can not be found in blockchain.
Also hit an issue that when external node uses same BLS keys are harmony nodes, the logic is messed up, external nodes may get reward because harmony node signed the block.

Fix APR's nill header issue; Compute APR based on last epoch

---

internal/hmyapi/apiv1/harmony.go
internal/hmyapi/apiv2/harmony.go

Need downstream for TUI & Watchdog.

[rpc] Return public BLSKeys as a list from getNodeMetadata

---

cmd/harmony/main.go
scripts/node.sh

* Limits max bls keys per node to 4
* adds feature to read passphrase for bls keys in node.sh
* adds feature to pass bls key folder as input to harmony binary in node.sh

limiting max bls keys per node to 4 and some node.sh enhancements

---

internal/hmyapi/apiv1/harmony.go
internal/hmyapi/apiv2/harmony.go

Fix nil pointer when explorer node is queried for nodeMetadata (no bls keys). Tested locally.
images.githubusercontent.com/56005637/77517910-25d38880-6e3a-11ea-9328-241ab4d6701e.png">

[rpc] Account for ExplorerNode with BLS keys changes for NodeMetadata

---

internal/hmyapi/apiv1/harmony.go
internal/hmyapi/apiv2/harmony.go

Cherry-pick to t3. Tested locally again.

[rpc] Account for ExplorerNode with BLS keys changes for NodeMetadata on t3

---

consensus/checks.go
consensus/double_sign.go
consensus/leader.go
consensus/votepower/roster.go
core/blockchain.go
internal/chain/engine.go
shard/committee/assignment.go
staking/apr/compute.go
staking/slash/double-sign.go
staking/slash/double-sign_test.go

Refactor slash detection code.
Fix previous audit todos:
1. Group slash records by blocks and apply separately.
2. Use the epoch at double sign rather than at current epoch.

[slashing][audit] Refactor slashing code and fix audit todos

---

consensus/checks.go
consensus/view_change.go

Fixes:
* Follows other validation checks to only info level message if the sender is not part of the slot committee (earlier this was error)
* Move leader check to much earlier before even new view sanity check

Fix view change message level and early return for non-leader

---

consensus/validator.go

commit delay of `delayCommit` was applied inside the loop that iterates through nodes multi-bls keys before sending commit message. taking it outside of the loop with this fix.

moving delay out of loop

---

hmy/api_backend.go
shard/committee/assignment.go

This original condition to check whether a validator is in last committee depends on whether the counter of NumBlocksToSign increased in last epoch. This condition is not stable because cross-links may arrive after the epoch ends and it still gets counted into the NumBlocksToSign, making this condition to be true after the new epoch even when the validator is actually not in committee.

Fix the validator auction eligibility condition

---

internal/hmyapi/apiv1/harmony.go
internal/hmyapi/apiv2/harmony.go

Cherry-pick to S3. Tested locally again.

[rpc] Account for ExplorerNode with BLS keys changes for NodeMetadata for s3

---

staking/availability/measure.go

The bug has caused leader failure to propose new blocks once there is a slashed validator in current epoch:
{"level":"error","port":"9000","ip":"34.209.133.63","error":"cannot finalize block: [ComputeAndMutateEPOSStatus] failed update validator info: have 9800000000000000000000 want 10000000000000000000000: self delegation can not be less than min_self_delegation","caller":"/home/ec2-user/harmony/node/node_newblock.go:78","time":"2020-03-28T06:04:59.350967974Z","message":"!!!!!!!!!Failed Proposing New Block!!!!!!!!!"}

Not update status for banned validators

---

api/service/explorer/storage.go

Currently there is no lock protection for processing txs from a new block. Need to a lock to protect that
Before:
```
```
After:
```
```
**YES|NO**
6. **What are the …

add lock to protection storage dump

---

internal/hmyapi/apiv1/types.go
internal/hmyapi/apiv2/types.go

This PR closes #2588. The reason why some block numbers failed to respond was that the RPC tried to dereference the commission rate of an edit validator transaction (which can be absent). 
No unit tests
I wrote a script to fetch all the blocks of a blockchain given the endpoint: https://github.com/harmony-one/harmony-ops/pull/518. I ran this script on an archival node connected to OSTN. 
Prior to my fix, I got the following:
```
$ python3 get_blockchain.py http://localhost:9500/  --stats
Fetched 37558/37559 blocks
Total bad loads with number: 926
=== Stats for fetched blocks ===
Total Blocks Fetched: 37559
Total tx count: 1521
Plain tx count: 1015
Total amount sent via plain tx: 5428149538.02
Staking tx count: 506
Staking tx type breakdown: {
"CollectRewards": 71,
"CreateValidator": 72, …
```

[#2588] Fix failed edit-validator tx fetch

---

core/staking_verifier.go
staking/types/validator.go
staking/types/validator_test.go

Duplicate bls keys as internal harmony node shouldn't be allowed. #2587
Output from local testing:
1. Create validator using internal key 
```
./hmy staking create-validator --validator-addr one1tpxl87y4g8ecsm6ceqay49qxyl5vs94jjyfvd9 --name Ganesh --identity ganesh --website ganesh@harmony.one --security-contact Alex --details "Ganesh the validator" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 10000 --max-total-delegation 100000 --bls-pubkeys 65f55eb3052f9e9f632b2923be594ba77c55543f5c58ee1454b9cfd658d25e06373b0f7d42a19c84768139ea294f6204 --amount 10000
Enter the bls passphrase:
[CreateValidator] slot key "65f55eb3052f9e9f632b2923be594ba77c55543f5c58ee1454b9cfd658d25e06373b0f7d42a19c84768139ea294f6204" conflicts with internal keys: slot keys can not have …
```

disallow duplicate bls keys as internal keys

---

core/staking_verifier.go
staking/types/validator.go
staking/types/validator_test.go

Local test output: 
1. Create validator with 10K stake
```
./hmy blockchain validator information one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy
{
"id": "0",
"result": {
"current-epoch-performance": null,
"currently-in-committee": true,
"epos-status": "currently elected and signing enough blocks to be eligible for election next epoch",
"lifetime": {
"apr": "0.000000000000000000",
"blocks": {
"signed": 1,
"to-sign": 2
},
"reward-accumulated": 0
},
"metrics": null,
"total-delegation": 1e+22,
"validator": {
"address": "one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy",
"bls-public-keys": [
"65f55eb3052f9e9f632b2923be594ba77c55543f5c58ee1454b9cfd658d25e06373b0f7d42a19c84768139ea294f6204"
],
"creation-height": 19,
"delegations": [
{
"amount": 1e+22,
"delegator-address": …
```

Fixes-#2558: Allow validator to withdraw all their stake if they want to quit

---

cmd/harmony/main.go
go.mod
internal/configs/viper/viper_config.go

#2494  : harmony node program use basic flag to define command line option support. We need to revamp it using latest library https://github.com/spf13/viper to support both command line option, plus configuration, and all kinds of configuration options.
Currently, it supports 1) config file like "config.json" to read and overwrite the command line options, also support config sections. 2) environment variables(ENV) to overwrite the command line options, the format is like "HMY_SECTION_FLAG".
Please notice the order of precedence: ENV > config_file value >  command line option > default value. The config value will be _0/ false/ ""_ if the config file or ENV is missing.
add more test cases

support config file and environment variable by the viper lib

---

consensus/reward/rewarder.go
core/blockchain.go
core/offchain.go
internal/chain/reward.go
staking/network/reward.go
staking/types/validator.go

Now `hmy blockchain validator information <ADDR>` should display a new field of `earned-reward` under the individual records of `metrics['by-shard']`
aka, 
you'll be able to see how much this BLS key is earning 
```
"metrics": {
"by-shard": [
{
"bls-public-key": "69adcdda12b8b2b19ea3d14762e179f370a1cbdd1d27a4ae556bee8955cb552b5760f246565b78c3ecda805e46a7f802",
"earning-account": "one167gc5t3f4uvupns2h8fsem9xzdgn2egra9w8d3",
"effective-stake": "233643750000000000000000.000000000000000000",
HERE WOULD BE THE NEW FIELD 
"group-percent": "0.028126054078104043",
"overall-percent": "0.009000337304993294",
"shard-id": 2
},
```

[reward][rpc] Extend ValidatorStats with earning per key, implement tracking rewards in payout, expose network wide

---

cmd/harmony/main.go
go.mod
internal/blsgen/lib.go

Added support for using AWS encrypted BLS key files... There are two ways to use it:
1) use command line option :  -aws_encrypted_blskey  [BLS_KEY_FILE]
2) put all bls key files (*.bls) under .hmy/blskeys/*.bls and use multi bls key
Also the aws credentials are needed to use aws CMK to decrypt the bls key files.  Aws credentials are a JSON string passed through stdin when the program runs, like below: 
``` 
echo "{\"aws-access-key-id\":\"AKIAZRWVEKULJHTOQ45I\", \"aws-secret-access-key\":\"xxxxxxxxxxxxxxxxxxxxxxxxxxxx\", \"aws-region\":\"us-east-1\"}"
|  ./bin/harmony -aws_blskey 812db0d4ca7c74b587eddf11ae820d9909f0783b8ad17f40d828e0017ad35fe9f194564927e1819bfc682e25099e7f83.bls
``` 
or put all bls key files under .hmy/blskeys/
``` 
ls .hmy/blskeys/ …
```

Added support for using AWS encrypted BLS key files

---

scripts/go_executable_build.sh

```
make linux_static
./scripts/go_executable_build.sh -s -N pangaea release
```
@john-harmony , this is how I manually release OSTN binaries to public bucket.

[build] fix the release action for static build

---

cmd/harmony/main.go
internal/blsgen/lib.go

This is a fix for issue https://github.com/harmony-one/harmony/issues/2689. The reason is that the blspass read from stdin when "-blspass std" is specified and it conflict with aws setting (which also read from stdin)  reading required for aws encrypted bls key. 
Tested both "-blspass std" and "--aws_blskey " works.  Note that only one way of reading from stdin is supported. Either for blspass or for aws credentials.

fix issue2689 error loading blspass

---

block/header.go
hmy/api_backend.go
hmy/backend.go
internal/hmyapi/apiv1/backend.go
internal/hmyapi/apiv1/blockchain.go
internal/hmyapi/apiv2/backend.go
internal/hmyapi/backend.go

Fast RPC to show headers. Deviates from `hmy blockchain latest-header` because that one uses an ad-hoc data structure and going forward the default for the RPC is to prefer using existing data structures. 
Please @janet-harmony add the corresponding CLI call in hmy cli 
```
curl --location \
--request POST 'http://localhost:9511' \
--data-raw '{
"method": "hmy_getLatestChainHeaders",
"params": [],
"id": 2
}'
```
```json
{
"id": 2,
"result": {
"beacon-chain-header": {
"shard-id": 0,
"block-header-hash": "0x6c7fb0c15673f7819ae01e885b5e646aa854b0eba68cf63040ca42f7bcef6e0f",
"block-number": 29,
"view-id": 29,
"epoch": 4
},
"shard-chain-header": {
"shard-id": 1,
"block-header-hash": …
```

[rpc] Show both latest header of beacon chain and shard chain

---

api/service/explorer/storage.go
api/service/explorer/storage_test.go
cmd/harmony/main.go

Current explorer node storage folder starts with /tmp and this causes losing db unexpectedly.
Before:
```
```
After:
```
```
**YES|NO**
6. **What are the planned flag …

change explorer node storage folder

---

core/blockchain.go
core/offchain.go

Previously the snapshot is taken after the last block is confirmed, while the election is taken on the state before the last block is executed.
So the two things are not consistent, you could have a validator elected but snapshotted with 0 delegation if that validator undelegate all its token right at that last block of epoch.

make validator snapshot consistent with election

---

scripts/node.sh

[node.sh] use rclone to fast sync harmony_db_0

---

core/blockchain.go

The cache key didn't take into account the epoch number for validator snapshot.

Fix snapshot cache key

---

core/blockchain.go
core/offchain.go

The new validator committed at the second to last block won't be snapshotted for the new epoch due to batched commit of ValidatorList data.

Make validator snapshot on new validator too

---

core/blockchain.go
core/offchain.go

commit f2524a888d6133e7d729ee22031d198695e8ce5f
Author: Rongjian Lan <rongjian.lan@gmail.com>
Date:   Sun Apr 5 12:33:35 2020 -0700
Make validator snapshot on new validator too (#2733)
commit 350b7a0bb45c68889547ac5b9521f46dcd97ced8
Author: Rongjian Lan <rongjian.lan@gmail.com>
Date:   Sat Apr 4 23:41:19 2020 -0700
fix validator snapshot cache
commit 8f5f287c749c62209f2dd08bfc0dbfc88df7b225
Author: Leo Chen <leo@harmony.one>
Date:   Sat Apr 4 19:09:38 2020 -0700
[node.sh] use rclone to fast sync harmony_db_0 (#2709)
commit 05f2e20a39e3472ee1ff506aa8b974a988a9a970
Author: Rongjian Lan <rongjian.lan@gmail.com>
Date:   Sat Apr 4 19:00:28 2020 -0700
make validator snapshot consistent with election (#2726)
* make validator snapshot consistent with …

Squashed commit of the following:

---

core/blockchain.go
core/offchain.go

Need to do snapshot for new validators at last block of an epoch for the new epoch.

do snapshot for validators at last block of epoch

---

consensus/consensus.go
core/blockchain.go
core/offchain.go
core/staking_verifier.go
hmy/api_backend.go
internal/chain/engine.go
internal/chain/reward.go
staking/availability/measure.go
staking/effective/eligible.go
staking/network/reward.go

Move EPoS Status check before the AccumulateRewards to be consistent with block proposal state.
Remove some dead code on delete validator snapshot.
Fix InCommittee condition check.
Add div by 0 safety guard to avoid crash.
Do no compute uptime for EPoS Booted status. It's not consistent with that for block proposal. Instead just use Inactive.
More cleanup on common.Big0 usage.

fix block proposal ordering; other offchain commits change

---

api/service/syncing/syncing.go
cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_v2.go
consensus/leader.go
consensus/quorum/one-node-one-vote.go
consensus/quorum/one-node-staked-vote.go
consensus/quorum/one-node-staked-vote_test.go
consensus/quorum/quorum.go
consensus/validator.go
core/blockchain.go
core/offchain.go
node/node.go
node/node_newblock.go

Leader sig collection strategy:
**before**: once 2/3 voting power/sig collected, wait for another 2s to collect more sigs; or if 90% reached, just commit.
**now**: 
1. always wait for the full block time (8s) and collect as much sigs as possible. New block won't be proposed before full block time.
2. once 2/3 voting power/sig collected, wait for another 2s or more if full block time not reached.
3. If 100% sig collected, commit the block immediately
4. Both 2 and 3 works under constraint of 1
This change will help improve the chance of slow node getting their signatures collected in block

optimize leader signature collection strategy; Clean up logs

---

consensus/checks.go

checked locally by trying to run a node on ostn. Currently with master code (@fxfactorial undo of protobuf changes) this crash is reproducible as ostn does not have this undo. It was convenient to test this fix.

[consensus] rejecting malformed messages before processing

---

api/service/explorer/storage.go

The default dbDir in deployment is empty - and it causes the path of explorer storage starts with the root `/`
Before:
```
```
After:
```
```
**YES|NO**
6. **What are …

fix explorer folder path

---

api/service/explorer/storage.go
node/node.go

Batch update caused data inconsistency when multiple read/write happens on the same address in the same batch.
Example: https://explorer.harmony.one/#/block/0xb1408bdf700cf7b78aef84d169e9a8fe77879ed8d3e77bbfe7c72a43cf348d7d/txs

Do not batch update explorer db.

---

core/evm.go
core/state_transition.go

To better conform with the new economic model. We need to burn all transactions fees after staking epoch.

burn all transaction fees after staking.

---

hmy/api_backend.go
hmy/backend.go
internal/hmyapi/README.md
internal/hmyapi/apiv1/backend.go
internal/hmyapi/apiv1/blockchain.go
internal/hmyapi/apiv1/transactionpool.go
internal/hmyapi/apiv2/backend.go
internal/hmyapi/apiv2/blockchain.go
internal/hmyapi/apiv2/transactionpool.go
internal/hmyapi/backend.go
node/node_explorer.go
scripts/api_test.sh

https://github.com/harmony-one/harmony/issues/2759
launched local network, sent staking and regular txns using hmy cli, from shard 0 with bls key in shard 0. then, saw hmy_getAccountNonce, hmy_getTransactionCount, hmy_getStakingTransactionCount all works correctly. 
```
curl --location --request POST 'http://localhost:9500' --header 'Content-Type: application/json' --data-raw '{
"method": "hmyv2_getStakingTransactionCount",
"params": ["one1grlw2qw7t9ulhms38w4ea0gssz0dk8vvsl7jum", "ALL"}],
"id": 1
}'
curl --location --request POST 'http://localhost:9500' --header 'Content-Type: application/json' --data-raw '{
"method": "hmyv2_getTransactionCount",
"params": ["one1grlw2qw7t9ulhms38w4ea0gssz0dk8vvsl7jum", "ALL"}],
"id": 1
}'
curl --location --request POST …
```

[rpc] separate transaction counts rpc into regular vs staking

---

cmd/harmony/main.go
consensus/consensus.go
consensus/double_sign.go
node/node.go
node/node_handler.go
node/node_newblock.go

* Remove self address assignment while starting node
* Move the self address out of consensus to node
* Get the self addresses for bls keys run by the node using shard state 
* Updates the self address every epoch

[node] move self address to node, make it updatable every epoch

---

core/blockchain.go

fixes https://github.com/harmony-one/harmony/issues/2808
problem is also observed in go-ethereum: https://github.com/ethereum/go-ethereum/issues/19286
this pr is simply porting their fix. basically, just make a nil pointer and initialize the `currentBlock` and `currentFastBlock` atomic with it.

port the fix from go-ethereum for interface conversion panic

---

consensus/view_change.go

Reverting this change, as it should actually submit vote for commit phase and not view change phase. This is because, if the view change happened during the commit phase, the new leader still needs to submit his vote for the commit message. OnNewView, other validators will do the same (they will also send the commit message to the new leader). 
The total-power-of-signers 0.0 problem will be fixed in the next pr.

Revert "[consensus][viewchange] fix total power of signers in IsQuorumAchieved for view change

---

consensus/view_change.go

There were several bugs in OnViewChange that might have caused view change delays due to only adding signatures and setting keys of new leader's leader key, instead all keys must be used in the multi-key case. Note that, this will not fix the `total-power-of-signers` bug. Actually, the `IsQuorumAchieved` does not make sense for view change, as view changes used multiple signature maps (nilSigs, bhpSigs, viewIDSigs) per viewID. `IsQuorumAchieved` is not needed at this moment for view change to work correctly. 
This pr should fix the view change bugs.

[consensus][view-change] onViewChange set keys and add signatures for all keys in case of multi-key new leader

---

api/service/syncing/syncing.go
core/blockchain.go
core/offchain.go
core/state_transition.go
multibls/multibls.go
staking/types/delegation.go

For delegationIndex used for collect rewards, when there is a crash, the offchain delegationIndex stay the same, but the latest blocks need to be re-processed to catch up
So when the node resync, it will use delegationIndex for the delegation that does not exist yet, which will lead to 0 rewards for the CollectReward txn which should have some rewards.
This PR add block number to the delegation index so the index can be used consistently with the current block.
Fixing: https://github.com/harmony-one/harmony/issues/2802

make delegation index consistent by block number

---

staking/types/validator.go

Fixes https://github.com/harmony-one/harmony/issues/2797
TODO, remove this field proper and remove parameters/logic threaded through ad-hoc just to satisfy this field creation

[rpc] Hide confusing num-beacon-blocks-until-next-epoch

---

api/service/explorer/storage.go
api/service/explorer/structs.go

- make staking txn field values to be decoded on explorer node ldb storage
- Explorer Staking Transaction message struct unified to contain all fields of different staking txns (Create/EditValidator, (Un)Delegate, CollectReward) so that the go struct of StakingTransaction for Explorer node can use that merged Staking Transaction msg struct as the return type and return the staking txns as decoded
- do use to-address field for staking txns for explorer node storage so that fetching by sent vs received txns work too for staking txns. 
Fixes issue: https://github.com/harmony-one/harmony-dashboard/issues/58 and https://github.com/harmony-one/harmony-dashboard/issues/69
Launched local net with an explorer node, query the explorer rpc for getStakingTransactionByHash and …

[Explorer Node] Explorer service StakingTransaction struct unification for explorer RPC level staking message data decoding

---

core/blockchain.go
core/chain_makers.go
core/evm.go
core/rawdb/accessors_offchain.go
core/state/statedb.go
core/vm/interface.go
hmy/api_backend.go
internal/chain/engine.go
internal/chain/reward.go
node/node_handler.go
shard/committee/assignment.go
staking/apr/compute.go
staking/availability/measure.go
staking/slash/double-sign.go
staking/slash/double-sign_test.go
staking/types/validator.go
test/chain/reward/main.go

1. Make validator snapshot tied with the epoch with a new struct ValidatorSnapshot
2. Use caching for the calculation of shares of delegators in the reward distribution time. This will save around 1/3 of the time in AddReward()
3. Fix the cache cleanup logic to always cleanup data 3 epochs ago.
Did more scalability testing, it turns out the loading (rlp decode) of the validator takes similar amount of time of calculating the shares of all its delegators.
```
Time required to read validator: 0.057869 seconds
Time required to calc percentage 100001 delegations: 0.064249 seconds
Time required to reward a validator with 100001 delegations: 0.122621 seconds
```
So we should next optimize the code to avoid reading and writing validator repeated for different operations.

Optimize delegation reward distribution with caching

---

scripts/go_executable_build.sh

don't release mainnet binary from the script

[build] support testnet binary release

---

staking/types/delegation.go
test/chain/reward/main.go

Since we are using the in-memory version of validatorWrapper, the nil big.Int will have trouble.
Need to avoid nils in the validatorWrapper.

Fix potential nil pointer when validator is first created

---

api/service/explorer/storage.go
api/service/explorer/structs.go
node/node_explorer.go

related https://github.com/harmony-one/harmony/issues/2831
This PR optimizes the block dump process in terms of memory usage during dump and also the disk storage size of transactions history. Both transaction and staking transactions.
```
dennis.won@Jongs-MacBook-Pro:~/harmony-one/harmony (explorer_node_dump_opt) $ go test ./api/service/explorer/
ok  	github.com/harmony-one/harmony/api/service/explorer	0.785s
dennis.won@Jongs-MacBook-Pro:~/harmony-one/harmony (explorer_node_dump_opt) $ go test ./node/node
node.go               node_cross_link.go    node_explorer.go      node_handler.go       node_newblock.go      node_test.go
node.md               node_cross_shard.go   node_genesis.go       node_handler_test.go  node_syncing.go       node_utils.go …
```

Explorer node dump opt

---

staking/slash/double-sign.go
staking/types/delegation.go
staking/types/delegation_test.go

Should be locking undelegation for only 7 epoch time. Previously to the user, it's actually locked for 8 epoch time.

[audit] Fix and make exact 7 epoch for undelegation

---

api/proto/node/node.go
consensus/leader.go
consensus/signature/signature.go
consensus/threshold.go
consensus/validator.go
consensus/view_change.go
core/types/crosslink.go
internal/chain/engine.go
node/node_cross_link.go
node/node_explorer.go
staking/slash/double-sign.go
staking/slash/double-sign_test.go
staking/verify/verify.go

This closes #2630 
Before:
```
PASS
coverage: 7.4% of statements
ok  	github.com/harmony-one/harmony/consensus	1.380s
```
```
PASS
coverage: 21.5% of statements
ok  	github.com/harmony-one/harmony/core	6.803s
```
```
PASS
coverage: 47.3% of statements
ok  	github.com/harmony-one/harmony/staking/slash	0.243s
```
After:
```
PASS
coverage: 7.5% of statements
ok      github.com/harmony-one/harmony/consensus        1.265s
```
```
PASS
coverage: 21.7% of statements
ok      github.com/harmony-one/harmony/core     6.865s
```
```
PASS
coverage: 47.2% of statements
ok      github.com/harmony-one/harmony/staking/slash    0.304s
```
**YES**
2. …

Add viewID to block signed content

---

core/evm.go
core/staking_verifier.go
core/state_transition.go

Add the dedup feature for validator identifying fields including identity and bls keys.
Fail the staking txn if dups are detected and return corresponding errors.

Validator dedup on identity and bls keys

---

hmy/api_backend.go
staking/effective/eligible.go
staking/types/validator.go

Fixing: https://github.com/harmony-one/harmony/issues/2851
* for a validator who is never elected and part of committee, will have no validator stats and needs booted status set to not booted.
* also, it does not make sense to show booted-status: none, for a validator who is currently elected and signing, hence added a new status "booted".

booted-status to show booted for elected/signing validator, not booted for never elected

---

core/blockchain.go
hmy/api_backend.go

* fixed super-committee rpc showing zero `epos-median-stake` 
* set raw-stake in per-key metric, such that getting validator information reflects raw-stake as well

Fix super committee bug and add raw-stake to per-key metrics

---

api/service/explorer/storage.go
api/service/explorer/structs.go

Explorer node fails to save transaction records to its storage, returning empty transaction history.
```
dennis.won@Jongs-MacBook-Pro:~/harmony-one/harmony (fix_explorer_node) $ go test ./api/service/explorer/
ok  	github.com/harmony-one/harmony/api/service/explorer	0.490s
```
checked the logs for txs are correctly saved on storage for each block during dump.
...
{"level":"info","port":"9099","ip":"127.0.0.1","addr":"one1a50tun737ulcvwy0yvve0pvu5skq0kjargvhwe","**num TXs":2,**"caller":"/Users/dennis.won/go/src/github.com/harmony-one/harmony/api/service/explorer/storage.go:139","time":"2020-04-        29T19:12:21.27235-07:00","message":"UpdateTxAddressStorage"}
235 {"level":"info","port":"9099","ip":"127.0.0.1","addr":"one1a50tun737ulcvwy0yvve0pvu5skq0kjargvhwe",**"num …

fix explorer storage for transactions and staking transactions

---

core/blockchain.go
hmy/api_backend.go

* fix super committee bug that was overwriting previous median instead of current
* read from validator wrapper to update raw-stake instead of snapshot, as snapshot is still in batch and not flushed.

fix super committee median for current committee and raw-stake assignment

---

consensus/double_sign.go
internal/chain/engine.go
node/worker/worker.go
staking/slash/double-sign.go
staking/slash/double-sign_test.go

Fix https://github.com/harmony-one/security-audit/issues/16
Fix another potential exploits by changing reporter addresses and get the same slashes applied multiple times.
Refactor the slash record so it's more organized and easily dedup'able.

Fix slash verify to avoid potential duplicate slashes exploit

---

core/blockchain.go
core/rawdb/accessors_offchain.go
core/state_processor.go
node/worker/worker.go

continue on failed slash record so it won't be added to succeeded record list.
Also fix the misuse of SetDifference when deleting failed slashes.

remove unused code; continue on failed slash record; Fix delete slash func on SetDifference

---

numeric/decimal.go
numeric/decimal_test.go
staking/types/commission.go
staking/types/commission_test.go
staking/types/messages.go
staking/types/messages_test.go

Closes [#2920 Fix StakingMsg Deep Copy](https://github.com/harmony-one/harmony/issues/2920).
* Reimplemented the deep copy methods for StakingMsgs in `staking/types`.
* Added the corresponding unit test cases.
Before:
```
$ go test --cover
PASS
coverage: 44.7% of statements
ok      github.com/harmony-one/harmony/staking/types    0.228s
```
After:
```
$ go test --cover
PASS
coverage: 52.2% of statements
ok      github.com/harmony-one/harmony/staking/types    0.494s
```
There shall not be any compatibility issues in this PR since it's just a reimplementation on the current method.

Msg copy fix

---

consensus/quorum/one-node-staked-vote.go

`total-raw-staked` field in deciders of super-committee roc was actually total effective stake. this pr fixes that and also adds `total-raw-stake` for clients to directly consume. This is still per-shard total amounts and all-shard aggregation is still required.

fix super-committee total-raw-staked bug

---

cmd/harmony/main.go
core/tx_pool.go
core/tx_pool_test.go
core/types/transaction.go
core/types/tx_errorsink.go
hmy/api_backend.go
hmy/backend.go
internal/configs/sharding/testnet.go
internal/hmyapi/apiv1/backend.go
internal/hmyapi/apiv1/transactionpool.go
internal/hmyapi/apiv2/backend.go
internal/hmyapi/apiv2/transactionpool.go
internal/hmyapi/backend.go
node/node.go
node/rpc.go
staking/types/transaction.go
test/chain/main.go

Currently, the error sink just dumps any error to a ring buffer and does not remove any error report from the buffer if the tx ended up being successful. Some downstream tools (like CLI and block explorer) use the sink to check if a recent transaction failed and short circuits a failure msg if it does not. Therefore, it is important that the error sink does not duplicate error msgs and removes error messages for txs that made it through.
Moreover, I exposed the TxPool stats RPC.
SS of RPC:
It is sufficient to test this on localnet as you can cause errors as needed. This was done & a unit test was added.
Before:
```
PASS
coverage: 26.5% of statements
ok  	github.com/harmony-one/harmony/core	7.030s
```
After:
```
PASS
coverage: 26.2% of statements
ok  	github.com/harmony-one/harmony/core …
```

Fix error sink msg duplication & false positives

---

consensus/consensus_service.go
consensus/validator.go

if the validator is in any other mode than normal, don't sign the block because the block can only be fully verified in normal mode. we still want to add the received block to the FBFTLog for later tryCatchup. in case of malicious leader forcing validators to syncing mode, validators that fail to verify the block won't sign, hence breaking the malicious leader attempt to flood validators with malformed blocks.
tested the fix by running a node on ostn, fully syncing and getting into consensus. also tried multiple times stopping the node to get it out-of-sync (syncing mode) and the node comes back online and successfully starts signing blocks. 
this should not have any regression.

don't sign the block that is not verified

---

core/offchain.go

Previously the shardstate was always added into DB with key of epoch+1. But it is not the case when a shard chain is lagged and jumped to a new epoch that's more than one epoch ahead.

Fix potential wrong epoch for shard state commitment

---

internal/configs/sharding/stress.go

@fxfactorial needs a larger STN network configuration to fully test his new p2p layer.
This PR increases the number of shards to 4 and the number of nodes per shard to 75 (75 operated by Harmony) for pre-staking epochs and 100 nodes (75 operated by Harmony) for staking epochs.

[STN] Updated network settings for Edgar's P2P tests

---

README.md
core/blockchain.go
hmy/api_backend.go
internal/hmyapi/apiv1/backend.go
internal/hmyapi/apiv1/blockchain.go
internal/hmyapi/apiv1/debug.go
internal/hmyapi/apiv1/error.go
internal/hmyapi/apiv1/transactionpool.go
internal/hmyapi/apiv2/backend.go
internal/hmyapi/apiv2/blockchain.go
internal/hmyapi/apiv2/debug.go
internal/hmyapi/apiv2/error.go
internal/hmyapi/apiv2/transactionpool.go
internal/hmyapi/backend.go

Add `GetDelegationsByDelegatorAtBlock`
Return error when calling staking RPCs on not beacon chain nodes
Return error when requesting information from block that is greater than current chain height
Tested on localnet.

[rpc] delegations by block & error checks

---

core/tx_pool.go
core/tx_pool_test.go
core/types/transaction.go
core/types/tx_pool.go
internal/hmyapi/apiv1/types.go
internal/hmyapi/apiv2/types.go

Plain tx had a cumbersome way to fetch sender address, so added `SenderAddress` to plain tx, to make the same as staking tx. Doing this meant I could remove uses of `PoolTransactionSender`, so did that as well and refactored all associated functions. 
Tested locally, sending staking and plain tx all worked and passed through the pool.
Before:
```
PASS
coverage: 26.0% of statements
ok      github.com/harmony-one/harmony/core     6.913s
```
After:
```
PASS
coverage: 26.0% of statements
ok      github.com/harmony-one/harmony/core     6.927s
```
**NO**
8. **Does this PR introduce backward-incompatible changes *NOT* related to on-disk data …

Add SenderAddress to plain Tx Type

---

core/blockchain.go
core/rawdb/accessors_offchain.go
shard/committee/assignment.go

Fixes following corner case:
Issue.1
Total stake counted the validators with duplicate keys. It shouldn't count those stake.
Issue.2 (https://github.com/harmony-one/harmony/issues/2882)
Delegators who delegated first and then create validator on themselves will have their delegation index cleared out. It shouldn't.

Fix both total stake counting and delegation index for validator itself

---

hmy/api_backend.go
hmy/backend.go
internal/hmyapi/common/types.go
node/rpc.go
p2p/host.go

hmy utility metadata 
```json
{
"id": "1",
"result": {
"blocks-per-epoch": 5,
"blskey": [
"65f55eb3052f9e9f632b2923be594ba77c55543f5c58ee1454b9cfd658d25e06373b0f7d42a19c84768139ea294f6204"
],
"chain-config": {
"chain-id": 2,
"cross-link-epoch": 2,
"cross-tx-epoch": 0,
"eip155-epoch": 0,
"prestaking-epoch": 0,
"receipt-log-epoch": 0,
"s3-epoch": 0,
"staking-epoch": 2
},
"current-epoch": 0,
"dns-zone": "",
"is-archival": false,
"is-leader": true,
"network": "localnet",
"node-unix-start-time": 1588955016,
"p2p-connectivity": {
"connected": 23,
"not-connected": 1,
"total-known-peers": 24
},
"role": "Validator",
"shard-id": 0,
"version": "Harmony (C) 2020. harmony, version v5920-v1.3.8-43-g2d0d9561-dirty (edgar@ 2020-05-08T09:23:27-0700)"
}
}
```

[rpc][p2p] Expose peer connectivity

---

consensus/consensus_service.go
consensus/votepower/roster.go
shard/committee/assignment.go
staking/effective/calculate.go

1. Avoid duplicate bls keys as harmony nodes from validators.
2. Fix a corner case issue when there is a epoch gap for shard chains, which will cause the Decider to be set incorrectly when it's already in staking epoch.
3. Add a check for div by 0

Avoid duplicate bls as harmony nodes; Fix epoch gap issue

---

internal/configs/sharding/stress.go

300 node network is now a separate network - p2p/p2pnet
Before:
```
```
After:
```
```
**YES|NO**
6. **What are the planned flag epoch numbers and their ETAs on …

[STN] Revert settings for a larger network

---

internal/configs/sharding/stress.go

@fxfactorial requested that STN should run without multi-bls in order to test some new changes.
Before:
```
```
After:
```
```
**YES|NO**
6. **What are the planned flag …

[STN] Run STN using 1 bls key instead of 3 bls keys per node

---

p2p/host/hostv2/hostv2.go

This is commit addressing issue 2959 "[Feature] enable NAT traversal for simple 1-level NAT situation with UPNP support: connecting local host validator behind a NAT to public leaders " 
Have tried this changes behind a NAT set up in an AWS VPC. And it seems the node is running properly and blockchain keeps synced to the network. 
Note: at this point we can't test every possible NATs in the world and there could be some NATs which do not support UPNP tools, but based on my impression, UPNP should be pretty common. And whenever libp2p add support to any more NATs, we get that additional support for free. 
Jians-MacBook-Pro:p2p jz$ go test --cover
PASS
coverage: 19.6% of statements
ok  	github.com/harmony-one/harmony/p2p	0.013s
Jians-MacBook-Pro:p2p jz$
./test/test_before_submit.sh
=== RUN …

Enable NatPortMap in p2p host

---

internal/hmyapi/apiv1/types.go
internal/hmyapi/apiv2/types.go

add viewID and epoch for RPCMarshalBlock function in order to check the consecutiveness of viewID in mainnet.

[rpc] add viewID and epoch to RPCMarshalBlock

---

consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/leader.go
consensus/threshold.go
consensus/validator.go
consensus/view_change.go
core/offchain.go
node/node_explorer.go
staking/slash/double-sign.go
staking/slash/double-sign_test.go
staking/slash/interface_test.go

The commit signature payload was changed with a forking logic based on epoch.
The original code used data from somewhere not directly from the block data, which can cause issues if those data are inconsistent.
Should always directly use the block's data for commit payload.
Also:
1. Add commit signature into block explorer commit
2. Remove consensus.epoch
Tested locally, consensus reached.
Fixing: https://github.com/harmony-one/harmony/issues/2976

Fix commit payload

---

consensus/view_change.go
core/types/block.go

fix crash:
panic: runtime error: invalid memory address or nil pointer dereference
May 12 20:29:25 ip-172-31-3-164.us-west-1.compute.internal harmony[17497]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10faaf5]
May 12 20:29:25 ip-172-31-3-164.us-west-1.compute.internal harmony[17497]: goroutine 799 [running]:
May 12 20:29:25 ip-172-31-3-164.us-west-1.compute.internal harmony[17497]: github.com/harmony-one/harmony/core/types.CopyHeader(...)
May 12 20:29:25 ip-172-31-3-164.us-west-1.compute.internal harmony[17497]: /home/ec2-user/go/src/github.com/harmony-one/harmony/core/types/block.go:387
May 12 20:29:25 ip-172-31-3-164.us-west-1.compute.internal harmony[17497]: github.com/harmony-one/harmony/core/types.(*Block).Header(...)
May 12 20:29:25 …

fix crash on parsed block

---

consensus/consensus_viewchange_msg.go
consensus/leader.go
consensus/view_change.go

Hit a view change stuck issue in https://github.com/harmony-one/harmony/issues/2976 . The issue is that leader added M1 msg itself, while no one else votes on M1 (prepared)
But Leader didn't put m1payload itself, which caused the newView msg validation failure on validators. `[onNewView] M1 (prepared) Type Payload Not Have Enough Length"`
Solution is to let the leader itself add m1payload when itself added M1 signatures.

Make leader commit m1payload itself

---

internal/chain/reward.go

all signer share should not include harmony node shares.

fix signers share computation to use only non-harmony nodes

---

internal/chain/engine.go
staking/availability/measure.go

LastEpochInCommittee wasn't set at prestaking epoch for the first staking epoch.
Which caused the unavailability rule to malfunctioning in the first staking epoch.
This PR changes the logic to also set LastEpochInCommittee in pre-staking epoch.

Add LastEpochInCommittee at prestaking epoch too

---

scripts/go_executable_build.sh

scripts/go_executable_build.sh -s (static build, default)
scripts/go_executable_build.sh -S (non-static build)

[build] enable static build by default

---

consensus/quorum/one-node-staked-vote.go
consensus/quorum/quorum.go
node/node_cross_link.go
node/node_newblock.go
staking/verify/verify.go

mainnet shard 0 leader is choking on CPU.
Mostly due to crosslink verification and processing is expensive, and there are a lot of them (redundant ones too).
Add caches on the processing and related components.
Also make crosslink batch smaller, as most of them are just duplicated data. (because of the delay of beacon sync in shard chains)
Also avoid repeated serialization of the voter bls keys in voting power computation, which happens for every validator votes!

Optimize crosslink verification logic and add more cache

---

node/node_cross_link.go
node/node_handler.go
node/node_syncing.go

Crosslinks on beacon chain are gradually lagging behind the tip of the shard chains blocks.
The reason was the reduced crosslink broadcast batch size (from 10 -> 3). Also because of the inherent design flaw in the braodcasting timing.
The current crosslink broadcast happens when there is a new block confirmed. But this is not efficient, many times, the same crosslinks are broadcasted because the beacon sync is lagged behind.
It's similar to submitting txns in sequence but only wait for the first txn confirmation then send the second one. Due to beacon sync delays, the crosslink submission will be hard to catch up if not sending in bigger batch.
The solution is to only broadcast crosslinks when there is a new block added in beacon sync. That's when the tip of crosslinks changes, so the new …

[wip]make crosslink broadcast smarter and more efficient

---

Makefile
core/tx_list.go
core/tx_pool.go
core/tx_pool_test.go
scripts/go_executable_build.sh
test/deploy.sh

Currently, the Tx pool does not report back if a transaction has been replaced in the pool before transactions are proposed for the next block. This PR fixes that and adds more error reporting on the promotion/demotion of transactions (essentially edge cases). Moreover, this PR fixes the local build for macOS.
Tested locally by sending 2 transactions within the same block where 1st transaction had lower gas price than 2nd transaction. Got the following error message in the error sink:
```json
{
"tx-hash-id": "0xc39c945f9d04ac580e5c649c7ba0cf65bec822747aeae0067d59812e4a93d411",
"time-at-rejection": 1589849288,
"error-message": "replaced transaction, new transaction 0xb7afe2e9d6ea0f6a11af73afb2365bab4196df7da6ab39abf0bf77362542c6f2 has same nonce & higher price"
}
```
Moreover, tested …

Tx pool error report fix & local build fix

---

core/tx_pool.go

Was `Warn()`, now `Info()`:
`Pooled new executable transaction`
`Pooled new future transaction`
`Promoting queued transaction`
Innocuous messages causing alerts in monitoring
**NO**
**NO**
**NO**

Change common messages to Info() to prevent false positive alerts

---

Makefile
hmy/api_backend.go
internal/hmyapi/apiv1/backend.go
internal/hmyapi/apiv1/blockchain.go
internal/hmyapi/apiv2/backend.go
internal/hmyapi/apiv2/blockchain.go
internal/hmyapi/backend.go
staking/effective/eligible.go
staking/types/validator.go

Requested by validators to clearly see effect of `edit-validator --active true` does
Also needed for AutoNode
Example in RPC:
```
"active-status": "active",
```
```
"active-status": "inactive",
```
```
"active-status": "banned",
```
```
"active-status": "unknown",
```

[rpc] Add active status back to Validator information

---

node/node.go
node/node_syncing.go

Added caching mechanism to node handling sync traffic for two requests:
1. `DownloaderRequest_BLOCKHEADER`
2. `DownloaderRequest_BLOCK`
The two requested are heavily handled in explorer node. Caching these two requests will save one rlp CPU time each request.
Code passed local test. 
[test log](https://gist.github.com/JackyWYX/c1e21f37ec4c0cdb8565f03d9b16f8c7)
After changed the solution from `singleflight` to `lru.Cache`, tested again and passed.
[test log](https://gist.github.com/JackyWYX/fa6a57acc78893ee7c8c3e9e9caf2629)
**NO**
8. **Does this PR introduce backward-incompatible changes *NOT* related to on-disk data structure and/or …

[network] Added caching to node server

---

cmd/harmony/main.go
hmy/api_backend.go
internal/hmyapi/apiv1/util.go
internal/hmyapi/apiv2/util.go
node/node.go
scripts/node.sh

Currently, we don't check if transactions have been finalized before adding it to tx pool.
Moreover, we don't broadcast failed tx which makes the error sink inconsistent across all nodes. However, to protect the network from needless tx spam in the case of an attack, one can enable the option to not broadcast failed txs. 
Tested locally by sending a bunch of invalid txs to all nodes on localnet, error sink stayed synced. 
Also tested replay of same tx, error sink didn't report and saw the warning in logs that tx was not added to pool. 
Before:
```
PASS
coverage: 11.3% of statements
ok      github.com/harmony-one/harmony/node     1.515s
```
After:
```
PASS
coverage: 11.2% of statements
ok      github.com/harmony-one/harmony/node     1.565s
```
1. **Does this PR introduce …

Transaction api improvements

---

api/service/explorer/service.go

The current explorer RPC/HTTP endpoint won't automatically close lingering connections, resulting in `"Too many open files"` errors.
This PR sets the following settings for the RPC/HTTP server:
```
ReadTimeout:  5 * time.Second,
WriteTimeout: 10 * time.Second,
IdleTimeout:  120 * time.Second,
```
Related: https://blog.cloudflare.com/exposing-go-on-the-internet/
Before:
```
PASS
coverage: 12.3% of statements
ok  	github.com/harmony-one/harmony/api/service/explorer	0.531s
```
After:
```
PASS
coverage: 12.3% of statements
ok  	github.com/harmony-one/harmony/api/service/explorer	0.310s
```
**NO**
2. …

Add timeouts for the explorer HTTP service

---

cmd/harmony/main.go

Closes https://github.com/harmony-one/harmony/issues/3056. Added a flag called dns_flag to seperate dns port to user defined port number. So user defined port number will not affect DNS node's port.
Run the node with node.sh on mainnet, the node can synchronize with the blockchain without error.
[Test log](https://gist.github.com/JackyWYX/ce7578dd367a78516001080c0f177508)
**NO**
**NO**

fix the sync port issue

---

api/service/syncing/syncing.go
api/service/syncing/syncing_test.go

Intend to solve https://github.com/harmony-one/harmony/issues/3029.
Limit the number of peers connected by GRPC at client end, thus will release more resource of GRPC at server end. Number of connected syncing nodes is first halved and then capped by 3 and 5.
Note this is just a temporary fix. Syncing can be done in a more elegant way.
Before:
```
PASS
coverage: 3.8% of statements
ok      github.com/harmony-one/harmony/api/service/syncing      0.351s
```
After:
```
PASS
coverage: 7.5% of statements
ok      github.com/harmony-one/harmony/api/service/syncing      0.361s
```
Test quick recap: Added some print log message and run a node connecting to mainnet, and test passed.
1. Connected syncing peers has reduced for each shard from 9 to 4.
2. Node's block number increasing, syncing in …

[network] Limit client sync connection

---

internal/hmyapi/apiv1/blockchain.go

"latest" block number param regression bug fix.
This caused truffle contract deployment to fail because current truffle version performs validates the deployment of contract by calling rpc apis of api v1, including for example getBlockByNumber(). 
Before:
```
dennis.won@Jongs-MacBook-Pro:~ $ curl -s --request POST 'http://localhost:9500' --header 'Content-Type: application/json' --data-raw '{ "jsonrpc": "2.0", "method": "hmy_getBlockByNumber", "params": ["latest", true], "id": 1}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"requested block number greater than current block number"}}
```
After:
```
dennis.won@Jongs-MacBook-Pro:~ $ curl -s --request POST 'http://localhost:9500' --header 'Content-Type: application/json' --data-raw '{ "jsonrpc": "2.0", "method": …
```

fix latest param handling in api v1

---

consensus/consensus_v2.go
consensus/leader.go
consensus/reward/schedule.go
core/block_validator.go
core/offchain.go
core/tx_pool.go
go.mod
hmy/api_backend.go
internal/chain/engine.go
internal/configs/sharding/mainnet.go
internal/params/config.go
node/node.go
node/node_handler.go
node/node_syncing.go
p2p/host.go
scripts/node.sh
staking/types/validator.go

Merge t3 to master branch.
The top of the t3 branch is: 
```
commit 433792662f2d98c051d0463aba724a9bdeeb3e4b (origin/t3, t3)
Author: Leo Chen <leo@harmony.one>
Date:   Thu May 21 10:44:29 2020 +0000
[go.mod] update go.mod for libp2p
```
Commit merged into t3 since the diverge of master.
```
43379266 (HEAD -> t3, origin/t3) [go.mod] update go.mod for libp2p
a6c29d24 [apr][rpc] validator information return all apr entries (#3082)
cde64e52 [node.sh] remove unused function
7839091f [node.sh] remove unused fuser
8a370c64 [node.sh] update version of node.sh
c2b271cd [node.sh] remove un-supported download db function
75da8cb4 [node.sh] randomize auto-update time
44f6cd65 [apr] fix wrong staking apr in the third staking epoch (#3070)
5d46fce2 Change …
```

Merge t3 to master 0523

---

core/block_validator.go
internal/chain/engine.go

Found the crash during release test.
https://github.com/harmony-one/harmony/issues/3088

fix a nil pointer crash due to previous revert

---

internal/chain/engine.go
internal/params/config.go
node/node_handler.go
staking/types/delegation.go
staking/types/delegation_test.go

Make unlocking of undelegated token to happen right at the end of current epoch.
Based on proposal in https://talk.harmony.one/t/proposal-shortening-of-undelegation-locking-period/634
Will need a rolling upgrade before the QuickUnlockEpoch.

Add quick unlock feature at epoch 190

---

api/service/syncing/syncing.go
node/node_handler.go

Potentially fixing https://github.com/harmony-one/harmony/issues/3098
The previous logic rollback current valid block and it caused following state issues.
We shouldn't rollback current block when receiving a new bad block.

Do not rollback current block on failed block sync

---

core/blockchain.go
core/offchain.go

This PR fixes the APR computation logic bug, which was iterating over next epoch validators for computing the APR, instead it should iterate over the current epoch validators. The PR also adds a APR correction logic to be applied at the epoch 191 to 192 transition to correct the previous APR values in the db.

[apr] compute APR for current committee not next committee, fix previous APRs in the snapshot

---

consensus/consensus.go
consensus/consensus_v2.go
consensus/view_change.go

The block is fetched from fbftLog and it was already verified before it's added to the log. So we don't need to verify it again.
This actually slows down the leader by 1-2s in beacon chain because the block verification of crosslinks is very expensive.

Remove unnecessary block verification

---

core/tx_list.go
core/tx_pool.go
hmy/api_backend.go
internal/hmyapi/apiv1/types.go
internal/hmyapi/apiv2/types.go
test/debug.sh

This closes #3107.
The primary issue was that the tx-pool was not demoting invalid or 'unexecutable' staking transactions from the pending list, thus the transactions could never be removed from the pool. Note that timeout only applies to queued (aka unexecutable/demoted) transactions, so even the timeout does not currently work. 
Moreover, the pending transactions & pending staking transactions RPC only returned pending transaction, when they should also return queued transactions.
Lastly, the RPC staking tx could not handle all staking transaction types (failed to RLP decode correctly on some staking txs). This caused pending staking txs RPC to falsely report no txs (b/c of error). This has been changed to follow the staking RLP decode flow used in the tx pool.
The stuck pending staking …

[TxPool] Fix stuck staking transactions

---

core/blockchain.go

Fixes https://github.com/harmony-one/harmony/issues/3120. Tested before and after the fix on mainnet node, seems to be fixing the `Invalid pending crosslink RLP decoding` problem.

[blockchain] fix Invalid pending crosslink RLP decoding

---

consensus/leader.go
consensus/threshold.go
consensus/view_change.go

Previously, the multi-key feature assumes all the keys are in committee for the leader. But if it's not true, the leader node will fail to propose new blocks or fail to count votes correctly.
tested in dryrun network with slot changes.
**NO**
**NO**
**NO**

Fix multi-key related issues when keys are not in committee

---

internal/hmyapi/apiv1/types.go

In apiv1, the NewRPCTransaction missed the input information, which exists in apiv2, then all the HRC transaction returned by apiv1 RPC showed '0x'

[RPC] add input on newRPCTransaction

---

core/blockchain.go

Fixes: https://github.com/harmony-one/harmony/issues/3139
* Applying patch from go-ethereum: https://github.com/ethereum/go-ethereum/blob/4b2ff1457ac28fb2894485194e0e344e84c2bcd7/core/blockchain.go#L626 for taking care of nil pointer when rewinding in repair. 
* Move validator remove call to rewind success branch, it was dead code before.

[core] fail repair on missing block

---

consensus/consensus_v2.go
node/node.go

* restore the ticker to the original 3 seconds
* try to address https://github.com/harmony-one/harmony/issues/3150

[p2p] increase timeout of validator

---

internal/hmyapi/apiv1/blockchain.go
internal/hmyapi/apiv2/blockchain.go

```
$ curl --location --request POST 'http://localhost:9500' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "jsonrpc": "2.0",
>     "method": "hmy_getHeaderByNumber",
>     "params": ["0x3"],
>     "id": 1
> }' | jq
{
"id": 1,
"result": {
"blockHash": "0xa818b2e33d7ff384bf53d3a1dac5bc14d40c2f97b79f77e5c69b0ab751310ef8",
"blockNumber": 3,
"shardID": 0,
"leader": "one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy",
"viewID": 3,
"epoch": 0,
"timestamp": "2020-06-16 00:57:39 +0000 UTC",
"unixtime": 1592269059,
"lastCommitSig": "98bc5101971640357d8a110b873777d1c34ec5248524d4d66ead157b5beb369d326bf0e11ab4e1474ea70811f0fc0b11d8d911578707dab763b8c263659bec0023cef06f090d554a369da261ea253aff77e543c833b22ac6e75e217d49725510",
"lastCommitBitmap": "7f",
"crossLinks": …
```

[rpc] Add rpc to get block headers from any block

---

consensus/consensus_v2.go
internal/utils/singleton.go
node/node.go
p2p/host.go

The sampledlogger helped me identify more p2p errors on mainnet so that I can tune the parameters and prepare for the blacklist feature, and adjust the timeout value for context.

Sampledlog for more p2p errors

---

core/staking_verifier.go
core/state/statedb.go
staking/slash/double-sign.go
staking/types/validator.go
staking/types/validator_test.go

The previous cap of bls key is a dynamic number based on total open slots. It was 1/3 of open slots, so 320/3 = 106 in mainnet. This change hard code that limit and not let it float. This way, we will keep a relatively low cap after we keep adding new open slots.
Tested locally
**NO**
**NO**
9. **Does the existing `node.sh` continue to work with this change?**
Yes
10. **What should node operators know about this change?**
We will have announcement on this.
11. **Does this PR …

Hard code 106 as the cap of bls keys per validator

---

api/service/networkinfo/service.go
api/service/syncing/syncing.go
cmd/bootnode/main.go
cmd/harmony/main.go
consensus/consensus_msg_sender.go
consensus/consensus_service.go
consensus/consensus_v2.go
core/blockchain.go
go.mod
internal/configs/sharding/fixedschedule.go
internal/configs/sharding/localnet.go
internal/configs/sharding/mainnet.go
internal/configs/sharding/pangaea.go
internal/configs/sharding/partner.go
internal/configs/sharding/shardingconfig.go
internal/configs/sharding/stress.go
internal/configs/sharding/testnet.go
internal/hmyapi/apiv1/blockchain.go
internal/hmyapi/apiv1/types.go
internal/hmyapi/apiv2/blockchain.go
internal/hmyapi/apiv2/types.go
internal/utils/singleton.go
node/node.go
node/node_syncing.go
p2p/host.go

```
3b72b4e4 (HEAD -> t3, leo/merge_master_to_t3_0616) Merge remote-tracking branch 'origin/master' into t3
8da55713 (origin/master, origin/HEAD) address review comments on #3164
3eb2b508 [log] add more debug info in errChan with p2p validation
8c01dbca [p2p] add some more comments and error messages
2b9f9c8e [context] change log level to warn if deadline exceeded
303c6eff [p2p] output validation context exceed error
fcc4a0c6 [p2p] set max pubsub message size to 256Kb
b32e2c2c [log] add more log context in err message
02967df2 [context] shorten the timeout of message handler
9f7d8bc3 [p2p] use validation function context
33d4bfb5 [log] add sample log of message handle time
e05724c6 [log] sample the cost log of p2p validation
6f7e8823 [p2p] sample log p2p validation error messages
e4026738 …
```

Merge master to t3 0616

---

internal/configs/sharding/mainnet.go

Set the epoch number for slot increase from 320->480 at epoch 208 and from 480->640 at epoch 213
Already tested slot increase in dryrun network.
**NO**
Tested in dryrun network with same slot change at epoch transition.
ETA for epoch 208 is around Wednesday June 24 2020
7. **What should …

set epochs for slot increase

---

hmy/api_backend.go
shard/committee/assignment.go

Previously, the EPoS computation uses the current epoch for fetching shard configs, which should be using the new epoch.
This PR correct that for both epoch transition and RPC logic with regard to the EPoS computation.

Make EPoS compute work with correct epoch shard config

---

consensus/consensus.go
consensus/consensus_v2.go
go.mod
node/node.go

Previous release v2.1.5 hit an issue that leaders weren't able to process all the commit messages sent by validators, even the consensus was reached.
The issue was the added validation layer as it's gone after we revert leader to v2.1.3 release.
When the pubsub validation function is added to p2p layer, every p2p message will spawn a goroutine (https://github.com/harmony-one/harmony/blob/23d1890619ba11a8f159c95dcbdb99724e7336b4/node/node.go#L390) to do validation. After the validation, every valid p2p message will spawn a new goroutine (https://github.com/harmony-one/harmony/blob/23d1890619ba11a8f159c95dcbdb99724e7336b4/consensus/consensus_v2.go#L29) to process each message.
However, due to the redundancy of p2p messages, not all messages are intended for leaders/validators, but the …

Reduce number of calls to consensus messages

---

internal/hmyapi/apiv1/util.go
internal/hmyapi/apiv2/util.go
node/node.go

add error info if shard does not match and make sure the rpc return it

return error info if shard does not match

---

consensus/quorum/quorum.go
crypto/bls/bls.go

Inline validator is used to solve the missing signature issue of leader.

Use lru to cache blspubkey

---

api/service/networkinfo/service.go

There is no need to add peer based on client topic

[libp2p] do not advertise on beacon client

---

internal/configs/sharding/mainnet.go

The current shard 0 block time is not optimal and network is loaded with invalid messages. We already seen issues after the first batch of slot increase due to increased network scale. It will likely have similar problems in the second batch. So postpone the increase of slots before we further optimize network layer.

Postpone second batch of slot increase

---

internal/hmyapi/apiv1/util.go
internal/hmyapi/apiv2/util.go

When no pageSize is passed from clients like explorer dashboard, it only lists 100 transactions on account page. By the specification, the default should be 1000.

[rpc] change default transaction limit to 1000

---

api/service/explorer/service.go
api/service/explorer/storage.go
api/service/explorer/storage_test.go
node/node_explorer.go

Do not reinit explorer db for every node restart to make explorer node troubleshooting easier.

Do not reinit the explorer db every restart

---

consensus/construct_test.go
consensus/double_sign.go
consensus/fbft_log.go
consensus/leader.go
consensus/quorum/one-node-one-vote.go
consensus/quorum/one-node-staked-vote.go
consensus/quorum/one-node-staked-vote_test.go
consensus/quorum/quorum.go
consensus/threshold.go
consensus/view_change.go
multibls/multibls.go
node/node_explorer.go
shard/shard_state.go

IsQuorumAchieved() is a pretty costly function as it loops through all votes and sum up the voting powers. It is called twice for every consensus messages, which can be a huge amount of CPU drain on the leader.
This PR refactor the whole leader consensus checking process to avoid redundant work on quorum checking and also BLS key serialization/deserialization.
This PR is fully compatible in terms of onchain logic.

Refactor quorum calculation and signature submission process

---

cmd/harmony/main.go
consensus/checks.go
consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_service_test.go
consensus/consensus_v2.go
consensus/consensus_viewchange_msg.go
consensus/construct.go
consensus/construct_test.go
consensus/double_sign.go
consensus/fbft_log.go
consensus/leader.go
consensus/quorum/one-node-one-vote.go
consensus/quorum/one-node-staked-vote.go
consensus/quorum/quorum.go
consensus/threshold.go
consensus/validator.go
consensus/view_change.go
hmy/api_backend.go
internal/chain/engine.go
internal/configs/node/config.go
internal/configs/node/config_test.go
multibls/multibls.go
node/node.go
node/node_cross_link.go
node/node_handler.go
node/node_newblock.go
shard/shard_state.go

Bind the C bls public key object with the serialized shard.BLSPublicKey bytes to avoid many unnecessary conversion between the two.

Refactor bls public key into a wrapper

---

consensus/consensus_service.go

OldLeader can be nill when the node is first started. This wasn't a problem because since the IsEqual works with nil param. But now we are dereferencing the Object from the oldLeader, and it needs a nil check.

Add nil check on leader checks

---

cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_service_test.go
consensus/consensus_test.go
consensus/consensus_v2.go
consensus/consensus_viewchange_msg.go
consensus/construct.go
consensus/construct_test.go
consensus/leader.go
consensus/threshold.go
consensus/validator.go
consensus/view_change.go
crypto/bls/bls.go
hmy/api_backend.go
internal/configs/node/config.go
multibls/multibls.go
node/node.go
node/node_handler.go
node/node_handler_test.go
node/node_test.go
shard/shard_state.go
staking/types/messages_test.go

Create BLSPrivateKeyWrapper and wrap private and public key together.
Also avoid recreation of BLS Mask for every round of consensus.
Tested locally with consensus and view change.

Bind public keys into private key wrapper

---

consensus/consensus_service.go
consensus/double_sign.go
crypto/bls/bls.go
hmy/api_backend.go
internal/hmyapi/apiv1/blockchain.go
internal/hmyapi/apiv2/blockchain.go
shard/shard_state.go
staking/slash/double-sign.go
staking/types/validator.go

Remove the usage of ToLibBLSPublicKey and always use BytesToBLSPublicKey which is the cached version.

Remove expensive bls key serialization code and use the cached version

---

consensus/fbft_log.go

The FBFTMessage.String() func may cause nil pointer if the sender and leader key field is nil.

Fix potential nil pointer on fbft log bls key fields.

---

core/types/block.go
internal/chain/reward.go
internal/utils/singleton.go
node/node.go
node/node_cross_link.go
shard/shard_state.go

Single flight is meant for duplicate func call avoidance (same-time duplicate calls). it's not cache. The func call results are not cached (https://medium.com/@vCabbage/go-avoid-duplicate-requests-with-sync-singleflight-311601b3068b)
Found the issue after seeing lots of accumulated pending goroutines in our node. They are caused by the sleep() and forget() part of singleFlight. Since it's not cache, actually the func got called many times: 
Besides the rpc layer, all other part of the singleFlight usage are wrong. Should instead just use lru cache.
This PR also fix the cache key on voting power cache which was hidden due to that single flight didn't do the cache work for voting power.

Remove all wrong usage of singlr flight; also fix voting power cache key

---

cmd/harmony/main.go
hmy/api_backend.go
hmy/backend.go
internal/configs/node/config.go
internal/hmyapi/apiv1/backend.go
internal/hmyapi/apiv1/harmony.go
internal/hmyapi/apiv2/backend.go
internal/hmyapi/apiv2/harmony.go
internal/hmyapi/backend.go
internal/hmyapi/common/types.go
node/rpc.go
p2p/host.go

support both apiv1 and apiv2
Examples on localnet:
curl -s --request POST 'http://127.0.0.1:9500/' \
--data-raw '{ "jsonrpc": "2.0", "method": "hmyv2_getPeerInfo", "params": [""], "id": 1}'
curl -s --request POST 'http://127.0.0.1:9500/' \
--data-raw '{ "jsonrpc": "2.0", "method": "hmy_getPeerInfo", "params": [""], "id": 1}'

[rpc] add API to return p2p peer info

---

consensus/consensus_v2.go
consensus/leader.go

Check the following issue on the detailed explanation of why this commit makes sense.
https://github.com/harmony-one/harmony/issues/3225
The onPrepare and onCommit will do signature verification of the message payload.
So, there is no need to do duplicated sanity check when handling Prepare/Commit messages.
We reserve the signature verification on other messages, as they are not duplicated.
This PR can reduce the CPU load of leader during consensus.

[consensus] remove duplicated signature verification

---

cmd/harmony/main.go
consensus/checks.go
consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_test.go
consensus/consensus_v2.go
consensus/leader.go
consensus/quorum/one-node-staked-vote.go
consensus/validator.go
node/node_newblock.go

Instead of locking on on all consensus logic with a single mutex. Use more fine grained RWMutex to lock on Read and Write separately, and also make signature checking not locked to parallelize the heavy CPU process.
Did more benchmarking on the code.
Compared to the version without this change. This PR makes the CPU usage lower by around **10%**.
However, on my instrumented node, I didn't see obvious improvement on the speed of processing consensus messages between code with and without this PR. It could be because the instrumented node can not exercise all operations of a real leader.
But compared to the mainnet leader node on shard 0, the instrumented node did perform about 20% better in consensus message processing.

Use finer grained RWMutex for consensus logic

---

consensus/checks.go
consensus/consensus_service.go

The signature map can be reset if without the lock (https://github.com/harmony-one/harmony/issues/3222)
Also correct the condition of sanity check to avoid the problems that cause view change to stuck.

fix view change race issue

---

go.mod
internal/cli/flag.go
internal/cli/flag_test.go
internal/cli/parse.go
internal/cli/parse_test.go
internal/cli/register.go

Another PR for #3110. Add a cli module which wraps `spf13/pflag` for clean cmd code. The module is not used right now. But will be used later.

[cmd] added a helper module cli for clean cmd

---

consensus/consensus_service.go
consensus/construct_test.go
consensus/fbft_log.go
consensus/leader.go
consensus/quorum/one-node-staked-vote.go
consensus/quorum/one-node-staked-vote_test.go
consensus/quorum/quorom_test.go
consensus/quorum/quorum.go
consensus/threshold.go
consensus/view_change.go
consensus/view_change_test.go
crypto/bls/mask.go
crypto/bls/mask_test.go
hmy/api_backend.go
internal/chain/engine.go
internal/chain/sig.go
internal/hmyapi/apiv1/blockchain.go
internal/hmyapi/apiv2/blockchain.go
node/node.go
node/node_handler.go
shard/shard_state.go

The bls Mask implementation contains lot of expensive loops which is replaced with efficient lookup index.
This should further speed up the leader process as leader need to do lots of BLS Mask operations.

Optimize bls Mask infra code to avoid expensive loops

---

scripts/node.sh

We used to check only the installed version of harmony binary.
There are cases when validator didn't restrart the harmony process
even though the binary was updated.
So, we print out both on-disk binary version and the running version.

[node.sh] print out running binary version

---

hmy/bloombits.go
hmy/hmy.go

This PR fixes fetching past event logs using block number ranges. Tested locally.
```
blockchain
.logs({
fromBlock: "0x23",
toBlock: "latest",
address: contractor
})
```
output
```
{ address: '0x486d25ffee86070f122376ec5eac73ab29bd4569',
topics:
[ '0x064b1e66d8d787e36504c45aac3405f69335030ab8dc365a34919de13b61799c' ],
data:
'0x000000000000000000000000c162199cdaeaa5a82f00651dd4536f5d2d4277c5',
blockNumber: '0x23',
transactionHash:
'0xf311682e9f43b2a5dabe5ef567de0961b145e7e7ee4af5bd25112f3b2c459730',
transactionIndex: '0x0',
blockHash:
'0xb7023b64fd0be0de4e268cb08dbecc47d1d4be9d3702c633d2c98f43c000123c',
logIndex: '0x0',
removed: false }
{ address: '0x486d25ffee86070f122376ec5eac73ab29bd4569',
topics:
[ '0x064b1e66d8d787e36504c45aac3405f69335030ab8dc365a34919de13b61799c' ],
data: …
```

Fix fetching past event logs using block ranges

---

hmy/staking.go
staking/types/validator.go

This PR adds signing information for the latest 30 epochs to validator information such that dashboard (other clients) can compute uptime for the last 30 epochs (or even less if required) instead of only lifetime uptime information.
Tested by running a node for mainnet:
```
...
{
"apr": "0.113261084045153310",
"epoch": 224
},
{
"apr": "0.109502671104892448",
"epoch": 225
}
],
"epoch-blocks": [
{
"blocks": {
"signed": 5159258,
"to-sign": 5193708
},
"epoch": 225
},
{
"blocks": {
"signed": 4995768,
"to-sign": 5029868
},
"epoch": 224
},
{
"blocks": {
"signed": 4832097,
"to-sign": 4866028
},
"epoch": 223
},
...
```

[Uptime] Compute and return lastest 30 epoch signing information

---

rpc/types.go

This is a fix for #3259.
As is, the RPC can return really large or small numbers in scientific notation. This can break some existing behavior (as caught in our testnet regression test [here](https://jenkins.harmony.one/job/regression_test/122/) (internal link)). This PR forces the use of JSON numbers in the RPC return's unmarshall. This should preserve old behavior.

Fix number return types of all RPCs

---

internal/blsgen/kms_test.go

Travis server occasionally failed in a timeout test due to virtual machine's performance. (https://travis-ci.com/github/harmony-one/harmony/jobs/366673332#L2067).
Increase the timeout to 1 second to avoid performance could impact test result.

[cmd] increase timeout in TestPromptACProvider_prompt

---

cmd/harmony/bls.go

Fix the problem that max bls key count 10 cannot be reached

[node.sh] fix max bls key count 10 cannot be reached

---

core/types/tx_pool.go

Hit transaction over size error when I try to deploy one of the bigger smart contracts (the txn size is 40.1k). 
The original txn size limit is kind of adhoc for ddos prevention, but we eventually shouldn't enforce such limit on the protocol level since many use cases require big txns such as data storage.

raize txn size limit to 128kb

---

rpc/staking.go

Currently, the `Undelegations` field for delegator info can return null due to improper construction of the undelegations JSON array. This PR fixes this bug. Moreover, tests were added [here](https://github.com/harmony-one/harmony-test/commit/f704c8969fe1745c94e1cd7dfd2942e85c7b43b3) to ensure this does not happen again.

RPC - Fix null undelegations in delegator info

---

internal/shardchain/dbfactory.go

It has been causing many issues for validators with "too many open files" error, which causes significant downside for signing. Reduce the file handle needed for level db so it won't cause trouble easily for validators.

reduce file handle needed for level db

---

cmd/harmony/main.go

Fix the high CPU usage in Local net. The error is from the wrong intepretation of legacy flag `--dns`. After the fix, the local test `make debug` cost drop from ~80% to ~5% on AWS Linux machine.

[cmd] fix localnet syncing provider

---

hmy/hmy.go
node/node_syncing.go
rpc/blockchain.go

[rpc] Add inSync & beaconInSync RPCs to check if node blockchains are in sync
[syncing] Expose IsOutOfSync
[hmy] Add IsOutOfSync to NodeAPI
Example:
```
$ curl --location --request POST 'http://localhost:9500' --header 'Content-Type: application/json' --data-raw '{"jsonrpc": "2.0", "method": "hmy_inSync", "params": [], "id": 1}' | jq 
{
"id": 1,
"result": true
}
```
```
$ curl --location --request POST 'http://localhost:9500' --header 'Content-Type: application/json' --data-raw '{"jsonrpc": "2.0","method": "hmy_beaconInSync","params": [],"id": 1}' | jq
{
"id": 1,
"result": true
}
```

[rpc]  Add sync check RPCs

---

cmd/harmony/flags.go
cmd/harmony/flags_test.go
cmd/harmony/main.go

Command line fix for explorer node. (https://github.com/harmony-one/harmony/pull/3304) Archive mode is now default to enabled when running explorer node.
Two test cases added for explorer archival mode.

[cmd] if running explorer node, set archive to true

---

api/service/syncing/syncing.go

Fix the testnet DNS being panic during bootstrap. The problem is that some new block are submitted to the DNS nodes while DNS syncing is not prepared for receiving this data. 
Note: this is just a temporary fix since pushing new block shall be removed. Also, if we switch to distributed syncing we can get rid of the DNS stuff totally. 
Not done yet. Need to test on testnet.

[sync] fix testnet syncing panic issue

---

api/service/syncing/syncing.go

Currently, block download requests are sent one by one - one block for each request. This can be a performance bottle net for nodes are connected to DNS nodes with very high RTT time (E.g. can reach 20~30s/1000 blocks).  In this case, long download time is mainly caused by RTT, and if we can request blocks in batches of 10, the download time is expected to be reduced by 10.
This PR make block download requests as a batch of 10 and achieve the performance boost of downloading blocks as expected. 
Tested with local macbook connecting to testnet shard 1. Since testnet shard 1 have only 2 DNS nodes so these nodes will not be randomed out (https://github.com/harmony-one/harmony/pull/3071) and is fixed. Before the batch change, downloading cost 47s/1000block, while with this update, downloading …

[sync] added batched block sync logic

---

go.mod
hmy/blockchain.go
rosetta/common/operations.go
rosetta/common/operations_test.go
rosetta/rosetta.go
rosetta/services/block.go
rosetta/services/block_test.go
rosetta/services/network.go
staking/network/reward.go

This PR is related to #3312 .
This fixes some decimal precision errors as well as add 'accounting' transactions for block rewards in the pre-staking era. 
Block reward operations on respective blocks/transactions will look a little something like this:
```json
{
"Type": "PreStakingBlockReward",
"Operations": [
{
"operation_identifier": {
"index": 0
},
"type": "PreStakingBlockReward",
"status": "success",
"account": {
"address": "one13rnn8uawlpqpcsh0hpm2k26xxusq639wkvl7r5",
"metadata": {
"hex_address": "0x88E733F3AEF8401c42EfB876Ab2B4637200d44AE"
}
},
"amount": {
"value": "113207547169811320",
"currency": {
"symbol": "ONE",
"decimals": 18
}
}
}
],
"Currencies": [
{
"symbol": "ONE",
"decimals": 18
}
],
"NilAmountPresent": false
}
```
This PR also refactors 'special' transactions (genesis & …

Rosetta Implementation - pt2 FIX (Stage 3.2 of Node API Overhaul)

---

api/service/syncing/downloader/client.go

Some node occasionally get stuck in the syncing process. There is no log message with `[SYNC]` presented in the log, so I guess there is some code get stuck in function `doSync` (node/node_syncing.go:226). 
After checking the the whole logic, found that the only place that might get stuck is the GRPC dial - dial is not set a timeout. So this PR is proposed to fix this issue.
Done in local node connected to testnet. The sync process can proceed as it used to.

[sync] Fix sync stuck issue.

---

internal/chain/reward.go

To fix https://github.com/harmony-one/harmony/issues/3292
Tested with testnet node which fully sync'ed without issues.

Add one-off fork for testnet adjusted reward

---

core/tx_pool.go

This PR closes #3329
Currently, we only add an account to the beat map if it is executable, but it is possible to only add a non-executable transaction (i.e: a 'pooled future transaction') having never submitted an executable transaction, thus never getting an initial beat --> never getting timeout evicted from the pool.
This PR adds a tx's sender address to the beat map after successfully adding the transaction to the pool.

Refresh acc timeout beat each time a tx is added

---

core/genesis.go
rosetta/services/block.go

This PR adds a test account that is specific to localnet for devs to use when building locally. This is needed, for example, in our [multichain](https://github.com/harmony-one/multichain) integration.
The account's private key is:
```
1f84c95ac16e6a50f08d44c7bde7aff8742212fda6e4321fde48bf83bef266dc
```
The account's address is: 
```
one155jp2y76nazx8uw5sa94fr0m4s5aj8e5xm6fu3
```
I've also updated the Rosetta genesis block logic to correctly report localnet genesis funds.

Add localnet only testing account in genesis conf

---

core/state_transition.go
node/node_handler.go

Currently the block link delay stays at around 100 blocks between beacon chain and shard chain for both testnet and mainnet.
We can see that the crosslink relay will slowly catchup if it sends 4 blocks in a batch, and will slowly fall behind if it sends 3 blocks in a batch.
So basically the condition to increase the catch up speed from 3 blocks to 4 blocks in the batch is the stable equilibrium for crosslink relay.
This PR change the stepping function's condition from 100 blocks to 5 blocks. Expect this to shorten the crosslink delay from ~100 blocks to roughly 5 blocks.
Tagged along in this PR is the change to print evm error as Info() for better troubleshooting.

Increase crosslink catching rate, expect to have equillibrium at 5 block delay

---

rpc/filters/filter.go

jellyswap reported issue where getting old logs like past 1000+ blocks times out. I was able to verify this and this seems to happen due to expensive `indexedLogs` call, which is not really needed and we could simply get the `unindexedLogs` which is sufficient.

[logs] disable log log filtering based on the bloom bits indexed and just do raw block iteration and bloom matching

---

rpc/transaction.go
rpc/v1/types.go
rpc/v2/types.go

This PR fixes the transaction receipt bug that happens when there are both normal and staking transaction. e.g., in https://explorer.harmony.one/#/staking-tx/0xb42e20638347a0296f8b54b0c3381a96ab1e3d9c120cb505eed89a73a0cc5631 the value is shown as Infinity. This happens due to multiple receipt logs wrongly fetched. 
Before
```
./hmy blockchain transaction-receipt 0xb42e20638347a0296f8b54b0c3381a96ab1e3d9c120cb505eed89a73a0cc5631 -n https://api.s0.t.hmny.io
{
"id": "0",
"result": {
"blockHash": "0x66ad6b31d39f89ac68d5d577e38c5df1256148c6de8daec5b1ea5a85811ff113",
"blockNumber": "0x0",
"contractAddress": "0x0000000000000000000000000000000000000000",
"cumulativeGasUsed": "0x1f04d",
"gasUsed": "0x1f04d",
"logs": [
{
"address": "0x3e37a9c5f2ec88b7566ae68a5d38707e5e25f243", …
```

[rpc] fix transaction receipt fetch bug

---

core/blockchain.go
hmy/hmy.go
hmy/staking.go
internal/chain/engine.go
rosetta/common/errors.go
rosetta/common/operations.go
rosetta/common/operations_test.go
rosetta/services/block.go
rosetta/services/block_test.go
rosetta/services/network.go

This PR is related to #3312 .
TLDR: This fixes the Undelegation reward operation as well as correctly accounts for the redelegation balance changes. This also adds an info dump for the last block that was garbage collected for non-archival DBs. 
Previously, the Undelegation transaction would result in a balance changing operation (other than gas). As this is not the case due to the locking period, the balance at a given block could be different than what it is on-chain. Therefore a 'special' transaction is added to the implementation to account for the Undelegation payouts at the last block of an epoch (similar to the pre-staking era block rewards). 
Note that all nodes (archival & pruned) store the last block of an epoch, however, the Undelegations saved for the said block are **after** …

Rosetta Implementation - pt2 FIX2 (Stage 3.2 of Node API Overhaul)

---

rpc/staking.go

Example:
```
$ curl --location --request POST 'http://localhost:9500' --header 'Content-Type: application/json' --data-raw '{ "jsonrpc": "2.0", "method": "hmy_getUndelegationPool", "params": ["one1zksj3evekayy90xt4psrz8h6j2v3hla4qwz4ur"], "id": 1}' | jq
{
"id": 1,
"result": 0
}
```

[rpc] Add RPC to return pool of locked undelegated tokens

---

api/service/syncing/syncing.go
consensus/validator.go

This PR is to enable better coordination between consensus and sync. Two problem is fixed:
1. Logic optimization. Move consensus spin up the state sync after `tryCatchup`. Remove the 2 block delay.
2. Remove an unnecessary time.Ticker in sync logic. Thus will reduce the sync speed (from 3.5s -> 1.5s in local test).
Test done locally. Test branch: https://github.com/JackyWYX/harmony/tree/sync_consensus_fix_test.
In this branch, Following changes are made:
1. Disable the consensus insertChain logic in `tryCatchup`. So all block update are done in sync module.
2. Added a lot of print logs to observe the behaviour.
Run a local node on 
Following are observed:
1. Consensus module inform sync module upon receiving onCommitted message.
2. Each sync process takes < 1.5s to complete.

[consensus] enable the consensus module can spin up doSync

---

core/tx_list.go
core/tx_pool.go
internal/configs/sharding/localnet.go

* [config] Fix confusing variable name in Localnet config
* [pool] Bypass balance check for Delegate transactions, let validation be done with validateStakingTx
* [list] Perform validation on staking transactions when filtering for overpriced/invalid transactions
* [list] Rename FilterCost to FilterValid, to reflect changes & update comment
* [pool] Remove now unnecessary staking logic in demotion logic
* [pool] Refactor pendingEpoch calculation into separate pool function
Tested locally before & after Redelegation epoch.

[pool] Update pool logic to accept Delegate transactions using redelegation tokens

---

api/service/syncing/syncing.go
consensus/validator.go

Reverts harmony-one/harmony#3340. Out of sync is flooding testnet. May research more later.

Revert "[consensus] enable the consensus module can spin up doSync"

---

internal/params/config.go

redelegation and 7 epoch locking have been tested in testnet manually and also tested with regression tests. Epoch 289 happens around 9PM Thursday. 
also refer to https://medium.com/harmony-one/restore-7-epochs-locking-period-with-redelegation-6b15c47c532c

enable mainnet redelegation+7epoch locking at epoch 289

---

internal/params/config.go

due to mainnet upgrade delay, we have to postpone redelegation+7epoch launch by 1 epoch to give more time for validators to upgrade.

Postpone redelegation to epoch 290

---

consensus/consensus.go
consensus/consensus_service.go
consensus/debug.go
consensus/validator.go
go.mod
hmy/hmy.go
node/api.go
node/node.go
node/node_handler.go
node/node_newblock.go
rpc/common/types.go

This is used to debug consensus/viewchange state.

[rpc] expose consensus internal data via rpc
