harmony-one/harmony

consensus/consensus_test.go
node/node.go
node/node_test.go

now the top of the tree passed the travis_checker.sh script.

fix travis_checker go test error

---

scripts/go_executable_build.sh

upload bls dependency libraries to s3 bucket

---

scripts/go_executable_build.sh

We may need to build one binary for testing.
This change enables building one binary only to speed up the testing
process.

support build one binary only

---

internal/utils/utils.go
internal/utils/utils_test.go

add test functions
this is to support issue #271 

add private key save and load functions

---

.gitignore
cmd/bootnode/main.go
p2p/host.go
p2p/host/hostv1/hostv1.go
p2p/host/hostv2/hostv2.go
p2p/host/mock/host_mock.go
p2p/p2pimpl/p2pimpl.go
scripts/go_executable_build.sh

support save/load private key to .bnkey file

add skeleton of bootnode

---

consensus/consensus.go
consensus/consensus_leader.go
consensus/consensus_leader_msg.go
consensus/consensus_validator.go
consensus/consensus_validator_msg.go

2 shards, 110 consensus, 317 total TPS, 11 nodes 127.0.0.1, 55, 155.107

Refactor basic message checking code in consensus

---

node/node.md

Update service doc
No need
No need
no need
no need

Update service doc

---

node/service/random_generation.go
node/service/role_conversion.go

https://github.com/harmony-one/harmony/issues/368
Will  add test later
NA
++ ./test/../test/cal_tps.sh tmp_log/log-20190130-213014/all-leaders.txt tmp_log/log-20190130-213014/all-validators.txt
+ results='2 shards, 130 consensus, 415 total TPS, 11 nodes
127.0.0.1, 65, 213.026'
+ echo 2 shards, 130 consensus, 415 total TPS, 11 nodes 127.0.0.1, 65, 213.026
+ tee -a tmp_log/log-20190130-213014/r.log
2 shards, 130 consensus, 415 total TPS, 11 nodes 127.0.0.1, 65, 213.026
+ echo 2 shards, 130 consensus, 415 total TPS, 11 nodes 127.0.0.1, 65, 213.026

Adding place holders for service (random generation, role conversion)

---

api/service/syncing/syncing.go
consensus/consensus.go
consensus/consensus_leader.go
consensus/consensus_validator.go
consensus/errors.go
node/node.go
node/node_handler.go

Fixing state syncing breaking with new BLS consensus code. The last mile problem still need to be fix.

make state syncing compatible with new BLS consensus code; last mile

---

api/service/manager.go
api/service/staking/service.go

Will add tests once there is more code.
* Before
* After
Will add later.

Adding Place Holder for Staking Service

---

api/service/discovery/service.go
node/node_handler.go

#373 
n/a
scripts/travis_checker.sh passed
The service is not enabled yet.  No impact to existing code.
enable discovery service in node and harmony.

Fix ping message in discovery service

---

.travis.yml
api/service/blockproposal/service.go
api/service/clientsupport/service.go
api/service/consensus/service.go
api/service/networkinfo/service.go
api/service/randgen/service.go
api/service/rconversion/service.go
api/service/staking/service.go
node/node.go

Refactoring code

---

api/service/discovery/discovery_test.go
api/service/discovery/service.go
api/service/networkinfo/service.go
api/service/staking/service.go
node/node.go
specs/p2p/peerdiscovery.md

#373 
n/a
local build and travis checker.
the services are not enabled yet.

Split discovery service

---

cmd/client/wallet/lib/lib.go
cmd/client/wallet/lib/lib_test.go
cmd/client/wallet/main.go

I was reading wallet code for beacon work and feel that we need to refactor this code to make it looking better.
NA

Refactor wallet code

---

p2p/errors.go
p2p/host/hostv2/hostv2.go
p2p/host/message.go
p2p/host/message_test.go

no retry on newstream error
reduce number of retry
local build and test passed

add error variables for p2p/host

---

scripts/node.sh

versioning of the node running script

---

node/node.go

clean up support client as its moved as a service

clean up support client as its moved as a service

---

api/service/syncing/syncing.go
consensus/consensus.go
node/node_newblock.go

Clean up code which caused a lot of noise in deploy.sh
NA
NA

cleanup syncing logging which prints very long debug code in deploy.sh

---

api/service/staking/readme.md

Doc for staking service. This will be used for overall architectural doc which is WIP.
NA 
NA

quick doc for staking

---

api/client/client.go
api/client/client_test.go
cmd/client/txgen/main.go
cmd/client/wallet/lib/lib.go
cmd/client/wallet/lib/lib_test.go
cmd/client/wallet/main.go
consensus/consensus.go
consensus/consensus_leader.go
consensus/consensus_leader_msg_test.go
consensus/consensus_leader_test.go
consensus/consensus_validator_test.go

Improve code quality.
Maps are reference types, so they are allways passed by reference. You don't need a pointer.
NA
NA

Maps are reference types, so they are allways passed by reference.

---

api/proto/discovery/pingpong.go
api/service/discovery/service.go
api/service/networkinfo/service.go
cmd/bootnode/main.go
cmd/client/txgen/main.go
cmd/client/wallet/main.go
cmd/harmony.go
consensus/consensus.go
internal/utils/flags.go
internal/utils/utils.go
internal/utils/utils_test.go
node/node.go
node/node_handler.go
p2p/group.go
p2p/host.go
p2p/host/hostv2/hostv2.go
p2p/host/mock/host_mock.go
test/deploy.sh
test/kill_node.sh

integration of libp2p peer discovery into harmony node program
local deploy.sh and travis_checker passed w/o enabling the libp2p_pd
test log is available on gist using -libp2p_pd mode.
https://gist.github.com/LeoHChen/a669d4e405443e91d0890e87bc0f3884

Integrate libp2p into harmony node

---

node/node.go

Now the state syncing works normally

fixed state syncing the last mile issue for BLS consensus integration

---

test/p2pchat/LICENSE
test/p2pchat/chat.go
test/p2pchat/flags.go

It is based on go-libp2p-examples/chat-with-rendezvous
It is used to test pubsub functions

add a p2pchat test app to test pubsub

---

core/blockchain.go
node/node_handler.go

fix bug with shard state not update correctly

fix shard state update bug

---

test/cal_tps.sh

It will be used in Jenkins server to check success of state syncing

add log for state syncing test

---

cmd/harmony.go
consensus/consensus.go
consensus/consensus_leader.go
consensus/consensus_validator.go
consensus/engine/consensus_engine.go
consensus/engine/errors.go
core/block_validator.go
core/blockchain.go
core/chain_makers.go
core/evm.go
core/headerchain.go
core/resharding.go
core/state_processor.go
drand/drand.go
drand/drand_leader.go
node/node_handler.go
node/node_newblock.go
node/worker/worker.go
test/p2pchat/chat.go

2 shards, 78 consensus, 1312 total TPS, 11 nodes 127.0.0.1, 1, 719.096

Add channel to pass pRnd from DRG to consensus; Make consensus engine a separate package to break import cycle.

---

api/service/manager_test.go
crypto/vrf/p256/p256.go
crypto/vrf/vrf.go
drand/drand.go
drand/drand_leader.go
drand/drand_validator_msg.go
drand/drand_validator_msg_test.go

go test succeeded.
Running golint...
golint passed.
Running goimports...
goimports passed.
All Checks Passed!!! :-)

Add real vrf into drand with validator generating vrf and leader verifying them; Also reduce manager_test.go's delay

---

scripts/go_executable_build.sh

support upload libraries to wallet repo on both mac and linux.
* Before
* After
tested on both mac and linux.

upload lib for wallet on mac/linux

---

api/proto/discovery/pingpong.go
api/proto/discovery/pingpong_test.go
api/proto/discovery/readme.md
api/service/blockproposal/service.go
api/service/clientsupport/service.go
api/service/config.go
api/service/consensus/service.go
api/service/discovery/discovery_test.go
api/service/discovery/service.go
api/service/explorer/service.go
api/service/manager.go
api/service/manager_test.go
api/service/networkinfo/service.go
api/service/randomness/service.go
api/service/rconversion/service.go
api/service/staking/service.go
cmd/harmony.go
consensus/consensus.go
consensus/consensus_leader.go
consensus/consensus_test.go
consensus/consensus_validator.go
node/node.go
node/node_handler.go
node/node_test.go
p2p/group.go
p2p/host/message.go

This set of change will enable consensus on beacon chain shard.
* Before
* After
Manual test to start Harmony node, and see consensus "HOORAY" on leader.

Use Libp2p pubsub to reach consensus

---

core/resharding.go
core/resharding_test.go

add resharding unit test 

---

node/node.go
node/node_syncing.go

clean up and move syncing code into separate files

clean up and move syncing code into separate files

---

node/node.go

add beacon chain for syncing as place holder

add beacon chain for syncing as place holder

---

node/node_newblock.go

set back default threshold to 1

---

api/proto/common.go
api/service/staking/service.go
api/service/syncing/syncing.go
drand/drand.go
drand/drand_leader.go
node/node.go

send staking transaction to beacon chain. Just follow discovery example and it needs help to verify the logic. it seems to be wrong.

send staking transaction to beacon chain

---

scripts/node.sh

support the testnode platform, to automate the download/run process.
* Before
* After

adjust node.sh for the testnet

---

cmd/harmony.go
node/node.go
p2p/host/hostv2/mock/hostv2_mock.go
p2p/host/mock/host_mock.go
p2p/mock_stream.go

add beaconchain database support for normal shard nodes

---

api/proto/common.go
node/node_handler.go

add logic to receive staking txns

add logic to receive staking txns

---

api/service/blockproposal/service.go
api/service/clientsupport/service.go
api/service/consensus/service.go
api/service/discovery/service.go
api/service/explorer/service.go
api/service/manager.go
api/service/manager_test.go
api/service/networkinfo/service.go
api/service/randomness/service.go
api/service/rconversion/service.go
api/service/staking/service.go
node/node.go

set up message channels for services

set up message channels for services

---

node/node.go
node/node_handler.go

clean up duplicate funcs

---

api/client/service/server_test.go
api/proto/identity/identity.go
api/proto/identity/identity_test.go
crypto/bls/bls_test.go

https://github.com/harmony-one/harmony/issues/316
Added tests for Identity messages
* Before
?   	github.com/harmony-one/harmony/api/proto/identity	[no test files]
* After
PASS
coverage: 86.7% of statements
ok  	github.com/harmony-one/harmony/api/proto/identity	0.009s

Increase test coverage by 10% or more

---

node/node.go
node/node_handler.go

Reverts harmony-one/harmony#492
it was breaking consensus

Revert "clean up duplicate funcs"

---

scripts/node.sh

Need to update the beacon node multiaddress after relaunch the testnet.
* Before
* After
Launched a new node, can join the shard.

update beacon chain multiaddr

---

node/node.go
node/node_test.go
node/staking.go
node/staking_test.go

go test succeeded.
Running golint...
golint passed.
Running goimports...
goimports passed.
Running go generate...
go generate succeeded; all generated files seem up to date.
All Checks Passed!!! :-)

Move staking related code to staking.go

---

.gitignore
README.md
cmd/harmony.go
consensus/consensus.go
consensus/consensus_leader.go
consensus/consensus_test.go
consensus/consensus_validator.go
drand/drand.go
drand/drand_leader.go
drand/drand_leader_msg_test.go
drand/drand_test.go
drand/drand_validator.go
drand/drand_validator_msg_test.go
node/node_handler.go
node/node_newblock.go
node/node_test.go
node/service_setup.go

Failed to reach consensus on DRG on AWS deployment because of drand validators started as leaders.
Reach consensus on AWS deployment. Only enable randomness service on validators.
* Before
* After
Run on AWS.
Sun Feb 24 10:20:09 UTC 2019 : deinit took 0 minutes and 1 seconds
1 shards, 41 consensus, 192 total TPS, 26 nodes
13.56.82.157, 41, 191.703

Fix consensus error with DRG

---

api/service/staking/service.go
internal/utils/contract/constants.go
internal/utils/contract/constants_test.go
node/contract.go

generate fake staking info for testing

generate fake staking info for testing

---

cmd/harmony.go
internal/utils/utils.go
test/deploy_newnode.sh

setup for having staking service working
new node will run with ip 127.0.0.1 and port 9100

setup for having staking service working

---

node/node_syncing.go

we need to pass reference as sync.Map contains mutex

we need to pass reference as sync.Map contains mutex

---

api/service/staking/service.go
core/resharding.go
core/resharding_test.go
core/types/shard_state.go
core/types/shard_state_test.go
p2p/host/hostv2/mock/hostv2_mock.go
p2p/host/mock/host_mock.go
p2p/mock_stream.go

Modify shard state calculation

Modify shard state calculation

---

api/service/manager.go
api/service/manager_test.go
api/service/resharding/service.go
api/service/staking/service.go
core/blockchain.go
node/node.go
node/node_newblock.go
node/service_setup.go

Add logic for resharding. I have to stop in the middle because i need to modify resharding calculation logic which currently does not calculate node role (leader or validator) but instead it only calculates new committees.

Add logic for resharding

---

core/resharding.go

quick fix for broken code at calculateKickoutRate

quick fix for broken code at calculateKickoutRate

---

contracts/DepositContract.sol
contracts/README.md
contracts/StakeLockContract.sol

We need a staking contract that support more functionalities such as locking based on epochs.  Will have another PR to add batch query func.

Add StakeLockContract with basic locking/unlocking based on epoch

---

api/service/config.go
api/service/manager_test.go
cmd/client/txgen/main.go
cmd/harmony.go
internal/configs/node/config.go
internal/configs/node/config_test.go
node/node.go
node/node_handler.go
node/service_setup.go
p2p/group.go

Add a nodeconfig module to group node specific configuration, so that it be included in both node and services modules.
* Before
* After

Add node config module

---

specs/test/testplan.md

add testplan draft

---

specs/test/testplan.md

Adding Tests to the TestPlan

---

specs/test/testplan.md

add state sync test and adjust priority

---

cmd/archival/README.md

Doc design for archival node.

---

api/service/networkinfo/service.go

#540 filter out private/multicast addresses

---

api/proto/node/node_test.go
api/service/syncing/syncing_test.go
consensus/consensus_state_test.go
crypto/pki/utils_test.go
drand/drand_leader_msg_test.go
drand/drand_test.go
drand/drand_validator_msg_test.go
internal/utils/bytes_test.go
p2p/backoff_test.go
p2p/group_test.go

https://github.com/harmony-one/harmony/issues/316
* Before
total:									(statements)				49.1%
* After
total:									(statements)				54.3%

Increase unit test coverage

---

api/proto/node/node.go
api/proto/node/node_test.go
go.mod

update go.mod to fix build issue after bls update.
* Before
* After

[build] fix build error after update of bls

---

internal/configs/node/config.go
node/service_setup.go

Simple PR to create a new nodeRole for Backup Node.

Backup Node

---

scripts/node.sh

Users may use different Linux distribution to run the node program.  And they may not use AWS.
We need a generic way to find out the public IP address of the host.
* Before
* After

get public IP on all Linux platform working

---

node/service_setup.go

enable explorer for beacon leader

enable explorer for beacon leader

---

api/service/manager.go
cmd/client/wallet/lib/lib.go
cmd/client/wallet/main.go

disable logging in wallet to make it simpler for user to use.
no need to display excessive log information to users.
local test passed.

[log] disable logging for wallet

---

node/node_genesis.go
test/chain/main.go

Refactor experiment smart contract code
This refactor is not perfect but at least it makes the code readable
--------- Funding addresses for Faucet Contract Call ---------
Balances before call of faucet contract
contract balance:
7000000000000000000
user address balance
100037
staking address balance
720000
--------- Funding addresses for Faucet Contract Call DONE ---------
--------- Now Setting up Faucet Contract Call ---------
Balances AFTER CALL of faucet contract
contract balance:
6500000000000000000
user address balance
500000000000100037
staking address balance
720000
--------- Faucet Contract Call DONE ---------
--------- ************************** ---------
--------- Now Setting up Staking Contract ---------
Before Staking Balances
user address balance
500000000000100037
The …

Refactor experiment smart contract code

---

scripts/node.sh

Update the node.sh script for external node runner.
* check running as root
* provide some more help message

Node script update

---

README.md

add go_card report

---

node/node.go

[node] fix a crash found in testnet #603

---

api/service/explorer/structs.go

add Data field for Transaction in explorer

add Data field for Transaction in explorer

---

api/proto/discovery/pingpong.go
node/node_handler.go

[panic] fix ping message panic #617

---

cmd/client/wallet/main.go

[wallet] adjust wallet with new testnet launch

---

node/staking.go

Previously, CurrentStakes were getting cleared if stakeInfoReturnValue == nil, which means that the stake information query has failed.
We still process non-nil but empty stake query result.

Do not update staking list if StakeInfo query failed

---

api/service/explorer/structs.go

save data field

---

consensus/consensus.go
node/node.go
node/node_handler.go

[pong] actively sending pong message

---

api/service/discovery/service.go
api/service/syncing/syncing.go
cmd/client/txgen/main.go
cmd/client/wallet/main.go
cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_validator.go
internal/configs/node/config.go
node/contract.go
node/contract_test.go
node/node.go
node/node_genesis.go
node/node_handler.go
node/node_handler_test.go
node/node_syncing.go
node/node_test.go
node/service_setup.go
node/staking_test.go
test/configs/oneshard2.txt
test/configs/oneshard3.txt
test/deploy.sh

contains three sub commits:
1. unify state sync and beacon sync (i.e. two cases depend on whether needs join consensus)
2. move archival node as validator role for security concern; archival node fully works
3. the network can resume after restart again (but one node restart has issue caused by leader pubkey not found, since the discovery service only run once)
two issues left:
1. last mile issue need to be solved for node do state sync and then join consensus
2. modify p2p discovery logic

unify state sync, beacon sync and archival sync

---

api/proto/discovery/pingpong.go
consensus/consensus.go
consensus/consensus_leader.go
consensus/consensus_validator.go
drand/drand.go
internal/utils/utils.go
internal/utils/utils_test.go
node/node_handler.go
p2p/p2p.go

* add test cases for GetAddressHex

[utils] move GetAddressHex to utils module

---

node/node_handler.go

This shall solve the issue of new node didn't get the pong message issue.

[pong] send regular pong message to new peers

---

.github/ISSUE_TEMPLATE/design_issue.md
.github/ISSUE_TEMPLATE/feature_request.md

Add a Feature request template

Update issue templates

---

node/demo_contract.go

call to get balances from native calls instead of calling smart contract

call to get balances from native calls instead of calling smart contract

---

consensus/consensus.go
node/node_handler.go

This will help the external node runner to check on their log.

[log] print a message in validator if consensus reached

---

api/client/service/server.go

The excessive log on RPC server shall be disabled.

[log] disable log from rpc server

---

node/node_syncing.go

[issue658](https://github.com/harmony-one/harmony/issues/658)

fix nil pointer error for calculate reponse in state sync

---

cmd/client/txgen/main.go
node/node_newblock.go

[consensus] wait for more tx in one consensus

---

api/service/explorer/service.go
api/service/explorer/structs.go
cmd/client/wallet/main.go
consensus/consensus.go
node/node_handler.go
node/service_setup.go

add api /shard for explorer.

---

core/blockchain.go
core/rawdb/accessors_chain.go
core/resharding.go

This is a partial WIP for #675.  Among other things, this PR eliminates the use of nil pointers returned upon failure.

Log and handle shard state retrieval errors

---

README.md

Enhance README.md to include information about sourcing BLS environment.
N/A
N/A
N/A

Include source command for Initializing BLS

---

api/service/syncing/errors.go
api/service/syncing/syncing.go
node/node_syncing.go

This is a simple cherry-pick of the #676 changes from master to banjo.

Fix #676 on banjo

---

node/contract.go

https://github.com/harmony-one/harmony/issues/694

[crash] fix index out of range crash

---

cmd/client/wallet/main.go

wallet getbalance didn't return the balance if one shard is not able to return balance.

Wallet fix on multi shards

---

api/service/syncing/syncing.go

https://github.com/harmony-one/harmony/issues/703

[crash] fix issue #703

---

cmd/harmony/main.go
consensus/consensus_leader.go
internal/configs/node/config.go
node/node.go
node/node_handler.go
node/service_setup.go

Remove drand

---

scripts/go_executable_build.sh

This PR is to enable debug option for go build by disabling optimizations so that it is friendlier to the debugger.

[debug] add debug option in build

---

scripts/node.sh

Also fix a message to use "pkill" instead of "kill" to terminate harmony

update node.sh to avoid adding config multiple times

---

core/blockchain.go
node/node_newblock.go

testnet leader runs out of space after 8k+ consensus because of too much
logs

[log] reduce logs on leader

---

core/resharding.go

[crash] fix integer divide by zero crash #675

---

node/node_handler.go

Fix Issue: https://github.com/harmony-one/harmony/issues/725

[crash] fix nil pointer deference

---

scripts/docker/Dockerfile
scripts/docker/docker-node.sh
scripts/docker/run
scripts/go_executable_build.sh

Add dockerfile to build docker image
Docker image harmonyone/node:master tested.

Add dockerfile to build docker image

---

cmd/harmony/main.go

[misc] remove unused flag in harmony

---

README.md

Minor change in README

---

scripts/node.sh

[node] update script for cello release

---

scripts/wallet.sh

[wallet] add a wallet wrapper script

---

scripts/docker/docker-node.sh

Update some message and add option to kill running container.

[script] Improve docker-node.sh with option to kill node

---

.gitignore
api/service/syncing/downloader/client.go
api/service/syncing/syncing.go
cmd/harmony/main.go
core/resharding.go
node/node.go
node/node_handler.go
node/node_syncing.go

fixed beaconchain syncing, it will not affect the current code base, so it's safe to merge the code; to make it fully work, need the beacon peer discovery fix  [#732](https://github.com/harmony-one/harmony/issues/732)

beacon chain syncing

---

scripts/docker/docker-node.sh

cello branch use different docker image.
update the script to use docker image for cello.

Update docker-node.sh for cello branch

---

cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_test.go
node/node_handler.go

3 changes in this PR.
* disable resharding logic and regular pong message (new for lottery app only)
* resume consensus is for explorer display (cherry-picked from master)

Banjo stablility improved

---

api/service/networkinfo/service.go

First part of fix of https://github.com/harmony-one/harmony/issues/733

[p2p] move ctx out of struct

---

core/resharding.go

Fix https://github.com/harmony-one/harmony/issues/744

[crash] fix index out of range #744

---

p2p/host/hostv2/hostv2.go
p2p/host/hostv2/hostv2_test.go

Fix issue https://github.com/harmony-one/harmony/issues/749

Fix null pointer error #749

---

node/demo_contract.go

[crash] fix nil pointer deference #759

---

node/node_handler.go
node/node_syncing.go

[log] reduce number of logs

---

node/contract.go
node/node.go
node/node_handler.go

Cherry pick from https://github.com/harmony-one/harmony/commit/78323c11e340964be97620011d3f9287b491b71c
to be able to fix freetoken. Currently only one free token transction per perlobkc.

fix logic to add more free Token

---

api/service/restclientsupport/service.go
node/service_setup.go

add FundMe skeleton

---

node/demo_contract.go
node/node_error.go

avoid account without enough balance participating the lottery

Banjo hack

---

node/demo_contract.go

Banjo quickfix

---

scripts/docker/docker-node.bat

Add a windows bat script to start docker node.

[script] Add windows bat to start docker node on windows

---

scripts/docker/docker-node.sh

[docker] update docker-node.sh

---

cmd/client/txgen/main.go
cmd/harmony/main.go
consensus/consensus.go
contracts/structs/structs.go
core/types/shard_state.go
node/node.go
node/staking.go

This is Banjo's foundational reward massaged to deal with only static set of nodes (foundational nodes) without new nodes joining.
Local test passed with a few thousand blocks.  Travis-CI succeeded.  Jenkins testing passed (see checks below).

Foundation node block reward for cello

---

node/node_handler.go

restore pong message, change to 10 minutes

---

node/contract.go

Temporary workaround for explorer address search issue

---

api/service/networkinfo/service.go
core/resharding.go
node/contract.go
node/node_handler.go
node/node_syncing.go
p2p/host/hostv2/hostv2.go

Cherry pick fixes to cello branch.

Cherry pick fixes

---

api/service/restclientsupport/service.go

Add params for payout endpoint

Cello payout

---

contracts/Puzzle.sol

Puzzle Smart Contract
Will refactor restclient according to new contract, if contract looks ok (i.e refactor https://github.com/harmony-one/harmony/pull/793/files)

Puzzle contract

---

contracts/Puzzle.sol

Harmony Puzzle

---

api/service/restclientsupport/service.go
node/node.go
node/service_setup.go

Deploy app contracts and rest api on all shards

---

node/node.go
node/node_handler.go
node/puzzle_contract.go

Fix same user nonce issue

---

api/service/explorer/storage.go

Fix txs issue: currently we only store the latest txn and it was because we did not decode the data correctly.

fix bugs of saving tnxs

---

api/service/explorer/storage.go

fix logic of dumping txn

---

api/service/explorer/storage.go

Clean up code after relaunching cello

Cello fixcleanup

---

scripts/docker/docker-node.sh
scripts/node.sh

[node] reserve more spot for foundational nodes to join testnet

---

node/node.go
node/node_handler.go
node/puzzle_contract.go

fix concurrent map write error #837

---

cmd/client/txgen/main.go

The TXGen sends stop messages and kills all nodes in the network.

Fixing TXGen

---

api/client/client.go
api/client/client_test.go
cmd/client/txgen/main.go
cmd/client/wallet/main.go

https://github.com/harmony-one/harmony/issues/846

Change Client Interface

---

cmd/bootnode/main.go
cmd/client/txgen/main.go
cmd/harmony/main.go
internal/hmyapi/backend.go
internal/hmyapi/debug.go
internal/utils/singleton.go

[logging] add verbosity flag to bootnode, txgen, harmony cmd

---

cmd/client/wallet/main.go

[wallet] ask for passphrase twice

---

cmd/client/txgen/main.go
test/deploy.sh

* Only set duration to 200 if -S is enabled and -D is not set

update deploy.sh for duration

---

.hmy/wallet.ini
cmd/client/wallet/generated_wallet.ini.go

[wallet] use dns name for rpc servers

---

cmd/client/wallet/main.go
cmd/harmony/main.go
scripts/go_executable_build.sh

A few fix of the wallet and node program. There was a regression introduced in my last commit of asking for passphrase twice. Fixed some minor parameter in node program and enable asking of passphrase by default.

Wallet fix empty passphrase

---

cmd/harmony/main.go
test/deploy.sh

[node] fix comment and add -nopass for local test

---

scripts/node.sh

[node] fix node.sh to input passphrase

---

core/api_backend.go
core/tx_pool.go
node/node.go
node/rpc.go
node/staking_test.go

remove bad practice code and add tx.

remove bad practice code and add tx

---

internal/hmyapi/README.md
internal/hmyapi/blockchain.go

https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_blocknumber
Validated using postman

hmy_blockNumber

---

cmd/harmony/main.go
consensus/consensus.go
consensus/view_change.go

`-disable_view_change` flag controls the behavior.  Default is enable view change.

Disable view change optionally

---

internal/shardchain/shardchains.go
node/node.go

I disabled it in the BRv2 and forgot to re-add it back.  Here's to fix that.
Pointy-hat-to: Eugene Kim &lt;ek@harmony.one&gt;

Re-enable archival mode

---

hmy/api_backend.go
hmy/backend.go
internal/hmyapi/backend.go
internal/hmyapi/blockchain.go

Add get_balance api for RPC

---

node/node.go
node/node_handler.go

[pingpong] check the right number of peers before start consensus

---

cmd/harmony/main.go
node/service_setup.go

clean up main.go code

---

node/contract.go
node/node.go

First steps of removing smart contract lottery and puzzle!!!

remove smart contract lottery and puzzle

---

consensus/config.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/pbft_log.go
consensus/view_change.go
node/node_newblock.go
node/node_syncing.go

Added the following:
- in view change mode, node accepts normal message and change state at committed message; 
- accept newview message regardless of leaderkey matching;
- In consensus SYNCING mode add normal consensus message in the log;
- leader also has timeout mechanism in consensus process

consensus logic fixes

---

accounts/abi/bind/backend.go
accounts/abi/bind/backends/simulated.go
accounts/abi/bind/base.go
accounts/abi/bind/base_test.go
consensus/consensus_leader_test.go
consensus/consensus_service.go
core/blockchain.go
crypto/hash/hash.go
crypto/pki/utils.go
crypto/pki/utils_test.go
crypto/sha256.go
drand/drand.go
node/node.go
node/node_handler.go
test/chain/main.go

for all onchain hashing, we should use keccak.

Remove bls address util and sha256 hash

---

api/service/explorer/service.go
cmd/harmony/main.go
go.mod
internal/configs/node/config.go
internal/memprofiling/lib.go
internal/memprofiling/singleton.go
internal/utils/utils.go
test/debug.sh

add tool to check memory of different objects.
Will add more main objects after this.

add tool to check memory of different objects

---

cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_service.go
consensus/view_change.go
internal/memprofiling/lib.go
internal/memprofiling/singleton.go
node/node.go
test/debug.sh

Scan more objects for OOM issues

Scan more objects

---

api/service/clientsupport/service.go
api/service/manager.go
node/node.go
node/service_setup.go

add back client support

---

hmy/api_backend.go
hmy/backend.go
internal/hmyapi/backend.go
internal/hmyapi/net.go
node/rpc.go

* added support for net module
This `net_version` API is needed for MM.

rpc net module

---

node/node.go

add limit for transaction pool. print out error for debugging

add limit for transaction pool. print out error for debugging

---

internal/memprofiling/lib.go

fix memsize concurrent issue

---

cmd/harmony/main.go

disable memsize logging by default

disable memsize logging by default

---

consensus/consensus.go
internal/memprofiling/lib.go
node/node.go

fix memsize profiling bug

---

consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/view_change.go
internal/utils/bytes.go

* switchPhase add override criterion
* remove sleep and wait for final committed signature in leader for stability
* add 2f+1 signatures checking

3-in-1 fixed in consensus protocol

---

api/service/discovery/service.go
node/node_handler.go

quick fix for logging

---

consensus/consensus_v2.go
consensus/consensus_validator_msg.go
consensus/view_change.go

modify commit phase message;
improve consensus log information;
modify newview logic;

modify commit phase message; improve consensus log info; modify newview logic

---

cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_service.go
consensus/view_change.go
internal/memprofiling/lib.go
node/node.go

proposing one of options to solve OOM issue.
- Run gc every 10 minutes

run gc every 10 minutes

---

scripts/node.sh

[node] adjust node.sh with the new -accounts option

---

consensus/view_change.go

[crash] fix invalid memory access crash

---

consensus/view_change.go
internal/utils/bytes.go

[crash] add more crash check

---

node/node_handler.go

[pingpong] remove hardcoded delay in sending pong message

---

cmd/client/wallet/main.go
internal/blsgen/lib.go
internal/blsgen/lib_test.go

blsgen lib and wallet bls generator

blsgen lib and wallet bls generator

---

scripts/wallet.sh

add blsgen instruction

---

consensus/consensus.go
consensus/consensus_v2.go
consensus/pbft_log.go
consensus/view_change.go

m2 NIL message might be nil, which is expected,  we should not assume it always nil.

fix view change m2mask checking issue

---

internal/genesis/foundational.go

Says he accidentally deleted his old instance.

Update FN 48

---

go.mod

using new bls version

---

test/deploy.sh

add arguments in deploy.sh for logging level

add arguments in deploy.sh for logging level

---

consensus/consensus_v2.go
node/node_newblock.go

[log] Use Info log level for important consensus messages

---

internal/genesis/foundational.go

one more fn node key

---

scripts/node.sh

* Restart harmony node if it exits for any reason, unless `-1` (one-time) flag is given.
* Wait 10s after restarting
* Re-download node software every 5m and see if they changed.
* If download/check fails, retry in 10s.
* If changed, kill the currently running node (making it restart in 10s).

Make node.sh auto-update/restart node

---

consensus/consensus.go
consensus/consensus_v2.go

leader either wait for grace period ending or collect enough signature
for block reward

add grace period for collect commit signatures

---

core/resharding.go

adjust hmy nodes

---

scripts/monitor.sh

Monitor Script to follow nodes.

monitor script

---

scripts/node.sh

SSIA.  Also fix the help string.

Make node.sh read passphrase once

---

cmd/harmony/main.go
node/node.go
node/service_setup.go

Disable drand.
Currently drand isn't functioning but we want to compeletely turn it off for full protection.

disabling drand.

---

cmd/bootnode/main.go
cmd/harmony/main.go
internal/utils/connlogger.go

SSIA.  This is for P2P troubleshooting.

Add -log_conn option to bootnode

---

consensus/config.go
consensus/consensus_v2.go

* start state sync buffer change to 2
* not continue if not catchup in view changing mode

in sync trigger buffer changed from 10 to 2

---

scripts/mystatus.sh

Optimized the script, ready for new features to be added
Signed-off-by: Lukas Kozak <luks.kozak@gmail.com>

Change mystatus scripts

---

core/resharding.go

use bls private key to get public key instead

use bls private key to get public key instead

---

node/node_handler.go

This PR logs detailed node information from pong message handler.  Requested and used by stse for tracking node liveness.

Log node keys

---

api/service/staking/service.go
cmd/harmony/main.go
internal/genesis/genesis.go
test/deploy.sh

find addresses by bls keys

---

cmd/harmony/main.go

[staking] remove unused gsif call in node

---

scripts/wallet.sh

Improved readability, compatible with more shells and won't fail in edge cases.
Signed-off-by: Lukas Kozak <luks.kozak@gmail.com>

Change wallet script

---

cmd/harmony/main.go

remove 2nd call for getting consensus key

remove 2nd call for getting consensus key

---

internal/blsgen/lib.go

remove panic in lib

---

cmd/client/wallet/main.go
internal/blsgen/lib.go

convert non-human readable to human-readable key

convert non-human readable to human-readable key

---

cmd/harmony/main.go

This fixes the segfault of blskey not set properly on consensus.

Revert 2nd call removal

---

internal/blsgen/lib.go

If both forms fail, return the error from the hexadecimal attempt, because hexadecimal is the canonical form and binary is only a fallback.
Below is a transcript of generating an ephemeral key (hex), converting that into old binary format (the `python3` one-liner), then trying out both versions using the `harmony` binary.  Both print out `Can not found your bls key`; the message means that the BLS key is not found in the genesis table, which proves that the key was at least successfully loaded from disk (in both hex and binary forms).
```
QuelThalas 14:54:52 harmony (binary_bls_key) $ 785 bin/wallet blsgen --pass=pass:omgwtf
Bls private key: c9cda1998d8f04434861f67c3f41d0c63b9c840435b490481a56626a9ba4d044
Bls public key: 526847f5b3e9bc77f996c216851f53829918ac837414ce6640b620c8794039ae20843 …
```

Try to decode BLS key as hex and binary forms

---

cmd/client/wallet/main.go

add import tool for bls
-----
Passphrase:      
Passphrase again:           
Your encrypted bls file with the passphrased is written at 8fb9de02c7f9b8baad2905994c6d9f559b99a72fdd6aa20eab692bb1fcc25c712ba7410d4dae8dad182d714e80d7d787.key.                                                
We loaded the file and the loaded private key DOES match your private key!

add import tool for bls

---

api/service/syncing/syncing.go
cmd/harmony/main.go
consensus/consensus_v2.go
internal/configs/net/config.go
node/node.go
node/node_syncing.go

* add dns server for node syncing
* add dns flag in main to turn on dns server syncing
* don't print viewID checking when in syncing mode

add dns server for node syncing

---

scripts/bls_bintohex.py

Tool to convert your BLS key from binary to the accepted hex format.
Signed-off-by: Lukas Kozak <luks.kozak@gmail.com>

Add BLS Bin2Hex conversion script

---

consensus/consensus.go
node/node_handler_test.go
node/node_test.go

[blskey] add error message when blskey is nil

---

scripts/wallet.sh

fix path of binaries for wallet.sh

fix path of binaries for wallet.sh

---

go.mod

[module] upgrade all modules in go.mod

---

.gitignore

[misc] ignore local test db and blspass.txt

---

scripts/mystatus.sh

Cater for latest log format and using jq

---

cmd/client/txgen/main.go
cmd/harmony/main.go

remove runtime.GOMAXPROCS
It was set last year as we thought this could bring up the perf of our benchmark.

remove runtime.GOMAXPROCS

---

api/service/networkinfo/service.go

fix cpu issues at networkinfo service

fix cpu issues at networkinfo service

---

cmd/harmony/main.go
consensus/consensus_v2.go
node/node.go
node/node_newblock.go

add flag for block period

---

node/node_newblock.go

remove confusing logic of sleeping when the deadline does not come yet.

remove confusing logic

---

consensus/consensus.go

That is:
- Make amounts distributed to signers sum up to 30 Ones; and
- Make amounts earned by any two signers differ by at most 1 Atto (rounding error).
Local test pending.

Pay a fixed total 30 Ones per block, split evenly

---

cmd/harmony/main.go

[log] filter out debug log by default

---

cmd/client/wallet/main.go
scripts/wallet.sh

get bls public key from bls raw private key.

get bls public key from bls raw private key.

---

cmd/client/wallet/main.go
scripts/wallet.sh

get option to get public key based on encrypted bls file and passphrase

get option to get public key based on encrypted bls file and passphrase

---

cmd/harmony/main.go
internal/configs/node/config.go
node/node_handler_test.go

disable rpc for mainnet

---

scripts/node.sh

[node.sh] run node.sh as non-root user is possible

---

api/service/networkinfo/service.go
cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_v2.go
consensus/pbft_log.go
node/node_genesis.go
node/node_newblock.go

Change block rewards to 24 per block.
Add genesis string to all shards: "Harmony for One and All. Open Consensus for 10B."
Fix consensus retry logic.
Other sys/network fine tunes.

Fine tune maxprocs and minpeer interval

---

internal/genesis/foundational.go

one more operator

---

test/deploy.sh

[deploy] keep all the key to .hmy directory

---

node/node_handler.go

[misc] disable DRand public key update

---

cmd/harmony/main.go
node/node_newblock.go

Test to kill and leader and restart the leader again. it is able to join consensus as a validator

add sleep time to avoid non-stop new block proposing in for loop

---

api/service/explorer/service.go
node/node.go
node/node_explorer.go
node/node_syncing.go

1/ node syncing for explorer node.
2/ calculate block reward for explorer node.
3/ add setup for explorer node.

Fix explorer issue of not showing balance.

---

cmd/harmony/main.go

refactor the main file

---

scripts/node.sh

[bootnode] add two more bootnodes for r3 release

---

accounts/abi/bind/util.go
accounts/keystore/account_cache.go
accounts/keystore/file_cache.go
api/client/client.go
api/proto/node/node.go
api/service/explorer/storage.go
api/service/explorer/structs.go
api/service/staking/service.go
core/blockchain.go
core/chain_indexer.go
core/genesis.go
core/headerchain.go
core/rawdb/accessors_chain.go
core/rawdb/accessors_indexes.go
core/rawdb/accessors_metadata.go
core/state_transition.go
core/tx_journal.go
core/tx_list.go
core/tx_pool.go
internal/hmyapi/private_account.go
internal/hmyapi/util.go
internal/utils/utils.go
node/contract.go
node/node_newblock.go
node/rpc.go
node/worker/worker.go
p2p/host/hostv2/util.go

#1174 
Note:
* Purposely chunked changes into different commits per package.
• There are still some loggers that may need to be replaced. Skipped in this PR given lack of context and want to avoid breaking things unintentionally.
N/A, ran `./test/test_before_submit.sh`
N/A

Unify loggers across application

---

node/node_explorer.go

add blocks for explorer correctly and clean them up to avoid OOM

add blocks for explorer correctly and clean them up to avoid OOM

---

cmd/harmony/main.go

#1173 caused IP/Port to be missing from log context.

Fix missing IP/port from logs

---

api/service/explorer/structs.go
cmd/client/txgen/main.go
node/node.go
node/node_explorer.go
node/node_handler.go
node/node_handler_test.go
node/node_syncing.go
node/staking_test.go

populate state sync data for explorer

populate state sync data for explorer

---

cmd/client/txgen/main.go
cmd/client/wallet/main.go
cmd/harmony/main.go

[version] update version of all binaries

---

scripts/go_executable_build.sh

[build] fix the folder for pubwallet

---

cmd/bootnode/main.go
cmd/harmony/main.go
go.mod
internal/utils/singleton.go

#1171 
No additional tests, ran `./test/test_before_submit`, all tests succeeded.
- Replace `utils.GetLogInstance` and `utils.GetLogger` with `utils.Logger`

Add ZeroLogger to utils

---

consensus/consensus.go
consensus/consensus_leader_msg.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/consensus_validator_msg.go
consensus/consensus_viewchange_msg.go
consensus/pbft_log.go
consensus/view_change.go

#1171 
N/A, ran `./test/test_before_submit`

Replace all logs in censensus module to use zerolog

---

api/client/client.go
api/client/service/server.go
api/proto/discovery/pingpong.go
api/proto/message/server.go
api/proto/node/node.go
api/service/blockproposal/service.go
api/service/consensus/service.go
api/service/discovery/service.go
api/service/explorer/service.go
api/service/explorer/storage.go
api/service/explorer/structs.go
api/service/manager.go
api/service/networkinfo/service.go
api/service/randomness/service.go
api/service/resharding/service.go
api/service/staking/service.go
api/service/syncing/downloader/client.go
api/service/syncing/downloader/server.go
api/service/syncing/syncing.go

#1171 
N/A, ran `./test/test_before_submit.sh`
- Merge #1191 and rebase `master`

Replace all logs in api module to use zerolog

---

test/deploy.sh

read zerolog to calculate consensus as we are moving log to zerolog

read zerolog instead to calculation CONSENSUS

---

drand/drand_leader.go
drand/drand_leader_msg.go
drand/drand_validator.go
drand/drand_validator_msg.go

#1171 
N/A, ran `./test/test_before_submit.sh`

Replace all logs in drand module to use zerolog

---

test/test_sdk.sh

Add script to enable testnet mode in local. At first, this is specific for SDK work.

add test sdk script

---

node/node_genesis.go
test/debug.sh

add minting demo addresses to local test

add minting demo addresses to local test

---

.hmy/wallet.ini
README.md
cmd/client/wallet/generated_wallet.ini.go

Updated README.md for localnet test

[wallet] support new localnet

---

internal/hmyapi/blockchain.go

minor fix to let `hmy_getBlockByNumber` accept the 2nd parameter.

return full tx

---

internal/hmyapi/types.go

fix timestamp marshal

---

cmd/hmyclient/main.go
core/types/block.go
hmyclient/hmyclient.go
hmyclient/signer.go
hmyclient/type.go
internal/hmyapi/types.go

Add hmyclient as the golang RPC client.
Currently support:
* net_version
* hmy_blockNumber

add hmyclient

---

core/blockchain.go
core/vm/evm.go
hmy/api_backend.go
hmy/backend.go
internal/hmyapi/backend.go
internal/hmyapi/blockchain.go
internal/hmyapi/types.go

Add `hmy_call` support
---
Also verified it supports input parameter.

add hmy_call

---

core/types/transaction.go
node/node_newblock.go
node/worker/worker.go

make the tx working again

---

core/types/transaction.go
core/types/transaction_signing.go

add ToShardID and add the field in signing tx.

add ToShardID

---

cmd/client/wallet/main.go

https://github.com/harmony-one/harmony/issues/1198
[balancesOldTime.txt](https://github.com/harmony-one/harmony/files/3404336/balancesOldTime.txt)
[balancesNewTime.txt](https://github.com/harmony-one/harmony/files/3404337/balancesNewTime.txt)

Concurrent rpc balances queries

---

test/debug.sh

[local] use local-resharding test config

---

consensus/config.go
consensus/consensus_v2.go
node/node.go
node/node_newblock.go
test/deploy.sh

fix network restart issue for mainnet shard0 down

---

consensus/config.go
consensus/consensus_service.go
consensus/consensus_v2.go
node/node.go
node/node_newblock.go

[consensus] recovery block when shard is stuck

---

consensus/config.go
consensus/consensus_service.go

[recovery] add block recovery for shard1

---

node/rpc.go

fix bugs causing websocket bug

fix bugs causing websocket bug

---

core/resharding.go
core/resharding_test.go
internal/hmyapi/blockchain.go
internal/hmyapi/sendtxargs.go

fix websocket crash and refactor for a better code to avoid warnings.

Fix websocket crash

---

node/node.go

[crash] fix a segfault using wallet for transfer

---

core/blockchain.go
core/core_test.go
internal/configs/sharding/shardingconfig_test.go

Implement is epoch block

---

internal/configs/sharding/mainnet.go

[epoch] adjust the first epoch block number on mainnet

---

node/node_handler.go
node/node_newblock.go

[log] convert to zerolog in node/ module

---

internal/configs/sharding/mainnet.go
internal/genesis/foundational.go

[epoch] add 4 more FN keys for epoch1 on mainnet

---

internal/genesis/foundational.go

[epoch] fix the wrong account in epoch1

---

cmd/harmony/main.go

[node] remove duplicated gc routine

---

internal/genesis/foundational.go

[foundation] fixed a typo in the account address

---

api/service/syncing/syncing.go
internal/configs/sharding/fixedschedule.go
internal/configs/sharding/localnet.go
internal/configs/sharding/mainnet.go
internal/configs/sharding/shardingconfig.go
internal/configs/sharding/testnet.go

Created different consensysratio for localnet/mainnet

---

node/contract.go
node/node.go
node/node_explorer.go
node/node_genesis.go
node/node_syncing.go
node/rpc.go
node/service_setup.go
node/staking.go

Zerolog replacement

---

api/service/config.go
api/service/metrics/service.go
api/service/metrics/storage.go
cmd/harmony/main.go
core/tx_pool.go
internal/configs/node/config.go
node/node.go
node/node_metrics.go
node/service_setup.go
scripts/node.sh

Added Tx Pool size metric (gauge type), added -metrics flag to node.sh (false by default - doesn't collect metrics), fixed storage (dumps metrics if failed to push to prometheus).

Metrics service update

---

api/service/metrics/service.go
node/node_metrics.go
node/service_setup.go

NodeBalanceCounter -> NodeBalanceGauge due to the issue found by Dennis Won (turns out prometheus counter cannot be decreased), also removed some unnecessary stuff in metrics service.
Test:
Tested by running wallet transfer on localnet, doesn't throw error now.

Metrics nodeBalanceCounter -> nodeBalanceGauge

---

cmd/harmony/main.go

Send launch errors to stderr, not stdout

Partial fix for #1320

---

api/service/syncing/downloader/client.go

"Register failed" seems to trigger too easily

Increase download register timeout

---

consensus/view_change.go
node/node_explorer.go

Fix typo :)

---

consensus/consensus_v2.go

"BlockNum" vs "blockNum" vs "MsgBlockNum" vs "hdrBlockNum"
"BlockHash" vs "blockHash"
When trying to do monitoring, the mix of json fields is very difficult to unravel. This attempts to make naming a bit more consistent.

Send ints as ints, unify json logging tagging, grammar fixes

---

.hmy/wallet.ini
api/service/syncing/downloader/client.go
cmd/client/wallet/generated_wallet.ini.go
consensus/view_change.go
internal/configs/sharding/mainnet.go
internal/genesis/foundational.go
internal/genesis/genesis_test.go
node/node_explorer.go

- Add the Travis check for invalid keys
- Add @nyetwurk's qol monitoring fixes
- Add Pangaea wallet.ini changes
- Add 4 more keys

Cherry pick Travis key check and wallet for Pangaea

---

api/service/metrics/service.go

https://github.com/harmony-one/harmony/issues/1349
BlockHeightCounter -> BlockHeightGauge.

Fix block height issue

---

core/tx_pool.md

add doc design of tx pool

---

cmd/client/wallet/generated_wallet.ini.go
cmd/client/wallet/main.go
cmd/client/wallet_stress_test/README.md
cmd/client/wallet_stress_test/generated_wallet.ini.go
cmd/client/wallet_stress_test/main.go
cmd/harmony/main.go
core/types/transaction.go
internal/configs/sharding/fixedschedule.go
internal/configs/sharding/localnet.go
internal/configs/sharding/mainnet.go
internal/configs/sharding/shardingconfig.go
internal/configs/sharding/testnet.go
node/node.go
node/node_handler.go
node/node_handler_test.go
node/node_newblock.go
node/staking_test.go
node/worker/worker.go
scripts/go_executable_build.sh

https://github.com/harmony-one/harmony/issues/1267
* Before
* After
dennis.won@mp-dennisw-ml2:~/go/src/github.com/harmony-one/harmony/internal/configs/sharding (txs_throttle) $ go test --cover
PASS
coverage: 17.1% of statements
ok  	github.com/harmony-one/harmony/internal/configs/sharding	0.080s
dennis.won@mp-dennisw-ml2:~/go/src/github.com/harmony-one/harmony/node (txs_throttle) $ go test --cover
wait 5 seconds to terminate the process ...
ok  	github.com/harmony-one/harmony/node	10.933s
Localnet testing:
{"level":"debug","port":"9000","ip":"127.0.0.1","MaxTxAmountLimit":1000,"Tx amount":12727183826875318272,"caller":"/Users/dennis.won/go/src/github.com/harmony-one/harmony/node/worker/worker.go:79","time":"2019-08-07T13:28:33-07:00","message":"Throttling tx with max amount limit"} …

 [r3 patch] throttle transactions with configuration per-network level

---

cmd/client/wallet/main.go

[wallet] fix transfer --pass parameter

---

test/debug.sh

[test] fix debug.sh to run for 10 minutes

---

cmd/harmony/main.go

This reverts commit 4629f3e9be5efff23d2b6bd915d1564dba08cfff.

Revert "[pangaea] temporary pause the harmony nodes on shard0/1"

---

api/service/explorer/service.go
api/service/explorer/structs.go
cmd/harmony/main.go
node/node.go
node/node_explorer.go

Fixes after API testing through postman, 
Run test on postman, now committee fetch is okay
[
](url)
GetTransaction on explorer doesn't fetch tx which was included in some block {"level":"warn","port":"9099","ip":"127.0.0.1","error":"leveldb: not found","id":"0x44479ab2140f6bbd198355a45d04a70314f8861c5969d9a1b05121fec3e6b07c","caller":"/Users/myspace/go/src/github.com/harmony-one/harmony/api/service/explorer/service.go:259","time":"2019-08-21T04:26:50+03:00","message":"cannot read TX"} 0x44479ab2140f6bbd198355a45d04a70314f8861c5969d9a1b05121fec3e6b07c

explorer fixes

---

internal/common/address.go
internal/common/address_test.go
internal/hmyapi/blockchain.go

support one address for rpc call

support one address for rpc call

---

api/service/networkinfo/service.go
cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_v2.go
internal/chain/engine.go
internal/chain/reward.go
internal/chain/sig.go
internal/configs/node/config.go
internal/shardchain/shardchains.go
node/node.go
node/node_handler.go
node/node_syncing.go

Local test passes, and beacon blocks—note `"blockShard":0`—are added on shard 1:
```json
{"level":"info","port":"9001","ip":"127.0.0.1","blockHash":"0x3cc002875b27514115a636b4ea97671dd4ae92431a3ab839257246ba5fe86be2","blockShard":0,"blockEpoch":"0","blockNumber":"1","segmentIndex":0,"parentHash":"0x844f7b3e6403ce18cc53ff2d5fc3c185b2cc854aef5c764716fbc185b913f122","caller":"/Users/ek/h/harmony/core/blockchain.go:1115","time":"2019-08-21T11:55:54-07:00","message":"added block to chain"}
{"level":"info","port":"9001","ip":"127.0.0.1","blockHash":"0x615eca554a9ec8211735d9a12fc06ff3fc05c112cf9187d4de2e96fe2250faba","blockShard":0,"blockEpoch":"0","blockNumber":"2","segmentIndex":0,"parentHash":"0x3cc002875b27514115a636b4ea97671dd4ae92431a3ab839257246ba5fe86be2","caller":"/Users/ek/h/harmony/cor …
```

Get syncing peers using DNS, part 2: Enable beacon syncing

---

api/client/service/server_test.go
api/service/explorer/storage_test.go
api/service/explorer/structs_test.go
api/service/syncing/syncing.go
core/block_validator.go
core/blockchain.go
core/core_test.go
core/rawdb/accessors_indexes_test.go
core/vm/runtime/runtime.go
drand/drand_test.go
node/node_cross_shard.go
node/node_handler.go
node/worker/worker_test.go

Tested locally and the beacon sync works with sig validation across epochs.

State sync sig validation

---

api/proto/discovery/pingpong.go
api/proto/discovery/pingpong_test.go
api/proto/discovery/readme.md
api/proto/node/node.go
api/service/discovery/errors.go
api/service/discovery/service.go
internal/utils/singleton.go
node/node.go
node/node_handler.go
node/node_test.go
node/service_setup.go
node/staking_test.go
p2p/host/hostv2/hostv2.go
p2p/p2pimpl/p2pimpl.go

[pingpong] remove pong messages from discovery service

---

consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_v2.go
core/blockchain.go
core/rawdb/accessors_chain.go
core/rawdb/schema.go
core/types/block.go
go.mod
internal/configs/sharding/fixedschedule.go
internal/configs/sharding/localnet.go
internal/configs/sharding/mainnet.go
internal/configs/sharding/pangaea.go
internal/configs/sharding/shardingconfig.go
internal/configs/sharding/testnet.go

Revert VRF/VDF for the s3 release branch.

Revert VRF/VDF

---

cmd/harmony/main.go
internal/configs/sharding/fixedschedule.go
internal/configs/sharding/instance.go
internal/configs/sharding/localnet.go
internal/configs/sharding/mainnet.go
internal/configs/sharding/pangaea.go
internal/configs/sharding/shardingconfig.go
internal/configs/sharding/testnet.go

add networkID for scheduling

---

scripts/node.sh

[node.sh] use mainnet folder for mainnet node

---

api/service/explorer/storage.go
internal/hmyapi/blockchain.go
internal/hmyapi/transactionpool.go

fix ONE address issues for other rpcs

fix ONE address issues for other rpcs

---

api/service/networkinfo/service.go
go.mod

[netinfo] limit the number of discovery

---

api/proto/message/server.go
api/service/syncing/syncing.go
consensus/consensus_v2.go
consensus/consensus_viewchange_msg.go
consensus/view_change.go
core/blockchain.go
core/rawdb/accessors_indexes.go
core/rawdb/accessors_metadata.go
drand/drand_leader.go
node/node_handler.go

Make sure we don't log raw []byte arrays. Convert them to Hex Strings.

[#1505] Log byte arrays as Hex Strings

---

scripts/api_test.sh

Added api test

---

cmd/client/wallet/main.go

[wallet] use random port to avoid .dht file conflict

---

node/node.go
node/node_handler.go
node/service_setup.go

[client] remove client peer support

---

internal/configs/sharding/testnet.go

quick typo fix for betanet

---

node/service_setup.go

[cleanup] remove discovery service on explorer node

---

hmy/api_backend.go
internal/configs/sharding/localnet.go

remove redandunt code

---

api/service/syncing/syncing.go
core/block_validator.go
node/node_handler.go

- refactoring block header signature verification

Improve cross shard transaction verification mechanism

---

cmd/client/wallet/main.go
go.mod

Cont of https://github.com/harmony-one/harmony/pull/1523

Wallet color

---

internal/configs/sharding/fixedschedule.go
internal/configs/sharding/localnet.go
internal/configs/sharding/mainnet.go
internal/configs/sharding/pangaea.go
internal/configs/sharding/shardingconfig.go
internal/configs/sharding/testnet.go
node/worker/worker.go

https://github.com/harmony-one/harmony/issues/1509
https://github.com/harmony-one/harmony/issues/1521
dennis.won@Jongs-MacBook-Pro:~/harmony/node (throttle_remove_pangaea) $ go test -cover
\PASS
coverage: 15.3% of statements
ok  	github.com/harmony-one/harmony/node	4.086s
wallet single-shard/cross-shard txn tested with throttling

add enabling txn throttling kill switch and disable on pangaea

---

Makefile
README.md

Simplify building using makefile
Source code did not change

Simplify build process with Makefile

---

cmd/harmony/main.go

[node] change min_peers to 32

---

internal/configs/sharding/mainnet.go
internal/configs/sharding/pangaea.go
internal/configs/sharding/testnet.go

Update the endpoints for ws
* Validate using math wallet on Betanet

Update wss endpoints

---

scripts/wallet.sh

Cosmetic fixes to wallet.sh

---

internal/configs/sharding/localnet.go
internal/genesis/localnodes.go
node/node_explorer.go

And update local shard config so the keys will change in both epoch 1 and 2.

Fix explorer node stuck issue

---

api/service/explorer/service.go
cmd/harmony/main.go
node/node_explorer.go

Add with_signers flag for explorer rest api
Make explorer block handler more robust.

Explorer node fix

---

core/blockchain.go
core/rawdb/accessors_indexes.go
core/rawdb/schema.go
core/types/block.go
core/types/bodyv0.go
core/types/bodyv1.go
internal/hmyapi/transactionpool.go
internal/hmyapi/types.go

- Add FromShardID and ToShardID fields in getTransactionByHash call
- Add write and retrieve for CXReceiptByHash
- Add RPC call getCXReceiptByHash

Add RPC call for CXReceipt

---

cmd/harmony/main.go
scripts/docker/run
scripts/node.sh

This reverts commit 97880b2c3a38a6b5c208c060e80b175427f1cde2.

Revert "[cleanup] remove is_genesis flag"

---

internal/hmyapi/error.go
internal/hmyapi/transactionpool.go

If chainID of incoming tx does not match the current network, return error.

[transactionpool.go] check chainID for incoming tx

---

scripts/node.sh

[node.sh] uses separate options to download harmony db

---

hmy/api_backend.go
internal/hmyapi/backend.go
internal/hmyapi/blockchain.go
internal/hmyapi/types.go

Add GetCommittee method similar to explorer.
* Before
* After
By the way, I guess we want to present balance in 10-digit format, not hex.

hmyapi update

---

api/service/explorer/service.go
api/service/explorer/storage.go
api/service/syncing/syncing.go

Also, revert some of the explorer address querying code to still support txn list query.

Verify sig every 100 blocks during state sync

---

internal/hmyapi/transactionpool.go

fix bug on chain id and specify real chain id

[transcationpool.go] fix bug on chain id and specify real chain id

---

hmy/api_backend.go
hmy/backend.go
internal/hmyapi/backend.go
internal/hmyapi/transactionpool.go
internal/hmyapi/types.go
internal/hmyapi/util.go
node/node_explorer.go

1/ fix bug on chain id and specify real chain id
2/ Cherry vlad's pr https://github.com/harmony-one/harmony/pull/1643

cherry-pick pr 1643 and 1642

---

consensus/consensus_v2.go

When leader is stuck and restart, it will waiting for enough peers in consensus, which can potentially cause the deadlock between state syncing and consensus.

previous leader node restart stuck fixing

---

go.mod
internal/bech32/bech32_test.go
staking/types/commission.go
staking/types/decimal.go
staking/types/decimal_test.go
staking/types/validator.go

The decimal.go and decimal_test.go are shamelessly copied from cosmos with lint and build fixes.

Basic data structure for staking

---

core/types/cx_receipt.go
internal/chain/engine.go
internal/utils/utils.go
node/node.go
node/node_newblock.go

- fix shard state reading error
- add duplication checking for pending cx receipts
- add empty field check for cx receipts

cross shard receipts fix

---

consensus/consensus_v2.go

fix previous leader restart stuck issue

---

hmy/api_backend.go
hmy/backend.go
internal/hmyapi/backend.go
internal/hmyapi/harmony.go
node/rpc.go

Expose if current node is leader, watchdog consumer appreciates.

[RPC] Expose if current node leader

---

scripts/api_test.sh
scripts/setup_bls_build_flags.sh

addition to help with testing.

---

api/proto/common.go
node/node_handler.go

Found while implementing new staking code.

[staking] Remove legacy code

---

api/service/explorer/service.go

return empty if the offset*page is greater than tx len

[explorer/service.go]return empty if the offset*page is greater than tx len

---

api/service/explorer/service.go

[api/service/explorer/service.go]fix out of range bounds bug

---

internal/hmyapi/transactionpool.go
internal/hmyapi/util.go

Change offset, page -> pageSize, pageIndex in hmy api transaction history.
* Before
* After

offset, page -> pageSize, pageIndex

---

consensus/consensus_v2.go

fix initial leader bootstrap issue

---

internal/hmyapi/transactionpool.go
internal/hmyapi/util.go

Leo requested small fixes for mainnet new release.
* Before
* After

Fixes requested by Leo

---

api/service/syncing/syncing.go
node/node_syncing.go
scripts/setup_bls_build_flags.sh

- update consensus and committee information at end of every epoch
- fix bls library source bug
- local test passed for new node join

update consensus and committee informatin for at end of every epoch

---

cmd/staking/root.go
core/rawdb/schema.go
staking/types/messages.go
staking/types/transaction.go

Following the design in https://docs.google.com/document/d/1e-jsA3YCVxOeaVGpX-2xK-cCopc2c-bToeArObbeYYY/edit#heading=h.tqwfya2sqr7w
also change NewValidator => CreateValidator to follow the verb... syntax.
and update cross-link db keys to be shorter to save storage (no compatibility issue since it's not launched yet)

update staking transaction structs

---

consensus/engine/consensus_engine.go
core/blockchain.go
core/rawdb/accessors_chain.go
core/state/state_object.go
core/state/statedb.go
core/state_processor.go
core/state_transition.go
core/types/transaction.go
core/vm/interface.go
node/node.go
node/node_handler_test.go
node/node_newblock.go
node/worker/worker.go
node/worker/worker_test.go
staking/params.go
staking/types/delegation.go
staking/types/messages.go
staking/types/validator.go
staking/types/validator_test.go
test/chain/main.go

- revert to previous design and fix conflicts
- add statedb operations
- add validator messages process

Staking part2

---

cmd/client/wallet/main.go
internal/configs/sharding/localnet.go
internal/configs/sharding/mainnet.go
internal/configs/sharding/testnet.go
node/worker/worker.go

Transactions will be limited by gasLimit of the block. But all amount/account and num/account limit is not needed anymore.

Disable throttling for txns

---

cmd/client/wallet/main.go
node/worker/worker.go

make our target block gas limit to be around 100M gas. 10 times bigger than current ethereum's gas limit of 10M
Also stop processing txns with gasPrice == 0

stop adding new txns when out of gas

---

api/service/syncing/syncing.go
go.mod

redo of https://github.com/harmony-one/harmony/pull/1753 that was accidentally closed with force git push. cc: @chaosma

remove incorrect quorum check but just use the max hash for new node syncing

---

node/service_setup.go
test/deploy.sh

[wallet] no need to create persistent dht for client node

---

scripts/go_executable_build.sh

[build] fix version in static build

---

test/one_address/main.go

add example for creating one address

add example for creating one address

---

staking/types/messages.go

switch the order of validatoraddress in staking messages

---

scripts/go_executable_build.sh

[build] do not upload so files if build statically

---

scripts/node.sh

[node.sh] updated version

---

api/client/service/server.go
api/proto/message/server.go
api/service/syncing/downloader/server.go

[net] only listen to tcp4 address

---

node/service_setup.go

This is a fix of https://github.com/harmony-one/harmony/issues/1803

[node] disable client support service on mainnet

---

internal/hmyapi/transactionpool.go
internal/hmyapi/util.go

https://github.com/harmony-one/security-audit/issues/1 Just add pageIndex < 0 condition to return empty array.
.
* Before
* After

Fix security overflow issue

---

consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/view_change.go

Fixing https://github.com/harmony-one/harmony/issues/1809
Tested with debug code to replay the issue first and see the issue gone with the fix locally.

Fix epoch change leader block proposal issue

---

node/node_handler.go

Fix https://github.com/harmony-one/harmony/issues/1810
Tested with debug code to replay the issue first and see the issue gone with the fix locally.

Fix validator at index 0 not showing BINGO at the epoch block

---

node/node_newblock.go

Fix https://github.com/harmony-one/harmony/issues/1807
Tested with debug code to replay the issue first and see the issue gone with the fix locally.

Do not propose new block if I am not the leader

---

cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_v2.go
consensus/quorum/one-node-one-vote.go
consensus/quorum/one-node-staked-vote.go
consensus/quorum/quorum.go
consensus/view_change.go
core/blockchain.go
internal/chain/engine.go
node/node_explorer.go
node/node_genesis.go
node/node_newblock.go
node/node_resharding.go
node/worker/worker.go
shard/committee/assignment.go

This is PR #2 of breaking this PR #1762 into smaller PRs, assumes PR#1 merged into master, then will rebase this one to reflect that.
1. Factored out quorum's single implm and provide implement for both plain one vote vs staked vote
2. Provide way for dependency injection to Decider from consensus

[quorum] Staked quorum member

---

consensus/consensus_v2.go
node/node_handler.go

Two leaking goroutines, one that leaks from beginning of program.

[project] Fix two leaking tickers

---

node/node_newblock.go
node/worker/worker.go
shard/committee/assignment.go

Only compute new committee when last block of shard0 (beaconchain)

[beacon] Only change epoch when beaconchain changed to higher epoch

---

cmd/staking/root.go
core/blockchain.go
core/state_transition.go
hmy/api_backend.go
internal/hmyapi/backend.go
internal/hmyapi/blockchain.go
internal/hmyapi/types.go
shard/committee/assignment.go
staking/types/delegation.go
staking/types/messages.go
staking/types/validator.go

hmy_getAllValidatorAddresses
hmy_getValidatorInfo
hmy_getDelegationsByDelegator
hmy_getDelegationsByValidator all works now.
Tested locally with postman.

Add more staking RPCs

---

staking/types/messages.go
staking/types/transaction.go
staking/types/transaction_test.go

- add unit test for staking transaction
- fix staking tx StakeMsg copy issue
- make stakeMsg deepcopy

add staking transaction unit test for tx copy

---

test/deploy.sh

* Add check for ops repo since it cannot be assumed to exist.

Add checks for dependent repos in test/deploy

---

core/blockchain.go
core/evm.go
core/rawdb/accessors_chain.go
core/state_transition.go
hmy/api_backend.go
staking/types/delegation.go

Add delegation index to avoid looping through all delegations

---

core/blockchain.go
core/rawdb/accessors_chain.go
core/rawdb/schema.go
core/state_transition.go
crypto/bls/bls.go
hmy/api_backend.go
internal/hmyapi/backend.go
internal/hmyapi/blockchain.go
internal/hmyapi/types.go
node/node.go
node/node_handler.go
node/node_newblock.go
staking/types/transaction.go
staking/types/validator.go

Tested locally via RPC
.........
"creation_height": 72,
"uptime": "1.000000000000000000"
}
}

Add uptime stats

---

api/service/syncing/syncing.go
node/node_syncing.go

Fix beacon sync

---

test/deploy.sh

* Remove dependency of harmony-ops repo by cloning it into /tmp on each run. Time-wise this should be fine as the localnet is still booting in the bg. 
* Checks CLI version on each run and asks to make the latest if out of date.

Fix dependency possible mismatch with test/deploy tests

---

consensus/quorum/one-node-one-vote.go
consensus/quorum/one-node-staked-vote.go
consensus/quorum/quorum.go
node/node_handler.go
shard/shard_state.go

[staking] Implement Quorum in staked case while taking into account hmy slots

---

consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/view_change.go
node/node_handler.go
node/node_newblock.go

Cherry pick fixes for epoch change bugs.

Epoch change fixes

---

consensus/consensus_v2.go
consensus/quorum/one-node-one-vote.go
consensus/quorum/one-node-staked-vote.go
consensus/quorum/quorum.go
consensus/view_change.go
node/node_explorer.go

Re post merge comments in Prior PR, https://github.com/harmony-one/harmony/pull/1855

[staking] Fix mistake on QurorumThreshold, change Harmony share to 68

---

hmy/api_backend.go
internal/configs/node/config.go
internal/hmyapi/harmony.go

Picked these two commits to include in release - for watchdog reporting

Cherry-pick for watchdog downstream consumer

---

internal/configs/sharding/pangaea.go

[devnet] updated pangaea network configuration for devnet usage

---

internal/configs/sharding/pangaea.go

[devnet] set 40 keys only for hmy node on devnet

---

PULL_REQUEST_TEMPLATE.md

This rolls operational review into the initial PR cycle for merge into the master branch, in order to eliminate the need for pre-release operational review of each feature.
Non-code change.
[Formatting good on GitHub](https://github.com/harmony-ek/harmony/blob/b6471212554059cf35535065d0b6640dcf50e811/PULL_REQUEST_TEMPLATE.md):

Add operational checklist to PR template

---

internal/configs/sharding/pangaea.go

[devnet] use pga for the hosted zone to avoid conflict with testnet

---

block/v0/header.go
block/v1/header.go
block/v2/header.go
block/v3/header.go
core/blockchain.go
core/rawdb/accessors_chain.go
shard/shard_state.go
shard/shard_state_test.go

Backward compat by hooking place where ShardState is read. 
Includes unit test of old shard state structure being decoded into new shard state structure.

[shard] Wrapper on decoding ShardState

---

api/proto/node/node.go
node/node.go
node/node_handler.go

Fix staking txn replication issue

---

internal/configs/sharding/pangaea.go

[devnet] shorten epoch time and increase slot to 50

---

shard/committee/assignment.go
staking/effective/calculate.go

`effective.Median` panics with empty slice of `SlotPurchase`

[effective] Guard median call site against zero length SlotList

---

cmd/harmony/main.go
cmd/staking/root.go
hmy/api_backend.go
hmyclient/hmyclient.go
internal/hmyapi/backend.go
internal/hmyapi/blockchain.go
internal/hmyapi/types.go
shard/committee/assignment.go

tested locally and with devnet.

Add shard assignment in validator RPC; fix main.go for staking validator setup

---

core/types/transaction.go

Before:
```
```
After:
```
```
**YES|NO** …

fixing the staking type not found bug for collect rewards

---

internal/hmyapi/blockchain.go
internal/hmyapi/transactionpool.go
internal/hmyapi/types.go
staking/types/transaction.go

…ing methods
Added new methods to support format of staking transactions in apis for tx fetch, at blocks, also added few small staking methods (add RawSignatureValues for staking transaction struct to use it for RPC result).
Before:
```
```
After:
```
```
**YES|NO**
4. **How much minimum baking period after the last flag epoch should we allow on Pangaea before …

Different APIs update to support staking txs format

---

node/node_newblock.go

Fix existing crosslinks being proposed

---

api/service/syncing/syncing.go

Before:
```
ok      github.com/harmony-one/harmony/api/service/syncing      0.236s  coverage: 3.9% of statements
```
After:
```
ok      github.com/harmony-one/harmony/api/service/syncing      0.654s  coverage: 3.9% of statements
```
Local test succeeds.
1. **Does this PR introduce backward-incompatible changes to the on-disk data structure and/or the over-the-wire protocol?**
NO
8. **Does this PR introduce backward-incompatible changes *NOT* related to on-disk data structure and/or over-the-wire protocol?**
NO
NO

Fix block sync rollback logic

---

consensus/reward/schedule.go
internal/chain/reward.go

Add Initial table from spreadsheet, need to change keys as unix time stamps to be used by block in reward.go

[reward] Add reward Schedule table from spreadsheet

---

core/blockchain.go

Fix uptime accounting bug And make it non-blocking normal flow.

---

shard/shard_state.go
staking/types/messages.go
staking/types/validator.go

Before:
```
```
After:
```
```
**YES|NO** …

add fields in create/edit validator to send bls sigs, also verify

---

internal/hmyapi/blockchain.go
internal/hmyapi/types.go

Use one1 address for staking rpcs.

---

scripts/go_executable_build.sh

fix the build issue of "undefined reference to `ceilf'" on ubuntu 16
https://stackoverflow.com/questions/10935029/undefined-reference-to-ceilf

[build] support static build on ubuntu

---

consensus/engine/consensus_engine.go
core/blockchain.go
core/chain_makers.go
internal/chain/engine.go
node/node_handler.go
node/node_newblock.go
node/worker/worker.go

- refactor shardState proposal into blockchain which can be shared between leader and validators
- add validator verification on shardState

add shardState verification

---

consensus/consensus_v2.go
consensus/view_change.go

Previous log in consensus didn't contain some important information e.g. consensus mode. Add it back

make consensus log verbose

---

Dockerfile

this is an opinionated dockerfile, lets adjust on this PR @LeoHChen

[docker] Init dockerfile

---

scripts/node.sh

`-N testnet` for Testnet/Pangaea
`-N devnet` for Devnet
Before:
```
```
After:
```
```
**YES|NO**
6. **What are the planned flag epoch numbers and their ETAs on …

[rename network] Rename network names for Testnet & Devnet

---

scripts/go_executable_build.sh

[build] add back library files to md5sum

---

internal/chain/engine.go
staking/types/delegation.go

The undelegation record was not removed due to the RemoveUnlockedUndelegations is called on a non-pointer struct.

Fix undelegation non-pointer modification bug

---

consensus/votepower/roster.go

Fixes segfault found by @Daniel-VDM

[votepower] Need to loop for right ShardID for BLS key ownership

---

core/state_processor.go

Same for master.
Before:
```
```
After:
```
```
**YES|NO**
Note that this must be enough to …

Enable logs for master

---

internal/configs/sharding/pangaea.go

Before:
```
```
After:
```
```
**YES|NO** …

update shard configs for testnet launching

---

core/block_validator.go
core/types/cx_receipt.go
node/node.go

[security] Audit fixes

---

node/node_explorer.go

The condition changed after staking. So should update it for explorer node too.
local test.

Fix condition for explorer node to update consensus info

---

cmd/client/wallet/main.go
core/blockchain.go
core/tx_pool.go
go.mod
internal/configs/sharding/fixedschedule.go
internal/configs/sharding/localnet.go
internal/configs/sharding/mainnet.go
internal/configs/sharding/pangaea.go
internal/configs/sharding/shardingconfig.go
internal/configs/sharding/testnet.go
node/node.go
node/node_handler_test.go
node/node_newblock.go
node/worker/worker.go
node/worker/worker_test.go
test/chain/main.go

Cherry pick txpool logic from master to s3
Tested locally:
====== WALLET BALANCES ======
Using local profile for wallet
Account: one1spshr72utf6rwxseaz339j09ed8p6f8ke370zj:
Balance in Shard 0:  183.38074238, nonce: 10
Balance in Shard 1:  0.0000, nonce: 0
Using local profile for wallet
Account: one1uyshu2jgv8w465yc8kkny36thlt2wvel89tcmg:
Balance in Shard 0:  0.0000, nonce: 0
Balance in Shard 1:  184.952170952, nonce: 10
Using local profile for wallet
Account: one1r4zyyjqrulf935a479sgqlpa78kz7zlcg2jfen:
Balance in Shard 0:  1.0000, nonce: 0
Balance in Shard 1:  1.0000, nonce: 0
====== RESULTS ======
PASS

 merge Txpool into s3

---

.travis.yml
api/client/service/proto/client.pb.go
api/proto/message/message.pb.go
api/service/syncing/downloader/proto/downloader.pb.go
go.mod

[build] upgrade to 1.13 for travis build

---

go.mod

[go.mod] upgrade go-libp2p to 0.5.0

---

consensus/consensus_v2.go
internal/hmyapi/transactionpool.go
node/node_handler.go

Fix all the OOB issue reported from security audit: https://github.com/harmony-one/security-audit/issues

Add debug info for overrun issue & fix OOB bugs from the audit

---

scripts/node.sh

[node.sh] update bootnodes and dns for t2 testnet

---

Dockerfile

[project] Update Dockerfile to go 1.13.6

---

cmd/harmony/main.go

Add rollback into s3

---

core/blockchain.go
node/node.go
node/node_cross_shard.go
node/node_handler.go

local test passed:
{"level":"debug","port":"9000","ip":"127.0.0.1","cxp":{"Receipts":[{"TxHash":"0x7ce0e24de8d22de1394a9637abad05a91dee559dcf1736c246c636cb365992b7","From":"0xe1217e2a4861dd5d50983dad32474bbfd6a7333f","To":"0x1d44424803e7d258d3b5f160807c3df1ec2f0bf8","ShardID":1,"ToShardID":0,"Amount":100000000000000000}],"MerkleProof":{"BlockNum":19,"BlockHash":"0x37c742d6dcfc173c3d0368fb5dfea667755a850a341571fb5217be23fae9a5af","ShardID":1,"CXReceiptHash":"0x34fb31e13a5cc2a9be6aba91dee18091d4ab16f9652c69980bade76914f27806","ShardIDs":[0],"CXShardHashes":["0x8d8d7d24b21c488b697c57d47a2def59e7c4ca084797de1ddb96501b28a0f225"]},"Header":{"Header":{"parentHash":"0x806d0f6452cccbfc4ae49df9b55bdf03a194c373b98e63cf2a3a62b70af896d4","miner":"0xdeb6fffe20f7e4d0236bba974979a9cea0b25b98","stateRoot": …

cx receipt verification should use IsCrossTx rather than IsCrossLink

---

node/node.go

for explorer dashboard to more easily keep up

[node] Increase error sink size

---

Dockerfile

hmy completion had a missing dependency in Dockerfile
Added dependency to Dockerfile.

Fixed Dockerfile to allow hmy completion

---

scripts/go_executable_build.sh

[build] fix version string in static build

---

core/core_test.go
internal/configs/sharding/testnet.go

[config] long running s3 testnet config
