harmony-one/harmony

internal/shardchain/shardchains.go
node/node.go

When beacon chain db is already occupied, the node panic and exit without giving a well defined print message. This PR handles the error case that beacon chain cannot be initialized due to db already occupied. 
Before:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4d5fae5]
goroutine 1 [running]:
github.com/harmony-one/harmony/node.New(0x55e4ee0, 0xc0000d4140, 0xc0000dcf00, 0x55adb00, 0xc0003b2d90, 0x0, 0x1, 0x50d7349)
/Users/yanxiangwang/go/src/github.com/harmony-one/harmony/node/node.go:911 +0xd65
main.setupConsensusAndNode(0x50da132, 0x5, 0x7ffeefbff5f0, 0x8, 0x0, 0x3, 0x1, 0x50d7349, 0x2, 0x50dd66a, ...)
/Users/yanxiangwang/go/src/github.com/harmony-one/harmony/cmd/harmony/main.go:547 +0x302 …
```

[node] fix print message if db already occupied

---

consensus/consensus_viewchange_msg.go
consensus/quorum/quorum.go
consensus/view_change.go
consensus/view_change_test.go

use a separate NextLeaderPubKey variable to keep track of the pubkey of the next leader
do not change current pubkey unless leader change succeeded

[viewchange] fix getNextLeader

---

core/state_transition.go

Non-deterministic ordering of the map will trigger invalid receipt root for some of the unlucky machines with a different ordering than the leader.

make receipt log sorted

---

.travis.yml
README.md
scripts/travis_checker.sh

Reverts harmony-one/harmony#3320   We don't have resources to follow all codecov recommendations. But it's causing huge amount of interference for the code reviewer. 
Remove it until we really need it.

Revert "[travis]integrate with codecov.io"

---

core/state_processor.go
core/state_transition.go
hmy/hmy.go
rpc/contract.go
rpc/transaction.go

Part 1 of [EVM Error changes](https://gist.github.com/janet-harmony/980f6cacc3e398a0a116b17fa79c6fd6)
**Reverted changes to RPC response to keep backwards compatibility**
Example error response from failed `require` statement :
```
{
"id": 1,
"result": "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000b56616c75652066616c7365000000000000000000000000000000000000000000"
}
```

[core] Return EVM errors from ApplyMessage for external use

---

api/service/syncing/syncing.go
cmd/harmony/main.go
common/fdlimit/fdlimit_darwin.go
common/fdlimit/fdlimit_test.go
common/fdlimit/fdlimit_unix.go
core/blockchain.go
core/genesis.go
core/headerchain.go
core/offchain.go
core/rawdb/accessors_chain.go
core/rawdb/accessors_chain_test.go
core/rawdb/accessors_indexes.go
core/rawdb/accessors_indexes_test.go
core/rawdb/accessors_metadata.go
core/rawdb/accessors_offchain.go
hmy/bloombits.go
internal/utils/singleton.go

Previously, it could happen that the node can fall out of sync when leveldb get an error `too many open files`. Sometimes the error will cause node stuck because the non-atomic operation in `WriteBlockWithState`. This PR aims to fix this error. 
1. Modify `WriteBlockWithState` logic to make db write operations atomic.
2. Add error handling to all rawdb related operations, which allows node to continue running if `too many open files` error happens.
3. Add fdlimit module to raise nofile limit for the process, which is effective for macos.
Tested locally on both MacOs and Linux machine. After running for about 1 days, there is no more too many open files error.

[core] node stuck fix

---

cmd/harmony/config.go
cmd/harmony/config_test.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
cmd/harmony/main.go
internal/configs/node/config.go
internal/configs/node/network.go
node/node.go
node/node_syncing.go
p2p/host.go
p2p/tests/host_test.go
rosetta/common/config.go
rosetta/services/network.go
test/helpers/p2p.go

This feature is needed for a correct deployment of a rosetta 'offline' node. That said, it is a perfectly reasonable feature to have on its own - rosetta notwithstanding. I imagine that it would great for debugging / devs. 
One can run a node in offline mode by adding the `--run.offline` option. This option has been tested to be backwards compatible with older config files. It defaults to an 'online' setting if the option/config is not provided. 
An offline node simply means that it does not sync & is not subscribed to any p2p topic or has any p2p peers. 
I've had to keep some service instantiations to ensure other services don't crash from a nil pointer.

Offline Node Support

---

node/node.go
rosetta/infra/Dockerfile
rosetta/infra/README.md
rosetta/infra/run.sh

This PR adds the Docker file and relevant README to deploy a rosetta enabled Harmony node. 
I had to make the pool's `transaction.rlp` file dependent on the `datadir` param to ensure that the path of that file can be determined by said param. This should not break any existing node deployment, as the default directory is the same as the `harmony_db_*` directory. In the worst case, a user would have to re-submit their transaction (if the `datadir` was used prior).
* Add uploading to dockerhub to the release pipeline.

Rosetta Dockerfile (Stage 4 of Node API Overhaul)

---

core/state/statedb.go
core/vm/evm.go

Empty accounts don't need to be created for cross-shard txns.

do not create new account for cx txn

---

consensus/consensus_service.go
consensus/consensus_v2.go
consensus/validator.go
consensus/view_change.go
consensus/view_change_construct.go
consensus/view_change_msg.go
node/node.go

This set of PR further improves the stability of the view change process.
The enhancement includes:
* retry sending view change messages, in case the new leader started view change process slower than the other validators that may miss a few view change messages. This commit can reduce another round of view change process.
* ignore viewchange/newview message if the validator is not in viewchanging mode
* RLock to protect the reading of m1Payload
* use consistent data to construct the newview message
* use sendCommitMessages functions to reduce code duplication onViewChange
* further protection of consensus data change during view change process using consensus.mutex

View Change Revamp 2

---

rpc/v1/types.go
rpc/v2/types.go

Display failing transaction status in transaction receipt.
Example (receipt hash from Seb's message in Discord):
```
$ ./hmy blockchain transaction-receipt 0xd3ce842e3f7f52ef4b8118463db2a3ad09c9fea1e4a823bac2f1b6988fd867bc
{
"id": "1",
"result": {
"blockHash": "0x5ff2b50a8f11320f1a8be8d2c6f3c2b95fe69f6d8810964d733e633f81c8d6c7",
"blockNumber": "0x1eb0fd",
"contractAddress": "0x0000000000000000000000000000000000000000",
"cumulativeGasUsed": "0x856c",
"from": "one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd",
"gasUsed": "0x856c",
"logs": [],
"logsBloom": "0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```

[rpc] Always display transaction status in the receipt

---

rosetta/infra/Dockerfile

This PR is related to #3385
To fully build from source, we cannot copy a local file to create the docker image. Instead, we should pull straight from GitHub.

Rosetta Dockerfile FIX (Stage 4 of Node API Overhaul)

---

cmd/harmony/main.go
common/ntp/ntp.go

In case of ntp server is busy, we added the following
protection.
* increase timeout of ntp query
* ignore timeout error for ntp query

[ntp] do not exit if ntp query failed

---

rosetta/infra/Dockerfile
rosetta/infra/README.md
rosetta/infra/run.sh

This PR is related to #3385
This PR greatly reduces the size of the built docker image to about 156MB (down from 1.7GB). It also fixes the documentation to match the release pipeline.

Rosetta Dockerfile FIX2 (Stage 4 of Node API Overhaul)

---

consensus/consensus_v2.go
node/node_handler.go

#3399 Sync consensus fix branch breaks the leader change during epoch change. The reason is that the leader public key was overwritten by fbft message sender key. After this fix, the leader will be automatically switched to index 0 bls key after epoch change.
Tested on stn shard 1. The epoch change can restore the leader key.

[consensus] fix leader change during epoch change

---

hmy/blockchain.go
hmy/hmy.go
rosetta/services/block_special.go
rosetta/services/tx_format.go
rosetta/services/tx_format_test.go

This is related to #3390 
In the clean-up PR, I attempted to fix the pre-staking block 'off-by-one' errors that I got in my testing using the rosetta-cli. However, in further fuzzing-esk testing (different committee sizes, different transactions going off in the pre-staking era, etc...) I found that in some (rare) cases, there would still be an off-by-one error.
I've now changed the pre-staking block reward calculations to call the exact same functions as in `chain.AccumulateRewardsAndCountSigs`, even when fetching the block signers. I've tested this fix against said test and it appears to work.

Rosetta Implementation Cleanup FIX (Stage 3 of Node API Overhaul)

---

consensus/checks.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/quorum/quorum.go
consensus/view_change.go
consensus/view_change_test.go
core/blockchain.go

For view change, the view change ID is the key to determine which node
will be next leader. In our original algorithm, the view ID always increased one step
at a time. The view change period increased exponetially based on the square of
the gap between current view changing ID and previous known block view change ID.
However, it is very slow to converge the view change if multiple nodes are offline and
view change can't be reached. Especially, during the shard down event, multiple nodes
are offline and other nodes have advanced their current view changing ID.
The new time-baed synchronuous view change algorithm uses the local timestamp and
the timestamp of the block to calculate the expected view changing ID. In this case,
offline nodes can immediately catch up with the latest view …

[viewchange] time-based synchronuous view change

---

cmd/harmony/config.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
cmd/harmony/main.go
internal/configs/node/config.go
rpc/rpc.go

* Disable debug APIs by default
* New hidden `--rpc.debug` flag
Example usage:
```
./harmony --testnet --run=explorer --run.shard=0 --rpc.debug
```

[config] Add flag to enable debug APIs

---

scripts/node.sh

This is to fix the IP query failure using opendns.com.
Noted we are deprecating the support of node.sh.

[node.sh] fix public ip query issue with opendns

---

consensus/view_change.go
consensus/view_change_msg.go

This PR handles a few more corner cases like empty NewView message.
Also, we shall stop sending retry viewchange messages once NewView message sent or received.

Viewchange stability

---

consensus/consensus_service.go
consensus/consensus_v2.go
consensus/view_change.go

Fix the issue that view changing id isn't updated as new block committed.
Also should keep the block hash in new view as the leader still need to finalize the block hash if it's a M1 view change.

Update viewchangingid; Keep block hash in the case of m1 view change

---

consensus/quorum/one-node-staked-vote.go

In local net, there could be no external validators, and the signer count == participants even when it's not 100% qourum.

Fix quorum check in localnet staking

---

cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/construct.go
consensus/double_sign.go
consensus/leader.go
consensus/threshold.go
consensus/validator.go
consensus/view_change.go
internal/chain/sig.go
node/node.go
node/node_handler.go
shard/committee/assignment.go

Some refactoring +
Add the logic so when validator receives new committed message with more signatures, it can update it's local database with that.

Allow validator to update block commit sigs if it has more sigs

---

rosetta/common/operations.go
rosetta/common/operations_test.go
rosetta/services/construction_check.go
rosetta/services/construction_check_test.go
rosetta/services/construction_create.go
rosetta/services/construction_parse.go
rosetta/services/construction_submit.go
rosetta/services/tx_construction.go
rosetta/services/tx_construction_test.go
rosetta/services/tx_format.go
rosetta/services/tx_format_test.go
rosetta/services/tx_operation.go
rosetta/services/tx_operation_components.go
rosetta/services/tx_operation_components_test.go
rosetta/services/tx_operation_test.go

It is possible to preprocess a transaction's construction with some weird options. For example, it was possible to specify a native same shard transfer in the operations, but then have it go cross-shard in the options. This PR adds errors to such inconsistency when preprocessing a transaction.
I also took this time to change the native token operation constant names for consistency's sake. 
Lastly, I added in some extra checks that should return errors with more context to help developers debug.

QOL Fixes for Rosetta

---

cmd/harmony/main.go

beacon sync is not needed for explorer node as it doesn't participate in consensus.

remove beacon sync for explorer node

---

api/service/syncing/syncing.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/construct_test.go
consensus/quorum/one-node-one-vote.go
consensus/quorum/one-node-staked-vote.go
consensus/quorum/quorom_test.go
consensus/quorum/quorum.go
consensus/validator.go
consensus/view_change.go

View change still got stuck when manually abort consensus on commit phase every 7 block, with following code added in leader.go:
```
func (consensus *Consensus) onCommit(msg *msg_pb.Message) {
+       utils.Logger().Info().Msgf("ViewChanging %d %d", consensus.GetCurBlockViewID(), consensus.GetViewChangingID())
+       if consensus.GetCurBlockViewID()%7 == 0 {
+               return
+       }
recvMsg, err := consensus.ParseFBFTMessage(msg)
if err != nil {
consensus.getLogger().Debug().Err(err).Msg("[OnCommit] Parse pbft message failed")
```
There are two bugs fixed in this PR:
1. When selfCommit, we need to use AddNewVote, instead of SubmitVote. SubmitVote is a lower level logic which doesn't take care of voting power calculation. Fixed and also refactored to make submitVote private.
2. …

Fix view change stuck issue

---

api/service/syncing/syncing.go

normal sync threshold can not be more than 1, because when the shard is stuck, the node lagging behind by 1 won't sync.

fix sync threshold, have to be 0

---

consensus/validator.go

TryCatchup will write the commit sig into db. so no need to write it beforehand.

Simplify commit override

---

cmd/harmony/main.go

Reverts harmony-one/harmony#3420
instead should make beacon chain non-archival.

Revert "remove beacon sync for explorer node"

---

rosetta/services/construction_check.go
rosetta/services/tx_operation.go

Previously, the EVM data & error message was only returned for transactions calling an existing contract. However, it may be useful to get the data/error message of a contract creation transaction that one is in the process of constructing. This PR exposes such functionality.

[rosetta] Support EVM pre-process for contract creation txs

---

consensus/consensus_v2.go

Fix the bug that FBFTLog in LastMileBlockIter is not initialized.

[consensus] fix nil map in fbftlog in lastMileBlockIter

---

api/service/syncing/syncing.go
api/service/syncing/syncing_test.go

To address pagerduty issue: https://harmonyone.pagerduty.com/incidents/P4U6NZ0/timeline.
Before this change, node dns peers are static: not changed after initialization. Thus if some node ips are removed from sync domain, the syncing peers are still not updated. Thus, this PR is proposed to dynamically update the DNS nodes according to the domain name.
Tested with local machine with customized code connecting to mainnet.
The root cause of the node stuck is:
1. Some of the DNS nodes IPs are reset. Old IPs are no longer available.
2. DNS syncing peers are not updated dynamically. DNS peers are actually static after initialization.
From the node logs we can see that the node is connected to 4 sync peers and all of them are not available, thus causing sync to be permanently stuck:
``` …
```

[SYNC] Dynamic DNS peer discovery

---

consensus/leader.go

right now the commit sig from 67%-100% collection takes less than 1 seconds (if there is no missing sig)

shorten leader waiting time

---

consensus/consensus_msg_sender.go

Should stop the old retry before starting new one. otherwise, the old ones are dangling and can't be stopped.
tested locally. no unnecessary retries anymore.

correctly stop old retries

---

consensus/consensus_v2.go
node/node_newblock.go

for leader, finality should be counted after block proposal is finish, now that we have async block proposal.

fix finality count for leader

---

api/service/syncing/syncing.go
consensus/consensus_v2.go
consensus/leader.go
node/node_newblock.go

make precommit's committed message construction in the same thread as the main consensus thread, so that no other thread can clear the state in between.

Avoid reset state that's resetting committed content.

---

consensus/checks.go
core/blockchain.go

string() is converting to a UTF-8-encoded text. It will give a bad output if the uint64 is very large.

fix cache key issue and viewID check overflow issue

---

consensus/config.go
consensus/quorum/one-node-staked-vote.go
consensus/view_change.go
consensus/view_change_construct.go

This PR fixed the gap calculation in getNextLeader.
It also increase the period when calculating the nextView ID to avoid view ID out of sync when nodes start view change at different time.  If the view ID period is the same as the view change timeout, the nodes will always have different view ID.  I have found this issue during another stress test on STN.
Tested on STN, shutdown 2/10 nodes and can still recover consensus after view change.

Viewchange fix out of sync

---

consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_test.go
consensus/consensus_v2.go
consensus/leader.go

Previously, the finalCommit is executed from a channel as a signal. there is a risk that if the commit Sig is reset before the finalCommit is called, then finalCommit will send out empty committed messages.
This PR make finalCommit in the same thread as consensus. so the data inconsistency will never happen

Make finalCommit in the same thread as consensus

---

consensus/config.go
consensus/view_change.go

[viewchange] shorten the viewchange timeout to 29s

---

consensus/checks.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/engine/consensus_engine.go
consensus/quorum/one-node-one-vote.go
consensus/validator.go
consensus/view_change.go
core/chain_makers.go
core/state_processor.go
internal/chain/engine.go
node/node_handler_test.go
node/node_newblock.go
node/node_newblock_test.go
node/worker/worker.go
test/chain/main.go

Many fixes:
1. Correct the viewID in proposed block when it's async proposal and the curBlockViewID isn't incremented yet.
2. Update timeout ticker frequency so nodes can start view change in similar time frame (rather than 3s apart)
3. Only start consensus timer when it's the first Committed message received on validators.
4. Counting next viewID based on stuck block viewID
5. prevent nil pointer crash in IsQuorumAchievedByMask before staking.

Fixes viewID and view change ID base

---

consensus/leader.go

if there are more time left for the block. Wait more than 1s up until block time is reached. Just to be more lenient on the slow nodes if it allows.

be more lenient on grace period

---

consensus/consensus_v2.go
consensus/leader.go
internal/chain/reward.go

When the leader is slow, the commit sig timeout is too short and it will just read from the 67% sig for next block. Better make the timeout longer so most of the signers can get into the new block.
Also return early to avoid expensive signature related computation for onCommit.

make commit sig timeout longer, also return early for onCommit

---

scripts/node.sh

As reported by node runner, in case the host has an ipv6 address and the ipv6 address will failure the script checking.

[node.sh] return ipv4 address only

---

node/metrics.go
node/node.go

* peerid, node version string
* number of different type of p2p messages
* metrics of node message type
* metrics of consensus message type
The metrics can be obtained using
```
curl http://ip:9900/metrics
```

[prometheus] add node metrics

---

api/service/syncing/syncing.go
consensus/consensus_v2.go

Currently, FBFTLog method might take extensive CPU resource:
The reason why this happens is that the look up mechanism is actually iterating over the FBFT log entries. And for leader nodes, currently there is no logic taking care of removing fbft log messages after commit. This PR add removing FBFT message logic after successfully committed for leader node.

[consensus] add remove fbft log in commitBlock on leader node.

---

consensus/consensus_v2.go

just in case something weird happened in the leader logic, it should still try propose new blocks. As long as validators still verify the blocks and messages. It doesn't hurt to try move forward optimisitically.

not return early for block proposal

---

cmd/harmony/config.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/main.go
hmy/hmy.go
internal/configs/node/config.go
internal/shardchain/shardchains.go
node/node.go
node/node_handler_test.go
node/node_newblock_test.go
node/node_test.go
rosetta/rosetta.go
rosetta/services/network.go

We used to use one `run.archive` flag to represent the archival mode for both beacon chain and shard chain.
This PR separates the archival configuration for beacon chain and shard chain.
By default, the beacon chain is not in archival mode, which is not necessary even for explorer node on shard chain.
This change can save a lot of disk space on the explorer node for shard chain.

Separate archival configuration for beacon chain and shard chain

---

internal/configs/sharding/localnet.go
internal/configs/sharding/mainnet.go
internal/configs/sharding/shardingconfig_test.go
internal/params/config.go

2s finality at epoch 366 on mainnet will happen Around Tuesday Dec 8th 2020, 8AM PST
Double the blocks per epoch to 32768 in mainnet so the epoch time can still be around 18hours after 2s finality.
Also added unit tests for the epoch transition logic around 2s epochs.

Add 2s logic for mainnet at epoch 366, also double the blocks per epoch in mainnet.

---

core/vm/gen_structlog.go
core/vm/logger.go
core/vm/logger_json.go
hmy/tracer.go
rosetta/common/operations.go
rosetta/rosetta.go
rosetta/services/block.go
rosetta/services/construction_parse.go
rosetta/services/construction_parse_test.go
rosetta/services/mempool.go
rosetta/services/tx_format.go
rosetta/services/tx_format_test.go
rosetta/services/tx_operation.go
rosetta/services/tx_operation_test.go

This PR closes #3434
In order to expose internal transactions, some extra field was added to the trace's `ExecutionResult`. Namely, I added the contract address (to account for nested method calls across different contracts) and opcode caller (for future use and to account for nest method calls across different contracts). 
Note that I correct the output of the trace RPC, this will break any implementation that already consumes this RPC. However, this is necessary for consistency and fixes an oversight during the review process of the initial trace PR. 
Some major refactoring of the operation formatter was done at the same time to make things more consistent. 
I've tested this implementation locally using [this payable contract](https://github.com/harmony-one/HRC/blob/751b856c8b205c3d1ff48 …

[Rosetta] Track internal transactions 

---

api/service/networkinfo/service.go
cmd/harmony/config_test.go
go.mod
internal/configs/node/network.go

This PR enabled /dnsaddr/ format support of the bootnode.
So that we don't have to change the hardcoded IP addresses in the code binary if bootnode is migrated or updated.
To support dns based bootnode address, just need to add TXT record in DNS.
The following official document depicts the details.
https://github.com/multiformats/go-multiaddr-dns

Bootnode dnsaddr support

---

api/service/syncing/syncing.go
api/service/syncing/syncing_test.go
node/node_syncing.go

Currently, some of the explorer node is synced every 30 seconds the explorer node block is always lagging behind. This PR aims to address this issue.
Following error log is found for every committed message in explorer node:
```
{"level":"error","msgBlock":6362649,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node_explorer.go:73","time":"2020-12-09T00:16:48.88101361Z","message":"[Explorer] Failed to verify the multi signature for commit phase"}
```
After digging a little deeper, the explorer node uses `consensus.Decider` to get the signature mask, which can be out of date. 
```
// node/node_explorer.go:43
aggSig, mask, err := node.Consensus.ReadSignatureBitmapPayload(
recvMsg.Payload, 0,
)
```
This issue is caused by removing `consensus.UpdateConsensusInformation` at the …

[sync] fix explorer sync

---

consensus/consensus_v2.go
consensus/validator.go
node/node.go
node/node_handler.go
node/node_newblock.go

It happened that when a leader is restarted, two part of the code triggered new block proposal and started announce phase, which messed up the consensus states (block content and block hash). This caused the second consensus to fail due to malformed prepared message (containing the second proposed block in last round):
```{"level":"warn","myBlock":1497743,"myViewID":1507399,"phase":"Prepare","mode":"Normal","MsgBlockNum":1497743,"blockNum":1497742,"caller":"/home/lc/go/src/github.com/harmony-one/harmony/consensus/checks.go:129","time":"2020-12-10T05:32:48.149366601Z","message":"[OnPrepared] BlockNum not match"}```
Then view change started with this bad prepared message, but it succeeded because verifyBlock() method doesn't take care of whether the block is at the tip of not. The second …

Fix inconsistent block proposal and verification

---

.github/workflows/ci.yaml

We are using a release job on our jenkins server for harmony node release. Since we are doing github release to publish the artifact now, we shall use github actions to do the release.
action test log: https://github.com/jhd2best/harmony-test/actions/runs/414783335
docker hub: https://hub.docker.com/r/haodi/harmony/tags?page=1&ordering=last_updated
release page: https://github.com/jhd2best/harmony-test/releases/tag/v3.1.1
- trigger GitHub action by push a new release using the published tag (start with `v`)
- build the static binary on both linux and macos platform
- build the signed DEB and RPM packages
- build docker image of the release binary to dockerhub
- publish the static binary with signature and packages to the release page

[devops]support github action

---

internal/params/config.go

To enable 40% external voting power

[config] adjust epoch number for testnet/mainet

---

cmd/harmony/main.go
core/state_processor.go
core/types/eth_transaction.go
core/types/transaction.go
core/types/transaction_signing.go
core/vm/runtime/runtime.go
internal/params/config.go
internal/shardchain/shardchains.go
node/node.go
node/worker/worker.go
rpc/pool.go

1. Add Eth<Network>Shard0ChainID in chainConfig so we have the base number for shard calculation or beacon chain reference.
2. Move UpdateEthChainIDByShard before Node() initialization so the worker struct can be initialized with the correct config with correct chainID.
3. Add sanity checks in txn ordering code to avoid nil pointer crash.
4. Fix EIP155Signer.Equal(), we only need to compare the chainID inside the signer as each signer is initialized differently.
5. Add ethSigner in SendRawTransaction for ethereum txns.
6. Correctly initialize beacon worker with the eth shard0 chainID.
7. Add forking logic at block proposal and rpc level for ethereum compatible txn support.
Tested locally with metamask for both shard 0 and shard 1. All worked well.

Resolves issues on eth comaptible txns

---

accounts/keystore/keystore.go
core/types/eth_transaction.go
core/types/transaction_signing.go

Adds support for `SignEthTx` to enable signing EthTransactions in go-sdk, go-lib etc.
`(tx *EthTransaction) WithSignature` was changed to return a `*EthTransaction` instead of `InternalTransaction` to follow the same pattern as `(tx *Transaction) WithSignature`.
(Changing `(tx *Transaction) WithSignature` to return a `InternalTransaction` results in a lot of failing tests due to failing type assertions - hence why `tx *Transaction` and `tx *EthTransaction` are returned respectively.)

Add SignEthTx()

---

internal/params/config.go

which happens closely before noon Monday 1/25/2021 PST

enable eth txn for testnet at epoch 73290

---

internal/shardchain/shardchains.go

Should use the updated chain config for beacon blockchain initialization.
Otherwise, beacon chain in non-beacon shards will recognize the eth-compatible txns and will report error:
```
{"level":"error","caller":"/mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:1645","time":"2021-01-25T22:01:28.59753681+01:00","message":"\n########## BAD BLOCK #########\nChain config: {ChainID: 2 EthCompatibleChainID: 1666700001 EIP155: 0 CrossTx: 0 Staking: 2 CrossLink: 2 ReceiptLog: 0}\n\nNumber: 5150267\nEpoch: 73290\nNumTxn: 1\nNumStkTxn: 0\nHash: 0x95aba0e885317a89b7ee9d81fba42c2d7d5092ed3ae1981cb4c22c88f06eb638\n\n\nError: invalid chain id for signer\n##############################\n"}
```

Update beacon chain config

---

node/api.go
rpc/blockchain.go
rpc/eth/rpc.go
rpc/eth/types.go
rpc/net.go
rpc/pool.go
rpc/rpc.go
rpc/transaction.go
rpc/utils/utils.go

This PR refactors the RPC endpoints so that they are more compatible with the format expected by Truffle, web3.js and similar tools - primarily by returning proper base16 addresses instead of bech32 addresses etc.
Ethereum RPC:s have now been moved to the `rpc/eth` package (previously they just used the V1 API:s with an `eth_` prefix).
This PR changes the `net_version` RPC to return our Ethereum-compatible chain ids (e.g. `1666700000`) instead of the Harmony chain ids (e.g. `1666700000`).
If we have services depending on this specific RPC and its return format they might break if they expect `1`/`2` to be returned vs e.g. `1666700000`. This change is mandatory if we aim to support Truffle, web3.js etc.
As a proof of concept I ported the Token Faucet demo dApp to use these RPC:s + MetaMask …

Refactor eth_ RPC:s to improve support for Truffle, web3.js etc

---

core/rawdb/accessors_indexes.go

Ethereum toolings such as Metamask will lookup txns based on the hash/iD of txn in the original ethereum format. So we need to also index the eth txns by their "ethereum" hash in our node.
Tested with Metamask in localnet. I was able to use the txn hash in MetaMask to look it up in hmy rpc

Add eth txn hash lookup entry

---

api/service/explorer/storage.go
api/service/explorer/structs.go
api/service/explorer/structs_test.go
core/rawdb/accessors_indexes.go
core/rawdb/accessors_indexes_test.go
core/types/transaction.go
core/types/tx_errorsink.go
hmy/blockchain.go
node/node.go
rpc/eth/types.go
rpc/filters/filter_system.go
rpc/pool.go

Since we store ethereum txn using the translated format of hmy txn on the chain. The txn hash of the two types of txns are not the same. We need streamline the logic to make sure to the developers/users, when they are sending eth txns, they are always handling the txns by the eth version of the txn hash.
Fix the txn lookup checking where txn hash and the lookup hash doesn't match.
Also update all the txn hash usage to use the appropriate version of the hash.

Use and return the Ethereum tx hash for Ethereum txs

---

internal/params/config.go

also correct the base chain ID for some test networks.

enable eth txn at epoch 442

---

rpc/eth/types.go
rpc/pool.go
rpc/transaction.go

This PR fixes an issue where `eth_getTransactionReceipt` was returning both a pre-Byzantium `root` field as well as a post-Byzantium `status` field - you're supposed to return one of them, not both.
Related EIP: https://eips.ethereum.org/EIPS/eip-658

Make eth_getTransactionReceipt compatible with EIP-658

---

core/state_transition.go
core/vm/evm.go
core/vm/instructions.go
core/vm/interpreter.go
rpc/transaction.go

Related issue: #3508 
Our nodes perform incorrect gas estimations for certain smart contract calls by underestimating the gas required. This results in certain smart contract txs being reverted by the EVM.
After applying this fix I can now run smart contract interactions that previously failed (see reproducible example in #3508 )
Regression tests are also passing on localnet. 
I upgraded the code based on the current code base in [https://github.com/ethereum/go-ethereum](https://github.com/ethereum/go-ethereum) and adjusted it where our API:s differ from Ethereum's.

Fix gas estimation for sc calls

---

consensus/config.go
consensus/consensus_service.go
consensus/quorum/quorum.go
consensus/view_change.go
node/node.go

when view change happended at the first block of the new epoch

[viewchange] always use first participant as base of leader pubkey

---

consensus/votepower/roster.go

shard 0 having a case where 1 external validator with 40% voting power signed previously. Thus, the new 70-30 assignment made the previous block's signature invalid because that 40% voting power become 30%.
This should always make testnet work during these stuck epochs.

make sure consensus always work in testnet

---

.travis.yml
scripts/travis_rosetta_checker.sh
scripts/travis_rpc_checker.sh

Cache the docker img to make ux better with the new docker-hub rate limit.
This is the only option that we have since we CANNOT use private env vars (via Travis) to auth a docker account as they DO NOT work on forks (for security reasons).

[travis] Cache docker imgs

---

node/api.go
rpc/rpc.go
rpc/web3.go

This PR adds support for `web3_clientVersion` which is required for Hardhat deployments/interactions.

Add web3_clientVersion

---

api/service/explorer/service.go
rpc/rpc.go

This adds a mechanism to remove burned token balance from supply-related stats.  
The only known burn account is `one10000000000000000000000000000dead5shlag`, though there are def more. 
This also adds the `/burn-addresses` to the explorer service so one can see what burn accounts the explorer is considering. 
I also added prints for all the servers that get started by the node and the relevant host and port. 
This was tested using my own explorer node using a full archival DB up to epoch 304. 
Here is what the relevant explorer endpoints use to return: 
```
ubuntu@ip-172-31-14-199:~/go/src/github.com/harmony-one/harmony$ curl http://localhost:2000/total-supply
"13091070831.999999999626190936"
ubuntu@ip-172-31-14-199:~/go/src/github.com/harmony-one/harmony$ curl …
```

[Explorer] Add burned tokens to supply related info

---

node/api.go
rpc/eth/types.go
rpc/filters/api.go

- Enable filter API:s for Ethereum RPC:s (e.g. to support https://github.com/blockchain-etl/ethereum-etl)
- Fix `difficulty` data type - should be hex, not uint.

RPC fixes - filter API:s + difficulty hex formatting

---

consensus/consensus_v2.go

To avoid race condition where the commitBitmap is modified in another thread.

make sig verification in the same thread as consensus message processing

---

consensus/consensus_v2.go

Fix https://github.com/harmony-one/harmony/issues/3538. 
Added logic that when consensus and sync races on insert block, the node is forever stuck in syncing mode.

[consensus] fix the rare consensus/sync race condition

---

api/service/blockproposal/service.go
api/service/consensus/service.go
api/service/explorer/service.go
api/service/manager.go
api/service/manager_test.go
api/service/networkinfo/service.go
api/service/networkinfo/service_test.go
api/service/prometheus/service.go
cmd/harmony/main.go
consensus/consensus_v2.go
node/api.go
node/node.go
node/node_newblock.go
node/service_setup.go
p2p/host.go
rosetta/rosetta.go

1. Refactored service manager with cleaner interface. 
2. Add prometheus to the service manager.
3. Graceful shutdown of the services (including consensus).
4. Some code refactor regarding consensus graceful shutdown.
1. Allow multiple interrupt signal to force quit when node program stuck in the shutdown process.
2. Allow node handle errors when starting / stopping services.
3. Resolve the initial 30s delay before the block proposal service can be stopped.
Passed local tests, all nodes can be shutdown gracefully.

Graceful shutdown

---

rpc/blockchain.go

Adds support for `hmy_accounts` and `eth_accounts`:
```
$ curl http://localhost:9500/ -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"hmy_accounts","params": [],"id":1}'
{"jsonrpc":"2.0","id":1,"result":[]}
```
```
$ curl http://localhost:9500/ -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_accounts","params": [],"id":1}'
{"jsonrpc":"2.0","id":1,"result":[]}
```
The endpoint will always return an empty array similar to how e.g. Infura (https://infura.io/docs/ethereum/json-rpc/eth-accounts) handles it:
> NOTE: While this JSON-RPC method is supported by Infura, it will not return any accounts. Infura does not support "unlocking" accounts. Instead, users should send already signed raw transactions using eth_sendRawTransaction.
The …

Add Accounts endpoint

---

rpc/eth/types.go

Our RPC:s (both `hmy_` & `eth_`) are currently returning block nonces as `uint64`.
The `eth_` RPC endpoints need to return these as 0x-prefixed hex strings with a length of 16 characters.
This currently breaks TheGraph node from working properly:
```
Feb 24 23:22:59.188 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #10) with result Err(Decoder error: Error("invalid type: number, expected a 0x-prefixed hex string with length of 16", line: 0, column: 0))
```
The solution is to simply use `BlockNonce` from `github.com/harmony-one/harmony/core/types` that will marshal to the proper format when requested via RPC:
Wrong format (testnet):
```
curl -s https://api.s0.b.hmny.io -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": …
```

[Ethereum RPC] Use BlockNonce type for marshaling nonce fields for blocks

---

shard/committee/assignment.go

In the apocalypse/rare case where there is no validator successfully elected, reuse the last committee to move the consensus forward.

Reuse old shard state if no validator is elected

---

consensus/quorum/one-node-staked-vote.go
internal/configs/sharding/stress.go
internal/params/config.go

This PR enables 40% external voting power on stressnet. It is used to test the voting power change w/o interruption of testnet.

enable 40% external voting power on stressnet

---

consensus/view_change_construct.go

This PR fixes the un-initialized map panic found in the following issue.
https://github.com/harmony-one/harmony/issues/3557

[panic] fix a panic in view change

---

rpc/eth/rpc.go
rpc/eth/types.go

`sha3Uncles` was missing from our Ethereum block related RPC calls (e.g. `eth_getBlockByNumber`), this results in e.g. TheGraph not being able to properly traverse blocks.
This PR adds a `sha3Uncles` response field that represents a hashed value of a block's uncles using `types.CalcUncleHash(block.Uncles())`.
E.g:
```
$ curl -s http://localhost:9500 -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": "eth_getBlockByNumber", "params": ["0x0", false]}' | jq '.result.sha3Uncles'
-> "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347"
```

[Ethereum RPC] Add sha3Uncles for block RPC endpoints

---

p2p/stream/common/streammanager/config.go
p2p/stream/common/streammanager/events.go
p2p/stream/common/streammanager/events_test.go
p2p/stream/common/streammanager/interface.go
p2p/stream/common/streammanager/interface_test.go
p2p/stream/common/streammanager/streammanager.go
p2p/stream/common/streammanager/streammanager_test.go
p2p/stream/types/stream.go

This is a breakdown PR of https://github.com/harmony-one/harmony/pull/3535 and is on top of https://github.com/harmony-one/harmony/pull/3552.
1. Added stream manager module to manage over streams of a stream protocol.
Stream manager do the following job:
1. add a new stream.
2. remove a stream.
3. discover and connect new streams when the number of streams is below threshold.
4. emit stream events to inform other modules.
5. reset all streams on close.

[stream] added stream manager module

---

consensus/consensus_service.go

This is a further fix of the following issue.
https://github.com/harmony-one/harmony/issues/3557

[viewchange] protect view change struct during reset

---

core/rawdb/accessors_indexes.go
rpc/eth/types.go

Fixing: https://github.com/harmony-one/harmony/issues/3564
1. support harmony txn lookup by its ethereum version of hash.
2. Return ethereum version of hash for txns in eth_getBlockByNumber

Support for eth hash lookup for hmy txns.

---

consensus/view_change.go
consensus/view_change_construct.go
staking/availability/measure.go

This PR fixes the crash found recent test node shard0 down event.
https://github.com/harmony-one/harmony/issues/3570
Added a few more defensive protection to guard un-initialized map.

Fix crashes found during view change

---

hmy/blockchain.go
rpc/eth/types.go
rpc/filters/api.go
rpc/filters/filter.go
rpc/filters/filter_system.go

receipt log used to have hmy txn hash for eth_ rpcs. This PR fixes it.

return eth hash for eth_ log related rpc

---

consensus/consensus_v2.go
consensus/leader.go
node/node_explorer.go

no need to verify the header signatures if it's already verified before.

avoid unnecessary header sig checking

---

hmy/downloader/adapter.go
hmy/downloader/adapter_test.go
hmy/downloader/beaconhelper.go
hmy/downloader/const.go
hmy/downloader/downloader.go
hmy/downloader/downloader_test.go
hmy/downloader/downloaders.go
hmy/downloader/inserthelper.go
hmy/downloader/inserthelper_test.go
hmy/downloader/longrange.go
hmy/downloader/longrange_test.go
hmy/downloader/shortrange.go
hmy/downloader/shortrange_test.go
hmy/downloader/types.go
hmy/downloader/types_test.go

This is a break down pr of #3535 and is rebased on https://github.com/harmony-one/harmony/pull/3583.
* Added downloader module to download block at time ticks or triggered by other modules.
Downloaders is the aggregation of downloader. Each downloader is responsible for syncing for one specific shard. Each downloader will host its own `sync.Protocol` on a specific topic.
Downloader has two modes:
1. Long range sync: aimed to sync for long range. Long range will happen the first time when the downloader does download task. The target block number of each long-range-sync iteration is set with a max vote, and it does not necessarily to be the latest. 
2. Short range sync: aimed to sync for a short range. After the bootstrap range range sync, short range sync is awaken periodically or by …

[Stream] Add downloader module

---

consensus/consensus.go
consensus/consensus_v2.go
consensus/downloader.go
consensus/validator.go

This is a break down of https://github.com/harmony-one/harmony/pull/3535, and is on top of https://github.com/harmony-one/harmony/pull/3587.
Added stream downloader to consensus. Now consensus will trigger new downloader logic only if downloader is setup.

[Stream] added stream downloader to consensus

---

api/service/manager.go
api/service/synchronize/service.go
cmd/harmony/config.go
cmd/harmony/config_test.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
cmd/harmony/main.go
hmy/downloader/beaconhelper.go
hmy/downloader/const.go
hmy/downloader/downloader.go
hmy/downloader/shortrange.go
hmy/hmy.go
internal/configs/node/config.go
node/double_signing.go
node/node.go
node/node_cross_link.go
node/node_handler.go
node/node_syncing.go
p2p/host.go
rosetta/services/network.go
rpc/blockchain.go
rpc/common/types.go

Added downloader service in main.go. Also added all flags for syncing. After this PR,
1. By default, nodes will use DNS sync on mainnet and testnet.
2. By default, nodes will run stream sync as a server but will not run as a client.
3. To start a node running only stream sync logic, run with command as follows or update harmony.conf.
```
./harmony --sync.downloader --sync.legacy.client=false
```
Running nodes with downloader as default will be enabled after mainnet internal tests.
According to https://github.com/harmony-one/harmony/issues/3590, we will need a binary running 
1. DNS client
2. DNS server
3. Stream server
4. NO downloader (stream client)
So in this PR, flag `--sync.downloader` is added to instruct the node not to start downloader module.
local test done.
For STN tests, nodes …

[Stream] Stream downloader flag

---

consensus/construct.go

It is reported that a following log is observed when the validator is not elected.
```
{"level":"error","myBlock":10629717,"myViewID":10629979,"phase":"Announce","mode":"Listening","error":"No private keys provided","message-type":"PREPARE","caller":"/mnt/jenkins/workspace/harmony-release/harmony/consensus/validator.go:367","time":"2021-03-17T22:17:03.59564878Z","message":"could not construct message"}
```
This log does not make sense thus added a condition before constructing p2p message.

[consensus] Resolve one consensus log does not makes sense

---

consensus/consensus_service.go
consensus/consensus_v2.go

When the node initially rebooted,
it may enter 'Syncing' mode, while it will
stop the bootstrap timer.
When the network is in viewchange mode, itself
can't enter view change mode anymore and will stuck
in syncing mode forever.
This PR is a fix of this long time issue,
https://github.com/harmony-one/harmony/issues/3572

[bootstrap] do not stop bootstrap timer

---

hmy/staking.go
internal/chain/engine.go
internal/params/config.go
staking/types/delegation.go
staking/types/delegation_test.go

After the introduction of redelegation feature, it's convenient for delegators to switch between validators without having to wait for the 7 epoch locking time. We also had the convenient feature in the very beginning to allow immediate unlock of undelegated tokens from validators who were elected in the last 7 epochs (it's also meant for easy switch away from bad validators). Together with this two feature, there is a path to achieve early unlocking by redelegating to an unelected validator and then undelegate from there.
This change disable the early unlock capability from unelected validators to fix this problem. This feature is not very relevant anyway after the introduction of redelegation.

disable early unlock of tokens

---

consensus/consensus_v2.go
hmy/downloader/const.go
hmy/downloader/shortrange.go

Resolve issue https://github.com/harmony-one/harmony/issues/3601 and some more stream fixes.
1. Added consensus start logic in a corner case of consensus/downloader interface.
2. Added some logs to short range sync.
3. Changed concurrency in short range to avoid the following unexpected error log message.
```
{"level":"debug","module":"request manager","error":"no more available streams","request":"REQUEST [GetBlocksByHashes: 5358c64bc1e8afea2560ec92e402f0885b5a2ebbdec409380eff3f3fc4ec5238]","caller":"/home/yx/go/src/github.com/harmony-one/harmony/p2p/stream/common/requestmanager/requestmanager.go:292","time":"2021-03-22T00:28:25.504096325Z","message":"Pick available streams."}
```

[stream][consensus] resolve stn stuck issue and some fixes to short range sync.

---

consensus/consensus.go
consensus/consensus_v2.go
consensus/validator.go
consensus/view_change_construct.go
consensus/view_change_msg.go

Verified blocks should always be marked to avoid repeated verification on the same block.

avoid repeated block verification

---

cmd/harmony/main.go
hmy/downloader/beaconhelper.go
node/node_handler.go
node/node_syncing.go

1. Let 2% of the validators do crosslink broadcast along with the leader.
2. Cealn up Rand seeding.

remove unnecessary crosslink broadcast in state sync

---

api/service/legacysync/syncing.go
cmd/harmony/config.go
cmd/harmony/default.go

Currently, travis test (local rpc test and rosetta test) is actually testing the downloader logic with stream sync. However, downloader module will not be enabled in production environment in the near future. So in this PR, add a new default config for local net, to instruct travis to test DNS sync logic instead of downloader logic.

[stream] make travis test dns sync logic

---

core/blockchain.go
core/chain_makers.go
hmy/downloader/adapter_test.go
hmy/staking.go
internal/chain/engine.go
shard/committee/assignment.go

Refactor the validator reading interface so we don't recreate a new state for each validator reading.
Also optimize undelegation payout logic to avoid repetitive/redundant execution.

Avoid repeated state creation in validator reading

---

core/tx_pool.go
internal/configs/sharding/mainnet.go
internal/params/config.go

* 40% external voting power enabled at epoch 530, around Apr 12th 2021, 22:30 UTC
* reduce number of internal slots to 50 per shard,
increase the number of available slots from 640 to 800 to external validators.

[config] set 40% external voting epoch

---

core/blockchain.go

Added cache to `Blockchain.ReadValidatorSnapshot` according to pprof results in https://github.com/harmony-one/harmony/issues/3635, and expect to reduce 30% CPU usage for newly started leader node. 
Previously, `validatorSnapshotCache` is only added when the node goes through epoch block. For a newly started node, it will read from db and decode `ValidatorWrapper` (a super nested structure poor in rlp performance) every time when accumulating rewards. So previously, it is expected that newly started node will have bad performance compared to nodes come through an epoch block.
This PR added cache to the `ReadValidatorSnapshot` method and shall resolve the high CPU usage for newly started machine.

[blockchain] added cache in ReadValidatorSnapshot

---

consensus/engine/consensus_engine.go
hmy/downloader/adapter_test.go
internal/chain/engine.go
node/node_cross_link.go

1. Added a new method `VerifyCrossLink` to engine interface.
2. Refactored some code of`engineImpl` to use the same cache for crosslink and headers.
3. Basically, `VerifyCrossLink` `VerifySeal` `VerifyHeaderSignature` will share the same cache to reduce duplicate signature verification.

[engine] Engine cache for `VerifyCrossLink`

---

node/node.go

When doing tests, hit the following panic error when shutting down:
```
^CGot interrupt signal. Gracefully shutting down...
panic: sync: WaitGroup is reused before previous Wait has returned
goroutine 369215 [running]:
sync.(*WaitGroup).Wait(0xc006a7c390)
/usr/local/go/src/sync/waitgroup.go:132 +0xad
github.com/harmony-one/harmony/core.(*BlockChain).Stop(0xc006a7c000)
/home/yx/go/src/github.com/harmony-one/harmony/core/blockchain.go:847 +0x9f
github.com/harmony-one/harmony/node.(*Node).ShutDown(0xc000338580)
/home/yx/go/src/github.com/harmony-one/harmony/node/node.go:1176 +0x4e
created by main.listenOSSigAndShutDown
/home/yx/go/src/github.com/harmony-one/harmony/cmd/harmony/main.go:772 +0x220
```
So, Blockchain shall be shutdown after all service stopped.

[misc] shut down blockchain at last

---

hmy/downloader/beaconhelper.go

A potential fix to https://github.com/harmony-one/harmony/issues/3618. 
`time.Tick` is creating a Ticker object every time when called and might potentially cause CPU and memory leak (Hard to discover in pprof). Replace `time.Tick` with `time.NewTicker`.

[stream] change time.Tick to Ticker

---

core/types/eth_transaction.go
rpc/eth/types.go
rpc/v2/types.go

When a harmony transaction is queried in eth_ rpc, the sender derivation logic should be based on the original harmony txn.
This pr also add eth hash of the txn in hmy_ rpc.

correct hmy txn sender in eth_ rpc; add ethHash in hmy txn rpc

---

api/service/explorer/service.go
api/service/legacysync/syncing.go
hmy/downloader/downloaders.go
node/node_syncing.go
rpc/blockchain.go

The RPC methods related to sync was updated when adding stream sync protocol. But it did not support DNS sync status update. So this PR is to make these RPCs compatible with DNS sync when downloader is inactive.
Tested locally

[sync] make sync rpc compatible with legacy sync

---

core/tx_pool.go

https://github.com/harmony-one/go-sdk/issues/242 (3.1.1 temporary fix)
Added balance check with gas price for delegation staking transaction. 
Some delegation transaction will pass `txPool.validateTx` with amount set equal to balance (not aware of the additional gas fee). This PR is to fix the validation for delegation transaction.
Tested locally and resolve the issue.

[txPool] added gas balance check when validating delegate transaction

---

hmy/downloader/downloader.go
hmy/downloader/downloaders.go

Resolve https://github.com/harmony-one/harmony/issues/3650.
downloaders.active is only set after `config.ServerOnly` check.

[downloader] fix inSync method

---

node/node.go

Hit runtime nil pointer when I was running query of /node-sync
Apr 12 09:04:06 ip-172-31-50-182.us-west-2.compute.internal harmony[9866]: 2021/04/12 09:04:06 http: panic serving 54.153.42.130:51206: runtime error: invalid memory address or nil poin

[sync] fix nil pointer when querying /node-sync

---

api/service/explorer/service.go
node/service_setup.go

A further fix based on https://github.com/harmony-one/harmony/pull/3653.
Instruct explorer node to use `NodeAPI.InSync` interface for compatibility with stream sync.
Tested locally, RPC returns true as expected.

[explorer] Instruct explorer.InSync RPC uses NodeAPI as backend.

---

block/header.go

Fixes https://github.com/harmony-one/harmony/issues/3581
NewBlockHeader subscription using eth ws should return standard eth response. The previous format was just dummy, I don't think anyone was using it, so it can assumed safe to standardize this format.
new output response:
```
{ parentHash:
'0xcbdeba1dbb882837bdad0f40cfbf478dc139b888644582bd7e9bef264fe7ef1f',
miner: '0x6911B75B2560be9a8F71164a33086be4511fC99A',
stateRoot:
'0x4d0b5b168bd3214e32f95718ef591e04c54f060f89e4304c8d4ff2745ebad3a9',
transactionsRoot:
'0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
receiptsRoot:
'0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
logsBloom:
'0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```

make block header subscription output format complaint with ethereum

---

block/header.go

adding missing sha3Uncles and nonce fields to new header response, which were missed in https://github.com/harmony-one/harmony/pull/3655

add missing sha3Uncles and nonce fields to new block header response

---

block/header.go

add missing difficulty field to new block header reponse, which is missed in https://github.com/harmony-one/harmony/pull/3658 and https://github.com/harmony-one/harmony/pull/3655

add the missing difficulty field to new block header response

---

core/tx_list.go
core/tx_pool.go
core/tx_pool_test.go
staking/types/transaction.go
staking/types/transaction_test.go

Another fix for https://github.com/harmony-one/go-sdk/issues/242
Enforce rigid transaction cost check during `txPool.Reset` to remove all invalid transactions. 

[txPool] Further fix in transaction pool

---

node/node_syncing.go

Fix https://github.com/harmony-one/harmony/issues/3685 of panic issue.
When user start node with dns server as false, node will panic and exit. The error is introduced in sync port fix.
Tested locally

[sync] fix a panic issue found in stream tests

---

consensus/consensus_service.go
consensus/consensus_v2.go
consensus/engine/consensus_engine.go
consensus/view_change.go
core/blockchain.go
crypto/vrf/bls/bls_vrf.go
hmy/downloader/adapter_test.go
internal/chain/engine.go
internal/configs/sharding/fixedschedule.go
internal/configs/sharding/localnet.go
internal/configs/sharding/mainnet.go
internal/configs/sharding/pangaea.go
internal/configs/sharding/partner.go
internal/configs/sharding/shardingconfig.go
internal/configs/sharding/stress.go
internal/configs/sharding/testnet.go
internal/params/config.go
node/node_handler.go
node/node_handler_test.go
node/node_newblock.go
test/chain/vrf/main.go

Add vrf epoch and the logic to propose vrf in a new block.
Starting from the VRF epoch, leaders are obligated to propose VRF in every block header.
The VRF is computed using the previous block's hash and the leader's private key.
The resulting vrf and proof are concatenated together and put in the vrf byte[] field of the block header.
Block verification now will verify the vrf data if needed.

Add vrf proposal and verification in block logic

---

p2p/stream/common/requestmanager/requestmanager.go

A fix to go unit test happened at request manager https://travis-ci.com/github/harmony-one/harmony/jobs/504879644. The problem is that an unbuffered response channel will block manager from delivering response data. After the fix, the unit test timing issue is gone.
This change will not effect `RequestManager` behavior. Only test cases are effected. 
Tests passed on local harmony rpc tests.

[stream] make doRequestAsync channel buffered

---

consensus/consensus_v2.go
core/evm.go
core/vm/contracts.go
core/vm/evm.go
core/vm/interpreter.go
core/vm/runtime/env.go
core/vm/runtime/runtime.go
internal/params/config.go

Adding vrf result from the consensus (stored in header) as a precompile contract in evm.
The precompile will simply return the VRF result stored in the current block header as a 32 bytes array, regardless of the input of the precompile contract.
The address for the the vrf contract is at 0xff to avoid having conflict with potentially new precompiles from Ethereum team.
Tested with a contract using evm assembly:
```
contract VRFReader {
function vrf() public view returns (bytes32 result) {
bytes32 input;
assembly {
let memPtr := mload(0x40)
if iszero(staticcall(not(0), 0xff, input, 32, memPtr, 32)) {
invalid()
}
result := mload(memPtr)
}
}
}
```

Add vrf as a precompile in evm

---

go.mod
rpc/types.go

- Fix usage of json.decoder: https://github.com/thanos-io/thanos/issues/1160  https://github.com/thanos-io/thanos/pull/1173
- related to OOM and improve my solution: https://github.com/harmony-one/harmony-ops-priv/issues/20
**NO**
**NO**
**NO**

[rpc] Improve json decode

---

cmd/harmony/config.go
cmd/harmony/config_migrations.go
cmd/harmony/config_migrations_test.go
cmd/harmony/config_test.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
cmd/harmony/main.go

https://github.com/harmony-one/bounties/issues/34
Before:
```
PASS
coverage: 46.0% of statements
ok      github.com/harmony-one/harmony/cmd/harmony      0.043s
```
After:
```
PASS
coverage: 47.1% of statements
ok      github.com/harmony-one/harmony/cmd/harmony      0.072s
```
When running and stdin is terminal
```
Loaded config version 1.0.4 which is not latest (2.0.0).
Do you want to update config to latest version: (Y/n)
Config updated from 1.0.4 to 2.0.0
```
When stdin is piped
```
echo Y |./harmony -c config.toml
Loaded config version 1.0.4 which is not latest (2.0.0).
Update saved config with `./harmony config update [config_file]`
```
1. **Does this PR introduce backward-incompatible changes to the on-disk data structure and/or the over-the-wire protocol?**. (If no, skip to question …

Config 2.0.0

---

core/evm.go
core/staking_verifier.go
core/staking_verifier_test.go
core/state/statedb.go
core/state_transition.go
core/vm/interface.go
internal/chain/engine.go
internal/params/config.go
staking/availability/measure.go
staking/params.go
staking/types/test/prototype.go

As per requested in this governance proposal: https://governance.harmony.one/#/staking-mainnet/proposal/QmYbBQuDSZbMVa6RBi3kzFiNkXxv8PMp9rrT25drkxQnTb
Specifically:
1. Add logic to set first elected epoch for all elected validators starting from the fork epoch (note the first elected epoch setting is not retroactive and only take effect after the fork epoch)
2. Enforce the minimum commission fee of 5% if the current epoch is 100/10 (mainnet/testnet) more than the validator's first elected epoch.
3. Add logic to enforce the minimum commission fee in EditValidator so validators can't go below 5% for commission fee once it's pass 100/10 (mainnet/testnet) epochs after first elected.

Add min commission rate logic

---

rpc/staking.go
rpc/types.go
rpc/types_test.go

https://github.com/harmony-one/harmony/issues/3695
Added multiple address support in rpc hmy_getDelegationsByDelegatorByBlockNumber. Now the first argument accepts a single address or an address list. If an address list is given, a list of results will be returned.
Tested locally on mainnet with explorer config. Example output:
```
▶ curl -d '{
"jsonrpc":"2.0",
"method":"hmy_getDelegationsByDelegatorByBlockNumber",
"params":[
"one1...",
13239347
],
"id":1
}' -H 'Content-Type:application/json' -X POST 'localhost:9500'
{"jsonrpc":"2.0","id":1,"result":[{"Undelegations":[],"amount":...}]}
▶ curl -d '{
"jsonrpc":"2.0",
"method":"hmy_getDelegationsByDelegatorByBlockNumber",
"params":[
["one1...","one1..."],
13239347
],
"id":1
}' -H 'Content-Type:application/json' -X POST 'localhost:9500' …
```

[rpc] added multiaddress in GetDelegationsByDelegatorByBlockNumber

---

cmd/harmony/config.go
cmd/harmony/config_migrations.go
cmd/harmony/config_migrations_test.go
cmd/harmony/config_test.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
cmd/harmony/main.go
go.mod
internal/configs/node/config.go
internal/configs/node/network.go
rpc/blockchain.go
rpc/rpc.go

https://github.com/harmony-one/harmony/issues/3696
- The current PR only supports BlockChain type RPCs, not other RPCs such as TxPool, Contract, etc. Because I don't know if restricting the flow of other RPCs will affect other products（ I'm not sure if I want to add rate limiter to all RPCs）
- add LRU cache for `GetBlockByNumber`. if it triggers rate limiter wait timeout, the RPC will return empty, This results in a large number of visits in an instant while reducing the user experience. so need to add cache for json body of block
- combine https://github.com/harmony-one/harmony/pull/3698 into this
- add two flags： `--rpc.ratelimiter` and `--rpc.ratelimit`. Or you can use it in config file, it all the same.
- the flag  `--rpc.ratelimiter` is default enabled, so you can ignore it
- the …

[rpc] Add Rate Limiter and cache for RPCs

---

cmd/harmony/config.go
cmd/harmony/config_migrations.go
cmd/harmony/config_migrations_test.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
cmd/harmony/main.go

As requested by @rlan35 , added flag to disable stream sync protocol on mainnet. All changes are backward compatible.
For backward compatibility, all legacy config running `sync.downloader` will have `sync.Enabled` on by default.
Cmd related unit test added accordingly.
Tested locally with following options:
1. v1.0.4 default config file.
2. v1.0.4 with downloaders turned on.
3. With `--sync` flags.
4. With `--sync=true` flags.

[cmd] Disable stream sync protocol as default on mainnet.

---

rpc/staking.go

As requested in https://github.com/harmony-one/harmony/issues/3694, now delegation rpc will not return delegation with zero amount and empty undelegation.
This will potentially break the backward compatibility. Please make sure there is not external dependency on this two functions before going forward.
```
hmy_getDelegationsByValidator
hmy_getAllDelegationInformation
```
Tested locally with explorer node on mainnet.
Result dumped here: https://gist.github.com/JackyWYX/a77f78f432971aed85a950b76d712fa5
Noticed that there are validators with zero delegation entries, is this expected? Any further change request? @jhd2best

[rpc] rpc skip delegations with zero amount and empty undelegation

---

hmy/downloader/beaconhelper.go
hmy/downloader/downloader.go
hmy/downloader/longrange.go
node/node_syncing.go
p2p/stream/common/requestmanager/requestmanager.go
p2p/stream/common/streammanager/streammanager.go
rpc/filters/api.go

Ticker Need to use like this: https://github.com/harmony-one/harmony/blob/b602e8d454694373ab8f68b4e95cfd3a60670bb9/core/tx_pool.go#L317-L324
Do not forget 
```go
defer ticker.Stop()
```
if forget do such thing, maybe leading this meory leak like this: 
- https://github.com/google/goexpect/issues/3
- https://github.com/google/goexpect/pull/4

Fix Ticker cannot stop for releasing resource

---

rpc/blockchain.go

https://github.com/harmony-one/harmony/issues/3732
test locally and have not test it with @hypnagonia 
test locally result：
```
mathxh@MathxH:~/harmony-explorer-v2$ curl -d '{ "jsonrpc":"2.0", "method":"eth_getBlockByNumber", "params":[ "0xbaa39d", true], "id":1 }' -H "Content-Type:application/json" -X POST "http://127.0.0.1:9500"
{"jsonrpc":"2.0","id":1,"result":{"difficulty":"0x0","extraData":"0x","gasLimit":"0x4c4b400","gasUsed":"0x32c4b","hash":"0xc71c4bfce57e68a2e4b0636c04b7aeb4fcf1083cf39d5010e31f7722e52f83cc","logsBloom":"0x00200000000000000002000080000000020001000000000000000000000000000000000040000000000000000000000000020000000000000008000000000000000000000000000000000008000000200000000000000000000000008000000200800000000000001000000000000000000008000000000000000010000000000001000 …
```

[rpc] Fix cache lead to inconsistent result

---

cmd/harmony/default.go

As discussed [here](https://github.com/harmony-one/harmony/pull/3666#issuecomment-857211586). Disable broadcasting invalid transactions.
No tests done yet. Shall be confirmed at mainnet deployment.

[cmd] stop broadcasting invalid transaction

---

api/service/legacysync/syncing.go

Half the gRPC getBlockAndSigs batch size. Since the block size is growing, the replied message with 30 block is exceeding gRPC default max message size as 4MB. This is a temporary fix and need to be investigated later.
This is a simple parameter tuning. It need to be tested on mainnet.

[sync] half the batch size of downloading a block

---

core/types/tx_pool.go

During the p2p message validation, the node will drop the node message if
the size is bigger than the MaxPoolTransactionDataSize.
The initial value was just a heuristic value set during the open staking testnet.
However, the valid node message becomes
bigger now due to the higher tx count in the mainnet. So we need to lift the
upper bound. We have observed the oversized node message from metrics.
Ex,
hmy_p2p_node_msg{type="invalid_oversized"} 3484

[p2p] increase the max size of node message validation

---

core/blockchain.go
core/rawdb/accessors_offchain.go
node/node_syncing.go

to avoid redundant serialization and deserialization of pending crosslinks.

remove unnecessary db writing for pending crosslinks

---

node/node.go

Filter beacon block message that has block smaller than current block number.
This is just a current fix of flooding beacon block sync message. A more strict sanity check will be done later. This is the first of many PRs to prevent p2p spamming. 
Tested on shard 2 explorer. A bunch of following message is observed, meaning the flooding message is rejected.
```
{"level":"warn","receivedNum":14089918,"currentNum":14092588,"caller":"/home/yx/go/src/github.com/harmony-one/harmony/node/node.go:421","time":"2021-06-10T06:38:42.610431334Z","message":"beacon block sync message rejected"}
```
Need to test on mainnet to see whether this help reduce network load.

P2p filterbeaconmsg

---

node/worker/worker.go

Temporary solution to recover consensus which is broken due to block size that's too large.

add limit on block size

---

node/node.go

Lower the log level when handling spamming message.
```
{"level":"warn","receivedNum":14112458,"currentNum":14126044,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node.go:418","time":"2021-06-12T06:47:50.350146771Z","message":"beacon block sync message rejected"}
```

[p2p] lower the debug level when handling spamming message

---

api/service/legacysync/downloader/client.go
api/service/legacysync/syncing.go

Changed parameters for nodes that have low network bandwidth at DNS service.
During the spamming attack, the spammer also spammed transaction with large data which make the block size to be huge. It is possible that a block reaches a size of 1.5M per block, thus causing some of the DNS client failed to download blocks within time out.
From a contabo node at Europe for testing, it is observed that the downloading 4MB block batch data requires ~55s which is way beyond the current timeout, which is only 10s before.
Thus this PR is changing the following parameters:
1. Changed GetBlocks request timeout to 300s.
2. Further reduce the number of blocks per request: 15 -> 5
3. Reduce the number of blocks per process loop: 1000 -> 30
4. Increase the client retry times from 5 -> 10 per process loop …

[sync] changed param to support low network bandwidth against large block

---

cmd/harmony/bls.go
cmd/harmony/config.go
cmd/harmony/config_migrations.go
cmd/harmony/config_migrations_test.go
cmd/harmony/config_test.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
cmd/harmony/main.go
go.mod
hmy/hmy.go
internal/configs/harmony/harmony.go
internal/configs/node/config.go
node/api.go
node/node.go
node/node_handler_test.go
node/node_newblock_test.go
node/node_test.go
rpc/common/types.go
rpc/debug.go

@LeoHChen
https://github.com/harmony-one/bounties/issues/41
- moving private config structs from within `cmd/harmony/config.go` to `internal/configs/harmony/harmony.go` exported as `harmonyconfig` package for `hmyv2_getConfig` RPC
- adding config migration from `2.0.0` to `2.1.0` which sets `Log.VerbosePrints` to default value of:
https://github.com/harmony-one/harmony/blob/b87f17f0effdcb2e186251e96df95390c1929fd1/cmd/harmony/default.go#L69-L77
- adding a RPC struct `Config` for printing internal config objects 
https://github.com/harmony-one/harmony/blob/b87f17f0effdcb2e186251e96df95390c1929fd1/node/api.go#L146-L152
- flag `--rpc.debug` must be added for enabling `hmyv2_getConfig`
```
./bin/harmony --log.dir . --log.name harmony.log --verbose-prints config --rpc.debug --network devnet …
```

[feature] expose all configuration variables and values

---

rosetta/infra/Dockerfile

To address errors in https://jenkins.harmony.one/job/docker-explorer-release/542/console
multiple similar error
```
20:25:03 internal/utils/utils.go:17:2: missing go.sum entry for module providing package github.com/ethereum/go-ethereum/common (imported by github.com/harmony-one/harmony/internal/utils); to add:
20:25:03 	go get github.com/harmony-one/harmony/internal/utils
```

[docker][rosetta] fix docker image build error

---

go.mod
node/api.go
rosetta/common/errors.go
rosetta/rosetta.go
rosetta/services/account.go
rosetta/services/call_service.go
rosetta/services/call_service_test.go
rosetta/services/construction_parse.go
rosetta/services/construction_parse_test.go
rosetta/services/network.go
rosetta/services/tx_format.go
rosetta/services/tx_format_test.go
rosetta/services/tx_operation.go
rosetta/services/tx_operation_test.go

#3428 
Before:
```
?   	github.com/harmony-one/harmony/rosetta	[no test files]
ok  	github.com/harmony-one/harmony/rosetta/common	(cached)	coverage: 41.4% of statements
ok  	github.com/harmony-one/harmony/rosetta/services	0.217s	coverage: 43.8% of statements
```
After:
```
?   	github.com/harmony-one/harmony/rosetta	[no test files]
ok  	github.com/harmony-one/harmony/rosetta/common	(cached)	coverage: 41.4% of statements
ok  	github.com/harmony-one/harmony/rosetta/services	0.190s	coverage: 39.6% of statements
```
No
2. **Describe the migration plan.**. For each flag epoch, describe what changes take place at the flag epoch, the …

[Rosetta]Implement the /call endpoint

---

core/tx_list.go
core/tx_pool.go
core/tx_pool_test.go
core/types/tx_pool.go
node/node.go
node/worker/worker.go
rpc/harmony.go

Update minimum txn gas price to 1 gwei
Remove temporary block txn size limit
Separate txn size limit from p2p node data limit
Update _gasPrice api to return 10Gwei as recommended gas price.

a few spam protections

---

api/service/explorer/service.go
api/service/explorer/storage.go
api/service/explorer/storage_test.go
api/service/explorer/structs.go
node/node_explorer.go

This PR is the temporary fix to address the explorer node data fails to catchup with beacon chain. In explorer service, instead of write address transaction every block, commit transaction data to db every 20 blocks. Meanwhile the data not committed will be kept in memory cache for external RPC queries. 
Note this PR is just optimizing the caching mechanism of explorer node, and it does not effect the leveldb schema.
1. Passed local test.
2. Benchmarked on mainnet explorer node (aws.c5.2xlarge)
Mainnet metrics: (cache and flush address info into db every 100 blocks)
1. Every batch need to write ~820MB data to db.
2. Each batch need ~1m10s to flush to db.
3. On average ~0.7s a block to commit explorer db.
4. Increased CPU usage 20% -> 30% (which is expected since previously all explorer …

Explorer db commit performance optimization

---

node/metrics.go
node/node_cross_link.go
node/node_syncing.go

- Add this issue: https://github.com/harmony-one/harmony/issues/3754
- Replace magic number `0` with constant `shard.BeaconChainShardID` when non-beacon chain exec `SyncLoop` syncing from Shard 0 for catching up beacon chain
Need to test it locally

[metrics] Add crosslink messages to metrics

---

rpc/blockchain.go

If the latest parameter is encountered as input, first get the real number of the latest block, and then look up the cache directly. Because a block comes out every two seconds, if a large number of requests for the latest parameter are accessed during this time period, the cache can be used directly
have test it locally
add some debug log using printf to test:
```go
blockNum := blockNumber.EthBlockNumber()
if blockNum != rpc.PendingBlockNumber {
realBlockNum := uint64(blockNum)
if blockNum == rpc.LatestBlockNumber {
realBlockNum = s.hmy.CurrentBlock().NumberU64()
fmt.Printf("real block number %d\n", realBlockNum)
}
cacheKey := combineCacheKey(realBlockNum, s.version, blockArgs)
if block, ok := s.blockCache.Get(cacheKey); ok {
fmt.Printf("get cached latest block number %d\n", …
```

[rpc] Optimized GetBlockByNumber with latest param

---

api/service/explorer/service.go
node/node_syncing.go

During the explorer DB migration, the explorer service is unavailable. Thus, set InSync RPC result to false when migration on going.
Tested on mainnet explorer machine with following command
```
curl localhost:5000/node-sync
false
```

Set Sync to false when explorer service unavailable

---

cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go

#3781
Before:
```
PASS
coverage: 48.1% of statements
ok  	github.com/harmony-one/harmony/cmd/harmony	0.040s
```
After:
```
PASS
coverage: 48.1% of statements
ok  	github.com/harmony-one/harmony/cmd/harmony	0.075s
```
```shell
➜  bin git:(fix-3781) ✗ ./harmony --config ./1_0_4.config                                                                                                                                                  [1:19:35]
Old config version detected 1.0.4
Do you want to update config to the latest version: [y/N]
y
Original config backed up to ./1_0_4.config.backup
Successfully migrated ./1_0_4.config from 1.0.4 to 2.1.0 
```
migrated config file
https://gist.github.com/touhonoob/e5b0a2239376e1bce42f6c64c0d1c401
1. **Does this PR introduce backward-incompatible changes to the …

[cmd] default Log.VerbosePrints.Config to true

---

go.mod
p2p/types/peerAddr.go

- orginal issue: https://github.com/harmony-one/harmony-ops-priv/issues/36
- go vet detected context leak:
```bash
p2p/types/peerAddr.go:89:8: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak
```
- go-yamux memory leak issue https://github.com/libp2p/go-yamux/pull/30
Since this library is a dependency of libp2p-kad-dht, choose to upgrade and update libp2p-kad-dht
According to the [latest analysis and speculation](https://github.com/harmony-one/harmony-ops-priv/issues/36#issuecomment-864555047), there is no evidence that the DNS node memory issue is related to these Fixes, but there is some correlation.   So try to reproduce on my local https://github.com/harmony-one/harmony-ops-priv/issues/36#issuecomment-864986243, test is on …

[p2p] Try to fix P2P memory issue

---

go.mod
p2p/discovery/option.go
p2p/discovery/option_test.go

- https://github.com/harmony-one/harmony-ops-priv/issues/36
- https://github.com/harmony-one/harmony/issues/3709
According to the test and verification in issue https://github.com/harmony-one/harmony-ops-priv/issues/36, the OOM is indeed caused by the Discovery function of libp2p's pubsub, but this feature cannot be simply disable. Otherwise, it will cause missing feature. After reading the code implementation of libp2p's kad-dht(https://github.com/libp2p/go-libp2p-kad-dht/blob/7cf0c1e05fe3a69cba5d3747358a25b937fcad89/query.go#L282-L300   https://github.com/libp2p/go-libp2p-kad-dht/blob/7cf0c1e05fe3a69cba5d3747358a25b937fcad89/query.go#L344-L349), I found that some Option parameters can reduce the frequency of queryPeer calls and reduce the calls related to `go-yamux's Stream` function. …

[DO NOT MERGE] [p2p] Reduce memory and CPU usage of libp2p

---

cmd/harmony/flags.go
cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/enums.go
consensus/validator.go
consensus/view_change.go
hmy/hmy.go
internal/configs/harmony/harmony.go
node/api.go
rpc/blockchain.go
rpc/common/types.go

follow https://github.com/harmony-one/harmony/pull/3689
harmony-one/harmony#3670 and https://github.com/harmony-one/bounties/issues/36
Before:
After:
```
=== RUN   TestMessageSenderInitialization
--- PASS: TestMessageSenderInitialization (0.13s)
=== RUN   TestMessageSenderReset
--- PASS: TestMessageSenderReset (0.10s)
=== RUN   TestSignAndMarshalConsensusMessage
--- PASS: TestSignAndMarshalConsensusMessage (0.16s)
=== RUN   TestSetViewID
--- PASS: TestSetViewID (0.13s)
=== RUN   TestConsensusInitialization
--- PASS: TestConsensusInitialization (0.23s)
=== RUN   TestConstructAnnounceMessage
--- PASS: TestConstructAnnounceMessage (0.16s)
=== RUN   TestConstructPreparedMessage
construct_test.go:100: vote is already submitted 7639ab784fc61cdd702809de5275c73f1c5fb0842878a8b0c53a5a311711d2d112db …
```

design and implement redundant validator setup

---

core/headerchain.go

According Pprof results, RPC `GetLogs` in calling `HeaderChain.GetHeaderByNumber` is causing intense CPU usage. Thus added a log to help query the canonical block number and increase the cache params in HeaderChain.
Passed local RPC tests.

[core] Increase caching at HeaderChain

---

core/headerchain.go

Fix an error introduced at https://github.com/harmony-one/harmony/pull/3813.
Tested locally

[core] fix cache introduced by getHashByNumber

---

api/service/explorer/service.go
internal/chain/supply.go
rpc/blockchain.go

Fixing https://github.com/harmony-one/harmony/issues/3800.
Sub the inaccessible tokens when calculating chain supply at RPC endpoints
Tested on localnode on mainnet. Result:
```
> curl localhost:5000/circulating-supply;
"10208016410.793122399090366864"
> curl -ls --request POST 'http://localhost:9500' --header 'Content-Type: application/json' --data-raw '{
>     "jsonrpc": "2.0",
>     "id": 1,
>     "method": "hmy_getCirculatingSupply",
>     "params": []
> }';
{"jsonrpc":"2.0","id":1,"result":"10208016410.793122399090366864"}
> curl localhost:5000/total-supply
"13078958823.793138999090362468"
> curl localhost:5000/burn-addresses
[{"EthAddress":"0x7bdef7bdef7bdef7bdef7bdef7bdef7bdef6e7ad","Address":"one10000000000000000000000000000dead5shlag","Balance":"319237512.206861000000000000","Nonc …
```

Fix circulating supply

---

rpc/blockchain.go
rpc/contract.go
rpc/filters/api.go
rpc/metrics.go
rpc/net.go
rpc/pool.go
rpc/staking.go
rpc/tracer.go
rpc/transaction.go

Add metircs for RPCs, Need to make sure if RPC is  the culprit for OUT OF SYNC or not.
use ` curl  http://127.0.0.1:9900/metrics | grep ^hmy_rpc`: 
```txt
1hmy_rpc_over_ratelimit{rate_limit="1000"} 302
00 hmy_rpc_query_info{info_type="failed_number",rpc_name="GetBlockByNumber"} 1
524hmy_rpc_query_info{info_type="query_number",rpc_name="GetBlockByNumber"} 3
7    hmy_rpc_query_info{info_type="query_number",rpc_name="GetShardingStructure"} 3
0  52hmy_rpc_rpc_request_delay_bucket{rpc_name="GetBlockByNumber",le="0.02"} 0
47hmy_rpc_rpc_request_delay_bucket{rpc_name="GetBlockByNumber",le="0.04"} 0
hmy_rpc_rpc_request_delay_bucket{rpc_name="GetBlockByNumber",le="0.08"} 0 …
```

[metrics] Add metrics for RPCs

---

rpc/eth/types.go
rpc/types.go
rpc/v1/types.go
rpc/v2/types.go

Add VRF and VRFProof field in block and header rpc.
Test result:
```
"result": {
"difficulty": 0,
"epoch": "0x0",
"extraData": "0x",
"gasLimit": "0x4c4b400",
"gasUsed": "0x0",
"hash": "0xb911aa8dc72e82add0821b603410e9aede6f592222a72de0b435245c1f538e95",
"logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
"miner": …
```

Add vrf and proof in header and block rpc

---

rpc/blockchain.go
rpc/common/types.go
rpc/filters/api.go
rpc/filters/filter.go
rpc/v2/types.go

Add limitation to GetBlocks and GetLogs.
Passed local tests.
Passed mainnet RPC tests.
```
curl -s --request POST 'http://localhost:9500/' --header 'Content-Type: application/json' --data-raw '{ "jsonrpc": "2.0", "method": "hmyv2_getBlocks", "params": [1, 1025, {"withSigners": false, "fullTx": false,"inclStaking": false}], "id": 1}'
> .... # Some data
curl -s --request POST 'http://localhost:9500/' --header 'Content-Type: application/json' --data-raw '{ "jsonrpc": "2.0", "method": "hmyv2_getBlocks", "params": [1, 1026, {"withSigners": false, "fullTx": false,"inclStaking": false}], "id": 1}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"GetBlocks query must be smaller than size 1024"}}
```

[rpc] add limitation on GetBlocks and GetLogs. Also some other small changes

---

.gitignore
api/service/manager.go
api/service/pprof/service.go
api/service/pprof/service_test.go
cmd/harmony/config_migrations.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
cmd/harmony/main.go
go.mod
internal/cli/flag.go
internal/cli/parse.go
internal/configs/harmony/harmony.go

@JackyWYX 
[harmony-one/bounties#46](https://github.com/harmony-one/bounties/issues/46)
`go test -cover ./cmd/harmony/`
Before:
```
ok  	github.com/harmony-one/harmony/cmd/harmony	0.266s	coverage: 47.8% of statements
```
After:
```
ok  	github.com/harmony-one/harmony/cmd/harmony	0.136s	coverage: 48.5% of statements
```
When running and stdin is terminal
```
./harmony -c config_1_0_4.toml 
Old config version detected 1.0.4
Do you want to update config to the latest version: [y/N]
y
Original config backed up to config_1_0_4.toml.backup
Successfully migrated config_1_0_4.toml from 1.0.4 to 2.1.0 
```
When stdin is piped
```
echo Y | ./harmony -c config_1_0_4.toml 
Old config version detected 1.0.4
Update saved config with `./harmony config update [config_file]`
```
1. **Does this PR …

Implement pprof module extension

---

go.mod

upgrade libp2p for fixing issues as follows:
- https://github.com/libp2p/go-libp2p-pubsub/pull/427 
- https://github.com/libp2p/go-libp2p-pubsub/pull/430 
- go-libp2p see here https://github.com/libp2p/go-libp2p/releases
- go-libp2p-core see here https://github.com/libp2p/go-libp2p-core/releases

[p2p] Upgrade libp2p stack

---

cmd/harmony/config_migrations.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
cmd/harmony/main.go
internal/configs/harmony/harmony.go
internal/configs/node/network.go
p2p/discovery/option.go
p2p/discovery/option_test.go
p2p/host.go

Because of the block time problem of all shards, the parameter of concurrency needs to be exposed for adjustment. If it is set to 1, it may currently go wrong and affect the consensus. Set to 1, according to the paper, KAD DHT query time will downgrade to Chord‘s algorithm
NOTE： Add p2p.disc.concurrency flag and default value with libp2p dht
Passed Local test
```bash
./harmony --p2p.disc.concurrency 5
```

[config] Add p2p.disc.concurrency flag

---

rpc/blockchain.go
rpc/contract.go
rpc/filters/api.go
rpc/metrics.go
rpc/net.go
rpc/pool.go
rpc/staking.go
rpc/tracer.go
rpc/transaction.go

record actual seconds for every rpc, not only in buckets discussed with @sophoah 
use browser access : "http://localhost:9900/metrics"
hmy_rpc_request_delay_gauge shown as follows:   
```txt
hmy_rpc_over_ratelimit{rate_limit="1000"} 0
hmy_rpc_query_info{info_type="query_number",rpc_name="GetBlockByNumber"} 10
hmy_rpc_request_delay_gauge{rpc_name="GetBlockByNumber"} 0.164471
hmy_rpc_request_delay_histogram_bucket{rpc_name="GetBlockByNumber",le="0.02"} 9
hmy_rpc_request_delay_histogram_bucket{rpc_name="GetBlockByNumber",le="0.04"} 9
hmy_rpc_request_delay_histogram_bucket{rpc_name="GetBlockByNumber",le="0.08"} 9
hmy_rpc_request_delay_histogram_bucket{rpc_name="GetBlockByNumber",le="0.16"} 9
hmy_rpc_request_delay_histogram_bucket{rpc_name="GetBlockByNumber",le="0.32"} 10 …
```

[metrics] Add NewGaugeVec metric to record actual duration for RPCs

---

consensus/reward/rewarder.go
core/offchain.go
internal/chain/reward.go
internal/params/config.go
internal/utils/singleton.go
staking/network/reward.go

Implement the logic to aggregate the block reward distribution so it only happens every 64 blocks. After the fork epoch, for every 64 blocks, the first 63 blocks won't execute any block reward or signature counting logic, and at the 64th block, it will go back and process all the crosslinks/signatures for the previous 64 blocks (including itself). This way shard 0 block time can be reduced by an amortized time of around 0.5s. 
The new logic keeps the accounting of validator reward the same as before. The part that's improving performance is the delegator reward distribution where previously, for each block, the reward is distributed to all delegators, which is a huge computation cost as there are tens of thousands of delegators. Right now, for every 64 blocks, the reward for each …

Add logic to do aggregated reward distribution once every 64 blocks

---

internal/common/address.go

We should accept 0x000000..... as a valid ethereum address.

add special case for 0x0000 address parsing

---

core/blockchain.go
rpc/blockchain.go
rpc/common/block.go
rpc/eth/block.go
rpc/eth/types.go
rpc/staking.go
rpc/transaction.go
rpc/v1/block.go
rpc/v1/types.go
rpc/v2/block.go
rpc/v2/types.go

Refactor and optimized public blockchain API requests. Effected APIs:
1. GetBlockByNumber
2. GetBlockByHash
3. GetBlocks
4. GetBlockSigners
5. GetBlockSignerKeys
6. IsBlockSigner
7. GetSignedBlocks
8. GetLeader
Also changed some parameters in caching.
Passed local test.
Did a stress test on AWS medium machine. Stress test scripts:
```
#!/bin/bash
COUNTER=0
while true;
do
curl -d '{
"jsonrpc":"2.0",
"method":"hmy_getBlocks",
"params":[
15524096,15524097,{"withSigners": true, "fullTx": true, "inclStaking": true}
],
"id":1
}' -H 'Content-Type:application/json' -X POST 'localhost:9500' > /dev/null;
COUNTER=$((COUNTER+1));
echo $COUNTER;
done;
```
Metrics compared with main branch. Both cases will hit cache.
1. Main branch: 230 requests / 30s
2. After the fix: 1120 requests / 30
More metrics …

Public blockchain API performance optimization

---

p2p/discovery/option.go

First remove the DiscConcurrency parameter setting code completely， `--p2p.disc,concurrency` flag does is No use for now. This is just a temporary quick fix

[p2p] Remove DiscConcurrency code

---

.github/workflows/ci-tag.yaml

Add github action CI for a manual release of a tag. Current automated CI include any new code committed.

[github-action] add CI for manual release

---

rpc/staking.go
rpc/types.go

Because of the complexity of RPC method of `GetAllValidatorInformation`, the RPC is expected to take some time to return the result. This PR is trying to do some optimization of the RPC method. 
1. Remove one unnecessary serialization/deserialization to save CPU and memory resources. 
2. Replace the usage of single flight with caching to mitigate the possible memory leak.
The heavy RPC was once a temporary solution to serve our explorer node. But now the method seems way too bloated that one single RPC request may return 36MB data on mainnet. This shall be mitigated by deprecating this RPC method with a number of small requests.
1. Passed local test.
2. Manual test with command:
```
curl --location --request POST 'http://localhost:9500' \ …
```

Optimize the `getAllValidatorInformation` rpc method

---

hmy/gasprice.go
hmy/hmy.go
hmy/pool.go
hmy/staking.go
rpc/harmony.go

Previously our GasPrice rpc returns a fixed number of 10Gwei as suggested gas price.
Now we are adding a more reasonable gas suggestion logic based on transactions in recent blocks. The main logic are exactly following ethereum's gas suggestion mechanism but with a minimum suggested gas price of 10Gwei.

Add gas price suggestion on GasPrice rpc

---

core/events.go
core/tx_pool.go
rpc/filters/filter_system.go

Feed promoted pending txns into the pending txn subscription channel, so all subscribed source can get the new pending txns.

add pending txn subscription support

---

README.md

Updating README because cask is no longer supported brew command. Should use `brew install --cask` instead.

update brew install in readme

---

internal/params/config.go

enable sha3-256 precompile at epoch 725 Around Mon Oct 11 2021, 19:00 UTC for mainnet.

enable sha3-256 fork on mainnet and testnet

---

api/service/blockproposal/service.go
api/service/consensus/service.go
api/service/explorer/service.go
api/service/manager.go
api/service/pprof/service.go
api/service/prometheus/service.go
api/service/synchronize/service.go
consensus/votepower/roster.go
eth/rpc/handler.go
eth/rpc/metrics.go
node/api.go

Previously we do not have the general solution for all RPC metrics. This PR add the general metric to all RPC methods.
The counters per method is now available at `hmy_rpc2_request_count` via `localhost:9900/metrics`
Tested locally. Example output for metrics result
```
curl localhost:9900
```
[Example output](https://gist.github.com/JackyWYX/874e571400d2362816e28afb5653dc09#file-metrics-txt)
1. Create the prometheus metric page at grafana using new metrics.
2. Retire the current prometheus RPC metric.

[RPC] General solution of prometheus metrics for all RPC methods

---

core/state/statedb.go
core/state/statedb_test.go

Copy function in statedb.go does not deeply copy stateValidators.
This push implements and tests correctness of these deep copies.
Tests were built matching the structure for existing testCopy tests:
A generic []validatorWrapper was built and stored in state.
State was copied using statedb.Copy() into variable copy.
The copy was copied again into ccopy.
Each *big.Int field in each value of []validatorWrapper in original, copy, and ccopy were modified and tested for expected values.
Before:
```
root@9dbbf7e849b7:~/go/src/github.com/harmony-one/harmony/core/state# go test -cover
PASS
coverage: 68.3% of statements
ok      github.com/harmony-one/harmony/core/state       9.996s
```
After:
```
root@9dbbf7e849b7:~/go/src/github.com/harmony-one/harmony/core/state# go test -cover
PASS
coverage: …
```

Deep Copy Validator Wrapper in StateDB

---

rpc/rpc.go

Trace APIs are heavy RPCs. Currently, the backend nodes are receiving a large amount of these RPC method calls,  causing bad RPC service performance.
We will disable the Trace methods for now, meanwhile it will effect the explorer contract code verification. We will enable the methods in private methods later.
```
curl --location --request POST 'localhost:9500' \
--data-raw '{
"id": 1,
"method": "hmyv2_traceTransaction",
"params": []
}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"the method hmyv2_traceTransaction does not exist/is not available"}}
```
@LeoHChen  Please verify the result before deployment. Thanks.

[rpc] disable trace api in rpc

---

rpc/rpc.go

#3931 was the original issue #3932 added the ws auth api port but was missing the correct auth api method
```
wscat -c ws://localhost:9801/ -x '{"method":"trace_block","params":["0x10E5117"],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":[{"blockNumber":17715479,"blockHash":"0x4da0178a2576976ecb8facb6b531a5405377d350a00b9cc9bf9e9b87e0db163f","transactionHash":"0xef47582f7b216b7cad548cc9294fa93af309f1b30467482412b1b2befd123930","transactionPosition":0,"subtraces":0,"traceAddress":[],"type":"call","action":{"callType":"call","value":"0x0","to":"0xbc744eca05d23694687a3a16cd26661dfb5570bf","gas":"0x73d18","from":"0x2580e45606271b656a933f6305e02b6c5259c369","input":"0xc9807539000000___Truncated___cec82b3275d54b362fc7dc96e01310e8d9b3ac15dfa3"},"result":{"output":"0x","gasUsed":"0x275e …
```

add correct auth api

---

node/node.go

We are experiencing high transaction volumes all the time on mainnet. Each node is accepting hundreds of txns per second and adding them to txns pools. Even though these txns are not included in the blocks yet. The node still need to process them in order to decide whether it's valid or not. This causes lots of resource consumption for the node, making other services slow and malfunciton.
Specifically, we've seen nodes sync'ing very slowly and fail to catch up to latest block for a long time. Digging in the log, it takes the node 1-2 second or more to sync one block, while there is a huge number of incoming txns being processed by the node at the same time. This is clearly an evidence that the incoming txn processing delayed the sync speed because each block should only takes ~400 ms to …

Do not process txns if node out of sync

---

internal/chain/sig.go

if `mask.SetMask` failed, should return an error

fix DecodeSigBitmap

---

api/service/legacysync/syncing.go
api/service/legacysync/syncing_test.go
node/node_syncing.go
rpc/blockchain.go

As requested from RPC health check requirements, make the sync status check interval smaller. Used a different implementation. In this PR, the sync check result is buffered for 6 seconds.
Tested locally with following RPC calls:
```
> curl --location --request POST 'localhost:9500' \
--data-raw '{
"id": 1,
"method": "hmyv2_inSync",
"params": []
}'
{"jsonrpc":"2.0","id":1,"result":true}
> curl --location --request POST 'localhost:9600' \
--data-raw '{
"id": 1,
"method": "hmyv2_beaconInSync",
"params": []
}'
{"jsonrpc":"2.0","id":1,"result":true}
> curl localhost:5099/node-sync
true
```
These RPCs still need to be verified on nodes that is fall behind the sync on …

[SYNC] refactor and make sync status check interval smaller

---

api/service/legacysync/syncing.go
api/service/legacysync/syncing_test.go
node/node_syncing.go

Extend the sync status cache expiration from 6s to 12s to reduce some loads at DNS server.

[sync] extend the expiration for sync status cache for non-validator nodes

---

node/node_syncing.go

Added metrics for DNS sync service for counting the request count per SYNC request
The new added metrics will be available through `$IP:9900/metrics`
Example:
```
hmy_dns_server_request_count{method="block_height"} 1
```
The code may be deployed to DNS server nodes to see the sync traffics.

Added metrics for dns server for sync service

---

api/service/legacysync/syncing.go
api/service/legacysync/syncing_test.go

Another minor fix for sync stuck issue. Have the cache field protested by the mutex. Added a concurrency test to test the intensive concurrent call of syncStatus.Get.

[SYNC] Sync stuck fix2

---

core/blockchain.go
core/staking_verifier.go
core/staking_verifier_test.go
core/state/journal.go
core/state/statedb.go
core/state/statedb_test.go
core/state_transition.go
core/vm/interface.go
internal/chain/engine.go
staking/availability/interface.go
staking/availability/measure.go
staking/availability/measure_test.go
staking/slash/double-sign.go
staking/slash/double-sign_test.go
staking/types/test/copy.go
test/chain/reward/main.go

1. Merge ValidatorWrapper and ValidatorWrapperCopy to let callers ask for either a copy, or a pointer to the cached object. Additionally, give callers the option to not deep copy delegations (which is a heavy process). Copies need to be explicitly committed (and thus can be reverted), while the pointers are (auto-)committed when Finalise is called.
1. Add a UpdateValidatorWrapperWithRevert function, which is used by staking txs `Delegate`, `Undelegate`, and `CollectRewards`. Other 2 types of staking txs and `db.Finalize` continue to use UpdateValidateWrapper without revert, again, to save memory
1. Add unit tests which check
1. Revert goes through
1. Wrapper is as expected after revert
1. State is as expected after revert
harmony-one/bounties#90
Before:
```
core/state: 70.0%
```
After: …

Resolve harmony-one/bounties#90: Add revert mechanism for UpdateValidatorWrapper

---

rpc/blockchain.go
rpc/contract.go
rpc/metrics.go
rpc/pool.go
rpc/staking.go

With more digging, there are more costly rpcs that's dragging nodes down. One of them is PendingTransactions:
this node got out of memory at the same time:
during that time, the pending txns in the node is "totalPending:3820". That pendingTransaction rpc is returning all of 3820 txns in each call...
Similarly GetDelegationsByValidator is also called extensively, and it could be costly if the validator has thousands of delegators.

add rate limit on PendingTransactions, Call, and GetDelegationsByValidator rpc

---

api/service/legacysync/syncing.go
rosetta/services/network.go

Release one rlock when iterating peers in sync. And change the default return result of getMaxPeerHeight as max uint64
Passed local tests.

[sync] release one rlock and change default value at getMaxPeerHeight

---

internal/rate/config.go
internal/rate/interface.go
internal/rate/limiter.go
internal/rate/limiter_test.go

Add a general purpose rate limiter to be used by RPC and SYNC module. Here are the features of the module:
1. Provide limit by ID (IP).
2. Self maintained loops to remove inactive IPs to avoid memory leak.
Note: This was part of the PR https://github.com/harmony-one/harmony/pull/3938/files. Handle sync rate limit later.
Implemented unit test case.

[misc] add a general purpose rate limiter

---

core/tx_pool.go
core/tx_pool_test.go
hmy/hmy.go
node/node.go
rpc/harmony.go

A refresh of the original PR: https://github.com/harmony-one/harmony/pull/3960
Bump min gas price to 30 gwei to deter spamming.
Currently the min gas price is 1 gwei and suggested gas price is 10 gwei. The spamming txns in mainnet blocks are using gas price randomly but mostly close to 1 gwei.
Assuming on average, the attackers gas price is 2 gwei. With a mainnet block with 100 txns (https://explorer.harmony.one/block/0x41ce7ec54ee61607f959cd891bceead274cb4efc1136cec6cb7cf6c217f43670), 16852987 gas is used, which is 16852987 * 0.000000002 ONE ~ = 0.034 ONE (~ $0.0067). So the cost to spam one block is $0.0067 and the cost to spam for a whole day is 24 * 1800 * 0.0067 = $289.44.
By changing the min gas price to 30 gwei, the cost of spamming our network for 1 day will be $289.44 * (30/2) = …

bump min gas price to 30 gwei

---

core/evm.go
core/evm_test.go
core/vm/contracts_write.go
core/vm/contracts_write_test.go
core/vm/evm.go
staking/precompile.go
staking/precompile_test.go

Disable migrate() precompile since we are not doing it as a user-facing feature anymore.

disable migrate

---

rpc/blockchain.go
rpc/v2/types.go

currently the block header information exposed exposed via rpc `GetHeaderByNumber` does not include all the fields which is important for light clients deployed in bridges in the crosschain context. this PR makes it available.

add rpc for exposing raw block header information

---

rpc/v2/types.go

Data type for Miner is string which causes issue on header hash verification. Should have been common.Address.
Before:
```
```
After:
```
```
**YES|NO**
6. **What are …

Fix data type for miner

---

consensus/view_change.go

`func (consensus *Consensus) onNewView(recvMsg *FBFTMessage)` locks and then immediately unlocks its mutex.
I can only assume the `Unlock()` should be deferred, since otherwise there's no point to it. I don't know if this has caused critical changes previously.
No changes.
No interesting logs or changes.
**NO**
2. ~~**Describe the migration plan.**. For each flag epoch, describe what changes take place at the flag epoch, the anticipated interactions between upgraded/non-upgraded nodes, and any special operational considerations for the migration.~~
3. ~~**Describe how the plan was tested.**~~
4. ~~**How much minimum baking period after …

Add defer statement to mutex critical code in consensus package

---

Dockerfile
README.md
scripts/install_protoc.sh

Unable to build main docker image for ARM-based platforms. I'm using a MBP M1 and cannot build the docker image unless i include, `--platform linux/amd64`; this builds me an image for `x86_64` arch. however, building for other supported archs, like `arm64`, should still be possible (better adoption? lower barrier to entry?). _side-note: my validator nodes run on `arm64` chips, so this allows me to build `hmy` properly_
Required changes
- in `Dockerfile`, use `$TARGETARCH` when defining gimme go platform
- in `install_protoc.sh`, fix mapping issue w/ `protoc` binaries. it denotes `aarch64` as `aarch_64` (legacy based on how maven does it?)
```bash
#27 55.62 Downloading protoc v3.15.8 for linux-aarch64...
#27 56.35 Downloaded as protoc-3.15.8-linux-aarch64.zip; unzipping into /usr/local... …
```

dockerfile uses target platform's CPU arch and fix aarch64 mapping in install_protoc

---

staking/slash/double-sign_test.go

In `staking/slash/double-sign_test.go`, there exists a big.Int constant with a wrong name. 
This may lead to logic errors in testing if this constant is used in more key parts of the code (since currently it's used as a placeholder in the `MaxTotalDelegation` property of the default validator).
All unit tests pass. There's nothing more that can be tested since this is a unit testing fix.

Rename hundredKOnes constant to thousandKOnes in doubleSign tests

---

rpc/blockchain.go
rpc/contract.go
rpc/filters/api.go
rpc/metrics.go
rpc/net.go
rpc/staking.go
rpc/tracer.go
rpc/tracerParity.go
rpc/transaction.go
rpc/web3.go

Cover all RPCs metrics
Tested locally
```bash
curl -d '{ "jsonrpc":"2.0", "method":"hmy_inSync", "params":[], "id":1 }' -H "Content-Type:application/json" -X POST "http://127.0.0.1:9500"
{"jsonrpc":"2.0","id":1,"result":false}
mathxh@MathxH:~/go/src/github.com/harmony-one/go-sdk$ curl http://127.0.0.1:9900/metrics | grep inSync
100  9202    0  9202    0     0  8986k      0 --:--:-- -hmy_rpc2_delay_histogram_bucket{method="hmy_inSync",le="0.05"} 3
-:hmy_rpc2_delay_histogram_bucket{method="hmy_inSync",le="0.1"} 3
--hmy_rpc2_delay_histogram_bucket{method="hmy_inSync",le="0.2"} 3
:hmy_rpc2_delay_histogram_bucket{method="hmy_inSync",le="0.4"} 3
-- …
```

[rpc] make PRCs metrics cover all RPCs

---

cmd/harmony/config_migrations.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
core/tx_pool.go
internal/configs/harmony/harmony.go
node/node.go
rosetta/infra/harmony-mainnet.conf
rosetta/infra/harmony-pstn.conf

Develop a `txpool.accountslots` flag to determine the "number of executable transaction slots guaranteed per account" according to node runners instead of a default value of 16.
Before:
```
?   	github.com/harmony-one/harmony/internal/configs/harmony	[no test files]
ok  	github.com/harmony-one/harmony/cmd/harmony	0.049s	coverage: 50.3% of statements
ok  	github.com/harmony-one/harmony/core	(cached)	coverage: 31.2% of statements
ok  	github.com/harmony-one/harmony/node	(cached)	coverage: 9.7% of statements
```
After:
```
?   	github.com/harmony-one/harmony/internal/configs/harmony	[no test files]
ok  	github.com/harmony-one/harmony/cmd/harmony	0.049s	coverage: 50.7% of statements
ok  	github.com/harmony-one/harmony/core	(cached)	coverage: 31.2% of statements
ok …
```

feat: Add AccountSlots flag for TxPool

---

cmd/harmony/config_migrations_test.go
cmd/harmony/config_test.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
cmd/harmony/main.go
go.mod
internal/configs/harmony/harmony.go
internal/shardchain/dbfactory.go
internal/shardchain/leveldb_shard/common.go
internal/shardchain/leveldb_shard/shard.go
internal/shardchain/leveldb_shard/shard_batch.go
internal/shardchain/local_cache/hack.go
internal/shardchain/local_cache/local_cache_batch.go
internal/shardchain/local_cache/local_cache_database.go
rosetta/infra/Dockerfile
rosetta/infra/rclone.conf
rosetta/infra/run.sh

Add new leveldb shard db mode, significantly improved read and write performance
during the testing for rosetta check data, the bottleneck of performance was found in the leveldb database.
afte we did an in-depth performance investigation on leveldb and found that there are 2 problems as follows:
1. when leveldb has reach more than 1T large amount of data, the read and write performance is greatly reduced, so the overall performance is degraded
2. when leveldb is multi-threaded concurrently reading, there is a lot of lock overhead, resulting in a decrease in competition performance too
so we upgraded the db of harmony node underlying architecture, evolved into a new model, which split the original one leveldb database into 32 to improve db performance
in the new mode, it will take up an …

leveldb shard

---

rpc/rpc.go

#4092
NA
Previous code would allow the logverbose settings even when the RPCOpt.DebugEnabled is false
now with `RPCOpt.DebugEnabled = false` :
```
curl -H "Content-Type: application/json" -d '{"method":"hmy_setLogVerbosity","params":[5],"id":1}' http://127.0.0.1:9500
{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"the method hmy_setLogVerbosity does not exist/is not available"}}
```
updating config `RPCOpt.DebugEnabled  = true`
````
curl -H "Content-Type: application/json" -d '{"method":"hmy_setLogVerbosity","params":[5],"id":1}' http://127.0.0.1:9500
{"jsonrpc":"2.0","id":1,"result":{"verbosity":"trce"}}
````
**NO**
2. …

[rpc] enable publicDebugAPI with config flag

---

internal/chain/engine.go
staking/slash/double-sign.go
staking/slash/double-sign_test.go

https://github.com/harmony-one/harmony/issues/4060
Before:
```
=== RUN   TestVerify
--- PASS: TestVerify (0.03s)
=== RUN   TestApplySlashRate
--- PASS: TestApplySlashRate (0.00s)
=== RUN   TestSetDifference
--- PASS: TestSetDifference (0.00s)
=== RUN   TestPayDownAsMuchAsCan
--- PASS: TestPayDownAsMuchAsCan (0.00s)
=== RUN   TestDelegatorSlashApply
--- PASS: TestDelegatorSlashApply (0.00s)
=== RUN   TestApply
--- PASS: TestApply (0.01s)
=== RUN   TestRate
--- PASS: TestRate (0.00s)
PASS
coverage: 86.0% of statements
ok  	github.com/harmony-one/harmony/staking/slash	0.089s	coverage: 86.0% of statements
=== RUN   TestCopyRecord
--- PASS: TestCopyRecord (0.00s)
PASS
coverage: 100.0% of statements
ok  	github.com/harmony-one/harmony/staking/slash/test	0.045s	coverage: 100.0% of statements
``` …

Change beneficiary of slashing rewards to be the block leader

---

cmd/harmony/main.go

Fix the hook between downloader and consensus. 
Consensus will only set downloader when sync also runs stream client service.

Fix consensus downloader hook

---

core/blockchain.go

Wg does not prevent from inserting new blocks, but may panic if `wg.Add(1)` happens while it `wg.Wait()`. This can lead to corrupted state.
**NO**
**NO**
**NO**

Removed wg because it doesn't work properly.

---

staking/slash/double-sign.go

Following #4081, the `slash.Record` struct is not changed in any way, thus its marshal function shouldn't be changed either. 
Slashing is not enabled at the moment, so this change doesn't lead to any protocol changes.

Change beneficiary to reporter in slash.Record marshal

---

scripts/snapdb_checker.sh

Add a script to check that the snapdb(#4096) downloaded by users is complete.
Usage:
`snapdb_checker.sh hash ./harmony_db_0` calculate hash of given DB
`snapdb_checker.sh check ./harmony_db_0` check that the DB is complete.
When a new snapdb is published, the hash should be calculated and added to the DBHashList map of the script. The key of DBHashList is block height, and the value is hash.

add script to check snapdb

---

rpc/blockchain.go
rpc/metrics.go
rpc/v1/types.go
rpc/v2/types.go

As type field in StakingTxReceipt is not encoded properly as per rpc/v1 specification, it could not be decoded into standard ethereum Receipt. This PR updates the type to hexutil.Uint64 (as done in geth client).

Make rpc/v1 StakingTxReceipt type field ethereum compatible

---

node/worker/worker.go

Spam txns are making most of blocks full. Causing network slow down. Temporarily reduce the gas limit to 20m. A more long-term gas limit solution will be added once https://github.com/harmony-one/harmony/issues/4113 is fixed.

temporarily reduce gas limit to 20m

---

core/types/eth_transaction.go
core/types/transaction.go
core/types/transaction_test.go

Closes harmony-one/harmony#4113 by sorting transactions by time received
instead of using a hashmap based transaction ordering. This sorting is
on top of the gas price and nonce sorting already implemented.
Effectively, this allows the production of almost a deterministic order
of transaction ordering, as opposed to a heap-based hash map ordering
which is affected by Golang's internal operations. Consequently,
arbitrageurs, who spam the network with a view to exist around
arbitrag-able transactions, will have to focus on latency instead of
network spamming.
See also bnb-chain/bsc#269 and ethereum/go-ethereum#21358 for related
issues in other chains.
#4113
Before:
```
core/test: 19.4%
```
After:
```
core/test: 19.6%
```
Ran the following contract + brownie script to observe that time based …

[core] fix: Use time-based ordering to avoid spam

---

node/worker/worker.go

Lift the temporary gas limit from 20m to 50m now that https://github.com/harmony-one/harmony/pull/4118 is deployed.

increase block gas limit to 50m

---

hmy/gasprice.go
hmy/hmy.go

...and set suggested gas percentile to 40 instead of 60.
Recently, the recommended gas price requested via `eth_gasPrice`,
`hmy_gasPrice` or `hmyv2_gasPrice` has been fairly high (think 100k
gwei). This patch changes the maximum suggested gas price via these APIs
to be capped at 500 gwei. Users are still allowed to change the gas
price manually to be higher than this, for faster execution.
The occurence of these extremely high gas prices can be attributed to
the self reinforcing mechanism of this implementation. If some 20 blocks
are produced with extremely high gas prices for all transactions, the
API queries the transactions and returns the (erstwhile) 60th percentile
from them. This then results in a feedback loop for the following
blocks. This loop continues until transactions which …

[core]: fix: Cap suggested gas price to 500 gwei

---

core/blockchain.go
hmy/staking.go
rpc/staking.go
rpc/types.go
rpc/types_test.go

Methods `GetAllValidatorInformation` and `GetAllDelegationInformation` could be called without pagination, which leads to huge amount of response data above 10 megabytes.
https://gist.github.com/Frozen/1b4fc7eb1f66606f4b08b7f4c0e297b7
For methods `hmy_getAllDelegationInformation` and `hmy_getAllValidatorInformation` we removed possibility to provide page `-1` and get all information at once. To get same data now pagination should be used. 
**NO**
**NO**
11. **Does this PR …

Fix rpc delegation method.

---

cmd/harmony/default.go
cmd/harmony/main.go
core/blockchain.go
hmy/staking.go
internal/chain/engine.go
internal/configs/harmony/harmony.go
internal/configs/sharding/instance.go
internal/configs/sharding/localnet.go
internal/configs/sharding/mainnet.go
internal/configs/sharding/pangaea.go
internal/configs/sharding/partner.go
internal/configs/sharding/shardingconfig.go
internal/configs/sharding/stress.go
internal/configs/sharding/testnet.go
internal/params/config.go
shard/committee/assignment.go
staking/effective/calculate.go
staking/types/validator.go

#4045 
the rules of #4045 only applied to external validators. 
Localnet: SUCCESS https://github.com/harmony-one/harmony/pull/4100#issuecomment-1107415219
1. **Does this PR introduce backward-incompatible changes to the on-disk data structure and/or the over-the-wire protocol?**.
**YES, the on-disk data structure is not modified, but the consensus algorithm is affected.**
1. Pass the test in the testnet.
2. Make sure all nodes contain this pr before HIP-16 epoch is reached.
There are two main tests, one is that …

[consensus] HIP-16: Enforce a 6% max keys per shard limit for each validator

---

go.mod
go.sum

The version of the reflect2 library we were pulling in (transitively,
via json-iterator) segfaults on go 1.18, due to some use of the unsafe
package that is not portable accross versions; I was seeing this manifest
not long after running `make debug`.
The problem is fixed in the latest version, and similarly the latest
version of json-iterator depends on the fixed version. So, this patch
updates to the latest version to  get he fix.

Increment version on dependency, to fix build on go 1.18

---

p2p/stream/types/stream.go

Bufio Reader/Writer is not thread safe, different goroutines can work with BaseStream at the same time.
**NO**
**NO**
**NO**

Fix BaseStream buf io concurrent access.

---

hmy/downloader/downloader.go
hmy/downloader/shortrange.go

Add a lot of logs in downloader short range sync for diagnostic at validator node stop syncing issue. 
The added logs are in Info level. And the information can be used on mainnet for internal debugging.

Downloader debug log

---

cmd/harmony/main.go
hmy/downloader/downloader.go

Explorer testnet nodes get stuck when doing stream sync. 
Disable the subscription sending feed when the node is explorer node to avoid a sync process stuck observed on testnet.
The issue is caused by sending an event to a subscription that is not subscribed. When the subscription is not subscribed by any handler, the notification service will be blocked at:
```
// hmy/downloader/downloader.go:254
d.evtDownloadStarted.Send(struct{}{})
```
Adding a boolean value to tell whether the subscription is subscribed before will resolve the issue (not not send the event when the subscription is not subscribed).
Tested on testnet node.

[downloader] fix explorer node get stuck when doing short range sync

---

hmy/downloader/longrange.go

When starting the local machine with downloader turned on, the initial consensus will not start for a while because the node will immediately set consensus to "SYNCING" mode when starting with long range sync. 
This PR defer the downloader set "SYNCING" mode and will only set consensus to "SYNCING" mode when it discovers that it is only behind the latest consensus.

[downloader] fix the local test. Do not set sync mode when bootstrapping.

---

internal/params/config.go

Launch HIP16 on mainnet at epoch 999. it's around '27 May 2022 09:41:02 UTC' with 2s block time. 
previous pr: #4100

set HIP16-epoch of mainnet to 999

---

cmd/harmony/dumpdb.go
core/rawdb/accessors_snapdb.go
core/rawdb/accessors_snapdb_test.go
core/rawdb/schema.go
core/state/dump.go

In the process of creating a 'snapdb' via 'dumpdb'(#4069), it may exit. The reason has not been found, but it can be continued, by restarting this command with some iterator keys manually entered. 
1. One issue is when restart the dump cmd, it incorrectly uses account iterator key as the state iterator key. This may cause the new DB to miss some state data.
2. Another issue is that it is a bit annoying to have to manually enter the key for restarting the cmd.
This pr fixed bug 1, and add 'SnapdbInfo' into the new DB. After restarting the cmd, it will read ‘SnapdbInfo’ from the new DB, and continue the process according to it.

Fix dumpdb bug and add SnapdbInfo into dumped db

---

internal/params/config.go

update the epoch number for the chain id fix to be the same as HIP-18

change testnet epoch number for appying fixes of unexpected chain id

---

internal/params/config.go

This reverts commit aa30288dcef9fc732dd7527174f1535de51d6f80. The commit
will be remade when #4146 is merged with the same epoch as that of HIP18
to make a combined hard fork for both features.
CC: @GheisMohammadi

Revert testnet hard fork for unexpected chainId.

---

core/blockchain.go
core/headerchain.go
eth/rpc/types.go
eth/rpc/types_test.go
hmy/blockchain.go
rosetta/services/account.go
rosetta/services/call_service.go
rosetta/services/construction_check.go
rpc/blockchain.go
rpc/contract.go
rpc/eth/rpc.go
rpc/staking.go
rpc/transaction.go
rpc/v1/legacy.go
rpc/v2/legacy.go
scripts/travis_rpc_checker.sh

merge https://github.com/ethereum/go-ethereum/pull/19491 to harmony.

align eip-1898: support block number or hash on state-related methods

---

internal/params/config.go

Set testnet epoch for cross shard transfer precompile (#4165) hard fork to be the same as that of HIP18 and `chainId` fix.

[params] testnet hard fork for cross shard xfer

---

node/node_syncing.go

Temporary fix to broadcast cross links for non-shard 0 leaders (always) or nodes (1%) without beacon sync.

[node] fix: broadcast cross links w/o beacon sync

---

rpc/transaction.go

because harmony does not support the pending block, it should use the latest block as default.

[rpc] use latest block as default params of EstimateGas

---

node/node_syncing.go

Continuation of #4199 to always broadcast cross links even when beacon blocks channel is empty.

[node] fix: always broadcast cross links

---

core/state/statedb.go
core/state/statedb_test.go
rpc/staking.go

The validator list is not per block, while the information being sought
is. Therefore, do not return error if validator address is not present
in state.
Fixes #4202

[rpc] fix: catch ErrAddressNotPresent old block

---

node/node_syncing.go

Since the log below was repeated incessantly after deployment, undo this change.
```json
{"level":"info","caller":"/home/sp/harmony/harmony/node/node_handler.go:330","time":"2022-06-21T14:45:28.568969528Z","message":"[BroadcastCrossLink] Broadcasting Block Headers, latestBlockNum 24906193, currentBlockNum 30545756, Number of Headers 6"}
{"level":"info","caller":"/home/sp/harmony/harmony/node/node_handler.go:330","time":"2022-06-21T14:45:30.337440738Z","message":"[BroadcastCrossLink] Broadcasting Block Headers, latestBlockNum 24906199, currentBlockNum 30545756, Number of Headers 6"}
{"level":"info","caller":"/home/sp/harmony/harmony/node/node_handler.go:330","time":"2022-06-21T14:45:32.637870094Z","message":"[BroadcastCrossLink] Broadcasting Block Headers, latestBlockNum 24906205, …
```

Revert cross link potential fix

---

cmd/harmony/config_migrations.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
core/tx_pool.go
internal/configs/harmony/harmony.go
node/node.go
rosetta/infra/harmony-mainnet.conf
rosetta/infra/harmony-pstn.conf

Test logs:
```bash
$ ./bin/harmony -c harmony.conf
Old config version detected 2.5.4
Do you want to update config to the latest version: [y/N]
y
Original config backed up to harmony.conf.backup
Successfully migrated harmony.conf from 2.5.4 to 2.5.5 
Started Explorer server at: 0.0.0.0:5000
Started RPC server at: 127.0.0.1:9500
Started Auth-RPC server at: 127.0.0.1:9501
Started WS server at: 127.0.0.1:9800
Started Auth-WS server at: 127.0.0.1:9801
^CGot interrupt signal. Gracefully shutting down...
Successfully shut down!
```
```diff
$ diff harmony.conf.backup harmony.conf
1c1
< Version = "2.5.4"
---
> Version = "2.5.5"
104a105
>   GlobalSlots = 5120
```

[pool] make GlobalSlots configurable

---

test/chain/chain/chain_makers.go
test/chain/main.go

Generate chain used only in tests, moved for clarity.

Moved generate chain to tests.

---

cmd/harmony/dumpdb.go
core/blockchain_impl.go
core/chain_indexer.go
core/headerchain.go
hmy/bloombits.go
hmy/hmy.go

Raw usages of `rawdb.ReadCanonicalHash` don't use cache and break encapsulation. It's still not perfect, but it's a good direction.
**NO**
**NO**
**NO**

Fix canonical hash usages.

---

api/service/legacysync/epoch_syncing.go
api/service/legacysync/syncing.go
node/node_syncing.go

There were errors like 
`{"level":"info","caller":"/root/go/src/github.com/harmony-one/harmony/api/service/legacysync/epoch_syncing.go:106","time":"2022-08-06T06:15:06.313198608Z","message":"[EPOCHSYNC] Node is now IN SYNC! (isBeacon: true, ShardID: 0, otherEpoch: 1075, currentEpoch: 1078)"}`
That means, that it gets height from connected peers and their height less than my. Less height => no need to do sync.
Current pr gets rid of those stale peers and tries to get new ones. 
**NO**
8. **Does this PR introduce backward-incompatible changes *NOT* related to on-disk data structure and/or over-the-wire protocol?** (If no, continue to …

Fix epoch sync: min bound, reconnect and additional checks.

---

core/blockchain_impl.go

Measured on explorer node, it saves about 1.5G of memory, and doesn't impact somehow on LA, CPU, DISC IO or reads count.

Reduced cache size.

---

cmd/harmony/flags.go

The Go-ETH metrics are [disabled by default](https://github.com/ethereum/go-ethereum/blob/master/metrics/metrics.go#L17-L22), even when we pass the correct config since this is embedded in the go-eth code. If the flag is not enabled then every time you create a metric the Go-ETH code will give you a NilCollector which will return zero all the time. Our binary does not support this flag, so I'm adding the support for this flag in our flag list so that can be read by the eth metrics code ([here](https://github.com/ethereum/go-ethereum/blob/master/metrics/metrics.go#L35-L55)).
The reason of why that was coded that way is written [here](https://geth.ethereum.org/docs/interface/metrics).
1. **Does this PR introduce backward-incompatible changes to the on-disk data structure and/or the …

fix: add go-eth metrics flags

---

internal/tikv/statedb_cache/statedb_cache_database.go

Sometimes when the writer is shutdown, panics because the channel **l2ExpiredRefresh** is closed before and there might still be some data being pushed to it, preventing the tikv and redis connection to close. In this PR I'm defering the close to make sure the connections are closed even if it panics, also moving the wait before the channel is closed to give some time to the cache to stop pushing messages to the channel 
**NO**
2. **Does this PR introduce backward-incompatible changes *NOT* related to on-disk data structure and/or over-the-wire protocol?** (If no, continue to question 11.)
**NO**

fix: tikv graceful shutdown on close

---

cmd/harmony/config_migrations.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
cmd/harmony/main.go
internal/configs/harmony/harmony.go
internal/configs/node/network.go
p2p/host.go
p2p/security/security.go
p2p/security/security_test.go
rosetta/infra/harmony-mainnet.conf
rosetta/infra/harmony-pstn.conf

https://discord.com/channels/532383335348043777/552562703537799172/1011165999929757746
Before:
```
?   	github.com/harmony-one/harmony/internal/configs/harmony	[no test files]
ok  	github.com/harmony-one/harmony/cmd/harmony	0.080s	coverage: 43.8% of statements
ok  	github.com/harmony-one/harmony/internal/configs/node	(cached)	coverage: 42.9% of statements
ok  	github.com/harmony-one/harmony/p2p	(cached)	coverage: 15.7% of statements
ok  	github.com/harmony-one/harmony/p2p/security	(cached)	coverage: 85.5% of statements
```
After:
```
?   	github.com/harmony-one/harmony/internal/configs/harmony	[no test files]
ok  	github.com/harmony-one/harmony/cmd/harmony	0.064s	coverage: 44.9% of statements
ok  	github.com/harmony-one/harmony/internal/configs/node	(cached)	coverage: 42.9% of statements …
```

[p2p] feat: add maximum peers limit

---

node/node.go

Initially the erpc reader was thought to only listen to existing tx from the reader, so any new transaction coming from a client would get broadcasted to the network by the reader without any validation, then the client would get a valid tx hash for every transaction even if that transaction could be discarded by the validator afterwards. 
We did this because we didn't want the reader to get tx from the p2p network and only from the writer. But we then decided to run the reader in offline mode which discarded that issue but we never enabled the readers to process and validate pending transactions. In this PR im removing the lines of code that prevented just that, now the reader can validate a transaction and only if valid then it will broadcasting it, giving timely feedback to the client, …

fix: erpc raw transaction error handling

---

p2p/discovery/option.go
p2p/gater.go
p2p/gater_test.go
p2p/host.go

The original feature (erroneously) prevents only querying of the private IPs. This change prevents dialing private IPs altogether when the flag is activated.
One of our (newly added) internal nodes received a netscan abuse email even though the flag `DisablePrivateIPScan` was turned on.
Before:
```
p2p: 15.7%
```
After:
```
p2p: 17.2%
```
No.
No.
11. **Does this PR introduce significant changes to the operational requirements of the node software, such as >20% increase in …

[p2p] prevent dialing of private ips

---

cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_service_test.go
consensus/consensus_test.go
consensus/construct_test.go
consensus/quorum/one-node-one-vote.go
consensus/quorum/one-node-staked-vote.go
consensus/quorum/quorum.go
node/node_handler_test.go
node/node_newblock_test.go
node/node_test.go

It was required by method that no one uses, removing this method allows us simplify Decider dependencies.

Decider no longer requires public keys as a dependency.

---

internal/configs/sharding/localnet.go

As a follow up to #4270, ensure that all localnet URLs returned as part of the sharding structure are accurate.
Signed-off-by: MaxMustermann2 <82761650+MaxMustermann2@users.noreply.github.com>
Before this change, `hmy balances <addr>` would produce the same balance on shards 0 and 1 because the first query was port 9500 and the next one was 9501 (the auth http port).
```json
[
{
"shard": 0,
"amount": 4999.469240800000000000
},
{
"shard": 1,
"amount": 4999.469240800000000000
},
{
"shard": 2,
"amount": 0.000000000000000000
},
{
"shard": 3,
"amount": 0.000000000000000000
}
]
```
After this change, `hmy balances <addr>` produces the expected result.
```json
[
{
"shard": 0,
"amount": 4999.469240800000000000
},
{
"shard": 1,
"amount": 0.000000000000000000
},
{
"shard": 2,
"amount": …
```

fix: make localnet sharding structure consistent

---

cmd/harmony/main.go
consensus/engine/consensus_engine.go
core/block_validator.go
core/blockchain_impl.go
core/evm_test.go
core/state_processor.go
core/tx_pool_test.go
hmy/downloader/adapter_test.go
internal/chain/engine.go
internal/shardchain/shardchains.go
node/node.go
node/worker/worker.go
node/worker/worker_test.go
test/chain/chain/chain_makers.go
test/chain/main.go
test/chain/reward/main.go

`Engine` is used like a storage for beaconChain, but doesn't use beaconChain internally.

Remove blockchain dependency from engine.

---

Makefile
README.md
scripts/go_executable_build.sh
scripts/setup_bls_build_flags.sh

Adds support for OpenSSL on macOS Ventura using m2 chips. This PR requires a commit on the `mcl` that includes SSL header files necessary to compile on m1/m2 systems.

add openssl compatibility on m2 chips using darwin

---

cmd/harmony/dumpdb.go
core/offchain.go

This pull request fixes the root cause behind the recent consensus stuck issue.
- `dumpdb` does not write the crosslink to disk.
- a new node is set up with `snapdb` (obtained from `dumpdb` command).
- it receives an old crosslink, likely over the wire, from a syncing s1/2/3 node.
- it adds this crosslink to the store of pending crosslinks, while a valid node would have dropped such a crosslink. 
- the pending crosslinks are saved to disk and reloaded each time the node restarts.
- with time more invalid crosslinks are stored in the list, since the list is capped at 1000 of them.
- when this node becomes a leader, it proposes a block with invalid crosslink.
- other nodes, which already have this crosslink, reject the block - but do not trigger a view change.
- some nodes, which were …

[dumpdb] ensure each cross link is dumped

---

consensus/validator.go
consensus/view_change_construct.go

We can see that error happened on `onNewView`:
`{"level":"warn","myBlock":33980416,"myViewID":33984024,"phase":"Commit","mode":"ViewChanging","error":"Block verification failed: crosslink already exist","caller":"/home/sp/harmony/harmony/consen
sus/view_change.go:496","time":"2022-11-15T05:44:05.852088781Z","message":"[onNewView] Verify New View Msg Failed"}`
`onNewView` is final step of view change mechanism, and block is already invalid. Previous step is `startNewView`, so i added check there for no unchecked blocks sending.

Fix for consensus stuck.

---

go.mod
go.sum

In this pull request, we are rebasing the dev branch onto the main branch and also making some hotfixes to the AWS SDK we use in our project. The AWS SDK is a collection of software tools and libraries that allow us to interact with various AWS services, and it is an essential component of our project.
By rebasing the dev branch onto the main branch, I am able to incorporate any changes that have been made to the main branch since the last time the dev branch was updated. This is important because it helps to ensure that our codebase is always in sync with the latest version of the main branch.

Rebase dev with AWS SDK hotfixes

---

cmd/harmony/main.go

If the node is not a beacon validator, we make sure the beacon already initialized. Even if we are only checking, calling ShardChain function can initialise blockchain for a node. So, this checking line is blocking epoch chain initialization. Because it sets a normal beacon chain for shard 0, while it has to be EpochChain if the node is a shard node. This could create a couple of issues for syncing.

fix epoch chain initialization issue

---

node/node.go

Before:
```
```
After:
```
```
**YES|NO** …

Fix getting epoch number.

---

.dockerignore
Makefile
scripts/docker/Dockerfile
scripts/docker/README.md
scripts/docker/docker-compose.yaml

Configuration file should be used as the single source of truth (ssot), and provide an simple and clean way for operation. a few enhancements have been included in this PR:
- refactor dockerfile to use multi stage build
- use non-root user & tini for better process handling
- provide docker-compose file for local testing
- add README.md
@diego1q2w  @MaxMustermann2 
my mistake, the original PR is approved but closed. https://github.com/harmony-one/harmony/pull/4239

feat: update dockerfile with some enhacement

---

cmd/harmony/config_migrations.go

Migrating config file from 2.5.10 to 2.5.11 doesn't work.
Config migration handles the transition from an older configuration version to the most recent version.The migration process uses the **doMigrations** function, and so **getNextVersion** is called to find the latest version and compare it with the toml file version.
**getNextVersion** creates an array of versions and sorts them in order to find the latest one. Each version is in the format "x.x.x." The issue here is that the normal sort won't work if the versions don't have the same number of digits, for example, 1.02.10 and 1.2.9. So, we need a custom sort.

fix config migration issue

---

consensus/quorum/one-node-staked-vote.go
consensus/quorum/quorum.go
consensus/view_change.go
consensus/view_change_construct.go
core/blockchain_impl.go
core/rawdb/accessors_offchain.go

Helps confirm that #4340 is caused by time drift. 
- The crash occurred due to an index out of bounds error on the list of leader public keys. 
- The index in question was negative.
- The index represented the location of the next leader's index in the list. 
- The index is calculated as `(gap in view ids + current leader index) % number of internal keys`. The gap acts as an offset parameter, and can be negative.
- _However_, if the gap becomes too negative (such that the numerator is less than 0), we will get a negative number. [For Go, `a % b` is negative if `a` is negative.](https://stackoverflow.com/questions/43018206/modulo-of-negative-integers-in-go).
- Most of the times, the gap is positive, except when the fallback mechanism for view id calculation is used.
- The fallback …

Add logging for `NthNextHmy` panic

---

.github/workflows/ci-tag.yaml
.github/workflows/ci.yaml
scripts/docker/Dockerfile

This is a PR going direct to main as there are no harmony code changes, and dev has been updated with the same changes already.
- fix issue https://github.com/harmony-one/harmony/actions/runs/4014263067/jobs/6894656037
- update github action tasks
github action run showing the build now works (only the push to the harmony docker repo is failing since it is done from my personal account)
https://github.com/sophoah/harmony/actions/runs/4023250279/jobs/6914199451

[ops] github action and docker image update

---

core/state/statedb.go

If a contract self destructs to self and then receives funds within the same transaction, it is possible for its stale state to be saved. This change removes that possibility by checking for deleted state objects before returning them.

[core] fix state handling of self destruct

---

cmd/harmony/config_migrations.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
cmd/harmony/main.go
internal/configs/harmony/harmony.go
internal/configs/harmony/harmony_test.go
internal/configs/node/config.go
internal/configs/node/network.go
rosetta/infra/harmony-mainnet.conf
rosetta/infra/harmony-pstn.conf
rosetta/rosetta.go
rosetta/services/call_service.go
rosetta/services/construction.go
rosetta/services/construction_check.go
rpc/contract.go
rpc/rpc.go

See ethereum/go-ethereum#23645 and #4332

rpc: add configurable http and `eth_call` timeout

---

core/vm/instructions.go
internal/params/config.go

Due to technical debt, validator information is stored in the code field of the address. The code field can be accessed in Solidity for an arbitrary address using `extcodesize`, `extcodehash`, and `extcodecopy` or helper commands (such as `address.code.Length`). The presence of this field is used by contract developers to (erroneously) deny smart contract access to other smart contracts (and therefore, validators). This PR fixes that oversight by returning the same values as other EOAs for known validator addresses. Obviously, it needs a hard fork that will be scheduled separately.

evm: don't return extcode for validators

---

.gitignore

The cache folder is generated by code introduced in #4316 when using `make debug`

git: ignore the cache folder

---

cmd/harmony/config_migrations.go
cmd/harmony/config_migrations_test.go
cmd/harmony/config_test.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
core/tx_pool.go
go.sum
internal/configs/harmony/harmony.go
internal/configs/harmony/harmony_test.go
node/node.go
rosetta/infra/harmony-mainnet.conf
rosetta/infra/harmony-pstn.conf

Adds new config variables to transaction pool:
TxPool.AccountQueue
TxPool.GlobalQueue
TxPool.Lifetime
TxPool.PriceLimit
TxPool.PriceBump
All of them have default variables, nothing to configure by hands
**NO**
**NO**
**NO**

Configurable tx pool.

---

scripts/docker/Dockerfile

Per the Alpine Linux package repositories, the version for cURL included with v3.16 has changed to revision 6
https://pkgs.alpinelinux.org/packages?name=curl&branch=v3.16&repo=&arch=&maintainer=

build: update pinned curl version

---

core/rawdb/schema.go

This PR adds a prefix to contract code.
- To write contract code to db, we add prefix by default. 
- To retrieve contract code from db, first we check with prefix and then we check without prefix. Either of them give us the code, we return it as code. 
If a node starts from genesis block, it will save all codes with prefix. So it will have slightly different db with a node that has been working since long back ago. But both data are valid and all nodes can work with both DBs. 
**NO**

Add prefix for contract code

---

consensus/consensus_service.go

If `consensus.finalityCounter` does not have anything stored (for example in Syncing mode), the `Load()` returns an interface that cannot be automatically asserted to an `int64`. This results in the node crashing. This commit fixes that.
This pull request is made directly to the `main` branch intentionally.
Systemd logs prior to the fix on release 09dba416
```
github.com/harmony-one/harmony/consensus.(*Consensus).FinishFinalityCount(0xc00323ea00)
/root/go/src/github.com/harmony-one/harmony/consensus/consensus_service.go:479 +0x127
github.com/harmony-one/harmony/consensus.(*Consensus).commitBlock(0xc00323ea00, 0xc003c72ee0, 0xc00063a700)
/root/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:673 +0x177
github.com/harmony-one/harmony/consensus.(*Consensus).tryCatchup(0xc00323e …
```

consensus: replace type assert with test

---

cmd/harmony/config_migrations_test.go
cmd/harmony/config_test.go
cmd/harmony/default.go
cmd/harmony/flags_test.go

Currently, the pprof module is default off. Need to turn it on by default to enable history pprof data persisting on disk.
For `harmony.conf`, it would be better to have `ProfileNames` set to `[]string{"cpu", "heap", "goroutine"}` so that the specified profiles will be persisted into disk.
Tested and run locally.

Turn pprof default on with local saved files

---

consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/validator.go
consensus/view_change.go
core/blockchain.go
core/blockchain_impl.go
core/blockchain_stub.go
core/rawdb/accessors_metadata.go
core/rawdb/accessors_metadata_test.go
core/rawdb/schema.go
internal/configs/sharding/shardingconfig.go
internal/params/config.go
numeric/decimal.go
numeric/decimal_test.go

When the feature NonBeaconLeaderRotation is activated, the leaders will be rotated on shards 1-3 an equal amount of blocks depending on the epoch length and slots count. Shard 0 will rotate only the internal validators.

Rotate external validators for non-beacon shards. 

---

consensus/consensus_v2.go
internal/utils/timer.go
internal/utils/timer_test.go

Timeout can accept current time as argument, which makes it more convenient to use.

Minor: removed time.Sleep from tests. 

---

internal/params/config.go

The below code was run on `make debug` to confirm that everything works as expected. It must be run after epoch 1 begins so that the network accepts the staking transaction.
```python
from pyhmy import account, blockchain, staking, transaction, validator as validator_module, numbers
import time
pk = "1f84c95ac16e6a50f08d44c7bde7aff8742212fda6e4321fde48bf83bef266dc"
validator_address = "one155jp2y76nazx8uw5sa94fr0m4s5aj8e5xm6fu3"
protocol_min_delegation = int( numbers.convert_one_to_atto( 100 ) )
validator_info = {
"name": "Alice",
"identity": "alice",
"website": "alice.harmony.one",
"security-contact": "Bob",
"details": "Are you even reading this?",
"min-self-delegation": int( numbers.convert_one_to_atto( 10000 ) ),
"max-total-delegation": int( numbers.convert_one_to_atto( 100000 ) ), …
```

internal/params: set validator code fix hard forks

---

consensus/consensus_v2.go
consensus/fbft_log.go
node/node_explorer.go

concurrent map iteration and map write
May 04 11:06:14 mhe-explorer0-01 systemd-journald[359497]: Suppressed 17945 messages from harmony.service
May 04 11:06:14 mhe-explorer0-01 harmony-explorer-node[1457088]: goroutine 6812396 [running]:
May 04 11:06:14 mhe-explorer0-01 harmony-explorer-node[1457088]: github.com/harmony-one/harmony/consensus.(*FBFTLog).DeleteBlocksLessThan(...)
May 04 11:06:14 mhe-explorer0-01 harmony-explorer-node[1457088]:         /home/sp/harmony/harmony/consensus/fbft_log.go:151
May 04 11:06:14 mhe-explorer0-01 harmony-explorer-node[1457088]: github.com/harmony-one/harmony/node.(*Node).commitBlockForExplorer(0xc028ac0000, 0xc138e7f500)...

Fix consensus concurrent map access.

---

cmd/harmony/inspectdb.go
cmd/harmony/main.go
core/rawdb/database.go

This PR adds inspectdb to the list of supported commands. It traverses the entire database and checks the size of all different categories of data. It records number of zero-value entries as well. Once the inspection is done, the report will be shown in a table.
`harmony inspectdb ./harmony_db_0`

add inspectdb to cli

---

api/service/legacysync/epoch_syncing.go
node/node_syncing.go

This PR fixes beacon-ness in legacy sync.
Previously, `isBeacon` parameter was hardcoded as `false` when called. Now, it is dynamic, based on the configuration. The parameter is only used in the logs.

fix beacon-ness in legacy sync

---

api/service/stagedstreamsync/staged_stream_sync.go

This PR fixes the stream printLog issue. It removes error made by print log and replace it with warning. So, any error on printLog won't break the syncing process.

fix stream log issue, replace print log error with warning

---

cmd/harmony/config_migrations.go
cmd/harmony/default.go
cmd/harmony/flags.go
cmd/harmony/flags_test.go
cmd/harmony/main.go
hmy/gasprice.go
hmy/hmy.go
internal/cli/flag.go
internal/cli/parse.go
internal/configs/harmony/harmony.go

This change makes the gas price oracle options available as options in the configuration file / command line. In addition, the gas price oracle's suggestion mechanism has been modified to return the default gas price when block utilization is low. In other words, the oracle can be configured to return the 60th percentile gas price from the last 5 blocks with 3 transactions each, or return the default gas price if those 5 blocks were utilized less than 50% of their capacity
Fixes #4357 and supersedes #4362

hmy: Gas Price Oracle improvements

---

core/blockchain_impl.go
core/evm_test.go
core/state/database.go
core/state/snapshot/snapshot.go
core/state/statedb.go
core/tx_pool_test.go
internal/shardchain/shardchains.go
node/worker/worker_test.go
test/chain/main.go
test/chain/reward/main.go

It is pointless to check and re-verify every state item every time we retrieve it from disk. This PR makes advantage of the Ethereum snapshot functionality. When a new block is processed using snapshot, we do not merge the writes directly into the disk layer, but rather generate a new in-memory diff layer containing the modifications. When enough in-memory diff layers are piled on top, the bottom ones begin to merge and are eventually pushed to disk. When we need to read a state item, we start at the topmost diff layer and work our way backwards until we discover it or reach the disk.
This PR has the potential to dramatically enhance the performance of the state database. The snapshot reduces read times from O(log n) to O(1).
1. **Does this PR introduce backward-incompatible changes to …

Snapshot integration and add cache to statedb

---

api/service/stagedstreamsync/short_range_helper.go
api/service/stagedstreamsync/stage.go
api/service/stagedstreamsync/stage_bodies.go
api/service/stagedstreamsync/stage_epoch.go
api/service/stagedstreamsync/stage_finish.go
api/service/stagedstreamsync/stage_heads.go
api/service/stagedstreamsync/stage_short_range.go
api/service/stagedstreamsync/stage_state.go
api/service/stagedstreamsync/staged_stream_sync.go
api/service/stagedstreamsync/syncing.go
consensus/consensus_service.go

Firstly, according to this article https://go.dev/blog/context-and-structs
**Contexts should not be stored inside a struct type, but instead passed to each function that needs it.**
Secondly, there is a bug with storing context at https://github.com/harmony-one/harmony/blob/main/api/service/stagedstreamsync/syncing.go#L190
```
ctx, cancel := context.WithCancel(downloaderContext)
s.ctx = ctx
s.SetNewContext(ctx)
```
not sure how exaclty it happenss, but this fix solved issue. 
When something happens, such as a network error, the already canceled context keeps getting passed repeatedly, thereby preventing subsequent synchronization.

Fixed bug with storing already cancelled context.

---

.travis.yml

On Docker versions < 20.10.9, `apt update` fails due to the use of syscall `clone3` by `Glibc >= 2.34`. This change upgrades the base distribution used by Travis to `jammy`, which contains Docker engine 20.10.12.
See https://docs.travis-ci.com/user/reference/jammy/#docker and moby/moby#42681 for reference.

build: update base distribution in Travis

---

.github/workflows/build-docker-proto-image.yaml

The harmony proto-image is on an individual developer docker account today. This PR create a new github action allowing harmony developer to build and push an updated version of the harmony proto docker image hosted on the harmonyone docker account https://hub.docker.com/u/harmonyone
NA
https://github.com/sophoah/harmony/actions/runs/5343077100
NA

[github action] build and push harmony proto docker image

---

scripts/install_build_tools.sh
tools/tools.go

Release Candidate 2023.2.3  

---

scripts/docker/Dockerfile

fix docker image build failing with go1.18 error, see https://github.com/harmony-one/harmony/actions/runs/5422632199/jobs/9872594637
```
docker buildx build --file ./scripts/docker/Dockerfile --tag harmonyone/testtag ./scripts/docker
[+] Building 120.4s (17/17) FINISHED
=> [internal] load build definition from Dockerfile                                                               0.0s
=> => transferring dockerfile: 1.93kB                                                                             0.0s
=> [internal] load .dockerignore                                                                                  0.0s
=> => transferring context: 2B                                                                                    0.0s
=> [internal] load metadata for …
```

[ops] Harmony Dockerfile go1.19 upgrade

---

test/kill_node.sh

The script to kill harmony process doesn't work. This is the error given from Travis logs:
```
pkill: pattern that searches for process name longer than 15 characters will result in zero matches
Try `pkill -f' option to match against the complete command line.
```
The issue is the pattern for **pkill** command can't be longer than 15 characters. This PR uses an array rather than a long pattern to address the issue.

Fix kill_node script

---

scripts/go_executable_build.sh

Based on https://github.com/harmony-one/harmony/issues/4471
In my case, there was a Docker container that got terminated and failed to save the DHT (Distributed Hash Table) data correctly. This directory with the corrupted DHT data was then copied into a Docker image. As a result, the new image failed to start properly at a later time.

Invalid dht prevents to start localnet.

---

core/state/state_object.go

The function `state_object.CodeSize` erroneously returns the validator code size to be 0. This functionality is only used by the EVM, where the size is overridden by the after the `ValidatorCodeFixEpoch` hard fork to be 0 anyway.
However, for nodes currently syncing blocks before the hard fork was effective, this causes an error. A transaction which attempts to mint an NFT to a validator address prior to the hard fork would have failed, because `onERC1155Received` is not implemented by a validator's code. With the erroneous line, the transaction goes through - causing a node with the unpatched binary to reject the block.

statedb: return correct validator code size

---

.travis.yml

travis-ci has been using different base image for the past one week containing a different version of docker. 
When docker 20.10.9  was installed, apt update failed to run
this PR make sure to upgrade docker to the latest supported by the OS loaded in the travis image.

[build] upgrade docker in travis build to latest

---

.travis.yml

after the docker installation using before_installation we have this message
```
docker.service is a disabled or a static unit, not starting it.
```
following https://travis-ci.community/t/docker-updating-to-newer-version/10229 we are converting the docker upgrade to use `addons`
and upgrading docker.io instead of docker-ce. docker.io was the package installed in the base image

[build] upgrade docker in travis using addons

---

node/node_syncing.go

Current logs show many issues like the one below:
```css
[TryCatchup] Consensus-verified block send to channel failed.
```
The issue is that the current code only joins consensus if the client is enabled, but it doesn't check the stream downloader. Therefore, if the node wants to disable DNS sync and only use the stream, it won't run `supportSyncing`, and as a result, it won't join consensus. This means that the `VerifiedNewBlock` channel will always be full, and new blocks will not be sent to unsynced nodes. Consequently, it will produce the catchup issue. This PR fixes this issue by adding a simple check for the downloader as well.

fix consensus catchup issue

---

.mergify.yml

Add mergify rules to re-enforce PR conditions before merging and how we merge the PRs

[build] add mergify rules

---

consensus/consensus_v2.go
core/blockchain_impl.go
core/blockchain_leader_rotation.go
core/state_processor.go
core_test/shardchain_test.go
internal/configs/node/config.go
node/node_handler_test.go
node/node_newblock_test.go

Before:
```
```
After:
```
```
**YES|NO** …

Keep rotation meta in memory.

---

test/kill_node.sh

Before:
```
```
After:
```
```
**YES|NO** …

Fixed debug run for mac.

---

consensus/consensus_v2.go
consensus/quorum/quorom_test.go
consensus/quorum/quorum.go
consensus/view_change.go
consensus/view_change_test.go

Multiple consecutive keys within a list of validators can be assigned to a single validator. In the worst-case scenario, these consecutive keys could be grouped together. If this validator becomes unavailable, the system experiences prolonged downtime as each key associated with the validator is sequentially checked. The current approach involves iterating through the list of keys, and if the next key belongs to the same validator, it is skipped to optimize the process.
In the default implementation, keys are retrieved one by one from a list, and in the current implementation, each key is checked sequentially. If the next key in line belongs to the same validator as the previous one, it is skipped during the validation process.
go test -cover …

Next validator in view change. 

---

internal/params/config.go
node/worker/worker.go

Default value for gas limit is 80m, but this value is for 5 seconds blocks. Harmony validators do not produce blocks more than 30m gas, and we should store this value across the network. Validators still allowed to reduce the value less than 30m, it's not restricted by protocol.

Block gas 30m.

---

core/genesis.go
core/preimages.go
core/state_processor.go
internal/configs/sharding/localnet.go
node/node_newblock.go
rpc/preimages.go

This PR fixes a few items :
- Consensus failed when the localnet genesis account didn't have their preimage
- Consensus failed when leader didn't process cross shard receipt account migration for the last block of epoch which was mainly used for shard 0, for non shard 0 it should still proceed. Normal validator were still processing the cross shard receipt hence the discrepancies in block verification
- Consensus failed when we finish the last account migration
During the merge conflict, I also removed the preimage rpc generate method that will not be used since the node is actively adding new preimage as it sees it when inserting a new block.
It also updates a few more items:
- update back in the generateOneMigrationMessage the failure when hitting the `cannot find preimage` error 
- …

Hip30 : localnet account migration fix

---

p2p/stream/protocols/sync/chain.go
p2p/stream/protocols/sync/chain_test.go
p2p/stream/protocols/sync/message/parse.go
p2p/stream/protocols/sync/stream_test.go

The stream uses the `getReceipts` function to respond to `GetReceipts` requests from other peers. The current code could result in a panic issue due to nil results from the database and incorrect assignment to the returned array. This PR addresses and fixes these issues while also adding a test case for this RPC.

[Hotfix] fix getReceipts rpc issue

---

internal/chain/reward.go

As part of HIP30, 25% of the total reward is supposed to be credited to the recovery multisig account.
NA
localnet test - every 64 blocks, with 2 shards and with 14 ONEs per block, we receive 448 ONE (14 * 0.25 * 2 * 64) into the recovery multisig account 
```bash
$ curl --location $URL --header 'Content-Type: application/json' --data '{"jsonrpc": "2.0", "id": 1, "method": "hmyv2_getBalanceByBlockNumber", "params": ["'$ADD'",192]}'
{"jsonrpc":"2.0","id":1,"result":448000000000000000000}
$ curl --location $URL --header 'Content-Type: application/json' --data '{"jsonrpc": "2.0", "id": 1, "method": "hmyv2_getBalanceByBlockNumber", "params": ["'$ADD'",256]}'
{"jsonrpc":"2.0","id":1,"result":896000000000000000000}
```

HIP30 - aggregate the recovery multisig reward

---

api/service/legacysync/syncing.go
api/service/stagedsync/syncing.go
core/state_processor.go
core/state_transition.go
core/state_transition_test.go
node/node.go
node/node_newblock.go
node/node_syncing.go
node/worker/types.go
node/worker/worker.go
node/worker/worker_test.go

- Removed unused worker
- Proper error checking
- Tests for gas 30m

Feature gas 30m testing and cleanup.

---

api/service/stagedstreamsync/const.go
api/service/stagedstreamsync/downloader.go
api/service/stagedstreamsync/errors.go
api/service/stagedstreamsync/short_range_helper.go
api/service/stagedstreamsync/stage_bodies.go
api/service/stagedstreamsync/stage_epoch.go
api/service/stagedstreamsync/stage_short_range.go
api/service/stagedstreamsync/staged_stream_sync.go
cmd/harmony/default.go
p2p/stream/common/requestmanager/interface_test.go
p2p/stream/common/streammanager/interface_test.go
p2p/stream/protocols/sync/chain.go
p2p/stream/protocols/sync/chain_test.go
p2p/stream/protocols/sync/const.go
p2p/stream/protocols/sync/message/parse.go
p2p/stream/protocols/sync/protocol.go
p2p/stream/protocols/sync/stream_test.go
p2p/stream/types/stream.go

The current stream sync codes find the neighboring peers and try to connect to them, completing the discovery through the bootstrap process. Once nodes have connected to the minimum number of peers adjusted in the config file, they consider the bootstrap complete and move on to the next step: syncing with the connected peers.
In the main-net, most validators do not have a full database and only have the latest blocks. If a node wants to ask them for old blocks, they most likely won't have them. In this scenario, new nodes won't be able to use neighbors for sync from scratch and will have to use explorer or archive nodes for syncing, which is more centralized.
After the bootstrap process is completed and the node is connected to its neighbors, during the syncing phase, if the remote peer …

Improvements of streamsync to deploy on mainnet

---

p2p/stream/protocols/sync/chain_test.go

function **checkGetReceiptsResult** is defined two times in same package. This issue could be because of merge conflicts resolution. This PR fixes that.

fix duplicate function def

---

internal/configs/sharding/partner.go
internal/params/config.go

This PR is preparing for the devnet reset by :
- updating the different epoch feature activation
- updating the devnet instance configuration
and also update the epoch activation for 30M block gas for all network except mainnet and testnet

reset devnet and set 30M epoch for all network except mainnet/testnet

---

p2p/stream/protocols/sync/chain_test.go
p2p/stream/protocols/sync/const.go
p2p/stream/protocols/sync/message/parse.go
p2p/stream/protocols/sync/stream_test.go

This PR adds a test for **GetNodeData** in stream client and increases the client cap for **GetNodedata** and **GetReceipts**. So, this PR increases the capacity for receipt and state requests. This enhancement enables nodes to request more data per query. Although the numbers are still lower than Ethereum's capacity, they are now substantial enough to handle large batches of receipts and states per request. This has the potential to significantly boost the performance of state synchronization.

add GetNodeData tests for stream client, increase nodes and receipts cap

---

internal/params/config.go

I think if we use the epoch variable as it's a pointer we would modify the original value, and since we just want to run a comparison I think it's safer to store the resulting Subtraction on a brand new variable by using `new(big.Int)`

use new(big.Int) so we don't modify the epoch value

---

core/state_processor.go
internal/params/config.go

Setting the epoch activation for hip30 in testnet

enable hip30 epoch for testnet

---

core/preimages.go

Fixing two things here:  
1. If the import haven't run in the past then we need to ignore the not found error when trying to fetch the last successful import (that is used for metrics only)
2. If the ending state is nil (meaning the generation is up to date) then we skip the final commitment

fix preimage import bugs

---

cmd/harmony/dumpdb.go

64 * 1024 * 1024 is too much high for items count.

Dumpdb cache size.

---

internal/blsgen/lib.go

This pull request addresses an issue that leads to a panic error in one of the nodes, originating from the `loadBasicKeyWithProvider` function. The problem arises when this function employs the `getPassphrase` method to read the passphrase from a key file. In certain instances, the `getPassphrase` method returns a nil or empty value. Consequently, when the subsequent function, `LoadBLSKeyWithPassPhrase`, is called, it attempts to decrypt a null value, leading to an error.
Based on a analysis of the code, it has been confirmed that this issue arises due to the `getPassphrase` function returning empty or nil values. This pull request introduces a modification to add a length check for the data obtained from `getPassphrase`. By verifying the data's length, we can ensure that it is non-empty …

fix decryptRaw issue for nil/empty data

---

p2p/host.go

While debugging these logs usually flood the logfiles making it a bit harder to look at, I think their level should be increased to debug.

Make peer connected/disconnected log debug

---

cmd/harmony/dumpdb.go

Dumpdb fixed memory leak.

---

consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/validator.go
consensus/view_change.go
consensus/view_change_construct.go
node/node_handler_test.go
node/node_newblock_test.go

Complicated logic with closures and abstraction level for no reason.

Refactored verify block.

---

consensus/consensus_service.go
consensus/consensus_v2.go
core/blockchain_impl.go
p2p/stream/common/streammanager/streammanager.go

https://github.com/harmony-one/harmony/issues/4558
https://github.com/harmony-one/harmony/issues/4557
https://github.com/harmony-one/harmony/issues/4556
https://github.com/harmony-one/harmony/issues/4555

Fixed data race.

---

cmd/harmony/main.go
consensus/consensus.go
consensus/consensus_v2.go
consensus/downloader.go
node/node.go

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a973f5]
goroutine 5441 [running]:
github.com/harmony-one/harmony/consensus.(*Consensus).spinUpStateSync(0xc00017a1e0)
/home/sp/harmony/harmony/consensus/downloader.go:107 +0x35
github.com/harmony-one/harmony/consensus.(*Consensus).onCommitted(0xc00017a1e0, 0xc008e3cfc0)

Fixed panic with dHelper.

---

api/service/legacysync/syncing.go

In the legacy sync, if a block insertion is attempted and the block already exists, it breaks the entire sync process. This PR addresses this issue by adding an exception for known blocks.

Fix the block insertion in legacy sync for existed block

---

core/blockchain_impl.go

Redundant code: It is imperative that we exercise control over block insertion. Running the specified goroutine may lead to unintended side effects.

Removed future blocks from blockchain_impl.go

---

core/blockchain.go
core/blockchain_impl.go
core/headerchain.go

Replaced `procmu`and `mu` locks with `chainmu`. 
I checked all places where this locks used, `mu` is used mostly in dead code. Replaced `Rollback` lock from `mu` to `chainmu`, same as `InsertChain` uses. 
PR takes code parts from https://github.com/harmony-one/harmony/pull/4568, so after merge both can be closed.

Removed unused functions and improved locks usage.

---

api/service/legacysync/syncing.go
api/service/stagedstreamsync/staged_stream_sync.go
api/service/stagedsync/stagedsync.go
consensus/downloader.go
core/blockchain_impl.go
core/epochchain.go

`LastMileBlockIter` may contain blocks other than last in epoch, but we can just skip this errors.

Skip epochchain errors.

---

rpc/transaction.go

This is a followup to https://github.com/harmony-one/harmony/pull/4581 where the hash calculation resulted in an incorrect from address when querying the eth api. 
This corrects the GetTransactionReceipt path that also incorported tx.ConvertEth() so that receipts will also show the correct from address.

Fix: Inconsistent from field Hash Calculation in Different API Versions #2

---

core/state/statedb.go
core/tx_pool.go
hmy/staking.go
internal/chain/engine.go
internal/params/config.go
rpc/blockchain.go
rpc/eth/types.go
rpc/transaction.go
rpc/v2/types.go
staking/availability/measure.go
staking/types/delegation.go
staking/types/delegation_test.go
test/build-localnet-validator.sh

This pull request is built on top of #4582 to fix the response of `eth_getTransactionReceipt` while retaining compatibility with eth tooling. 
There is still a leftover bug in the 7% fee implementation that I discovered while doing some localnet tests. This pull request fixes that and adds some minor cleanup / validation logic.

do not return bech32 in receipt, fix 7% fee

---

rpc/blockchain.go
rpc/eth/types.go
rpc/transaction.go
rpc/v2/types.go

Fixed an issue in the v2 package where certain integer fields in the transaction receipt were not correctly serialized in hexadecimal format such as (gas, blocknumber, etc). This PR introduces a new Receipt method for transactions within the `eth` package, ensuring all integer fields are properly converted to hexadecimal representation.

fix getTransactionReceipt response

---

consensus/consensus_v2.go

blocksCountAliveness can't be bigger than minimumBlocksForLeaderInRow

Minor fix for leader rotation. 

---

consensus/quorum/one-node-staked-vote.go
hmy/hmy.go
node/api.go
rpc/private_debug.go
rpc/rpc.go

Calculation on last inserted block, no leader required.

Feature: last signing power.

---

internal/params/config.go

There was a minor inconvenience setting up the node in devent and I need to delay the activation for a few epochs

delay for a few epochs the leader rotations devnet

---

internal/configs/sharding/partner.go
internal/params/config.go

To keep testing the leader rotation in devnet we need to reduce the internal voting power to 10% so we can start migrating internal validators to external validators.

Feat reduce internal devent

---

api/service/legacysync/epoch_syncing.go
api/service/legacysync/syncing.go

There is an issue could make node stuck and node can't sync due to that. the error is `block already exists: block already known`. This PR address this issue by ignoring it.

Ignore known blocks for processsing state sync in legacy sync

---

api/service/legacysync/syncing.go
api/service/stagedsync/stage_lastmile.go
api/service/stagedsync/stagedsync.go
node/node.go

When we try to insert with `varefyAllSign := false`, we insert bunch of blocks, and later rollback, if smth went wrong. If force `varefyAllSign` being always true, no rollback code is executed.

Force verify all sign.

---

p2p/stream/protocols/sync/protocol.go

closing stream removes it from stream manager as well, so it doesn't need to remove it on caller function. This can make a few warning on logs. This PR addresses this issue.

fix stream closure

---

consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_test.go
consensus/consensus_v2.go
consensus/construct.go
consensus/construct_test.go
consensus/double_sign.go
consensus/leader.go
consensus/quorum/thread_safe_decider.go
consensus/threshold.go
consensus/validator.go
consensus/view_change.go
consensus/view_change_test.go
node/api.go
node/node.go
node/node_explorer.go

fatal error: concurrent map read and map write
goroutine 38653979 [running]:
github.com/harmony-one/harmony/consensus/quorum.(*stakedVoteWeight).CurrentTotalPower(0xc0116f2880, 0x1)
/home/sp/harmony/harmony/consensus/quorum/one-node-staked-vote.go:330 +0x55

Fixed decider concurrent map access.

---

api/service/stagedstreamsync/stage_statesync_full.go
api/service/stagedstreamsync/syncing.go
core/blockchain_impl.go
p2p/stream/protocols/sync/chain.go

If a snapshot is not available, the client receives null for snapshots and attempts to call methods on a null instance. This pull request addresses the issue of null snapshots and null responses in fast sync by checking and validating values.

Fix fast sync null snapshot and null response issue

---

internal/configs/sharding/partner.go
internal/params/config.go

This is to activate the devnet external hardfork which will make devnet run on external only

activate devnet external hardfork

---

cmd/harmony/main.go
cmd/harmony/main_test.go
core/tx_pool.go
node/node.go

The allowed transactions file could have multiple entries for the same "from" address. The current code only keeps the latest entry and ignores the previous ones. This PR addresses this issue by setting a map of allowed transactions to an array of transaction data, rather than a map of "from" to a single transaction data.

fix allowed txs to be able to handle multiple txs for same from address

---

internal/configs/sharding/testnet.go
internal/params/config.go

Make testnet external, by bringing the internal power to zero and the slot limit.

add hardfork to make testnet external

---

internal/params/config.go

Somewhere in between the back and forth we had with master and dev this lines got lost, these are part of the latest hardfork release we had. And we cannot have another release without these set.

bring back the lost maxRate epochs

---

consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/view_change.go
internal/utils/utils.go
node/node_newblock.go

`Proposal` type stores caller for debug purpose.

Additional logging on a block proposing.

---

consensus/consensus_msg_sender.go
consensus/consensus_service.go
consensus/leader.go
consensus/validator.go
consensus/votepower/roster.go
crypto/bls/bls.go
internal/chain/reward.go
staking/availability/measure.go
staking/availability/measure_test.go

1. More logs
2. Additional check for keys count
3. Removed unused argument.

Additional logs and cleanup.

---

core/state/statedb.go
internal/chain/engine.go
internal/params/config.go
staking/availability/measure.go

During the previous hardfork we mad sure to update the max-rate to be at least the `min-rate` + `max-rate-change` to comply with the the minimum 7% rate imposed in HIP30, for validators running under that threshold. However, with that we introduced a subtle bug under the assumption that `max-rate-change` was a small value but in practice is not, it can go up to a 100% which will sum to a number higher than a 100% when adding the min-rate. 
For a handful of validators that caused the sanity checks fails when persisting the state in the hard-drive. A issue that is hard to catch as it'll only happen once per epoch, this bug explains issues like the buggy validator or the validator with undelegated funds issues.
As this is a change in the way the data is stored in the state this will have to …

fix validator state when trying to update the max-rate

---

api/service/stagedstreamsync/block_manager.go
api/service/stagedstreamsync/stage_bodies.go
api/service/stagedstreamsync/stages.go
api/service/stagedstreamsync/syncing.go
api/service/stagedsync/syncing.go
cmd/harmony/config.go
cmd/harmony/default.go
p2p/stream/common/requestmanager/requestmanager.go

This PR improves staged stream sync stages and refactors block storage.

Improve staged stream sync

---

api/service/legacysync/epoch_syncing.go
api/service/legacysync/syncing.go
api/service/stagedsync/stagedsync.go

The unsynchronized node continues to log "OUT OF SYNC" while it is syncing. This PR addresses this issue and enhances the logging mechanism to reduce the occurrence of "OUT OF SYNC" lines.

improve logs to reduce OUT of SYNC lines

---

consensus/quorum/quorom_test.go
consensus/quorum/quorum.go
consensus/quorum/thread_safe_decider.go

Removed unused method `NthNextHmyExt`

Minor: removed unused method `NthNextHmyExt`

---

node/node_newblock.go

Fix for crosslink snap db.

---

node/node_newblock.go

Removes threshold for 10 blocks for devnet crosslinks fix.

Removed threshold 10 epochs

---

consensus/consensus_service.go

There are some cases when the leader is unknown at the function call time.

Fix possible panic when the leader is unknown.

---

internal/chain/engine.go
internal/params/config.go
staking/availability/measure.go

Before:
```
```
After:
```
```
**YES|NO** …

Hotfix for max commisstion rate.

---

cmd/harmony/default.go

this is to avoid unnecessary creation of the snapshot which is currently still experimental

set default snapshotlimit to 0

---

internal/chain/reward.go
internal/configs/sharding/fixedschedule.go
internal/configs/sharding/localnet.go
internal/configs/sharding/mainnet.go
internal/configs/sharding/pangaea.go
internal/configs/sharding/partner.go
internal/configs/sharding/shardingconfig.go
internal/configs/sharding/stress.go
internal/configs/sharding/testnet.go

disabled: make travis_rpc_checker  0.47s user 0.30s system 0% cpu **6:25.26** total
enabled:  make travis_rpc_checker  0.45s user 0.28s system 0% cpu **3:46.12** total

Configurable reward frequency. 2x times faster tests. No drawbacks.

---

.travis.yml

Travis CI changed the way how we install docker - travis updated their basic image and add Docker via docker.list, so I've checked how addon instruction is working under the hood - this is just a tee to sources.list, so I've changed docker.list to have the latest stable Docker.
Details on the failed build:
https://app.travis-ci.com/github/harmony-one/harmony/jobs/623369799
Specifically: 
```
W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:51 and /etc/apt/sources.list.d/docker.list:1
```
Proof from logs that docker is working now:
```
sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
...
The following packages will be upgraded:
docker-ce
1 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.
Get:1 …
```

Fix: travis CI changed the way how we install docker - travis updated

---

.travis.yml
p2p/host.go

This PR improves p2p host connection manager and removes QUIC transporters from p2p host.

improve p2p host connection manager, remove quic transporters

---

api/service/legacysync/helpers.go
api/service/legacysync/syncing.go
hmy/downloader/shortrange.go

This pull request addresses two minor issues in the synchronization process:
- Added a check to ensure that the response is not nil before using its value.
- Updated the doGetBlocksByHashesRequest function to correctly utilize the ctx parameter. Previously, the context was not being used, which could lead to improper request handling and potential resource leaks.

Fix Sync Response Handling and Context Usage in doGetBlocksByHashesRequest

---

go.sum
internal/chain/engine.go
staking/availability/measure.go
staking/availability/measure_test.go

UpdateMaxCommissionFee updates commission fee, fee can't be more 100%. Function has 100% coverage

UpdateMaxCommissionFee 100% coverage.

---

node/node_handler.go
p2p/host.go

PeerStore is storage for all known peers.
`host.Network().Peers()` is connected peer.

Fixed PeerStore usage.

---

api/service/stagedstreamsync/staged_stream_sync.go
api/service/stagedstreamsync/state_sync_full.go

This PR addresses a syntax issue (missed defer) with using lock in stream sync.

Fix syntax issue in stream sync

---

core/tx_journal.go
go.mod
go.sum
internal/blsgen/console.go
internal/configs/harmony/harmony.go
internal/utils/passphrase.go

This pull request addresses the issue of deprecated dependencies within our Go project by updating several outdated packages to their recommended alternatives

Update a few of Deprecated Dependencies

---

Makefile

This pull request introduces a new command in the Makefile to create a Linux executable more quickly by only building the main binary without recompiling dependencies. The existing linux_static command remains unchanged and continues to perform a full build, including all dependencies (mcl & bls). The new command is named **linux_static_quick**

add linux static quick command to make file

---

cmd/bootnode/main.go

The following part of code from `cmd/bootnode/main.go`:
```go
fmt.Printf("bootnode BN_MA=%s",
fmt.Sprintf("/ip4/%s/tcp/%s/p2p/%s", *ip, *port, host.GetID().Pretty()),
)
```
prints the bootnode address in the format `BN_MA=<address>`. If any output is printed after this line, it will be appended to the same line. 
In the `deploy.sh` script, the bootnode address is extracted using the `launch_bootnode` function:
```shell
function launch_bootnode() {
echo "launching boot node ..."
${DRYRUN} ${ROOT}/bin/bootnode -port 19876 -max_conn_per_ip 100 -force_public true >"${log_folder}"/bootnode.log 2>&1 | tee -a "${LOG_FILE}" &
sleep 1
BN_MA=$(grep "BN_MA" "${log_folder}"/bootnode.log | awk -F\= ' { print $2 } ')
echo "bootnode launched. $BN_MA"
}
```
This function maps the terminal log to a log …

fix boot node invalid address issue

---

test/debug-external.sh
test/debug.sh

This PR updates the debug scripts to remove unnecessary error messages when attempting to delete non-existent directories and files. An example of unnecessary error messages is like this:
```
cannot remove '*.rlp': No such file or directory
```
The changes improves the script's cleanliness by preventing unwanted error output during forced deletions.

Remove Unnecessary Error Message for Force Deleting of Non-Existent Directories

---

.travis.yml
Makefile
scripts/travis_rosetta_checker.sh
scripts/travis_rpc_checker.sh

**TL;DR**: this PR give us an easier way to point to any harmony-test repo branch, details below.
**What was done:**
* add possibility to point harmony-test repo to non-master branch via CI, for this I've added this logic - https://github.com/harmony-one/harmony/blob/8b1cda41fa8f17a27d966f615fb9894cf12ee1bf/scripts/travis_rosetta_checker.sh#L5-L8, if it is PR - use special PR env, if it is regular branch - use branch env. 
* Q: why not to check it vice-versa like `MAIN_REPO_BRANCH=${TRAVIS_BRANCH:-${TRAVIS_PULL_REQUEST_BRANCH}}`?
* A: Because TRAVIS_BRANCH becomes the branch name in which you want to merge, `dev` in my case
* add MAIN_REPO_BRANCH to point exactly the same repo version in the test run instead of hardcoded main branch
* cover local runs of travis_rosetta_checker.sh and …

feat(CI) - add possibility to point harmony-test repo to non-master branch via CI and locally

---

cmd/harmony/default.go
cmd/harmony/main.go
common/ntp/ntp.go
common/ntp/ntp_test.go

This PR refactors the NTP functionality to support querying multiple NTP servers and addresses the NTP timeout issue commonly encountered in localnet. The PR also includes minor adjustments to error handling and logging for better troubleshooting and debugging.
- **Multiple NTP Servers Support:** 
- The NTP functionality now accepts a comma-separated list of NTP servers. It adds `0.beevik-ntp.pool.ntp.org` to ntp servers as well.
- It iterates through the provided servers, using the first successful response to determine time accuracy. If all servers fail, detailed error messages are returned.
- **Timeout Issue Fix:**
- Fixed the issue where NTP queries would frequently time out in localnet.
- Increased the NTP query timeout from 10 seconds to 30 seconds to provide more resilience in …

Refactor NTP, support multiple NTP servers

---

cmd/harmony/main.go

This PR resolves the issue where an error occurs if the `allowedtxs.txt` file is not present in the `.hmy` directory. Previously, the absence of this file would result in an error:
```
AllowedTxs setup error: open ./.hmy/allowedtxs.txt: no such file or directory
```
The fix involves adding a check to verify the existence of the `allowedtxs.txt` file before proceeding with the setup logic.

Fix Check for Existence of `allowedtxs.txt` File Before Applying Logic

---

cmd/harmony/default.go

This PR configure default snapshot limit to 0 to avoid enabling the feature that is still currently being tested

zero snapshot limit config

---

cmd/bootnode/main.go

This PR replicates PR #4710 to dev branch.

add connection manager high water mark flag to boot node

---

.travis.yml
scripts/travis_rosetta_checker.sh
scripts/travis_rpc_checker.sh

This PR includes several changes:
1. Switch to the `master` branch of harmony-test repo
2. CI Support for the forks via  `TRAVIS_PULL_REQUEST_SLUG`.
* Example of faulty run where we skipped CI - https://github.com/harmony-one/harmony/pull/4742
* Example of successful fix - this PR itself, I'm using fork
3. Fix for the docker logs with `--progress plain`, 
* problematic example - https://app.travis-ci.com/github/harmony-one/harmony/jobs/625579512 - it failed due to huge amount of docker debug logs.  
* Example of successful fix - last run for this PR - just layer info and that is it 
Before:
```
```
After:
```
```
**YES|NO**
5. …

[CI] - point to master, cover fork repos in ci, silence docker output

---

.gitignore
Makefile
scripts/docker/README.md
test/logs_aggregator/docker-compose.yml
test/logs_aggregator/loki-config.yml
test/logs_aggregator/loki-datasource.yaml
test/logs_aggregator/promtail-config.yml
test/logs_aggregator/start_log_aggregator.sh
test/logs_aggregator/stop_log_aggregator.sh

I've covered localnet deployment with the same tool set as higher networks - Promtail-Loki-Grafana.
What was done: 
* 3 Makefile commands to start and stop log aggregation - `debug-start-log` and `debug-stop-log`, `debug-restart-log`
* these 2 new Makefile are just are wrappers between our localnet logs location, promtail-grafana-loki configs and the docker-compose file
* WARNING - grafana runs in the anon access, just in case - **DON'T RUN IT AGAINST PRODUCTION**
Details:
*  test/logs_aggregator/start_log_aggregator.sh
* go to `test/logs_aggregator/` folder
* find the current localnet logs folder
* put it inside `.env` file in `test/logs_aggregator/.env`
* this `test/logs_aggregator/.env` is a source of variables for docker-compose
* start docker-compose detached
* open the Grafana in …

feat(localnet) - add localnet log aggregation tool

---

Makefile
test/debug-external.sh
test/debug.sh
test/deploy.sh

What was done:
* add stream sync as a default option for the `make debug` and `make debug-ext`
* add legacy sync as implicit option to put as variable/export for  `make debug` and `make debug-ext`
* to cover both scenarios above add -L option to the deploy script, which has default value `false` and will use stream sync
* implicitly show the sync options in the deploy.sh:
```
if [ "${LEGACY_SYNC}" == "true" ]; then
sync_options=("--dns=true" "--sync=false" "--dns.client=true" "--sync.downloader=false" "--sync.stagedsync=false")
else
sync_options=("--dns=false" "--sync=true" "--dns.client=false" "--sync.downloader=true" "--sync.stagedsync=true")
fi
``` 
* shortly - main idea was to add new option and provide it through wrappers like (Makefile->debug.sh->deploy.sh) and make **the stream …

feat(Makefile) - add switch for the legacy sync, make stream sync default option

---

test/deploy.sh

This PR addresses stream stability issues caused by the mplex muxer. Specifically, mplex has been identified as the source of instability, leading to streams being closed or restarted unexpectedly.
To resolve this, the PR removes the use of the mplex muxer for localnet and configures localnet to exclusively use the Yamux muxer. This change aims to enhance stability and fixes the stream handling within the localnet environment.
**This PR addresses the issue mentioned in #4749**

Switch Localnet Muxer to Yamux

---

rpc/harmony/harmony.go
rpc/harmony/public_debug.go
test/deploy.sh

As agreed, move GetLastSigningPower to the public harmony API from debug public debug, it should be available by default.
Additionally, remove rpc.debug from the deploy.sh
Via curl:
```
uladzislau@MURAVEIKANB:~$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": "hmy_getLastSigningPower","params": []}' 127.0.0.1:9504
{"jsonrpc":"2.0","id":1,"result":0.88}
uladzislau@MURAVEIKANB:~$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": "hmyv2_getLastSigningPower","params": []}' 127.0.0.1:9504
{"jsonrpc":"2.0","id":1,"result":0.88}
```
Watchdog logs, all types of nodes(validator, RPC) can return sign power:
```
2024/10/03 18:32:47 [SignPower] checking 127.0.0.1:9614, shard 1, sp is 1.00
2024/10/03 18:32:47 …
```

feat(RPC) - GetLastSigningPower on public harmony API 

---

consensus/consensus_block_proposing.go
core/blockchain_impl.go
core/offchain.go
hmy/blockchain.go
node/harmony/node_handler.go

This PR introduces a check for the Crosslink Epoch before attempting to retrieve crosslinks from the database. By validating the epoch first, it prevents errors related to the retrieval of non-existent crosslinks.

Improve Crosslink Retrieve from RawDB

---

node/harmony/node.go

The current code attempts to delete pending crosslinks that are older than 10 epochs. However, if the pending crosslinks were not added to the database within the first 10 epochs, this can lead to an `leveldb: not found`. This PR resolves the issue by adding a condition to skip checking pending crosslinks during the first 10 epochs, ensuring we avoid unnecessary database lookups and potential errors.

Not Checking Pending Crosslinks for First ten Epoch

---

consensus/post_processing.go
hmy/staking.go
internal/params/config.go
shard/committee/assignment.go
staking/availability/interface.go
staking/availability/measure.go
staking/availability/measure_test.go

https://github.com/harmony-one/harmony/pull/4663/files#diff-9cfef24a4e8a4cf4ef84b772edcde2d1c3993f8373a9b9a376377c1385802f29R156
if crosslink are not sent for an entire epoch signed and toSign will be 0 and 0.
when that happen, next epoch there will no shard 1 validator elected in the committee.

Empty signing power workaround

---

internal/configs/sharding/mainnet.go
internal/params/config.go

2151 epoch as 2024-10-30 19:50 UTC
2 internal slot out of 200 per shard
1% internal vote power

HIP32 epoch activation and new sharding config

---

.github/workflows/build-docker-proto-image.yaml
.github/workflows/ci-tag.yaml
.github/workflows/ci.yaml

Testing logs for ci.yaml can be seen here : https://github.com/sophoah/harmony/actions/runs/11362513771/job/31604875903
the error at the end is the docker image push which would work if the github action was running on the harmony github organization
upload-artifact:v4 doesn't accept an artefact with the same name, they all have to be unique and be merged at the end. More detail here https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#merging-multiple-artifacts

[ci] upgrade github actions and merge artifacts

---

consensus/consensus_service.go
consensus/consensus_v2.go

This PR enhances the finalCommit function in the consensus module. It improves the logs and adds return statements after error checks to prevent further processing in case of a failure. This change ensures that the function terminates immediately when critical errors occur:
- `Failed WriteCommitSig`: The WriteCommitSig saves the commits signatures signed on a block. This function is responsible for writing the commit signature of a block to the blockchain's database (rawdb). The commit signature is essential for proving that the block has reached consensus and that it has been accepted by the network.
- `Failed commitBlock`: This function adds a new block to the blockchain after consensus is reached. It inserts the block into the chain and performs additional post-consensus processing, …

Enhance Final Commit Function with Improved Error Handling

---

consensus/consensus_v2.go

This PR enhances the log messages in `setupForNewConsensus` for clearer differentiation between consensus block leader and prev produced blocks.

Improve logging for consensus leader setup

---

api/service/stagedstreamsync/syncing.go
consensus/consensus_v2.go
node/harmony/node_syncing.go

This PR resolves a communication issue between the consensus and syncing modules by refining the conditions for triggering `BlocksSynchronized`. Now, `BlocksSynchronized` is only triggered if new blocks are added to the chain during the syncing process loop. This change prevents unnecessary consensus reset states, ensuring that resets are triggered only when genuinely needed, thereby improving the stability and efficiency of the synchronization process.

Optimize Syncing-Consensus Communication to Prevent Unnecessary Consensus Resets

---

consensus/consensus.go
consensus/consensus_service.go
consensus/construct_test.go

Moved the `UpdateConsensusInformation` method to the test suite, given its primary usage in testing. Notably, `UpdateConsensusInformation` internally invokes `resetState`, which clears blockHash and could potentially trigger a hard fork.

Moved the `UpdateConsensusInformation` method to the test suite

---

consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_v2.go
consensus/view_change.go

This PR enhances the ReadySignal method by adding a log entry each time it is called, which occurs whenever a new block proposal is produced. The added log provides visibility into the source and reason behind each ReadySignal invocation, aiding in tracking block proposal events during consensus.

Add Logging to ReadySignal Method for New Block Proposals

---

test/build-localnet-validator.sh

This PR introduces a validation step to ensure that the required faucet key exists in the `hmy keys list` output before proceeding with building an external validator. If the faucet key is not found, the process raises an error, preventing further steps from executing.

Add Check for Faucet Key Existence Before Building External Validator

---

api/service/blockproposal/service.go
consensus/consensus_block_proposing.go
consensus/proposer.go
node/harmony/service_setup.go

Moved method `WaitForConsensusReadyV2` from `Consensus` struct, because the method does not use private properties, and used only once in consensus service.

Minor: Moved method `WaitForConsensusReadyV2` from `Consensus` struct.

---

consensus/leader.go
consensus/quorum/quorum.go
consensus/quorum/thread_safe_decider.go

This PR improves the consensus logic to handle cases where validators with multiple BLS keys achieve quorum on their initial signatures or commits. Currently, such scenarios can block phase transitions because the condition `if !quorumWasMet && quorumIsMet` doesn't account for quorum being achieved immediately.
To fix this, a new function, `checkFirstReceivedSignature`, is introduced. It checks whether quorum is reached on the first batch of signatures or commits. The PR also updates the logic for `Prepare` and `Commit` phases to properly handle these edge cases. The PR helps to better handling of multi-BLS key validators while maintaining compatibility with single-key setups.

Improve Consensus logic for Multi-BLS Validators with quorum

---

consensus/consensus_service.go
consensus/consensus_v2.go

This PR resolves an issue in the consensus module where multi-BLS key validators, upon retaining leadership, could create multiple block proposals and potentially crash the network. It adds the logic to verify if the leader has changed or if the previous leader belongs to the same node (multi-BLS key validator scenario) and ensures that the consensus does not re-trigger leadership actions unnecessarily for the same node. Also, it updates logs to better describe leader transitions and ensure clarity in network operation debugging.

Fix Multi-BLS Key Validator Leader Rotation to Prevent Multiple Block Proposals

---

consensus/consensus.go
consensus/consensus_test.go
consensus/consensus_v2.go
consensus/leader.go

Before onCommit and finalCommit exists time gap, but no more BlocksSynchronized can erase state before finalCommit.

Prevents BlocksSynchronized being called before finalCommit

---

Makefile

This PR adds a new Makefile command, `debug-multi-bls-with-terminal`, to improve the debugging process for running a localnet with external validators and multiple BLS keys. Unlike the existing `debug-multi-bls` command, which runs the localnet in the background and requires manual process management to view logs or handle errors, the new command uses `screen` to run the localnet in the foreground, allowing developers to easily attach to the session (`screen -r localnet`) and view live logs. All logs are stored in `./tmp_log/localnet_terminal.log` for convenient access. Additionally, the localnet automatically shuts down when the terminal or `screen` session is closed, streamlining cleanup and making it easier to debug issues without manual intervention.

Add New Command to Makefile for Enhanced Localnet Debugging

---

.travis.yml
Makefile
scripts/travis_rosetta_checker.sh
scripts/travis_rpc_checker.sh

What was done:
* turn back logic where we are expecting harmony-test repo to have the branch with the same name, if not  fallback to `master` by default
* remove all `TEST_REPO_BRANCH` mentions
* remove - `echo $TRAVIS_PULL_REQUEST_BRANCH` in `.travisci.yml`, because it doesn't give us any extra information in print
Tested locally against both situations:
* harmony-test branch exist, e.x. - feature/effective-gas-price
```
$ make travis_rpc_checker
bash ./scripts/travis_rpc_checker.sh
[harmony repo] - working on 'feature/effective-gas-price' branch
Working dir is  /fullpath/github.com/harmony-one/harmony/scripts
GOPATH is  /fullpath/go1.22.5/global
[harmony-test repo] - working on 'feature/effective-gas-price' branch
From https://github.com/harmony-one/harmony-test
* branch …
```

refactor: CI - fallback to the master branch in harmony-test if same branch name doesn't exitst

---

cmd/bootnode/main.go
cmd/config/version.go
cmd/harmony/main.go
scripts/go_executable_build.sh

updated the show version of bootnode and harmony binary to dynamically use the current year from the last commit
```
~$ bin/bootnode -version
Harmony (C) 2025. bootnode, version v8508-v2024.3.1-86-g0b5c9ed07 (soph@ 2025-01-21T14:43:16+0700)
~$ bin/harmony -V
Harmony (C) 2025. harmony, version v8508-v2024.3.1-86-g0b5c9ed07 (soph@ 2025-01-21T14:43:16+0700)
```

update harmony and bootnode version

---

.gitignore
Makefile
test/debug-external.sh
test/debug.sh
test/logs_aggregator/docker-compose.yml
test/logs_aggregator/loki-config.yml
test/logs_aggregator/promtail-config.yml
test/logs_aggregator/start_log_aggregator.sh

What was done:
- change rm and clean commands to remove only subfolder for tmp_log folder- justification - tmp_log folder needed for the log aggregator, prevent removal on the go when log stack is running
- fix promtail config to point it to the right place
- add named volume to the docker-compose to store Loki indexed between localnet runs
- echance debug-start-log - it checking that localnet is running, exits
if not
- add debug-delete-volume-log to  make, it removes loki named volume,
warns about sudo rm for the loki files
UPD by 24 Jan:
- fixed loki config path
- tweak loki limits config
Main use case:
1. You started localnet via `make debug-ext` or similiar
2. You started log stack - debug-start-log
3. Open grafana and search against this run, e.g. …

feat: store localnet logs between runs

---

consensus/consensus_v2.go

Fix for doulbe proposing on epoch change.
Note: 
1) tested with legacy sync only
2) better contains [this](https://github.com/harmony-one/harmony/pull/4820/files#diff-65c92fad7c09270b02e7cb7b0d66f7a7a4145645cdea36a9061bb45c62e9670fR209) change to reduce side effects

Improve multiple propose at epoch change

---

internal/configs/node/config.go
internal/configs/node/config_test.go

https://github.com/harmony-one/harmony/issues/4564

Fix for `ShardIDFromKey`

---

p2p/stream/common/streammanager/config.go
p2p/stream/common/streammanager/interface_test.go
p2p/stream/common/streammanager/streammanager.go
p2p/stream/common/streammanager/streammanager_test.go
p2p/stream/common/streammanager/streamset.go

This PR introduces a new feature to the Harmony P2P stream management system: a **reserved stream list**. The reserved stream list acts as a backup pool of pre-established streams, ensuring that peer connections can be replaced immediately whenever a stream is removed due to invalid data, connectivity issues, or other disruptions. This improvement eliminates the need to go through the discovery process to find new peers, resulting in faster recovery and maintaining stable network operations.  
The core functionality allows the stream manager to replace removed streams with available streams from the reserved list. By doing so, the system ensures that the number of connected peers remains sufficient to support syncing and consensus processes without interruptions. This mechanism is …

Enhance P2P Streams with Reserved Stream Replacement

---

consensus/checks_test.go
consensus/consensus.go
consensus/consensus_service.go
consensus/consensus_service_test.go
consensus/consensus_test.go
consensus/consensus_v2.go
consensus/construct.go
consensus/construct_test.go
consensus/debug.go
consensus/leader.go
consensus/reward/schedule.go
consensus/reward/schedule_test.go
consensus/signature/signature_test.go
consensus/state.go
consensus/state_test.go
consensus/threshold.go
consensus/validator.go
consensus/view_change.go
consensus/view_change_test.go
consensus/votepower/roster_test.go
internal/chain/supply.go
staking/network/reward.go

Motivation:
Refactored the consensus module by splitting it into smaller, modular structs to enhance testability and maintainability.
Results:
- Increased test coverage for consensus statements from 15% to 18%.
- Successfully addressed and validated corner cases through comprehensive testing.

Moved several consensus fields to state struct.

---

Makefile

after `make debug-kill` i've noticed that some processes are still functional.

Proper deploy.sh termination

---

p2p/stream/common/streammanager/streammanager.go
p2p/stream/protocols/sync/protocol.go

This PR addresses the connectivity issue of explorer nodes. It adds explorer nodes as a beacon node to protocol ID and let's them see other nodes with same protocol ID.

Fix Explorer Node's Stream Connectivity Issues

---

node/harmony/node_explorer.go

This PR ensures that explorer nodes do not accept future blocks that are not the immediate next block during the COMMIT and PREPARE phase. Previously, there was no strict check on whether a received block was sequential, which could lead to inconsistencies.

Prevent Explorer Nodes from Adding Future Blocks

---

p2p/host.go
p2p/stream/common/streammanager/streammanager.go

This PR removes stream from peer store if its sanity check fails.

Stream Removal if its Sanity Check Fails

---

api/service/stagedstreamsync/beacon_helper.go
api/service/stagedstreamsync/download_manager.go
api/service/stagedstreamsync/downloader.go
api/service/stagedstreamsync/receipt_download_manager.go
api/service/stagedstreamsync/short_range_helper.go
api/service/stagedstreamsync/stage_blockhashes.go
api/service/stagedstreamsync/stage_bodies.go
api/service/stagedstreamsync/stage_epoch.go
api/service/stagedstreamsync/stage_finish.go
api/service/stagedstreamsync/stage_heads.go
api/service/stagedstreamsync/stage_lastmile.go
api/service/stagedstreamsync/stage_receipts.go
api/service/stagedstreamsync/stage_short_range.go
api/service/stagedstreamsync/stage_states.go
api/service/stagedstreamsync/stage_statesync.go
api/service/stagedstreamsync/stage_statesync_full.go
api/service/stagedstreamsync/staged_stream_sync.go
api/service/stagedstreamsync/state_download_manager.go
api/service/stagedstreamsync/state_sync_full.go
api/service/stagedstreamsync/syncing.go

This PR refactors the staged stream sync loggers by introducing a dedicated local logger for each stage. This enhancement ensures that logs contain more detailed and relevant information, improving traceability and debugging. Additionally, it simplifies filtering staged stream sync logs using `loki` or other log monitoring tools, making log analysis more efficient.

Refactor Staged Stream Sync Logger

---

p2p/stream/protocols/sync/protocol.go
p2p/stream/protocols/sync/protocol_test.go

This PR updates the advertisement logic in the `Protocol` to make it more reliable and adaptive. It is manually tested the retry mechanism and sleep time changes. Everything seems to adjust correctly based on peer discoveries and network conditions. 
This PR adds these items:
- **Retry Mechanism**: 
- If the advertisement fails, it will now retry up to 3 times with an increasing wait time between each try. This helps handle temporary network issues more smoothly.
- **Dynamic Timeout**: 
- We’ve made the timeout for advertisement calls dynamic. It increases by 5 seconds after each try, giving more time if the process is taking longer.
- **Tracking Peer Discoveries**: 
- Added a new counter to keep track of how many new peers are found during advertisement. This helps adjust the sleep time …

Refactor advertisement logic with retries and dynamic sleep adjustments

---

p2p/stream/common/streammanager/config.go
p2p/stream/common/streammanager/streammanager.go

This PR improves the P2P layer by introducing a cooldown mechanism for removed streams. Previously, when a stream was removed, the next peer discovery cycle could reconnect to the same stream immediately, potentially causing issues if the peer was invalid or unsynced. This could prevent our node from fully syncing.  
✅ **Added `RemovalInfo` struct** to track the removal timestamp, expiration time, and removal count for each stream.  
✅ **Introduced `RemovalCooldownDuration`** (default: **60 minutes**) to enforce a cooldown period before a removed stream can be reconnected.  
✅ **Updated `streamManager.handleAddStream`** to check if a stream was recently removed before allowing reconnection.  
✅ **Ensured removed streams are stored in `removedStreams`** and properly marked when removal …

Enhance P2P Layer: Stream Removal Tracking and Cooldown Handling

---

core/state_transition.go
core/state_transition_test.go
core/tx_pool.go
core/types/eth_transaction.go
core/types/transaction.go
rpc/harmony/types.go

- Implemented core logic for EOA validation based on EIP-3607
- Added unit tests to cover EOA validation and `preCheck` functionality
This update enhances security by preventing contract accounts from sending transactions directly, aligning with the EIP-3607 standard. It addresses inconsistencies in sender validation logic within the core module. Notably, staking messages are still exempt from the EOA check, as Harmony permits multisig accounts (which are non-EOAs) to send staking messages.
- Run `make go-test` to verify all unit tests pass
- Run `go test -run ^TestPreCheck$ github.com/harmony-one/harmony/core ` for the specific unit test
This PR was based on an earlier version (#4840) but has been updated and cleaned up.

feat(core): EOA sender validation (EIP-3607)

---

p2p/stream/common/requestmanager/config.go
p2p/stream/common/requestmanager/requestmanager.go
p2p/stream/common/requestmanager/requestmanager_test.go
p2p/stream/common/requestmanager/types.go

This PR introduces the `monitorStreamHealth` function to enhance the request manager's ability to detect and handle situations where no active streams are available. It acts as a watchdog by continuously checking the stream list and, if no connections remain for a predefined threshold, it cancels all pending requests to prevent overload and unnecessary waiting. This change helps ensure that requests do not remain indefinitely in the queue when no valid peers are reachable.  
Additionally, a test has been added to verify that when all streams are removed, pending requests are correctly canceled with an appropriate error.

Add Stream Health Monitoring and Improve Request Handling

---

core/state/statedb.go
core/state_processor.go
core/state_transition.go
core/state_transition_test.go
core/vm/eips.go
core/vm/instructions_test.go
core/vm/interface.go
core/vm/opcodes.go
core/vm/runtime/runtime.go
hmy/tracer.go
internal/params/protocol_params.go
node/harmony/worker/worker.go
rpc/harmony/tracer.go
test/chain/chain/chain_makers.go

- Implemented `TLOAD` and `TSTORE` opcodes.
- Implemented new `DB.Prepare()` method to clean up transient storage before state transitions.
- `core/state/statedb.go`: Renamed `DB.Prepare(...)` to `DB.SetTxContext(...)`
This PR introduces two opcodes (`TLOAD` (0x5C) and `TSTORE` (0x5D)) to the EVM. The opcodes are more efficient to execute than the `SSTORE` and `SLOAD` opcodes because the original value never needs to be loaded from storage. The gas accounting rules are also simpler, since no refunds are required. More details on the motivation can be found [here](https://eips.ethereum.org/EIPS/eip-1153).
- `TransientStorage` struct within state db, as well as the unit tests, has already been implemented in #4374.
- EIP 1153 depends on EIP-2200 (#3356) and EIP-3529.
- The EIP (and the …

feat: tload and tstore opcodes for transient storage (EIP-1153) 

---

p2p/stream/protocols/sync/protocol.go

This PR enhances the `advertise` function by introducing **dynamic timeout adjustments** and **adaptive backoff** to improve resilience and efficiency. Previously, if the first attempt failed due to a timeout, the function remained stuck at `60s`, causing unnecessary delays. Now, timeouts increase incrementally up to `5m`, ensuring better adaptation to network conditions.  
A **progressive backoff strategy** is implemented, starting at `2s` per retry (capped at `10s`), reducing excessive delays while preventing unnecessary retries. Logging is improved to explicitly track timeout adjustments and failures. The next wait interval is also refined to ensure a minimum threshold and adjust dynamically based on success or failure.

Optimize advertise Function: Dynamic Timeout Handling & Adaptive Backoff

---

api/service/stagedstreamsync/downloader.go
p2p/stream/protocols/sync/protocol.go

This PR fixes a deadlock in the Downloader loop and improves the handling of downloadC signals. Previously, the syncMutex was being locked twice, causing handleDownload to block indefinitely. Additionally, frequent downloadC signals could lead to excessive goroutine creation and memory usage.

Fix deadlock in Downloader loop and improve handling of downloadC signals

---

.travis.yml

Both latest goimports and gencodec dependencies wants to have `golang.org/x/tools@v0.31.0` library, which supports only golang >= 1.23, but we are running 1.22.5.
Solution is consisted of 2 parts:
* pin goimports version to the 0.30.0 - previous latest and supports 1.22.5, thanks @Frozen for the fix
* start to use [gencodec@v0.1.0](https://github.com/fjl/gencodec/releases/tag/v0.1.0) :
* no more vendors folder - previous reason to fork original repo
* v0.1.0 release supports go 1.22.5
Additionally:
* travis ci time to time creates symlink from `$GOPATH/src/github.com/harmony-one/` to the `/home/travis/gopath/src/github.com/harmony-one/harmony` and it is crashing all our relative paths -solution is to remove if it exists
Before:
```
```
After:
```
```
1. **Does this PR introduce …

fix(CI) - pin goimports and gencodec versions

---

api/service/stagedstreamsync/downloader.go
hmy/downloader/downloader.go
p2p/stream/common/streammanager/interface_test.go
p2p/stream/common/streammanager/streammanager.go
p2p/stream/common/streammanager/streammanager_test.go
p2p/stream/protocols/sync/protocol.go
p2p/stream/protocols/sync/protocol_test.go
p2p/stream/types/interface.go
p2p/stream/types/utils.go

Previously, only shard nodes had an epoch chain, and epoch sync relied on a separate protocol ID while attempting to discover beacon peers based on the last part of the protocol ID. This approach was flawed because stream connections were later rejected due to protocol ID mismatches.  
This PR resolves the issue by introducing a dedicated protocol for beacon validators to handle the epoch sync. As a result, the P2P host for beacon validators now supports multiple protocols:  
- One for the **beacon chain**  
- Another for the **epoch chain**  
Each protocol operates independently, with its own **stream manager** and **set of discovered nodes**, ensuring proper synchronization and preventing connection rejections due to protocol mismatches.

Refactor Stream Protocol ID, Add New Protocol for Epoch Sync to P2P Host

---

consensus/consensus_service.go
internal/chain/reward.go
internal/configs/sharding/localnet.go
internal/params/config.go
node/harmony/node_syncing.go
staking/reward/values.go

1 second finality
1. Created config `IsOneSecondEpoch`
2. Reward reduced 2 times.

1 second finality

---

cmd/config/default.go

In devnet, the explorer nodes are synced, but since they are limited to only two connections, they often end up connecting to other explorer nodes instead of validators. As a result, they never obtain the actual chain height and end up syncing with each other despite being out of sync. This PR increases the minimum number of connections from the current limit of two to three.

update devnet default settings, set  Min Peers to three

---

core/types/receipt.go
core/types/transaction.go
eth/rpc/service.go
rosetta/services/tx_operation_test.go
rpc/harmony/eth/types.go
rpc/harmony/eth/types_test.go
rpc/harmony/v1/types.go
rpc/harmony/v1/types_test.go
rpc/harmony/v2/types.go
rpc/harmony/v2/types_test.go
test/helpers/transaction.go

Fixed issue with effective gas price panic. Covered wth tests.

Fix effective gas price for rpc getTransactionReceipt

---

node/harmony/node.go
node/harmony/node_syncing.go

The PR that removed Staged DNS Sync was intended to create a Sync Instance regardless of the StagedSync flag value. However, we overlooked removing the condition check. This PR resolves the issue with DNS sync instance creation.

Fix DNS Sync Instance Creation Issue

---

api/service/stagedstreamsync/downloader.go
api/service/stagedstreamsync/stage_blockhashes.go
api/service/stagedstreamsync/stage_bodies.go
api/service/stagedstreamsync/syncing.go
p2p/stream/common/requestmanager/config.go
p2p/stream/common/requestmanager/requestmanager.go
p2p/stream/common/requestmanager/types.go
p2p/stream/common/streammanager/streamset.go

This PR refactors the stage block body download loop to implement a more robust pull-based worker model. The current implementation can deadlock in edge cases, particularly when workers fail during processing of the final batches. These changes address several reliability issues while maintaining the same core functionality.
The key improvement is the transition to a pull-based model where workers explicitly request tasks when they're ready to process them. This eliminates coordination issues and busy waiting that were present in the previous implementation. Workers now synchronize directly with the dispatcher through unbuffered channels, creating a more natural flow of work distribution. The dispatcher only prepares tasks when workers are ready to receive them, preventing any task queue …

Refactor stage body download loop to use pull-based worker model with robust error handling

---

api/service/stagedstreamsync/downloader.go
api/service/stagedstreamsync/short_range_helper.go
api/service/stagedstreamsync/stage_blockhashes.go
api/service/stagedstreamsync/stage_bodies.go
api/service/stagedstreamsync/stage_receipts.go
api/service/stagedstreamsync/stage_statesync.go
api/service/stagedstreamsync/stage_statesync_full.go
api/service/stagedstreamsync/staged_stream_sync.go
p2p/stream/common/requestmanager/config.go
p2p/stream/common/requestmanager/requestmanager.go
p2p/stream/common/requestmanager/requestmanager_test.go
p2p/stream/common/requestmanager/types.go

This PR introduces several key improvements and fixes to the stream request and block download systems to enhance the stability, performance, and observability of the staged sync protocol.
The most notable addition is the new `isDownloading` flag, which provides better visibility into the download loop’s state, helping to prevent early termination during active work and improve stage reliability. Along with this, the request queue logic has been fixed to correctly remove elements after popping, addressing a bug that could lead to stale or duplicated work items.
Stream request handling has been refactored to separate health checks and request lifecycle management into distinct routines. This change not only simplifies the main request path but also improves responsiveness and failure …

Fix Stream Request Manager Deadlock, Optimize Stage Block Bodies

---

p2p/discovery/discovery.go

Main problem is described in the https://github.com/harmony-one/harmony/issues/4883
Fix helped on the devnet nodes, I've checked all 4 of them:
* service was running for 23 hours:
```
● bootnode.service - harmony bootnode service
Loaded: loaded (/etc/systemd/system/bootnode.service; enabled; vendor preset: enabled)
Active: active (running) since Wed 2025-04-16 07:10:06 CDT; 21h ago
Main PID: 20726 (bootnode)
Tasks: 10 (limit: 4915)
CGroup: /system.slice/bootnode.service
└─20726 /usr/sbin/bootnode -port 20220 -key boot1-devnet.key -ip 0.0.0.0 -max_conn_per_ip 20 -cmg_high_watermark 3600
```
* after restart it was able to stop in a matter of seconds, so it was a deadlock on the dht discovery part
* after restart is running smoothly with the previous leveldb without db corruption:
```
● …
```

Fix Boot Node Data Store Creation Issue

---

cmd/bootnode/main.go

I've put the same ip from the cli setup, because previously bootnode was listening only localhost aka 127.0.0.1 by default.
Additionally, I've moved default port from 9500 to 9513 and 9800 to 9813, because when we have both harmony and bootnode on the same server - we are starting to play the game who is faster for takeover the port after server reboot.
* I've installed my updated version on the one of devnet bootnodes and what I have, as you can see it is listening on the 0.0.0.0 as original config from the cli:
```
sudo netstat -plnt | grep bootnode
tcp        0      0 0.0.0.0:9020            0.0.0.0:*               LISTEN      6636/bootnode       
tcp6       0      0 :::9813                 :::*                    LISTEN      6636/bootnode       
tcp6       0      0 :::9513 …
```

[bootnode] - sync the http and ws setup with cli IP variable

---

api/service/stagedstreamsync/beacon_helper.go
api/service/stagedstreamsync/downloader.go
api/service/stagedstreamsync/short_range_helper.go
api/service/stagedstreamsync/stage_blockhashes.go
api/service/stagedstreamsync/stage_bodies.go
api/service/stagedstreamsync/stage_epoch.go
api/service/stagedstreamsync/stage_receipts.go
api/service/stagedstreamsync/stage_short_range.go
api/service/stagedstreamsync/staged_stream_sync.go
api/service/stagedstreamsync/syncing.go
cmd/harmony/main.go
p2p/stream/common/requestmanager/interface_test.go
p2p/stream/common/streammanager/interface_test.go
p2p/stream/protocols/sync/protocol.go
p2p/stream/types/stream.go

This PR improves the reliability and clarity of the sync process. The P2P stream is now thread-safe and resets automatically on failure, which helps prevent sync hangs. Short range sync was updated to accept partial blocks and properly break the loop when done, improving flexibility and performance during catch-up.
Several refactors and clean-ups were made to staged sync: initSync now uses internal parameters instead of external variables, and the unused LogProgress option was removed. We also fixed DB path handling for stream sync and re-added last mile blocks to ensure full chain coverage.
On the beacon side, we cleaned up redundant shard checks, fixed beacon helper initialization, and clarified internal comments. Minor improvements include fixing stream failure type handling and …

Optimize and Clean-Up Stages in Staged Stream Sync, Thread Safe P2P Stream

---

api/service/stagedstreamsync/adapter.go
api/service/stagedstreamsync/short_range_helper.go
api/service/stagedstreamsync/stage_blockhashes.go
api/service/stagedstreamsync/stage_bodies.go
api/service/stagedstreamsync/syncing.go
hmy/downloader/adapter.go
hmy/downloader/adapter_test.go
hmy/downloader/longrange.go
hmy/downloader/shortrange.go
p2p/stream/common/streammanager/events_test.go
p2p/stream/common/streammanager/interface.go
p2p/stream/common/streammanager/streammanager.go
p2p/stream/common/streammanager/streammanager_test.go
p2p/stream/protocols/sync/client_test.go
p2p/stream/protocols/sync/protocol.go
p2p/stream/protocols/sync/stream.go

This PR improves logging and observability by adding reason strings whenever a stream is removed. It covers the P2P layer, the sync downloader, and staged stream sync. Each stream removal now clearly logs why it happened, such as invalid blocks, connectivity issues, or missing responses.
Previously, it was hard to trace the cause of stream closures, which made investigations slower. With this change, we can quickly identify issues in the logs and improve troubleshooting for sync and networking problems.

Add Stream Removal Reason

---

.travis.yml
scripts/travis_pyhmy_checker.sh

Main idea of this PR is to enable pyhmy test suite run on the each run, this will help to verify that one of widely used SDK is up and running and haven't been broken by changes in the main repo.
~Additionally, I've disabled cache, because it look like it is just eating our time rn~, ignore this, looks like it is working, I've tested - https://app.travis-ci.com/github/harmony-one/harmony/builds/275141167 vs https://app.travis-ci.com/github/harmony-one/harmony/builds/275140927
Note: please merge this RP only after merge of:
* https://github.com/harmony-one/pyhmy/pull/41
* https://github.com/harmony-one/harmony-test/pull/43
Before:
```
```
After:
```
```
1. **Does this PR introduce backward-incompatible changes to the on-disk data structure and/or the over-the-wire protocol?**. (If no, skip …

feat(hmy_tests) - enable new test job for each PR and new commits to main and dev

---

p2p/stream/common/requestmanager/requestmanager.go
p2p/stream/protocols/sync/sync_stream.go

This PR cleans up all of the waiting requests in RequestManager's close method to prevent lingering goroutines when the manager shuts down.

Clean up Waiting Requests as well to Avoid Goroutine Leaks

---

api/service/stagedstreamsync/downloaders.go

This PR corrects the condition in `DownloadAsync` to ensure the `downloader` for a shard is invoked when present

Fix a Logic Bug Preventing Download Triggers

---

api/service/stagedstreamsync/short_range_helper.go
api/service/stagedstreamsync/stage_epoch.go

This PR improves the robustness of the epoch sync mechanism by handling cases where:
- The requested block is in the future, or
- The remote peer is not fully synced and doesn't have the requested block.
Previously, such scenarios would trigger repeated errors and retries, resulting in excessive error logs and unnecessary load on stream connections.
With this update, the code detects these cases and skips or partially applies blocks, allowing epoch sync to continue without flooding logs or overloading the system.

Handle Future Blocks and Partially Synced Peers Gracefully During Epoch Sync

---

p2p/host.go

This PR logs which stream muxer is negotiated for each new connection.

Log active muxer in p2p host

---

test/configs/local-extra-nodes.txt

This PR fixes port conflicts that occur when adding extra nodes to the running localnet for staged stream sync testing. The issue was that the extra nodes configuration was using port ranges that conflicted with the calculated ports of existing nodes.
When Harmony nodes use the legacy `--port` flag, they automatically calculate all other service ports (RPC, Rosetta, WebSocket, Prometheus) by adding offsets to the base port. The original extra nodes configuration used ports 9101-9110 for shard 1, which calculated to Rosetta port 9801, causing conflicts with existing nodes and resulting in `"bind: address already in use"` errors.
The fix updates the extra nodes configuration to use higher, non-conflicting port ranges. Shard 0 extra nodes now use ports 9301-9310, and shard 1 extra nodes use …

Resolve Port Conflicts in Localnet Extra Nodes Configuration

---

node/harmony/node_cross_link.go

The node was getting stuck in an infinite loop when processing cross-links from epochs it couldn't handle due to being out of sync. This caused:
- **RPC unresponsiveness** - Node became unusable for API calls
- **Resource exhaustion** - CPU and memory usage skyrocketed
- **Sync failure** - Node couldn't complete synchronization
- **Service degradation** - Consensus and other services were affected
When a node is out of sync (e.g., local epoch 5755, network epoch 5757), it receives cross-links for epochs it doesn't have shard state data for. The original code would:
1. Attempt to verify cross-links
2. Fail with "failed to read shard state from DB" 
3. Retry the same cross-links indefinitely
4. Never complete synchronization
Implemented a comprehensive fix with two main components:
- …

Fix cross-link processing infinite loop by adding sync status checks and retry mechanism

---

.hmy/wallet.ini
cmd/config/config_migrations_test.go
cmd/config/config_test.go
cmd/config/default.go
cmd/config/flags_test.go
consensus/consensus_block_proposing.go
core/vm/contracts_write_test.go
internal/chain/engine_test.go
rosetta/infra/harmony-mainnet.conf
rosetta/infra/harmony-pstn.conf
scripts/package/harmony-rclone.sh
test/helpers/p2p.go

This PR addresses legacy configuration inconsistencies that have persisted since Harmony's shard reduction from 4 to 2 shards approximately two years ago. While these outdated configurations don't affect current functionality since the network has been operating on 2 shards, this cleanup ensures complete alignment across all system components and prevents potential confusion for developers and operators.
The changes primarily focus on updating configuration files that still referenced the old 4-shard architecture. This includes default configuration settings, test configurations, and Rosetta service configurations that were still using the legacy shard count. The consensus system constants have also been updated to reflect the current 2-shard topology, with the `IncomingReceiptsLimit` …

Reduce shard count from 4 to 2 across entire codebase
